Attempt 3 at N-hydroxy-alpha-amino-acid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: SMILES: O=C1OC(CC(=O)NC(C(O)CC(=O)NC(C(NC(C(NC(C(NC1C(O)C(=O)O)=O)CO)=O)CCCN)=O)C(O)C)CCCN(O)C=O)C NAME: Acidobactin B REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1C(O)=CC2=CC=3NC(N4C3N(C2=C1)C(C(=O)N[C@H](C(=O)N[C@@H](C(=O)N[C@H](C(=O)NCC(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@@H](C(=O)N[C@@H]5C(=O)OCC5)CCCN(O)C(=O)C)CCO)CCCNC(=O)N)CO)[C@@H](O)C(=O)O)CCO)CO)CC(=O)O)CC4)=O NAME: Azotobactin delta REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1N(O)CCCC1NC(=O)C(NC(=O)C(NC(=O)C(NC(=O)C(NC(=O)C(NC(=O)C(NC(=O)[C@H]2NC3=[N+](C=4C(=CC(O)=C(C4)O)C=C3NC(=O)CCC(N)C(=O)O)CC2)CC(=O)O)CCCCN)C(O)C)C(O)C(=O)O)C(O)C)C(O)C NAME: Isopyoverdin REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1N(O)CCC[C@@H]1NC(=O)[C@@H](NC(=O)[C@H](NC(=O)C(NC(=O)[C@@H](NC(=O)C(NC(=O)CCCCCCCCCCCCC)C(O)C(=O)O)CO)C(O)C(=O)O)[C@@H](O)C)CO NAME: Serobactin C REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: S(CC1N(O)C(C(NC(=O)CN)C(=O)O)CC1OC(=O)/C=N/N)CC(NC(=O)C)C(=O)O NAME: S56-P1 REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=NN(O)CCC[C@@H](NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@H](NC(=O)CNC(=O)C[C@H](O)CCCCCCCCCCC)[C@@H](O)C(=O)O)CO)[C@H](O)C)CCCN(O)N=O)CO)C(=O)O NAME: Megapolibactin F REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)C(O)C(NC(=O)CCCCCCCCC)C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)O)CCCN(O)C(=O)C)CO)CCCN(O)C(=O)C)CCC(=O)N)CO)CO NAME: Aquachelin J REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1NCCC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)O)CCCN(O)C(=O)C)CO)CCCN(O)C(=O)C)CO)NC(C(C1O)NC(=O)CCCCCCCCCCC)=O NAME: Marinobactin A REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1N(O)CCC[C@H]1NC(=O)[C@H](NC(=O)/C(/NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)[C@H](NC(=O)CCC/C=C\CCCCCC)[C@@H](O)C(=O)O)CO)CCC(=O)N)CO)CCCN(O)C(=O)C)=C/C)CO NAME: Loihichelin C REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1N(O)CCC[C@@H]1NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)[C@H](NC(=O)CNC(=O)[C@H](NC(=O)[C@@H](NC(=O)CC(O)CCCCCCCCC)[C@H](O)C(=O)O)CO)CO)CO)[C@@H](O)C(=O)O)[C@H](O)C)CO NAME: Potashchelin A REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1OC(C(C(=O)NC(C(=O)NC(CO)C(NC(C(NC(C(NC1CCCN(O)C(=O)C)=O)CCCNC(=O)N)=O)CCCN)=O)C(O)C(=O)O)C)C(NC(=O)CCCCCCCCC)CCCN(O)C(=O)C NAME: Variobactin B REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1N(O)CCC[C@H]1NC(=O)[C@H](NC(=O)/C(/NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)[C@H](NC(=O)CC(O)CCCCCCCCC)[C@@H](O)C(=O)O)CO)CCC(=O)N)CO)CCCN(O)C(=O)C)=C/C)CO NAME: Loihichelin B REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)[C@H](O)[C@@H](NC(=O)[C@@H](NC=O)CCCN(O)C=O)C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CC(C)C)CO NAME: Malleobactin F REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: [C@H](C(NC)=O)(NC([C@H](CCCC=1C=CC=CC1)[C@@H](N(O)C=O)C)=O)C(C)(C)C NAME: GI254023X REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)[C@H](O)[C@@H](NC(=O)[C@@H](NC=O)CCC/[N+](/[O-])=N/CCC[C@H](NC=O)C(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CCCN(O)C=O)CO)[C@@H](O)C(=O)O)C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CCCN(O)C=O)CO NAME: Malleobactin D REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1NCC[C@@H](C(=O)N[C@@H](C(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)O)CCCN(O)C(=O)C)CO)CCCN(O)C(=O)C)CO)NC([C@@H]([C@H]1O)NC(=O)CCCCCCC/C=C\CCCCCC)=O NAME: Marinobactin-D1 REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1C(O)=CC2=CC(NC(=O)CCC(=O)N)=C3N(C2=C1)C(C(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)NCC(=O)N[C@H](C(=O)N[C@@H](C(=O)N[C@@H]4C(=O)N(O)CCC4)CO)[C@H](O)C)[C@H](O)C(=O)O)C(C)C)CO)CCN3 NAME: Pseudomonas fluorescens BTP2 Pyoverdin REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)[C@H](O)[C@@H](NC(=O)[C@@H](NC=O)CCCN(O)C=O)C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CC=1C2=C(C=CC=C2)NC1)CO NAME: Malleobactin H REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1OC(CC(=O)NC(C(O)CC(=O)NC(C(NC(C(NC(C(NC1C(O)C(=O)O)=O)CO)=O)CCCNO)=O)C(O)C)CCCN(O)C=O)C NAME: Acidobactin A REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=NN(O)CCC[C@H]1NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)CCCCCCCCCCC)[C@@H](O)C(=O)O)CO)CO)CCCNC(=O)[C@@H](CCCN(O)N=O)NC(CNC([C@@H](NC1=O)CCC(=O)N)=O)=O NAME: Plantaribactin REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)[C@H](O)[C@H](NC(=O)[C@@H](NC(=O)CC(O)C(NC(=O)CCCC=CCCCC)CO)CO)C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CCCN(O)C=O)CCN NAME: Crochelin D REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=NN(O)CCC[C@H]1NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)CCCCCCCCCCC)[C@@H](O)C(=O)O)CO)CO)CCCNC(=O)[C@@H](CCCN(O)N=O)NC(CNC([C@@H](NC1=O)CCCCN)=O)=O NAME: Gladiobactin REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C1N(CCC[C@@H]1NC(=O)[C@H](NC(=O)[C@@H](NC(=O)C2NC(=NCC2)[C@H](NC(=O)[C@@H](N(O)C(=O)CNC(=O)CNC(=O)[C@H](NC(=O)[C@H](NC(=O)[C@H]3[N+]4=C(NCC3)C(NC(=O)CCC(=O)N)=CC=5C4=CC(O)=C(C5)O)C)CCCCN)CC(=O)N)CCC(=O)N)CO)C)C NAME: Pyoverdin Pf/3 ATCC 17400 REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)[C@H](O)[C@@H](NC(=O)[C@@H](NC=O)CCCN(O)C=O)C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CCCN(O)C=O)CO NAME: Malleobactin E REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
 * SMILES: O=C(O)[C@H](O)[C@H](NC(=O)[C@@H](NC(=O)CC(O)C(NC(=O)CCCCCCCCCCC)CO)CO)C(=O)N[C@H](C(=O)N[C@H](C(=O)NCCCCN)CCCN(O)C=O)CCN NAME: Crochelin B REASON: WRONGLY CLASSIFIED Contains N-hydroxy group in alpha position of amino acid backbone
False negatives: SMILES: CSCCCCC(N(O)O)C(O)=O NAME: N,N-dihydroxydihomomethionine REASON: MISSED No amino acid backbone found
 * SMILES: O=C(O)[C@@H](NO)CCCCSC NAME: N-hydroxy-L-dihomomethionine REASON: MISSED No amino acid backbone found
 * SMILES: N1([C@@H](CCCC1)C(=O)O)O NAME: N-hydroxy-L-pipecolic acid REASON: MISSED No amino acid backbone found
 * SMILES: CSCCCCCCCCC(NO)C(O)=O NAME: N-hydroxyhexahomomethionine REASON: MISSED No amino acid backbone found
 * SMILES: CSCCCCCCCCC(N(O)O)C(O)=O NAME: N,N-dihydroxyhexahomomethionine REASON: MISSED No amino acid backbone found
 * SMILES: ON(O)[C@@H](Cc1ccc(O)cc1)C(O)=O NAME: N,N-dihydroxy-L-tyrosine REASON: MISSED No amino acid backbone found
 * SMILES: CC[C@H](C)[C@H](N(O)O)C(O)=O NAME: N,N-dihydroxy-L-isoleucine REASON: MISSED No amino acid backbone found
 * SMILES: O=C(O)[C@@H](N(O)O)CCCCCCCSC NAME: N,N-dihydroxy-L-pentahomomethionine REASON: MISSED No amino acid backbone found
 * SMILES: CSCCCCCCC(N(O)O)C(O)=O NAME: N,N-dihydroxytetrahomomethionine REASON: MISSED No amino acid backbone found
 * SMILES: O=C(O)[C@@H](N(O)O)CCCCCCCCSC NAME: N,N-dihydroxy-L-hexahomomethionine REASON: MISSED No amino acid backbone found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:50760
  name: N-hydroxy-alpha-amino-acid
  definition: Any amino acid in which at least one hydrogen attached to the amino
    group is replaced by a hydroxy group.
  parents:
  - CHEBI:24662
  - CHEBI:24709
  xrefs:
  - KEGG:C05710
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: unterminated string literal (detected at line 10) (<string>, line 10)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []