Attempt 3 at sesterterpenoid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Error: Error executing is_sesterterpenoid('CO[C@@H]1OC(=O)C2=CC[C@H]3[C@]4(C)CC[C@H]5C(C)(C)CCC[C@]5(C)[C@H]4C[C@@H](OC(C)=O)[C@]3(C)[C@@H]12'):
 Python argument types in
    Mol.HasSubstructMatch(Mol, NoneType)
did not match C++ signature:
    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle query, RDKit::SubstructMatchParameters params=True)
    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)
    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)
    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)
Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: NONE
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:26660
  name: sesterterpenoid
  definition: Any terpenoid derived from a sesterterpene. The term includes compounds
    in which the C25 skeleton of the parent sesterterpene has been rearranged or modified
    by the removal of one or more skeletal atoms (generally methyl groups). Sometimes
    sesterterpenoids are erroneously referred to as sesterpenoids.
  parents:
  - CHEBI:26873
  xrefs:
  - LIPID_MAPS_class:LMPR0105
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: unterminated string literal (detected at line 15) (<string>, line 15)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []