Reverting to best solution for B vitamin, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:75769
  name: B vitamin
  definition: Any member of the group of eight water-soluble vitamins originally thought
    to be a single compound (vitamin B) that play important roles in cell metabolism.
    The group comprises of vitamin B1, B2, B3, B5, B6, B7, B9, and B12 (Around 20
    other compounds were once thought to be B vitamins but are no longer classified
    as such).
  parents:
  - CHEBI:35352
  - CHEBI:36963
  xrefs:
  - MetaCyc:B-vitamins
  - PMID:22743781
  - PMID:23093174
  - PMID:23238962
  - PMID:23449527
  - PMID:23462586
  - PMID:23690582
  - Wikipedia:B_vitamin
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 46
  log_lines_of_code: 3.828641396489095
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdMolDescriptors
  - from rdkit.Chem import AllChem
  imports_count: 3
  methods_called:
  - CalcExactMolWt
  - CalcNumRings
  - MolFromSmarts
  - HasSubstructMatch
  - MolFromSmiles
  methods_called_count: 5
  smarts_strings:
  - '[n;X3]1[c;H0][n;H0][c;H1]2[c;H1]([n;X2][c;H1]1[n;X3][c;H0]2[C;X4][C;X4]=[O;X1])[C;X4][C;X4]=[O;X1]'
  - '[c;H1]1[c;H1][c;H1][c;H1]([C;X3](=[O;X1])[N;X3][C;X4]([C;H2][C;H2][C;X3](=[O;X1])[O;H1])[C;X3](=[O;X1])[O;H1])[c;H1][c;H1]1'
  - '[C;H3][C;H1]([C;H3])([C;H3])[C;H2]([C;X3](=[O;X1])[N;X3][C;X4][C;X4][C;X3](=[O;X1])[O;H1])[O;H1]'
  - '[C;H3][c;H1]1[c;H0][c;H0][c;H1]([C;X3](=[O;X1])[O;H1])[c;H0][c;H0][n;X2]1[C;X4][O;H1]'
  - c1[c;H1][c;H1][c;H1][c;H1][c;H1]1[C;X3](=[O;X1])[N;X3][C;X4]1[C;X4][S;X2][C;X4]([C;H3])([C;H1])[N;X3][C;X3]1=[O;X1]
  - '[Co-3]1234[N;X4]5[C;X4]6=[N;+]1[C;X4](=[C;X3][C;X4]1=[N;+]2[C;X4](=[C;X3][C;X4]2=[N;+]3[C;X4]([C;H3])([C;H3])[C;X4]([C;H3])([C;H3])[C;H3][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]3([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]4([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]5([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]1([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]2([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;H3][C;X3](=[O;X1])[N;X3])[C;X4]6=[C;X3][C;X4]5=[N;+]1[C;X4](=[C;X3][C;X4]5=[N;+]6[C;X4]([C;H3])([C;H3])[C;X4]([C;H3])([C;H3])[C;H3][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]4([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;X4]2([C;H3])[C;X4][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;H3][C;X3](=[O;X1])[N;X3])[C;X4]4([C;H3])([C;H3])[C;X4][C;H3][C;X3](=[O;X1])[N;X3][C;X4]([C;H3])[C;H3][C;X3](=[O;X1])[N;X3])[C;H3]([C;H3])[C;H3]'
  - c1[c;H1][c;H1][c;H1][n;X2][c;H1]1[C;X3](=[O;X1])[O;H1]
  - '[C;H3][c;H1][c;H0][n;+]([C;H2][c;H1][s;H0]([C;H2][C;H2][O;H1][P;X4]=[O;X1])([C;H3])[C;H3])[c;H1][n;H1][c;H1]([C;H3])[C;H3]=[N;X2+]'
  smarts_strings_count: 8
  defs:
  - 'is_B_vitamin(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - True, "Molecule matches a known B vitamin substructure"
  - False, "Molecular weight too high for B vitamin"
  - False, "Too many rings for B vitamin"
  - False, "Molecule does not match any known B vitamin substructure"
  returns_count: 5
  complexity: 3.5657282792978195
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_B_vitamin('CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O'):\n\
  \ Python argument types in\n    Mol.HasSubstructMatch(Mol, NoneType)\ndid not match\
  \ C++ signature:\n    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle query,\
  \ RDKit::SubstructMatchParameters params=True)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False,\
  \ bool useQueryQueryMatches=False)\n    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol\
  \ query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0