Attempt 1 at vitamin D, f1=0.0
(currently fails to compile, but committing anyway

Here is a Python program to classify chemical entities of the class vitamin D:
# INFORMATION:

---
chemical_class:
  id: CHEBI:27300
  name: vitamin D
  definition: Any member of a group of fat-soluble hydroxy seco-steroids that exhibit
    biological activity against vitamin D deficiency. Vitamin D  can be obtained from
    sun exposure, food and supplements and is biologically inactive and converted
    into the biologically active calcitriol via double hydroxylation in the body.
  parents:
  - CHEBI:36853
  xrefs:
  - MetaCyc:Vitamin-D
  - Wikipedia:Vitamin_D
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 32
  log_lines_of_code: 3.4657359027997265
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - GetAtoms
  - GetIsAromatic
  - MolFromSmiles
  - HasSubstructMatch
  - MolFromSmarts
  - GetAtomicNum
  methods_called_count: 6
  smarts_strings:
  - '"[C@@]12[C@H](C[C@H](C=C)C1)C[C@@H](O)[C@]2(O'
  - '"[C@@]12[C@@]([C@H]([C@@H]3[C@H]([C@@H](C[C@@H]4[C@@]3(CC[C@@]4(O)[C@@H](O)[C@H]3[C@@]4([C@]2(C[C@@H](CC1)C)(CC[C@]34C)C)C)C)C)C)CC=C'
  smarts_strings_count: 2
  defs:
  - 'is_vitamin_D(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No cholesterol-like steroid backbone found"
  - False, "Missing characteristic vitamin D side chain"
  - False, "No hydroxyl groups present"
  - True, "Contains cholesterol-like steroid backbone with characteristic vitamin
    D side chain and one hydroxyl group"
  - True, "Contains cholesterol-like steroid backbone with characteristic vitamin
    D side chain and two hydroxyl groups (calcitriol)"
  - True, f"Contains cholesterol-like steroid backbone with characteristic vitamin
    D side chain and {hydroxy_count} hydroxyl groups"
  - False, "Unable to classify molecule"
  returns_count: 8
  complexity: 4.093147180559945
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: invalid syntax (<string>, line 31)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []