Reverting to best solution for nitrohydrocarbon, f1=0.5 iteration 2
---
chemical_class:
  id: CHEBI:51129
  name: nitrohydrocarbon
  definition: A C-nitro compound that is a hydrocarbon in which one or more of the
    hydrogens has been replaced by nitro groups.
  parents:
  - CHEBI:35716
  xrefs:
  - PMCID:PMC3909368
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 71
  log_lines_of_code: 4.2626798770413155
  max_indent: 5
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import EditableMol
  imports_count: 3
  methods_called:
  - GetEndAtomIdx
  - GetNeighbors
  - RemoveBond
  - GetBondWithIdx
  - GetSymbol
  - MolFromSmiles
  - MolFromSmarts
  - GetAtoms
  - append
  - GetMol
  - RemoveAtom
  - Mol
  - BeginBatchEdit
  - CommitBatchEdit
  - GetIdx
  - GetSubstructMatches
  - GetAtomicNum
  - GetTotalDegree
  - HasSubstructMatch
  - GetBeginAtomIdx
  - GetAtomWithIdx
  methods_called_count: 21
  smarts_strings:
  - '[N+](=O)[O-]'
  smarts_strings_count: 1
  defs:
  - 'is_nitrohydrocarbon(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - 'False, f"Contains invalid atom: {atom.GetSymbol()}"'
  - False, "No nitro group found"
  - False, "No nitro group found"
  - False, "Could not find nitrogen in -NO2 group"
  - False, "Could not remove bond from molecule copy"
  - False, "Could not remove atom from molecule copy"
  - False, "After removing nitro groups, non-hydrocarbon fragment remains"
  - False, "Nitrogen is not part of -NO2 group (does not have 3 bonds)"
  - False, "Nitrogen is not part of -NO2 group (does not have 2 oxygen neighbors)"
  - True, "Molecule is a nitrohydrocarbon"
  returns_count: 11
  complexity: 8.452535975408264
message: "\nError: Error executing is_nitrohydrocarbon('[O-][N+](=O)c1ccc-2c(c1)-c1ccc([N+]([O-])=O)c3cccc-2c13'):\n\
  \ 'Mol' object has no attribute 'RemoveBond'\nAttempt failed: F1 score of 0 is too\
  \ low.\nOutcomes:\n------\n\nTrue positives: NONE\nFalse positives: NONE\nFalse\
  \ negatives: NONE\n------\n\nIn your reasoning step, analyze the previous program\
  \ and the above outcomes, hypothesizing about what went wrong, and how to improve.\n"
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: CCN1N=C(N=N1)C2=CC=CC=C2NC(=O)C3=CC=C(C=C3)N4C=NN=N4
  name: N-[2-(2-ethyl-5-tetrazolyl)phenyl]-4-(1-tetrazolyl)benzamide
  reason: No nitro group found
- smiles: CCS(=O)(=O)N1CC2(C1)[C@@H]([C@@H](N2C(=O)C3CCCC3)CO)C4=CC=C(C=C4)C=CC
  name: LSM-38092
  reason: 'Contains invalid atom: S'
- smiles: O=C/1N/C(/C(=O)N\C1=C\C2=CC=CC=C2)=C\C=3N=CNC3C(C=C)(C)C
  name: DeltaPLH
  reason: No nitro group found
- smiles: C1CCN(CC1)C(=O)C[C@H]2C[C@@H]3[C@H]([C@@H](O2)CO)OC4=C3C=C(C=C4)NC(=O)CC5CC5
  name: N-[(1S,3R,4aS,9aR)-1-(hydroxymethyl)-3-[2-oxo-2-(1-piperidinyl)ethyl]-3,4,4a,9a-tetrahydro-1H-pyrano[3,4-b]benzofuran-6-yl]-2-cyclopropylacetamide
  reason: No nitro group found
- smiles: C[C@H]1C[C@@]2(OC(=O)c3ccccc3)[C@H]([C@H]1OC(C)=O)[C@@H](O)\C(C)=C/C[C@H]1[C@@H](\C=C(C)\C2=O)C1(C)C
  name: (-)-(6Z,12E,2S,3S,4R,5R,9S,11S,15R)-3-acetoxy-15-benzoyloxylathyra-6,12-dien-5-ol-14-one
  reason: No nitro group found
- smiles: O=C1C(O)=CC=2O[C@]3([C@H](O)C[C@@H]4[C@](OC=5C=C(O)C(C=C(C5C4)C)=O)(CC=CC(C[C@H]3CC2C(=C1)C)(C)C)C)C
  name: Eupenifeldin
  reason: No nitro group found
- smiles: O1[C@@H](O[C@@H]2[C@@H](OC[C@H]3O[C@@H](O[C@H]4[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]4CO)O[C@H]5[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]5CO[C@@H]6O[C@H]([C@@H](O)[C@@H](O)[C@@H]6O)C)O)[C@@H](O)[C@@H](O[C@H]7O[C@@H]([C@@H](O)[C@H](O)[C@@H]7O[C@@H]8O[C@@H]([C@@H](O[C@@H]9O[C@@H]([C@H](O)[C@H](O)[C@H]9NC(=O)C)CO)[C@H](O)[C@H]8NC(=O)C)CO)CO)[C@@H]3O)O[C@@H]([C@@H](O)[C@@H]2O)CO)[C@H](NC(=O)C)[C@@H](O[C@@H]%10O[C@H]([C@@H](O)[C@@H](O)[C@@H]%10O)C)[C@H](O[C@@H]%11O[C@@H]([C@H](O)[C@H](O)[C@H]%11NC(=O)C)CO)[C@H]1CO
  name: N-[(3R,4R,5S,6R)-5-[(2S,3R,4R,5S,6R)-3-Acetamido-5-[(2S,3S,4S,5R,6R)-4-[(2R,3S,4S,5S,6R)-3-[(2S,3R,4R,5S,6R)-3-acetamido-5-[(2S,3R,4R,5R,6R)-3-acetamido-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5S,6R)-3-[(2S,3R,4R,5S,6R)-3-acetamido-5-[(2S,3R,4R,5R,6R)-3-acetamido-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-(hydroxymethyl)-4-[(2R,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]-3,5-dihydroxyoxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-[[(2R,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxymethyl]oxan-3-yl]acetamide
  reason: No nitro group found
- smiles: CN1C[C@@H]2C[C@H](Cn3c2cccc3=O)[C@H]1CC=C
  name: Tinctorine
  reason: No nitro group found
- smiles: CCC1=C2COC(CC2=C3C(=C(OC3=N1)C(=O)C4=CC=CC=C4)N)(C)C
  name: LSM-4563
  reason: No nitro group found
- smiles: CN1CCN(CC1)C(=O)C[C@@H]2CC[C@H]3[C@H](O2)COC[C@@H](CN3C(=O)NC4=CC5=C(C=C4)OCO5)O
  name: (3R,6aS,8S,10aS)-N-(1,3-benzodioxol-5-yl)-3-hydroxy-8-[2-(4-methyl-1-piperazinyl)-2-oxoethyl]-3,4,6,6a,8,9,10,10a-octahydro-2H-pyrano[2,3-c][1,5]oxazocine-1-carboxamide
  reason: No nitro group found
sample_false_negatives:
- smiles: '[O-][N+](=O)c1cccc2C=CC3OC3c12'
  name: 1-Nitronaphthalene-7,8-oxide
  reason: After removing nitro groups, non-hydrocarbon fragment remains
- smiles: C1=CC(=CC(=C1)N2C(=O)C3=CC(=CC4=CC(=CC(=C43)C2=O)[N+](=O)[O-])[N+](=O)[O-])C(=O)O
  name: 3-(5,8-dinitro-1,3-dioxo-2-benzo[de]isoquinolinyl)benzoic acid
  reason: After removing nitro groups, non-hydrocarbon fragment remains
- smiles: C1=CC2=C(C=CC3=C2C(=C1)C(=O)N(C3=O)CCC(=O)O)[N+](=O)[O-]
  name: 3-(6-nitro-1,3-dioxo-2-benzo[de]isoquinolinyl)propanoic acid
  reason: After removing nitro groups, non-hydrocarbon fragment remains
- smiles: '[O-][N+](=O)c1cccc2C3OC3C=Cc12'
  name: 1-Nitronaphthalene-5,6-oxide
  reason: After removing nitro groups, non-hydrocarbon fragment remains
- smiles: O\N=C1\C(=O)Nc2c1cc(c1CCCCc21)N(=O)=O
  name: NS-102
  reason: After removing nitro groups, non-hydrocarbon fragment remains
- smiles: C1=CC=C2C(=C1)C=CC(=C2O)NN=C3C4=C(C=C(C=C4)[N+](=O)[O-])C(=CC3=O)S(=O)(=O)O
  name: 4-[(1-hydroxy-2-naphthalenyl)hydrazinylidene]-7-nitro-3-oxo-1-naphthalenesulfonic
    acid
  reason: 'Contains invalid atom: S'
attempt: 2
success: true
best: true
error: ''
stdout: null
num_true_positives: 20
num_false_positives: 34
num_true_negatives: 142240
num_false_negatives: 6
num_negatives: null
precision: 0.37037037037037035
recall: 0.7692307692307693
f1: 0.5
accuracy: 0.9997189037245257
negative_predictive_value: 0.9999578195520437