Reverting to best solution for prostaglandin, f1=0.4019138755980861 iteration 2
---
chemical_class:
  id: CHEBI:26333
  name: prostaglandin
  definition: Naturally occurring compounds derived from the parent C20 acid, prostanoic
    acid.
  parents:
  - CHEBI:26347
  xrefs:
  - CAS:11000-26-3
  - LIPID_MAPS_class:LMFA0301
  all_positive_examples: []
config: null
message: '

  Error: ''Mol'' object has no attribute ''GetSubstructureMatches''

  Attempt failed: F1 score of 0 is too low.

  Outcomes:

  ------

  True positives: NONE

  False positives: NONE

  False negatives: NONE

  ------

  In your reasoning step, analyze the previous program and the above outcomes, hypothesizing
  about what went wrong, and how to improve.

  '
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: O=C(NC1=C(C(=O)CCNC(=O)CCC(NC(=O)C)C(=O)OCC(O)CO)C=CC=C1)C(C=C)(C)C
  name: Citrinamide B
  reason: Number of carbons is 25, which is not in the expected range for prostaglandins
- smiles: S(CC[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CC=1C=2C(NC1)=CC=CC2)CC(O)=O)C(O)=O)C
  name: Trp-Asp-Met
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
- smiles: C(CC)(O)(C)C
  name: 2-methylbutan-2-ol
  reason: Number of carbons is 5, which is not in the expected range for prostaglandins
- smiles: O1[C@@H]([C@H](O)[C@@H](O)[C@@H](NC(=O)C)C1O)CO
  name: N-Acetyl-D-Gulosamine
  reason: Number of carbons is 8, which is not in the expected range for prostaglandins
- smiles: '[C@@]12([C@]3([C@](CC[C@@]1([C@@]4(C(C[C@H](CC4)OS([O-])(=O)=O)=CC2)C)[H])([C@](CC3)([C@H](C)CC[C@@H](C(C)C)O)[H])C)[H])[H]'
  name: (24S)-hydroxycholesterol 3-sulfate(1-)
  reason: Number of carbons is 27, which is not in the expected range for prostaglandins
- smiles: '[H][C@@]12CCC3=CC(=O)CC[C@]3(C)[C@@]1([H])CC[C@@]1(C)[C@@]2([H])CC[C@]1(O)C(C)O'
  name: 17,20-dihydroxypregn-4-en-3-one
  reason: Molecule has 4 rings, expected 1 cyclopentane ring
- smiles: O=C1N2[C@H](C(=O)NCC(=O)N[C@H](C(=O)NCC(N[C@H](C(NCC(N[C@H]1CC=3C4=C(C=CC=C4)NC3)=O)=O)C(O)C5=CC(=C(O)C=C5)CC=C(C)C)=O)C(C)C)CCC2
  name: WIN 66306
  reason: Number of carbons is 41, which is not in the expected range for prostaglandins
- smiles: CCCCCCCCCCc1c(C)c(O)c(OC)c(OC)c1O
  name: 6-decylubiquinol
  reason: Ring size is 6, expected 5
- smiles: COC1=CC(=C(C=C1Br)OC)S(=O)(=O)N2CCCCCC2
  name: 1-(4-bromo-2,5-dimethoxyphenyl)sulfonylazepane
  reason: Number of carbons is 14, which is not in the expected range for prostaglandins
- smiles: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)C(=O)NC3=CC=C(C=C3)F)[C@@H](C)CO
  name: 1-[[(2S,3R)-8-(dimethylamino)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-2-yl]methyl]-3-(4-fluorophenyl)-1-methylurea
  reason: Number of carbons is 25, which is not in the expected range for prostaglandins
sample_false_negatives:
- smiles: CCCCC[C@H](O)\C=C\[C@H]1[C@H]2C[C@H](OO2)[C@@H]1C\C=C/CCCC(O)=O
  name: prostaglandin H2
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
- smiles: CCCCC[C@H](O)\C=C\[C@H]1[C@H](O)C[C@H](O)[C@@H]1C\C=C/CCCCN(C)C
  name: prostaglandin F2alpha dimethylamine
  reason: No carboxylic acid group found
- smiles: '[C@@H]1(/C=C/[C@@H](O)CCCCC)[C@H]([C@H](C[C@H]1O)O)C/C=C\CCCC(=O)OCC(CO)O'
  name: prostaglandin F2alpha 1-glyceryl ester
  reason: No carboxylic acid group found
- smiles: C(\[C@H]1[C@@H](CC([C@@H]1C/C=C\CCCC(=O)OCC(CO)O)=O)O)=C/[C@H](CCCCC)O
  name: prostaglandin E2 1-glyceryl ester
  reason: No carboxylic acid group found
- smiles: '[C@@H]1([C@@H]([C@@H]2[C@H](C1)O[C@@H](C2)CCCCC(O)=O)/C=C/[C@H](CCCCC)O)O'
  name: 6alpha-Prostaglandin I1
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
- smiles: O[C@@H](CCc1ccccc1)\C=C\[C@H]1[C@H](O)C[C@H](O)[C@@H]1C\C=C/CCCC(O)=O
  name: 17-phenyl-trinor-prostaglandin F2alpha
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
- smiles: CCCCC[C@H](O)\C=C\[C@H]1[C@H](O)C[C@H](O)[C@@H]1C\C=C/CCCC(=O)NCCO
  name: prostaglandin F2alpha 1-ethanolamide
  reason: No carboxylic acid group found
- smiles: C1[C@H]2[C@@H]([C@H]([C@@H]1OO2)/C=C/[C@H](CCCC(C)O)O)CCCCCCC(O)=O
  name: 19-hydroxyprostaglandin H1
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
- smiles: O[C@H](CC[C@H]1[C@H](O)C[C@H](O)[C@@H]1C\C=C/CCCC(O)=O)CCc1ccccc1
  name: latanoprost free acid
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
- smiles: CC(O)CCC[C@H](O)\C=C\[C@H]1[C@H]2C[C@H](OO2)[C@@H]1C\C=C/CCCC(O)=O
  name: 19-hydroxyprostaglandin H2
  reason: Molecule has 2 rings, expected 1 cyclopentane ring
attempt: 2
success: true
best: true
error: ''
stdout: null
num_true_positives: 42
num_false_positives: 100
num_true_negatives: 45030
num_false_negatives: 25
num_negatives: null
precision: 0.29577464788732394
recall: 0.6268656716417911
f1: 0.4019138755980861
accuracy: 0.997234329712149
negative_predictive_value: 0.9994451226278992