Attempt 1 at oligosaccharide, f1=0.0
(currently fails to compile, but committing anyway

# INFORMATION:

---
chemical_class:
  id: CHEBI:50699
  name: oligosaccharide
  definition: A compound in which monosaccharide units are joined by glycosidic linkages.
    The term is commonly used to refer to a defined structure as opposed to a polymer
    of unspecified length or a homologous mixture. When the linkages are of other
    types the compounds are regarded as oligosaccharide analogues.
  parents:
  - CHEBI:16646
  - CHEBI:167559
  xrefs:
  - KEGG:C00930
  all_positive_examples: []
config: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: "Python argument types in\n    Mol.GetSubstructMatches(Mol, NoneType)\ndid\
  \ not match C++ signature:\n    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle\
  \ query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool uniquify=True, bool useChirality=False, bool\
  \ useQueryQueryMatches=False, unsigned int maxMatches=1000)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False,\
  \ unsigned int maxMatches=1000)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0