Attempt 1 at carbonate ester, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:46722
  name: carbonate ester
  definition: Any carbonate that is carbonic acid in which the hydrogens have been
    replaced by organyl groups.
  parents:
  - CHEBI:23016
  - CHEBI:33308
  xrefs:
  - Wikipedia:Carbonate_ester
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 2
  log_lines_of_code: 0.6931471805599453
  max_indent: 1
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_carbonate_ester(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES"
  - False, "No carbonate group (O-C(=O)-O) found"
  returns_count: 2
  complexity: 0.9386294361119891
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []