Attempt 2 at aromatic primary alcohol, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.0026979844469131884 is too low.
Outcomes:
------

True positives: SMILES: OCc1cc(O)c2C(=O)c3c(O)cccc3C(=O)c2c1 NAME: Aloe emodin REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: CCCCCC1=C(CO)C(O)=CC=C1 NAME: 2-hydroxymethyl-3-pentylphenol REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: [H]C(=CC(=O)C(O)=O)c1ccc(CO)cc1O NAME: 2-hydroxy-4-hydroxymethylbenzylidenepyruvic acid REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C=1(C=C(C(=CC1)O)CO)O NAME: gentisyl alcohol REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C1=CC=C(C(=C1/C=C/C=C/[C@H]([C@H](C)O)O)CO)O NAME: dihydropyriculariol REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: COC1=CC2=NC3=C(OC2=C(OC)C1=O)C=CC(CO)=C3 NAME: michigazone REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: OCC=1OC(C(O)=O)=CC1 NAME: 5-hydroxymethyl-2-furoic acid REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C=1C2=C(C=CC1)SC(=C2)C(=O)N[C@@H](CC(C)C)C(=O)N3CCN(CC3)C(=O)[C@H](CO)NS(C=4C=CC(=CC4Cl)Cl)(=O)=O NAME: GSK1016790A REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: CCCCC\C=C\C=C\C=C\C1=C(CO)C(O)=CC=C1O NAME: virensol A REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: COC(=O)[C@H]1[C@H](O)C=Cc2oc3cc(CO)cc(O)c3c(=O)c12 NAME: (7R,8R)-AGI-B4 REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O=C1C=C2[C@@]3([C@]([C@]4([C@@](CC3)(CC[C@](C4)(C(=O)O)C)C)[H])(CC[C@]2(C=5C1=C(C(OC)=C(O)C5)CO)C)C)C NAME: triptohypol A REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: Nc1nc(=O)[nH]cc1CO NAME: 5-(hydroxymethyl)cytosine REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: CCCCC\C=C\C=C\C=C\C1=C(CO)C(O)=CC=C1 NAME: virensol B REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: CCCC1=C(C(O)=O)C(CO)=CO1 NAME: 4-(hydroxymethyl)-2-propylfuran-3-carboxylic acid REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C1(=NC(C=2N(C=3C1=CC(=CC3)Cl)C(=NC2)CO)O)C=4C=CC=CC4F NAME: 1',4-dihydroxymidazolam REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O1[C@@H]([C@@H](O)[C@H](O)[C@@H](OC(=O)C2=CC=CC=C2)[C@@H]1OC=3C(=CC=CC3)CO)CO NAME: tremuloidin REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O=C1NC=2C(N(C3CC3)C=4N=CC=CC41)=NC=CC2CO NAME: 12-hydroxynevirapine REASON: CORRECT Contains an aromatic ring with a primary alcoholic group attached
False positives: SMILES: C[C@@H]1CCCCO[C@@H]([C@@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)C3CCCCC3)[C@H](C)CO)C)CN(C)C(=O)C4=CC=NC=C4 NAME: N-[[(3R,9S,10R)-16-[[cyclohexyl(oxo)methyl]amino]-12-[(2R)-1-hydroxypropan-2-yl]-3,10-dimethyl-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-9-yl]methyl]-N-methyl-4-pyridinecarboxamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CCCCO[C@@H]([C@@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)NC3=C(ON=C3C)C)[C@H](C)CO)C)CN(C)CC4=CC=C(C=C4)OC NAME: 1-(3,5-dimethyl-4-isoxazolyl)-3-[(3R,9S,10R)-12-[(2R)-1-hydroxypropan-2-yl]-9-[[(4-methoxyphenyl)methyl-methylamino]methyl]-3,10-dimethyl-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-16-yl]urea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@H]1CN(C(=O)C2=C(C(=CC=C2)NC(=O)C3CCOCC3)O[C@H]1CN(C)CC4=CC=NC=C4)[C@H](C)CO NAME: N-[(2R,3S)-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-2-[[methyl(pyridin-4-ylmethyl)amino]methyl]-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-10-yl]-4-oxanecarboxamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CCCCO[C@H]([C@@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)NC(C)C)[C@H](C)CO)C)CN(C)CC3=CC=CC=C3 NAME: 1-[(3R,9R,10R)-12-[(2R)-1-hydroxypropan-2-yl]-3,10-dimethyl-9-[[methyl-(phenylmethyl)amino]methyl]-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-16-yl]-3-propan-2-ylurea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O(C1C(O)C(O)C(OC1OC=2C=C3OC(C4=CC=C(OC5OC(C(O)C(O)C5O)C(O)=O)C=C4)=CC(=O)C3=C(O)C2)COC(=O)C)C6OCC(O)(C6O)CO NAME: 6-{4-[7-({6-[(acetyloxy)methyl]-3-{[3,4-dihydroxy-4-(hydroxymethyl)oxolan-2-yl]oxy}-4,5-dihydroxyoxan-2-yl}oxy)-5-hydroxy-4-oxo-4H-chromen-2-yl]phenoxy}-3,4,5-trihydroxyoxane-2-carboxylic acid REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)CC3CCCCC3)[C@H](C)CO NAME: (2S,3R)-2-[[cyclohexylmethyl(methyl)amino]methyl]-8-(dimethylamino)-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-3,4-dihydro-2H-1,5-benzoxazocin-6-one REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O=C1NC(=NC=2C=C3C([C@@H](N(C4=CC=C(C=C4)C(=O)N[C@@H](CCC(=O)N[C@H](CCC(O)=O)C(O)=O)C(O)=O)CC#C)CC3)=CC21)CO NAME: BGC 945 REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C(=CC=C2)NC(=O)C3=CC=NC=C3)O[C@H]1CN(C)CC4CC4)[C@@H](C)CO NAME: N-[(2R,3R)-2-[[cyclopropylmethyl(methyl)amino]methyl]-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-10-yl]-4-pyridinecarboxamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: CCNC(=O)[C@H]1[C@@H]([C@H]2CN3C(=CC=C(C3=O)C=CC)[C@@H]1N2CC4=CC(=CC=C4)Cl)CO NAME: LSM-14602 REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H](CN([C@@H](C)CO)C(=O)C1=CC=CC=C1)[C@H](CN(C)CC2=CC3=C(C=C2)OCO3)OC NAME: N-[(2S,3R)-4-[1,3-benzodioxol-5-ylmethyl(methyl)amino]-3-methoxy-2-methylbutyl]-N-[(2S)-1-hydroxypropan-2-yl]benzamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@H]1CN(C(=O)C2=C(C(=CC=C2)NS(=O)(=O)C)O[C@@H]1CN(C)C(=O)NC3=CC=CC4=CC=CC=C43)[C@@H](C)CO NAME: 1-[[(2S,3S)-5-[(2S)-1-hydroxypropan-2-yl]-10-(methanesulfonamido)-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-2-yl]methyl]-1-methyl-3-(1-naphthalenyl)urea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@H]1CN(C(=O)C2=CC=CC=C2C3=CC=CC=C3CO[C@H]1CN(C)C(=O)[C@@H](C)C4=CC=CC=C4)[C@H](C)CO NAME: LSM-11484 REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: COC1=CC=C(C=C1)NC(=O)N[C@H]2CC[C@@H](O[C@H]2CO)CCNC(=O)C3=CC(=CC(=C3)Cl)Cl NAME: 3,5-dichloro-N-[2-[(2R,5S,6R)-6-(hydroxymethyl)-5-[[(4-methoxyanilino)-oxomethyl]amino]-2-oxanyl]ethyl]benzamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O=C1OC(=CC(=C1C=NCCO)O)[C@]2([C@H]3[C@@H](C=C[C@@H]2C)CCC[C@@H]3C)C NAME: Solanapyrone K REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@H]1CN(C(=O)C2=C(C=CC(=C2)NC(=O)CCCCCC(=O)NC3=CC=CC=C3N)O[C@@H]1CN(C)CC4=CC5=C(C=C4)OCO5)[C@H](C)CO NAME: N'-(2-aminophenyl)-N-[(2S,3S)-2-[[1,3-benzodioxol-5-ylmethyl(methyl)amino]methyl]-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-8-yl]heptanediamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C(=CC=C2)NC(=O)NC(C)C)O[C@@H]1CN(C)S(=O)(=O)C3=CC=C(C=C3)F)[C@H](C)CO NAME: 1-[(2S,3R)-2-[[(4-fluorophenyl)sulfonyl-methylamino]methyl]-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-10-yl]-3-propan-2-ylurea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CCCCO[C@H]([C@@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)C3CCCCC3)[C@H](C)CO)C)CN(C)C(=O)NC4=CC=CC=C4 NAME: N-[(3R,9R,10R)-9-[[[anilino(oxo)methyl]-methylamino]methyl]-12-[(2R)-1-hydroxypropan-2-yl]-3,10-dimethyl-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-16-yl]cyclohexanecarboxamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CCCCO[C@@H]([C@@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)NC3=CC=CC4=CC=CC=C43)[C@H](C)CO)C)CN(C)C NAME: 1-[(3R,9S,10R)-9-[(dimethylamino)methyl]-12-[(2R)-1-hydroxypropan-2-yl]-3,10-dimethyl-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-16-yl]-3-(1-naphthalenyl)urea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CCCCO[C@H]([C@@H](CN(C(=O)C2=C(O1)C=CC(=C2)NS(=O)(=O)C3=CC=C(C=C3)Cl)[C@@H](C)CO)C)CN(C)C(=O)CCC(F)(F)F NAME: N-[[(3R,9R,10R)-16-[(4-chlorophenyl)sulfonylamino]-12-[(2S)-1-hydroxypropan-2-yl]-3,10-dimethyl-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-9-yl]methyl]-4,4,4-trifluoro-N-methylbutanamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@H]1CN(C(=O)C2=C(N=CC(=C2)C#CC3=CC=CC=C3OC)O[C@@H]1CN(C)C(=O)C4=CC5=C(C=C4)OCO5)[C@@H](C)CO NAME: N-[[(2S,3S)-5-[(2S)-1-hydroxypropan-2-yl]-8-[2-(2-methoxyphenyl)ethynyl]-3-methyl-6-oxo-3,4-dihydro-2H-pyrido[2,3-b][1,5]oxazocin-2-yl]methyl]-N-methyl-1,3-benzodioxole-5-carboxamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: O(C1C(C2C(C3C(C4(C(C5C(CC4)(CCC(C5(O)C)C)C(O)=O)=CC3)C)(CC2)C)(CC1)C)(CO)C)C(=O)/C=C/C6=CC=C(O)C=C6 NAME: 3-trans-p-Coumaroylrotundic acid REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@H]1CN(C(=O)C2=C(C=CC(=C2)NC(=O)NC3=CC=CC=C3)O[C@H]1CN(C)CC4=CC=CC=C4)[C@@H](C)CO NAME: 1-[(2R,3S)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-2-[[methyl-(phenylmethyl)amino]methyl]-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-8-yl]-3-phenylurea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)NC(=O)NC(C)C)O[C@H]1CN(C)C)[C@@H](C)CO NAME: 1-[(2R,3R)-2-[(dimethylamino)methyl]-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-8-yl]-3-propan-2-ylurea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C1C[C@H]([C@@H](O[C@H]1CCNS(=O)(=O)CC2=CC=CC=C2)CO)NC(=O)C3=NC=CN=C3 NAME: N-[(2R,3R,6R)-2-(hydroxymethyl)-6-[2-[(phenylmethyl)sulfonylamino]ethyl]-3-oxanyl]-2-pyrazinecarboxamide REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)NC(=O)NC3=C(ON=C3C)C)O[C@@H]1CN(C)CC4CCCCC4)[C@H](C)CO NAME: 1-[(2S,3R)-2-[[cyclohexylmethyl(methyl)amino]methyl]-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-8-yl]-3-(3,5-dimethyl-4-isoxazolyl)urea REASON: WRONGLY CLASSIFIED Contains an aromatic ring with a primary alcoholic group attached
False negatives: SMILES: CC1=CC=C(CO)C=C1C NAME: 3,4-dimethylbenzyl alcohol REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: C(N1N=C(C2=C1C=CC=C2)C=3OC(=CC3)CO)C=4C=CC=CC4 NAME: lificiguat REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: C1(=NCC=2N(C=3C1=CC(=CC3)Cl)C(=NC2)CO)C=4C=CC=CC4F NAME: 1-hydroxymidazolam REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: OCc1ccc(C=O)n1CCCCCC(O)=O NAME: 1-(5-carboxypentyl)pyrraline REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: CCCCn1c(CO)ccc1C=O NAME: 1-butylpyrraline REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: OCC1=NC=CC=N1 NAME: 2-pyrimidinemethanol REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: CCCn1c(CO)ccc1C=O NAME: 1-propylpyrraline REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: C1=CC(=CN=C1)CO NAME: 3-pyridinemethanol REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: Cc1ncc(CO)c(N)n1 NAME: 4-amino-5-hydroxymethyl-2-methylpyrimidine REASON: MISSED Primary alcoholic group not attached to an aromatic ring
 * SMILES: OC[C@H]1O[C@@H](Oc2ccccc2CO)[C@H](O)[C@@H](O)[C@@H]1O NAME: salicin REASON: MISSED Primary alcoholic group not attached to an aromatic ring
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:33857
  name: aromatic primary alcohol
  definition: Any primary alcohol in which the alcoholic hydroxy group is attached
    to a carbon which is itself bonded to an aromatic ring.
  parents:
  - CHEBI:15734
  - CHEBI:33854
  xrefs:
  - KEGG:C03485
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: invalid syntax (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []