Reverting to best solution for macrolide, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:25106
  name: macrolide
  definition: A macrocyclic lactone with a ring of twelve or more members derived
    from a polyketide.
  parents:
  - CHEBI:26188
  - CHEBI:63944
  xrefs:
  - Wikipedia:Macrolide
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 38
  log_lines_of_code: 3.6375861597263857
  max_indent: 4
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmarts
  - GetRingInfo
  - PathToSubmol
  - HasSubstructMatch
  - MolFromSmiles
  - AtomRings
  methods_called_count: 6
  smarts_strings:
  - C(=O)O[C;R]
  smarts_strings_count: 1
  defs:
  - 'is_macrolide(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No ring structures found in molecule"
  - None, "Error in defining lactone SMARTS pattern"
  - True, "Contains macrocyclic lactone ring of 12 or more members"
  - False, "No macrocyclic lactone rings of required size found"
  returns_count: 5
  complexity: 3.927517231945277
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_macrolide('P(=O)(OC1C=CC(=CCC(OC(=O)CC(=C)C(CC=CC=CC=CC=CC(=CC1O)C)C)/C=C/C(/C=C\\\
  \\C=C)C)C)(O)O'):\n Pre-condition Violation\n\tRingInfo not initialized\n\tViolation\
  \ occurred on line 52 in file Code/GraphMol/RingInfo.cpp\n\tFailed Expression: df_init\n\
  \tRDKIT: 2024.09.1\n\tBOOST: 1_85\n"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0