Attempt 1 at B vitamin, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:75769
  name: B vitamin
  definition: Any member of the group of eight water-soluble vitamins originally thought
    to be a single compound (vitamin B) that play important roles in cell metabolism.
    The group comprises of vitamin B1, B2, B3, B5, B6, B7, B9, and B12 (Around 20
    other compounds were once thought to be B vitamins but are no longer classified
    as such).
  parents:
  - CHEBI:35352
  - CHEBI:36963
  xrefs:
  - MetaCyc:B-vitamins
  - PMID:22743781
  - PMID:23093174
  - PMID:23238962
  - PMID:23449527
  - PMID:23462586
  - PMID:23690582
  - Wikipedia:B_vitamin
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []