Attempt 3 at polypyrrole, f1=0.0
(currently fails to compile, but committing anyway

To address the shortcomings in the previous implementation of the `is_polypyrrole` function, let's consider the following points:

1. **Definition of Pyrrole Units**: The SMARTS pattern used needs to be flexible enough to capture variations like fused rings and nitrogen configurations in porphyrin-like structures. The previous patterns may have missed more complex structures where pyrrole units are parts of larger conjugated systems.

2. **Fused Systems**: We should ensure that the pyrrole pattern accounts for cases where pyrrole might be fused with other rings, as seen in porphyrins and other complex macrocycles. It might be necessary to include checks for systems where the pyrrole unit is not isolated but instead part of a larger aromatic system.

3. **Unique Counting**: Ensure that pyrrole units are accurately counted even when they are part of fused systems or macrocyclic structures, and modify our counting logic to adapt to this.

Armed with these observations, the code can be adjusted to better detect polypyrrole systems:

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.12185159972770593 is too low.
Outcomes:
------

True positives: SMILES: O(C(=O)CCC=1C2=NC(C1C)=CC=3NC(=C(C3C)C=C)C=C4NC(C(=C4C)C=C)=CC5=NC(C(=C5C)CCC(OC)=O)=C2)C NAME: Dimethylprotoporphyrin IX dimethyl ester REASON: CORRECT Contains 2 pyrrole units
 * SMILES: O=C1C=2N=C(C1(O)C)C=C3NC(=CC4=NC(=CC=5NC(C2)=C(C5)C)C(C4=O)(C6OC(C(O)CC6OC(=O)C)C)C)C=C3C NAME: Tolyporphin F REASON: CORRECT Contains 2 pyrrole units
 * SMILES: O=C1[C@@H](C2=C3NC([C@H]([C@@H]3CCC(O)=O)C)=CC=4NC(=C(C4C)C=C)C=C5NC(=CC=6NC2=C1C6C)C(=C5C)CC)C(OC)=O NAME: 3-[(3R,21S,22S)-16-Ethenyl-11-ethyl-3-methoxycarbonyl-12,17,21,26-tetramethyl-4-oxo-7,23,24,25-tetrazahexacyclo[18.2.1.15,8.110,13.115,18.02,6]hexacosa-1,5,8(26),9,11,13,15,17,19-nonaen-22-yl]propanoic acid REASON: CORRECT Contains 3 pyrrole units
 * SMILES: C12=N3C(=NC=4N5C(N=C6N7=C(N=C8N(C(=N1)C9=CC=CC=C89)[Cu]357)C%10=CC=CC=C6%10)=C%11C=CC=CC4%11)C%12=CC=CC=C2%12 NAME: copper(II) phthalocyanine REASON: CORRECT Contains 2 pyrrole units
 * SMILES: C1=C2C(=C(C=3N2[Mg]N4C(C=C5N=C(C3)C(=C5CC)CC)=C(C(=C4C=C6N=C1C(=C6CC)CC)CC)CC)CC)CC NAME: magnesium octaethylporphyrin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: O=C1C(C(C=2NC(=C(C21)C)CC=3NC(=C(C3CCOC(=O)CC(O)=O)C)C=O)C=4NC(=C(C4CCC(O)=O)C)CC5NC(=O)C(=C5C)C=C)C(O)=O NAME: Bn-NCC-1 REASON: CORRECT Contains 3 pyrrole units
 * SMILES: Cc1cc(C)c(c(C)c1)C1=C2C=CC3=[N]2[Zn]24n5c1ccc5C(c1c(C)cc(C)cc1C)=C1C=CC(C(c5c(C)cc(C)cc5C)=c5ccc(=C3c3c(C)cc(C)cc3C)n25)=[N]41 NAME: zinc tetramesitylporphyrin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: C1=2N3C(C=C4N5=C(C=C6N7C(=CC8=N(C(=C1)C(=C8CCC(O)=O)C)[Fe+]573)C(=C6C)CCC(O)=O)C(=C4C)C=C)=C(C2C)C=C NAME: ferriheme b REASON: CORRECT Contains 2 pyrrole units
 * SMILES: [H]C(=O)c1c(CC)c2cc3[nH]c4c([C@@H](C(=O)OC)C(=O)c4c3C)c3nc(cc4[nH]c(cc1n2)c(C=C)c4C)[C@@H](C)[C@@H]3CCC(O)=O NAME: pheophorbide b REASON: CORRECT Contains 2 pyrrole units
 * SMILES: c1cc2cc3ccc([nH]3)c(-c3cc4cc5ccc(cc6ccc(cc7ccc(cc3[nH]4)n7)[nH]6)n5)c3ccc(cc4ccc(cc1n2)[nH]4)n3 NAME: 2,5'-biporphyrin REASON: CORRECT Contains 4 pyrrole units
 * SMILES: Oc1c2ccc(n2)c(O)c2ccc([nH]2)c(O)c2ccc(cc3ccc1[nH]3)n2 NAME: 5,10,15-trihydroxyporphyrin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: [H]C(C)=C1C(C)C2=CC3=C(C(C)=O)C(C)=C4C=C5[C@@H](C)[C@H](CCC(=O)OC\C=C(/C)CCC[C@H](C)CCC[C@H](C)CCCC(C)C)C6=[N+]5[Mg--]5(N34)N3C(=CC1=[N+]25)C(C)=C1C(=O)[C@H](C(=O)OC)C6=C31 NAME: bacteriochlorophyll b REASON: CORRECT Contains 2 pyrrole units
 * SMILES: C=1(/C=C/2\NC(=O)C(=C2C=C)C)NC(=C(C1C)CCC(=O)O)CC=3NC(/C=C/4\NC(C(=C4C=C)C)=O)=C(C3CCC(=O)O)C NAME: bilirubin XIIIalpha REASON: CORRECT Contains 2 pyrrole units
 * SMILES: CC1=C(CCC(O)=O)\C(NC1=O)=C\c1[nH]c(C(=O)c2[nH]c(\C=C3NC(=O)C(C)=C/3C=C)c(C)c2C=C)c(C)c1CCC(O)=O NAME: 5-oxo-delta-bilirubin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: c1ccc2c3nc(nc4[nH]c(nc5nc(nc6[nH]c(n3)c3ccccc63)c3ccccc53)c3ccccc43)c2c1 NAME: phthalocyanine REASON: CORRECT Contains 4 pyrrole units
 * SMILES: CN(C)CCNC(=O)CCC1=[N+]2C(C=C1)=Cc1ccc(-c3ccc[nH]3)n1[B-]2(F)F NAME: DND-99 dye REASON: CORRECT Contains 2 pyrrole units
 * SMILES: C=12N3C(=CC4=[N+]5C(=CC=6N7C=8C(=C9[N+](=C(C1)[C@H]([C@@H]9CCC(O)=O)C)[Mg-2]735)[C@H](C(C8C6C)=O)C(=O)OC)[C@@H]([C@H]4C)CC)C(=C2C)C(=O)C NAME: bacteriochlorophyllide a REASON: CORRECT Contains 2 pyrrole units
 * SMILES: c1cc2cc3ccc(cc4ccc(cc5ccc(cc1n2)[nH]5)n4)[nH]3 NAME: porphyrin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: C1=2N3C(C=C4N5=C(C=C6N7C(=CC8=N(C(=C1)C(=C8CCC([O-])=O)C([H])=O)[Fe+]735)C(=C6C)CCC([O-])=O)C(=C4C)C=C)=C(C2C)[C@H](CC/C=C(\C)/CC/C=C(/CCC=C(C)C)\C)O NAME: ferriheme a(1-) REASON: CORRECT Contains 2 pyrrole units
 * SMILES: [H][C@@]1(N\C([C@@H](CCC(O)=O)[C@@H]1C)=C1\C(=O)C(=O)c2c(C)c(Cc3[nH]c(CC4NC(=O)C(C)=C4C=C)c(C)c3CC)[nH]c12)C(O)=O NAME: oxidized dinoflagellate luciferin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: CCC1=C(C)C2=Cc3c(C=C)c(C)c4C=C5[C@@H](C)[C@H](CCC(O)=O)C6=[N+]5[Mg--]5(n34)n3c(=CC1=[N+]25)c(C)c1C(=O)[C@H](C(=O)OC)C6=c31 NAME: chlorophyllide a REASON: CORRECT Contains 2 pyrrole units
 * SMILES: Cc1cc(C)c(c(C)c1)-c1c2ccc(cc2)c(-c2c(C)cc(C)cc2C)c2ccc([nH]2)c(-c2ccccc2)c2ccc(n2)c(-c2c(C)cc(C)cc2C)c2ccc(cc2)c(-c2c(C)cc(C)cc2C)c2ccc([nH]2)c(-c2ccccc2)c2ccc1n2 NAME: A,D-di-p-benzi[28]hexaphyrin(1.1.1.1.1.1) REASON: CORRECT Contains 2 pyrrole units
 * SMILES: C1=C2C(=C(C(N2)=CC3=NC(C(=C3C)CC)=CC=4NC(=C(C4C)CCC(=O)O)C=C5N=C1C(=C5CCC(=O)O)C)CC)C NAME: mesoporphyrin IX REASON: CORRECT Contains 2 pyrrole units
 * SMILES: CC1C2=[N+]3C(=Cc4c(C)c(CCC(O)=O)c5C=C6C(CCC(O)=O)=C(C)C7=[N+]6[Fe--]3(n45)n3c(=C2)c(C)c(C)c3=C7)C1(C)C NAME: iron methylchlorin REASON: CORRECT Contains 2 pyrrole units
 * SMILES: CCc1c(C)c2[nH]c1cc1nc(cc3[nH]c(cc4nc(cc5[nH]c2c(C)c5CC)c(C)c4CCCOC(=O)N(CCOCCOCCOC)CCOCCOCCOC)c(CC)c3CC)c(CCCOC(=O)N(CCOCCOCCOC)CCOCCOCCOC)c1C NAME: sapphyrin PCI-2050 REASON: CORRECT Contains 3 pyrrole units
False positives: SMILES: O=C1N[C@H](C(=O)NC1CC=2C3=C(C(=CC=C3)CC=C(C)C)NC2)C NAME: Terezine D REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O/N=C\CC=1C2=C(C=CC(=C2)/C=C/C(=C)C)NC1 NAME: (1E)-N-Hydroxy-2-{5-[(1E)-3-methylbuta-1,3-dien-1-yl]-1H-indol-3-yl}ethanimine REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: S(CC[C@H](NC(=O)[C@@H](N)C(C)C)C(=O)N[C@@H](CC=1C=2C(NC1)=CC=CC2)C(O)=O)C NAME: Val-Met-Trp REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C(N[C@@H](CC=1C=2C(NC1)=CC=CC2)C(=O)N[C@@H](C)C(O)=O)[C@@H](N)CC=3C=4C(NC3)=CC=CC4 NAME: Trp-Trp-Ala REASON: WRONGLY CLASSIFIED Contains 4 pyrrole units
 * SMILES: O(C12C(N(C[C@@H](C1)CO)C)CC=3C4=C2C=CC=C4NC3)C NAME: 10-alpha-methoxy-9,10-dihydrolysergol REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: [H][C@]12NC(=[NH2+])N[C@@]1(O)[C@@]1([H])[C@H](CNC(=O)c3cc(Br)c(Br)[nH]3)[C@@H](CNC(=O)c3cc(Br)c(Br)[nH]3)[C@H](O)[C@@]11NC(=[NH2+])N[C@@]1([H])O2 NAME: massadine(2+) REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(=O)N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(=O)N1[C@H](C(=O)O)CCC1)CC(C)C)=O)CCCCN)=O)CC=2C=CC=CC2)=O)CC3=CNC4=C3C=CC=C4)CC(=O)O)=O)CCCNC(=N)N)=O)CC5=CNC6=C5C=CC=C6)=O)C(C)C)([C@H](CCC(=O)N)NC(=O)[C@H]7N(CCC7)C([C@@H](N)C(CC)C)=O)=O NAME: IPQVWRDWFKLP REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1[C@@H]([C@@]2([C@H]([C@]3([C@@H]([C@]([C@H](C)CC3)(CC=4C5=C(C=CC=C5)NC4)C)CC2)C)CC1)C)C NAME: Radarin C REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C/1/C(=C/2\C=3C4=C(C=CC=C4)NC3C(C2=O)(OC)C(OC)C5=CC=C(O)C=C5)/C=6C7=C(C=CC=C7)NC6\C1=C\C8=CC=C(O)C=C8 NAME: Dimethoxyscytonemin REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1N(OC)[C@H](C(=O)N[C@]1(OC)CC=2C3=C(C=CC=C3)NC2)C NAME: (+)-acrozine C REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C(N[C@@H]([C@H](O)C)C(O)=O)[C@@H](NC(=O)CN)CC=1C=2C(NC1)=CC=CC2 NAME: Gly-Trp-Thr REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1[C@H](N[C@H](C(=O)O)CC2=CC=C(O)C=C2)CCC(O)=NCCCC[C@@H]3N=C(O)[C@@H](N=C([C@H]([C@H](OC(C[C@H]4C(=N[C@H](C(=N[C@H]1CCC(=O)OC[C@H](N=C(O)[C@H]5N(C(=O)[C@@H](N=C3O)CC6=CC=C(O)C=C6)CCC5)C(O)=N4)O)CC=7C8=C(C=CC=C8)NC7)O)=O)C)N=C(O)[C@@H](N=C(O)[C@@H](N=C(O)C)CC9=CC=C(O)C=C9)CO)O)CC(C)C NAME: Microviridin LH1667 REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C(N1[C@@H](CCC1)C(O)=O)[C@H]2N(CCC2)C(=O)[C@@H](N)CC=3C=4C(NC3)=CC=CC4 NAME: Trp-Pro-Pro REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: C1=CC=CC=2NC=C(C12)CC(O[C@H]3[C@@H]([C@H]([C@@H]([C@H](O3)C(O)=O)O)O)O)=O NAME: Indole-3-acetic-acid-O-glucuronide REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1OC(C(NC(=O)/C=C/C2=C(C=CC=C2)/C=C\C)C(=O)NC(C(=O)NC(C(=O)NCC(=O)NC(C(=O)N3CCCC3C(NC(C(NC(C(NC(C(NC(C(NC1C(O)C(C)C)=O)CC(C)C)=O)O)=O)CC=4C5=C(C=CC=C5)NC4)=O)C(O)C6=CC=C(OC)C=C6)=O)C(O)C7=CC=CC=C7)C(C(=O)O)C)C)C NAME: RP-1776 REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1OC(=CC(=C1C)OC)/C=C/C=C/C=C/C=C/C=2NC=CC2 NAME: Auxarconjugatin C REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1N[C@H](C(=O)O)CC2=C(C1C=3C4=C(C=CC=C4)NC3)NC=5C=CC=CC25 NAME: Malabetaezindole A REASON: WRONGLY CLASSIFIED Contains 3 pyrrole units
 * SMILES: OC1C2(C(C(C)CC1)(CCC(C2CC=3C4=C(C=CC=C4)NC3)=C)C)CCC=C(C)C NAME: Anominine REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1[C@@]23C(=O)NC([C@@H]2C(C)=C([C@H]([C@@H]3C=CC[C@@H](C[C@H]([C@@H](C1)O)O)C)O)C)CC=4C5=C(C=CC=C5)NC4 NAME: Cytochalasin Y REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1N[C@H](C(=O)N[C@H]1C(C)C)CC=2C3=C(C=CC=C3)NC2 NAME: L-valyl-L-tryptophan anhydride REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: SC[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CCCN=C(N)N)CC=1C=2C(NC1)=CC=CC2)C(O)=O NAME: Arg-Trp-Cys REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1N[C@@H]2[C@](O)(NC([C@@H]2OC)=O)CC(=O)N(CC(=O)N[C@@H](C(=O)NCC(NC[C@H](CC(N[C@@H]([C@@H]1O)[C@H](O)[C@@H](O)C/C=C/C=C/C3=CC=CC=C3)=O)O)=O)CC=4C5=C(C=CC=C5)NC4)C NAME: Pedein B REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C(N[C@@H]([C@H](CC)C)C(=O)N[C@@H](CC=1C=2C(NC1)=CC=CC2)C(O)=O)[C@@H](NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CC=3NC=NC3)CC(C)C)CC(O)=O)[C@H](CC)C NAME: His-leu-asp-ile-ile-trp REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C1O[C@@H]([C@H](NC(=O)[C@@H](NC(=O)CCCCC)CC(=O)O)C(=O)N[C@H](C(=O)N[C@H]2CC[C@H](N([C@H](C(N([C@H](C(N[C@H]1C(C)C)=O)CC=3C4=C(C=CC=C4)NC3)C)=O)[C@H](CC)C)C2=O)O)CCCN=C(N)N)C NAME: Micropeptin SF995 REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
 * SMILES: O=C(N[C@@H](CC=1C=2C(NC1)=CC=CC2)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC=3NC=NC3)CC(O)=O NAME: His-Asp-Trp REASON: WRONGLY CLASSIFIED Contains 2 pyrrole units
False negatives: SMILES: C[C@]1(CC(O)=O)[C@H](CCC(O)=O)C2=CC3=[N+]4C(=Cc5c(CCC(O)=O)c(CC(O)=O)c6C=C7[N+]8=C(C=C1N2[Co--]48n56)[C@@H](CCC(O)=O)[C@]7(C)CC(O)=O)C(CCC(O)=O)=C3CC(O)=O NAME: cobalt-sirohydrochlorin REASON: MISSED Less than 2 pyrrole units found
 * SMILES: CC1=C2[N+]3=C(C=C4N5C(=CC6=[N+]7C(=Cc8c(CCC(O)=O)c(CC(O)=O)c1n8[Co--]357)C(CCC(O)=O)=C6CC(O)=O)[C@@H](CCC(O)=O)[C@]4(C)CC(O)=O)[C@@H](CCC(O)=O)[C@]2(C)CC(O)=O NAME: cobalt(II)-factor III REASON: MISSED Less than 2 pyrrole units found
 * SMILES: [C@@H]1(n2c3c(c(N)ncn3)nc2)O[C@H](C[Co-3]2345N6[C@H]7[C@@]8([N+]2=C([C@H]([C@]8(C)CC(N)=O)CCC(N)=O)C(=C2[N+]3=C([C@H]([C@]2(C)CC(N)=O)CCC(N)=O)C=C2[N+]4=C([C@H](C2(C)C)CCC(N)=O)C(=C6[C@](C)(CCC(=O)NC[C@@H](C)OP([O-])(=O)O[C@@H]2[C@@H](CO)O[C@H](n3c4c(N)ncnc4[n+]5c3)[C@@H]2O)[C@H]7CC(N)=O)C)C)C)[C@@H](O)[C@H]1O NAME: adenosylpseudocoenzyme B12 REASON: MISSED Less than 2 pyrrole units found
 * SMILES: [H][C@@]12[C@H](CC(O)=O)[C@@](C)(CCC(O)=O)C3=C(C)C4=[N+]5C(=CC6=[N+]7C(=C(C)C8=[N+]([C@]1(C)[C@@](C)(CC(O)=O)[C@@H]8CCC(O)=O)[Co--]57N23)[C@@](C)(CC(N)=O)[C@@H]6CCC(O)=O)C(C)(C)[C@@H]4CCC(O)=O NAME: cob(II)yrinic acid c monoamide REASON: MISSED Less than 2 pyrrole units found
 * SMILES: CC[C@H]1[C@H](Cc2[nH]c(\C=C3/N=C(C[C@@H]4NC(=O)[C@H](CC)[C@H]4C)C(C)=C/3CCC(O)=O)c(CCC(O)=O)c2C)NC(=O)[C@@H]1C NAME: (-)-stercobilin REASON: MISSED Less than 2 pyrrole units found
 * SMILES: C1=CC(=CC2=NC(C=C2)=CC2=NC(C=C2)=Cc2ccc[nH]2)N=C1 NAME: 21H-bilin REASON: MISSED Less than 2 pyrrole units found
 * SMILES: C=1(NC(/C=C/2\NC(C(=C2C)C=C)=O)=C(C1C)C=C)/C=C/3\N=C(\C=C/4\C(=C(C(N4)=O)C)CCC(O)=O)C(=C3C)CCC(O)=O NAME: biliverdin beta REASON: MISSED Less than 2 pyrrole units found
 * SMILES: CC1=CC2=C(C=C1C)N(C=N2)[C@@H]3[C@@H]([C@@H]([C@H](O3)CO)OP(=O)(O)O[C@H](C)CNC(=O)CC[C@@]4([C@H]([C@H]5[C@]6([C@@]([C@@H](C(=C(C7=NC(=CC8=NC(=C(C4=N5)C)[C@H](C8(C)C)CCC(=O)N)[C@H]([C@]7(C)CC(=O)N)CCC(=O)N)C)[N-]6)CCC(=O)N)(C)CC(=O)N)C)CC(=O)N)C)O.[C-]#N.[Co+3] NAME: cobalt(3+) [(2R,3S,4R,5S)-5-(5,6-dimethylbenzimidazol-1-yl)-4-hydroxy-2-(hydroxymethyl)oxolan-3-yl] [(2R)-1-[3-[(1S,2R,3R,5Z,7S,10Z,12S,13S,15Z,17S,18S,19R)-2,13,18-tris(2-amino-2-oxoethyl)-7,12,17-tris(3-amino-3-oxopropyl)-3,5,8,8,13,15,18,19-octamethyl-2,7,12,17-tetrahydro-1H-corrin-24-id-3-yl]propanoylamino]propan-2-yl] hydrogen phosphate cyanide REASON: MISSED Less than 2 pyrrole units found
 * SMILES: C(\C=1C(=C(\C(\N1)=C\C=2NC(=C(C2CCC(O)=O)C)/C=C/3\NC([C@@H](\C3=C/C)C)=O)CCC(=O)O)C)=C/4\NC(C(=C4C)C=C)=O NAME: (3E)-phytochromobilin REASON: MISSED Less than 2 pyrrole units found
 * SMILES: [H][C@]12[C@H](CC(O)=O)[C@@](C)(CCC(O)=O)\C(N1[Co+])=C(C)\C1=N\C(=C/C3=N/C(=C(C)\C4=N[C@]2(C)[C@@](C)(CC(O)=O)[C@@H]4CCC(O)=O)[C@@](C)(CC(O)=O)[C@@H]3CCC(O)=O)C(C)(C)[C@@H]1CCC(O)=O NAME: cob(II)yrinic acid REASON: MISSED Less than 2 pyrrole units found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:38077
  name: polypyrrole
  definition: A compound composed of two or more pyrrole units.
  parents:
  - CHEBI:38101
  xrefs:
  - Beilstein:8538310
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 24
  log_lines_of_code: 3.1780538303479458
  max_indent: 2
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - GetSubstructMatches
  - MolFromSmiles
  - MolFromSmarts
  methods_called_count: 3
  smarts_strings:
  - '[nH1]1cccc1 | [n]1ccccc1'
  smarts_strings_count: 1
  defs:
  - 'is_polypyrrole(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - True, f"Contains {len(unique_matches)} pyrrole units"
  - False, "Less than 2 pyrrole units found"
  returns_count: 3
  complexity: 2.435610766069589
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: "Error executing is_polypyrrole('O(C(=O)CCC=1C2=NC(C1C)=CC=3NC(=C(C3C)C=C)C=C4NC(C(=C4C)C=C)=CC5=NC(C(=C5C)CCC(OC)=O)=C2)C'):\n\
  \ Python argument types in\n    Mol.GetSubstructMatches(Mol, NoneType)\ndid not\
  \ match C++ signature:\n    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle\
  \ query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool uniquify=True, bool useChirality=False, bool\
  \ useQueryQueryMatches=False, unsigned int maxMatches=1000)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False,\
  \ unsigned int maxMatches=1000)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []