Reverting to best solution for ribonucleoside, f1=0.05328005328005328 iteration 1
---
chemical_class:
  id: CHEBI:18254
  name: ribonucleoside
  definition: Any nucleoside where the sugar component is D-ribose.
  parents:
  - CHEBI:33838
  - CHEBI:47019
  xrefs:
  - KEGG:C00911
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 39
  log_lines_of_code: 3.6635616461296463
  max_indent: 4
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - GetNeighbors
  - GetAtomicNum
  - MolFromSmiles
  - GetSubstructMatches
  - HasSubstructMatch
  - MolFromSmarts
  - GetIsAromatic
  - GetAtoms
  - GetAtomWithIdx
  methods_called_count: 9
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_ribonucleoside(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES"
  - False, "No D-ribose sugar detected"
  - False, "Ribose structure mismatch"
  - False, "No glycosidic bond to nucleobase"
  - False, "No aromatic system (missing nucleobase?)"
  - True, "D-ribose sugar connected to nucleobase via glycosidic bond"
  returns_count: 6
  complexity: 4.732712329225929
message: '

  Error: unexpected indent (<string>, line 1)

  Attempt failed: F1 score of 0 is too low.

  Outcomes:

  ------

  True positives: NONE

  False positives: NONE

  False negatives: NONE

  ------

  In your reasoning step, analyze the previous program and the above outcomes, hypothesizing
  about what went wrong, and how to improve.

  '
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: O=C1NC=C2[C@@]3(O)[C@@H](O)[C@@H](OC2=C1OC(=O)[C@H]4[C@H]5[C@H](C=C[C@H]4C)C[C@H](C)CC5)[C@@H](O)CC3
  name: Arthpyrone D
  reason: No D-ribose sugar detected
- smiles: CCN(CC)S(=O)(=O)C1=CC=CC(=C1)C(=O)NC2=CC(=CC(=C2)C)C
  name: 3-(diethylsulfamoyl)-N-(3,5-dimethylphenyl)benzamide
  reason: No D-ribose sugar detected
- smiles: O=C1[C@@]([C@H]2[C@]([C@@H]3C(C[C@](C=C)(C)CC3)=CC2)(C)CC1)(CO[C@@H]4O[C@H](C(=O)O)[C@@H](O)[C@H]([C@@H]4O)O)C
  name: Virescenoside Z4
  reason: No D-ribose sugar detected
- smiles: C[C@H]1CN(C(=O)CCCN2C(=CN=N2)CO[C@@H]1CN(C)C(=O)NC3=CC=CC(=C3)C(F)(F)F)[C@@H](C)CO
  name: 1-[[(8S,9S)-6-[(2S)-1-hydroxypropan-2-yl]-8-methyl-5-oxo-10-oxa-1,6,14,15-tetrazabicyclo[10.3.0]pentadeca-12,14-dien-9-yl]methyl]-1-methyl-3-[3-(trifluoromethyl)phenyl]urea
  reason: No D-ribose sugar detected
- smiles: O([C@H]1[C@@H](O)[C@H](O[C@@H]2O[C@@H]([C@@H](O[C@@H]3O[C@@H]([C@H](O)[C@H](O[C@H]4O[C@@H]([C@H](O)[C@H](O)[C@H]4O)CO)[C@H]3O)CO)[C@H](O)[C@H]2NC(=O)C)CO)[C@H](O[C@@H]1O[C@H]5[C@H](O)[C@H](O[C@@H](O[C@H]6[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]6CO)O[C@H]7[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]7CO[C@@H]8O[C@H]([C@@H](O)[C@@H](O)[C@@H]8O)C)O)[C@H]5O)CO[C@H]9O[C@@H]([C@@H](O)[C@H](O)[C@@H]9O[C@@H]%10O[C@@H]([C@@H](O[C@@H]%11O[C@@H]([C@H](O)[C@H](O[C@]%12(O[C@H]([C@H](NC(=O)C)[C@@H](O)C%12)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]%11O)CO)[C@H](O)[C@H]%10NC(=O)C)CO)CO)CO)[C@@H]%13O[C@@H]([C@@H](O[C@@H]%14O[C@@H]([C@H](O)[C@H](O[C@]%15(O[C@H]([C@H](NC(=O)C)[C@@H](O)C%15)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]%14O)CO)[C@H](O)[C@@H]%13NC(=O)C)CO
  name: CID 91846694
  reason: No D-ribose sugar detected
- smiles: CCOC(=O)NCC(C)(C)CNC(=O)OCC
  name: N-[3-(ethoxycarbonylamino)-2,2-dimethylpropyl]carbamic acid ethyl ester
  reason: No D-ribose sugar detected
- smiles: S1C(=NC(=C1)/C=C/C(OC)C(/C(/OC)=C\C(=O)OC)C)C2N=C(C3(OC3)C)SC2
  name: Melithiazol K
  reason: No D-ribose sugar detected
- smiles: CCCCC\C=C/C\C=C/CCCCCC(=O)O[C@@H](CO[C@@H]1O[C@H](CO)[C@H](O)[C@H](O)[C@H]1O)COC(=O)CCCCC\C=C/C\C=C/C\C=C/CC
  name: (2S)-1-O-(7Z,10Z,13Z)-hexadecatrienoyl-2-O-(7Z,10Z)-hexadecadienoyl-3-O-beta-D-galactopyranosyl-sn-glycerol
  reason: No D-ribose sugar detected
- smiles: CC(C)(C)OC(=O)N[C@H]1CCCCCC=C[C@@H]2C[C@]2(NC(=O)[C@@H]3C[C@H](CN3C1=O)OC(=O)N4CC5=C(C4)C(=CC=C5)F)CNS(=O)(=O)C6CC6
  name: LSM-5352
  reason: No D-ribose sugar detected
- smiles: O=C1O[C@@H]2C[C@@]3(O[C@H](/C(=C/C)/C)[C@@H](C)C[C@H]3O)O[C@@H](C2)CC=C(C[C@H](C=CC=C4[C@]5([C@H]1C=C([C@@H](O)C5OC4)COC(=O)CC6=COC=C6)O)C)C
  name: VM48642
  reason: No D-ribose sugar detected
sample_false_negatives:
- smiles: Nc1nc(Cl)nc2n(cnc12)[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1F
  name: clofarabine
  reason: No D-ribose sugar detected
- smiles: CCNC(=O)[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1cnc2c(N)ncnc12
  name: N-ethyl-5'-carboxamidoadenosine
  reason: No D-ribose sugar detected
- smiles: CSC[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1cnc2c(O)ncnc12
  name: 5'-S-methyl-5'-thioinosine
  reason: No D-ribose sugar detected
- smiles: CNC(=O)[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1cnc2c(NCc3cccc(I)c3)ncnc12
  name: 3-iodobenzyl-5'-N-methylcarboxamidoadenosine
  reason: No D-ribose sugar detected
- smiles: CC(=O)C1(N)NC(=O)N(C=C1)[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O
  name: 4-acetylcytidine
  reason: No aromatic system (missing nucleobase?)
- smiles: Nc1nc2n([C@H]3C[C@H](O)[C@@H](CO)O3)c(O)nc2c(=O)[nH]1
  name: 8-hydroxy-2'-deoxyguanosine
  reason: No D-ribose sugar detected
- smiles: CN(C)c1ncnc2n(cnc12)[C@@H]1O[C@H](CO)[C@@H](N)[C@H]1O
  name: 3'-amino-3'-deoxy-N(6),N(6)-dimethyladenosine
  reason: No D-ribose sugar detected
- smiles: NC(CCN1C(=O)CCN([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)C1=O)C(O)=O
  name: 3-(3-amino-3-carboxypropyl)-5,6-dihydrouridine
  reason: No aromatic system (missing nucleobase?)
- smiles: NC1=C2N=CN([C@@H]3O[C@](F)(COS(N)(=O)=O)[C@@H](O)[C@H]3O)C2=NC=N1
  name: nucleocidin
  reason: No D-ribose sugar detected
- smiles: '[H]C(=O)[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1cnc2c(N)ncnc12'
  name: 5'-dehydroadenosine
  reason: No D-ribose sugar detected
attempt: 1
success: true
best: true
error: ''
stdout: null
num_true_positives: 80
num_false_positives: 2799
num_true_negatives: 139377
num_false_negatives: 44
num_negatives: null
precision: 0.027787426189649182
recall: 0.6451612903225806
f1: 0.05328005328005328
accuracy: 0.9800210822206605
negative_predictive_value: 0.9996844090918872