Attempt 2 at sesterterpenoid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.03620210993892282 is too low.
Outcomes:
------

True positives: SMILES: O1[C@]2([C@]([C@]3([C@]4([C@]5([C@](C3)([C@](O)(CC[C@@]6([C@@]5(OC(=O)C6=C)[H])[H])C)C=C4)[H])C)C1=O)([C@@H](OC(=O)C)C[C@@](O)([C@]7([C@@]2(C(=CC7)C)[H])[H])C)[H])[H] NAME: Handelin REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C(O)[C@H]([C@H]1[C@@H]2[C@@](CC=C(CC=C3[C@H](C(=CC2)C)CC[C@@H]3C)C)(C)CC1)C NAME: Betaestacin IV REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: C1CC(C2[C@](C1)(C3[C@@](CC2)(C4[C@]([C@H](C3)O)([C@@H]5C(=CC4)CO[C@H]5O)C)C)C)(C)C NAME: (+)-Desoxyscalarin REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C\1N(C(C)C(/C1=C(\O)/C(=C/C(CC(CC(O)C(O)C(C(O)C(C(O)C(C(O)CC(O)C(C(O)C(C(O)CC(O)CC(O)CC(O)C(O)C(O)C(O)C(O)C[C@H]2O[C@](O)([C@@H](O)[C@H]([C@@H]2O)O)CC(O)CCCCCCCCC)C)C)C)C)C)C)C)/C)=O)C NAME: Aflastatin A REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=[N+]([O-])[C@@]1([C@@H](NC(=O)OC)[C@H](O[C@H](C1)O[C@@H]2C(=C[C@H]3C4(OC(=O)C(C4=O)=C([C@@]5([C@H](C(=CC2)C)C=C[C@@H]6C(O[C@@H]7O[C@H]([C@H](OC(=O)C)[C@@H](C7)O)C)[C@@H](C)C[C@@H]([C@@H]56)C)C)O)CC(C=O)=C[C@@H]3O)C)C)C NAME: Tetrocarcin E1 REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=[N+]([O-])[C@@]1([C@@H](N)[C@H](O[C@H](C1)O[C@@H]2C(=C[C@H]3[C@@]4(OC(=O)C(C4=O)=C([C@@]5([C@H](C(=CC2)C)C=C[C@@H]6[C@@H](O[C@@H]7O[C@H]([C@H](OC(=O)C)[C@@H](C7)O[C@@H]8O[C@H]([C@H](O[C@H]9O[C@H]([C@H](O[C@@H]%10O[C@H]([C@H](O)CC%10)C)[C@@H](C9)O)C)CC8)C)COC(=O)C)[C@@H](C)C[C@@H]([C@@H]56)C)C)O)CC(C=O)=C[C@@H]3O)C)C(=O)OC)C NAME: Tetrocarcin Q REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: [C@]12([C@]([C@@]3([C@@]4([C@]([C@]5(C(C[C@]3(CC1)C(=O)[O-])=C(CC5)C(=O)[O-])[H])(C4)C)[H])[H])([C@H](CC2)C(C)C)[H])C NAME: asperterpenoid B(2-) REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1OC23C(C=C(CCC=C(C4C(C(=C1C2=O)O)(C5C=C(CC(C5CC4C)OC6OC(C(OC(=O)C7=C(OC)C=C(O)C=C7C)C(C6O)O)C)C)C)C)C)(C=C(C(=O)O)C(C3)C)C NAME: Tetromycin 4 REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=[N+]([O-])[C@@]1([C@@H](NC(=O)OC)[C@H](O[C@H](C1)O[C@@H]2C(=C[C@H]3C4(OC(=O)C(C4=O)=C([C@@]5([C@H](C(=CC2)C)C=C[C@@H]6C(O[C@@H]7O[C@H]([C@H](OC(=O)C)[C@@H](C7)OC8COC(C)C(C8)OC9OC(C(O)C(C9)O)C)C)[C@@H](C)C[C@@H]([C@@H]56)C)C)O)CC(C=O)=C[C@@H]3O)C)C)C NAME: Tetrocarcin B REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C1[C@H]2C(C(=O)O)=CC[C@H]3[C@]4(O[C@@H](C=C(C)C)C[C@@H]4C)CC[C@@]3(C[C@@H]2[C@@](C1)(O)C)C NAME: Bipolarin D REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1C2=C([C@@H](O)C[C@H]3[C@]4(O[C@@H](C=C(CO)C)C[C@@H]4C)CC[C@@]3(C[C@@H]2C(=C1)C)C)CO NAME: Bipolaricin B REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=[N+]([O-])[C@@]1([C@@H](NC(=O)OC)[C@H](O[C@H](C1)O[C@@H]2C(=C[C@H]3C4(OC(=O)C(C4=O)=C([C@@]5([C@H](C(=CC2)C)C=C[C@@H]6[C@@H](O[C@@H]7O[C@H]([C@H](OC(=O)C)[C@@H](C7)O[C@@H]8O[C@H]([C@H](O[C@@H]9O[C@H]([C@H](O[C@@H]%10O[C@H]([C@H](O)CC%10)C)[C@@H](C9)O)C)CC8)C)C)[C@@H](C)C[C@@H]([C@@H]56)C)C)O)C=C(C=O)C[C@@H]3O)C)C)C NAME: Tetrocarcin A REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C1C=C(C)[C@@H]2[C@@H]1C(=CC[C@H]3[C@]4(O[C@@H](C=C(C)C)C[C@@H]4C)CC[C@@]3(C2)C)CO NAME: Ophiobolin I REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1O[C@@]23[C@H](C=C([C@@H](O[C@@H]4O[C@@H]([C@H](NC(=O)OC)[C@](C4)(N)C)C)CC=C([C@H]5[C@@](C(=C1C2=O)O)([C@H]6[C@@H]([C@@H](O[C@@H]7O[C@H]([C@H](OC(=O)C)[C@@H](C7)O[C@@H]8O[C@H]([C@H](O[C@H]9O[C@H]([C@H](O[C@@H]%10O[C@H]([C@H](O)CC%10)C)[C@@H](C9)O)C)CC8)C)C)[C@@H](C)C[C@@H]6C)C=C5)C)C)C)[C@@H](O)C=C(C3)/C=C/C(=O)C NAME: Microsporanate D REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C1OC23C(C=C(C(OC4OC(C(NC(=O)C)C(C4)(O)C)C)C(C)C=C(C5C(C(=C1C2=O)O)(C6C(C(OC7OC(C(OC8OC(C(OC9OC(C(O)C(C9)O)C)C(C8)OC%10OC(C(O)CC%10)C)C)CC7)C)C(C)CC6C)C=C5)C)C)C)C=CC(C3)CCC NAME: Saccharosacrin F REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C1C2=C(CC[C@H]3[C@]4(O[C@@H](/C=C(/CO)\C)C[C@@H]4C)CC[C@@]3(C[C@@H]2C(=C1)C)C)CO NAME: Bipolaricin F REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: [H][C@@]12CC[C@]3(C)[C@]([H])(C[C@H](OC(C)=O)[C@@]4(C)[C@@]3([H])CC=C3C(=O)O[C@@H](O)[C@]43[H])[C@@]1(C)CCCC2(C)C NAME: scalarin REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C(O)[C@H]([C@H]1[C@@H]2[C@@](C[C@@H](O)[C@@](O)(CC=C3[C@H](C(=CC2)C)CC[C@]3(O)C)C)(C)CC1)C NAME: Betaestacin Vb REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: CC(=O)O[C@@H]1C[C@@H]2[C@@]3(C)CCCC(C)(C)[C@@H]3CC[C@@]2(C)[C@@H]2CC=C3CO[C@@H](O)[C@@H]3[C@@]12C NAME: 12-epi-deoxoscalarin REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1OC23C(C=C(C(OC4OC(C(NC(=O)C)C(C4)(O)C)C)C(C)C=C(C5C(C(=C1C2=O)O)(C6C(C(OC7OC(C(OC8OC(C(OC9OC(C(O)C(C9)O)C)C(C8)O)C)CC7)C)C(C)CC6C)C=C5)C)C)C)C=CC(C3)CC NAME: Saccharosacrin C REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: [H][C@@]12CC[C@]3(C)[C@]([H])(CC[C@@]4(C)[C@@]3([H])CC=C3C(=O)O[C@@H](O)[C@@]43[H])[C@@]1(C)CCC[C@@]2(C)COC(C)=O NAME: 12-deacetoxy-21-acetoxyscalarin REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1C=C(C)[C@@H]2[C@@H]1C(=CC[C@H]3[C@@H]([C@H](CCC=C(C)C)C)CC[C@@]3(C2)C)C=O NAME: 6-epi-ophiobolin N REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=[N+]([O-])[C@@]1([C@@H](NC(=O)OC)[C@H](O[C@H](C1)O[C@@H]2C(=C[C@H]3[C@@]4(OC(=O)C(C4=O)=C([C@@]5([C@H](C(=CC2)C)C=C[C@@H]6[C@@H](O[C@@H]7O[C@H]([C@H](OC(=O)C)[C@@H](C7)O[C@@H]8O[C@H]([C@H](O[C@H]9O[C@H]([C@H](O[C@@H]%10O[C@H]([C@H](O)CC%10)C)[C@@H](C9)O)C)CC8)C)C)[C@@H](C)C[C@@H]([C@@H]56)C)C)O)CC(/C=C/C(=O)C)=C[C@@H]3O)C)C)C NAME: Microsporanate A REASON: CORRECT Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C(O)C1=CC[C@@H]2[C@@](CC[C@]3([C@H]2[C@@H](C(=C)C)CC3)C)(C)C[C@@H]4[C@H]1C=C[C@@H]4C NAME: Emericolin D REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1C=C(C)[C@@H]2[C@@H]1C(=CC[C@H]3[C@@H]([C@H](/C=C\[C@@H]4OC4(C)C)C)CC[C@@]3(C2)C)C=O NAME: Asperophiobolin I REASON: CORRECT Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
False positives: SMILES: [H][C@]12CC[C@@]3(C)[C@@]([H])(CC[C@@]3(O)CCC([O-])=O)[C@]1([H])C=CC1=CC(=O)CC[C@]21C NAME: canrenoate REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: CC[C@H](C)\C=C\C1=CC2=C(Cl)C(=O)[C@@]3(C)OC(=O)C4=C(OC(O1)C2(O)C34O)C(C)C(C)O NAME: chaetoviridin I REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: CC1=C2[N+]3=C(C=C4N5C(=CC6=[N+]7C(=Cc8c(CCC(O)=O)c(CC(O)=O)c1n8[Co--]357)C(CCC(O)=O)=C6CC(O)=O)[C@@H](CCC(O)=O)[C@]4(C)CC(O)=O)[C@@H](CCC(O)=O)[C@]2(C)CC(O)=O NAME: cobalt(II)-factor III REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: S(OC1CC=2[C@@]([C@@]3([C@]([C@]4([C@](CC3)(C(=CC4)C=5C=CC=NC5)C)[H])(CC2)[H])[H])(CC1)C)(O)(=O)=O NAME: Abiraterone sulfate REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: COC(=O)C[C@H]1[C@@]2(C)C[C@]3(OC(C)=O)[C@](CC4=C(CC[C@@]5(C)[C@@H](OC(=O)C(O)=C45)c4ccoc4)[C@]13C)(OC(C)=O)[C@H]2OC(=O)C(C)=C NAME: trichagmalin B REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C1O/C(=C\C2=CC=C(O)C=C2)/C(=C1C3=C(C4=C(C(=O)C(C4(O)C(=O)C)O)CC(=O)/C=C/C(=C/C(CC)C)/C)C=C(O)C(=C3)O)O NAME: Kodaistatin A REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: C1C[C@@H](C([C@@]2([C@@]1([C@]3([C@](CC2)([C@]4([C@@](C(=C3)C)(C(C(=C4[O-])C)=O)C)C(OC)=O)C)[H])CO)[H])(C)C)OC(C)=O NAME: andrastin B(1-) REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1C(=C[C@@H]2C=C[C@@H]3CC(N[C@]43[C@@H]2C(=O)C5=C(C(O)=C(C)C(=C5C4=O)O)C([C@@H](C=C[C@H]([C@@H]1C)O)C)=O)=O)CC(C)C NAME: Ansaseomycin A REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C(O[C@@H]1C=C2[C@](O)(CC[C@]3([C@H]2CC[C@@H]3[C@@H](/C=C/[C@@H](C(C)C)C)C)C)[C@@]4(C1(O)C[C@@H](O)CC4)C)C NAME: Fusaristerol D REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])CC=C4C[C@H](CC[C@]4(C)[C@@]3([H])CC[C@]12C)OS(O)(=O)=O)[C@H](C)CCCC(C)CO NAME: 26-hydroxycholesterol 3-sulfate REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: ClC1=C2C(C3=C(C(=O)[C@H](CC)C)C(O[C@@]3(C1=O)C)=O)=COC(=C2)/C=C/[C@H](CC)C NAME: Chaetoviridin F REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O=C1C2=C(C=C3CC[C@@H](CC3=C2C)O)[C@@H]4CC[C@@H]([C@]4(C1)C)[C@@H](/C=C/[C@@H](C(C)C)C)C NAME: Citreoanthrasteroide A REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O([C@H]([C@@H]1[C@@]2([C@@H](CC1)/C(/CCC2)=C/C=C/3\C[C@@H](O)C[C@H](O)C3)C)C)CCC(O)(C)C NAME: 1alpha,25-dihydroxy-19-nor-22-oxavitamin d3 / 1alpha,25-dihydroxy-19-nor-22-oxacholecalciferol REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: BrC1=CC2=C(NC3[C@@]2(C(C=C)(C)C)C[C@H]4C(=O)N\C(\C(N34)=O)=C\C=5NC=NC5)C=C1 NAME: Bromoroquefortine C REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: [H][C@@]12CC[C@H]3C[C@]1(C(=O)C3=C)[C@@]1(O)OC[C@]22[C@H](O)CC[C@@](C)(COC(C)=O)[C@@]2([H])[C@@H]1O NAME: Xerophilusin H REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C(O)[C@H]([C@@H]1[C@@]2([C@@](C=3C([C@@]4([C@H](C([C@@H](O)CC4)(C)C)CC3)C)=CC2)(C)CC1)C)C NAME: 3beta-hydroxy-4,4,14alpha-trimethyl-5alpha-pregna-7,9(11)-diene-20S-carboxylic acid REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O[C@H]1C([C@H]2[C@](C3=C([C@]4([C@]([C@@H]([C@@H]([C@@H](O)C/C=C(/CO)\C)C)CC4)(C)CC3)C)CC2)(C)CC1)(C)C NAME: Astraeusin F REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: O[C@H](C[C@H]([C@@]1([C@@]2([C@@](CC1)(/C(/CCC2)=C/C=C\3/C[C@@H](O)C[C@H](O)C3=C)[H])C)[H])C)C[C@](O)(CO)C NAME: 1alpha,23R,25S,26-Tetrahydroxyvitamin D3 REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: ClC1=C(OC)C=C(O)C(=C1C)C(=O)O[C@H]2[C@@]3(O)C(=C[C@@H]4CC([C@@H]([C@@H]4[C@@]3(C)C2)O)(C)C)C=O NAME: Armillarikin REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1N[C@@H](CC(C)C)[C@H]2[C@@]13[C@]4(O[C@]5(CCC[C@]([C@@H]5[C@H]3C=C(CO)[C@H]2C)(O)C)CC4)O NAME: Flavipesine B REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O=C1C2=C([C@@]3(C(=O)C[C@@H]([C@]3(C1)C)[C@@H](CC(=O)C(O)C(C(=O)OC)C)C)C)[C@@H](O)CC4[C@@]2(CC[C@@H](C4(C)C)O)C NAME: Resinacein O REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: [H][C@]12C[C@@]1([H])[C@]1(C)[C@@H](O)C(=O)\C(=C(\C)C(=O)OC)[C@@]3([H])C1=C2C[C@@]1([H])[C@@]2(C)[C@]4([H])C[C@]4([H])[C@](O)(C\C(C)=C\C(=O)OC)[C@@]2([H])CC2=C(CO)C(=O)O[C@]312 NAME: shizukaol C REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: C1CC(=CC[C@@]2(C(CC=C(C3C1=C(CC3)C)C)C(CC2)C(C)C)C)C NAME: variculatriene A REASON: WRONGLY CLASSIFIED Contains C25 skeleton with few rotatable bonds, likely sesterterpenoid
 * SMILES: O[C@@H]1[C@@H]([C@H]([C@H](O)C1)/C=C/[C@@H](O)CCCCCCC)C/C=C\CCCC(O)=O NAME: 20-ethyl PGF2alpha REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
 * SMILES: CCCC[C@@H](C)\C=C(/C)\C=C(/C)C(=O)NC1=C[C@@](O)(\C=C\C=C\C=C\C(=O)NC2=C(O)CCC2=O)[C@@H]2O[C@@H]2C1=O NAME: manumycin A REASON: WRONGLY CLASSIFIED Contains C25 skeleton and isoprene units, with modifications - sesterterpenoid
False negatives: SMILES: O1C(O)(C2(OC(C(C2)C)C(C(=O)C(C(O)C(C3OC(O)(C(CC3C)C)CC)C)C)CC)C)C(CC1(C(O)C)CC)C NAME: Antibiotic X 14889A REASON: MISSED No isoprene units found, not a terpenoid
 * SMILES: O=C1OC(=C)C(=C1C(=O)C[C@@H]2O[C@H]([C@@H](C)C[C@@H]2C)[C@H]([C@H](O)[C@@H](C(=O)[C@@](O)([C@@H]3O[C@]([C@@H]4O[C@@H]([C@](O)([C@@H](OC)C)CC4)C)(CC)CC3)C)CC)C)O NAME: Ecteinamycin REASON: MISSED No isoprene units found, not a terpenoid
 * SMILES: O=C(OC[C@@H](O)[C@@H](O)[C@H](O)[C@H](O)CO)[C@@H]([C@H](O)/C(=C/[C@@H]([C@H](O)/C(=C/[C@@H]([C@H](O)/C(=C/[C@@H]([C@H](O[C@@H]1O[C@@H]([C@@H](O)[C@@H]([C@@H]1O)O)COC(=O)C)[C@H](C[C@H](C[C@H](CC)C)C)C)C)/C)C)/C)C)/C)C NAME: Bionectriol C REASON: MISSED No C25 skeleton found
 * SMILES: OC1(C(C2(C(C3(C(C(CCC3)(C)C)CC2)C)CC1)C)CC(O)C=4C(OC(=O)C4)OC(=O)/C=C/C5=CC=CC=C5)COC(=O)C NAME: 24-Acetyl- 25-cinnamoylvulgaroside REASON: MISSED No isoprene units found, not a terpenoid
 * SMILES: [H][C@@]12CC[C@@]3(C)C4=CC[C@@]5(C)CCC(C)(C)C[C@@]5([H])[C@]4(C)CC[C@]3([H])[C@@]1(C)CCC(=O)C2(C)C NAME: taraxerone REASON: MISSED No C25 skeleton found
 * SMILES: C1CCC(C2[C@]1(C3[C@@](CC2)([C@@]4([C@](CC3)([C@H]([C@](CC4)(C)O)CO)C)[H])C)C)(C)C NAME: 14betaH-scalarane-17alpha-19-diol REASON: MISSED No C25 skeleton found
 * SMILES: O=C(O)/C(=C/[C@@H]([C@H](O[C@@H]1O[C@H]([C@H](O)[C@H]([C@H]1O)O)C)/C(=C/[C@@H]([C@H](O[C@@H]2O[C@H]([C@H](O)[C@H]([C@H]2O)O)C)/C(=C/[C@@H]([C@H](O)/C(=C/C(C(O)/C(=C/C(C(O)C(CC)C)C)/C)C)/C)C)/C)C)/C)C)/C NAME: Phialotide H REASON: MISSED No C25 skeleton found
 * SMILES: O=C(C=1C(=[N+]([O-])C2=CC=CC=C2C1)C)CC(CC/C=C/3\CO[C@H](C3)/C=C(/CC/C=C/4\CO[C@H](C4)C=C(C)C)\C)C NAME: Marinoterpin A REASON: MISSED No isoprene units found, not a terpenoid
 * SMILES: O=C(O)/C(=C/[C@@H]([C@H](O[C@@H]1O[C@H]([C@H](O)[C@H]([C@H]1O)O)C)/C(=C/[C@@H]([C@H](O[C@@H]2O[C@H]([C@H](O)[C@H]([C@H]2O)O)C)/C(=C/[C@@H]([C@H](O[C@@H]3O[C@@H]([C@@H](O)[C@@H]([C@@H]3O)O)CO)/C(=C/C(C(O)/C(=C/C(C(O)C(CC)C)C)/C)C)/C)C)/C)C)/C)C)/C NAME: Phialotide G REASON: MISSED No C25 skeleton found
 * SMILES: O=C1O[C@@H](C(C)C)CC(=O)[C@@H](C[C@@H]([C@@H](O)[C@@H]([C@@H](O)C[C@@H](OC)[C@@H](C)[C@H](CC=C(C=CC=C(C=CC=C1C)C)C)OC(=O)/C=C/C(=O)NC2=C(O)CCC2=O)C)C)C NAME: Hexacosalactone A REASON: MISSED No isoprene units found, not a terpenoid
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:26660
  name: sesterterpenoid
  definition: Any terpenoid derived from a sesterterpene. The term includes compounds
    in which the C25 skeleton of the parent sesterterpene has been rearranged or modified
    by the removal of one or more skeletal atoms (generally methyl groups). Sometimes
    sesterterpenoids are erroneously referred to as sesterpenoids.
  parents:
  - CHEBI:26873
  xrefs:
  - LIPID_MAPS_class:LMPR0105
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: invalid syntax (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []