Reverting to best solution for monoterpenoid indole alkaloid, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:65323
  name: monoterpenoid indole alkaloid
  definition: A terpenoid indole alkaloid which is biosynthesised from L-tryptophan
    and diisoprenoid (usually secolaganin) building blocks.
  parents:
  - CHEBI:65321
  xrefs:
  - PMID:18280746
  - PMID:20717879
  - PMID:21425787
  - PMID:22679912
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 36
  log_lines_of_code: 3.58351893845611
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 2
  methods_called:
  - MolFromSmarts
  - HasSubstructMatch
  - GetRingInfo
  - GetAtomWithIdx
  - GetMolFrags
  - GetAtomicNum
  - AtomRings
  - MolFromSmiles
  methods_called_count: 8
  smarts_strings:
  - '[C@](C)(CC=C)'
  - '[C@](C)(CC=C)(CC=C)" if 10 in chain_lengths else "[C@](C)(CC=C)(CC=C)(CC=C)'
  - c1ccc2c(c1)nc(c2)C
  smarts_strings_count: 3
  defs:
  - 'is_monoterpenoid_indole_alkaloid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No indole substructure found"
  - False, "No terpene substructure found"
  - False, "No diisoprenoid chain found (C10 or C15)"
  - False, "No nitrogen atom found"
  - False, "Not enough fused rings"
  - False, "Terpenoid backbone not found"
  - True, "Contains indole nucleus and terpenoid (C10 or C15) backbone"
  returns_count: 8
  complexity: 4.516703787691222
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_monoterpenoid_indole_alkaloid('COC(=O)C1=CO[C@H](C)C2=CN3CCc4c([nH]c5ccccc45)[C@@H]3C[C@H]12'):\n\
  \ Python argument types in\n    rdkit.Chem.rdmolops.GetMolFrags(Mol)\ndid not match\
  \ C++ signature:\n    GetMolFrags(RDKit::ROMol mol, bool asMols=False, bool sanitizeFrags=True,\
  \ boost::python::api::object frags=None, boost::python::api::object fragsMolAtomMapping=None)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0