Reverting to best solution for lactol, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:38131
  name: lactol
  definition: Cyclic hemiacetals formed by intramolecular addition of a hydroxy group
    to an aldehydic or ketonic carbonyl group. They are thus 1-oxacycloalkan-2-ols
    or unsaturated analogues.
  parents:
  - CHEBI:5653
  xrefs:
  - Wikipedia:Lactol
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 42
  log_lines_of_code: 3.7376696182833684
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - GetSubstructMatches
  - IsRingAtom
  - GetNeighbors
  - MolFromSmarts
  - GetAtomicNum
  - GetAtoms
  - MolFromSmiles
  - GetIdx
  - GetAtomWithIdx
  - GetRingInfo
  methods_called_count: 10
  smarts_strings:
  - '[CX4]([OX2H1])[OX2]1[#6]~[#6]1'
  - '[CX4]([OX2H1])[OX2][#6]1~[#6]~[#6]1'
  - '[CX4]([OX2H1])[OX2]'
  - '[#6][CX4]([OX2H1])[OX2][#6]1~[#6]~[#6]1'
  - '[#6][CX4]([OX2H1])[OX2]1[#6]~[#6]1'
  smarts_strings_count: 5
  defs:
  - 'is_lactol(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Molecule does not contain a ring"
  - False, "No hemiacetal group found in ring system"
  - False, "Hemiacetal carbon is connected to more than 2 oxygens."
  - True, "Contains a cyclic hemiacetal structure"
  returns_count: 5
  complexity: 4.547533923656674
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_lactol('C[C@@H]1O[C@H](O)[C@H](O)C[C@H]1O'):\n 'RingInfo'\
  \ object has no attribute 'IsRingAtom'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0