Reverting to best solution for nucleoside phosphate, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:25608
  name: nucleoside phosphate
  definition: A nucleobase-containing molecular entity that is a nucleoside in which
    one or more of the sugar hydroxy groups has been converted into a mono- or poly-phosphate.
    The term includes both nucleotides and non-nucleotide nucleoside phosphates.
  parents:
  - CHEBI:25703
  - CHEBI:37734
  - CHEBI:61120
  xrefs:
  - KEGG:C01329
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 49
  log_lines_of_code: 3.8918202981106265
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmarts
  - HasSubstructMatch
  - MolFromSmiles
  methods_called_count: 3
  smarts_strings:
  - phosphate
  - base
  smarts_strings_count: 2
  defs:
  - 'is_nucleoside_phosphate(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Nucleobase not found in molecule"
  - False, "No phosphate group found in molecule"
  - True, "Contains a nucleobase and phosphate group, thus classified as nucleoside
    phosphate"
  returns_count: 4
  complexity: 2.9783640596221255
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0