Attempt 4 at amino sugar, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.0006555227794165847 is too low.
Outcomes:
------

True positives: SMILES: OC[C@H]1NC(O)[C@H](O)[C@@H](O)[C@@H]1O NAME: nojirimycin REASON: CORRECT Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
False positives: SMILES: CC[C@@H]1[C@@H]2C[C@H]3[C@@H]4N(C)c5ccccc5[C@]44C[C@@H](C2[C@H]4O)N3[C@H]1O NAME: Isoajmaline REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: N1C(C2=C(N=C1N)N3[C@](N2)([C@]4([C@H]([C@H]3O[C@@H]4COP(=O)(OP(=O)(OP(=O)([O-])[O-])[O-])[O-])O)O)[H])=O NAME: (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate(4-) REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: N1C(C2=C(N=C1N)N3[C@](N2)([C@]4([C@H]([C@H]3O[C@@H]4COP(=O)(OP(=O)(OP(=O)(O)O)O)O)O)O)[H])=O NAME: (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: OC12NC(C(O)C1)C(O)C(O)C2O NAME: Calystegine C1 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O[C@]12[C@]3(N(C([C@@H]3CO)(C)C)C=4C1=CC=CC4)N5[C@@](O)([C@@H]2OC)C(=O)N6C(C5=O)=CC7=C(NC=8C7=CC=CC8)C(C=C6)(C)C NAME: Okaramine D_120149 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O=C1C(OC)=C(C(=O)C2(C1=C3N4C5[C@@H]6N(C)[C@H](C4OC3O)C[C@@H]6C7N(C25)CCO7)O)C NAME: Aclidinomycin B REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O[C@]12N([C@](CC1)([C@H](O)[C@@H](O)[C@@H]2O)[H])C NAME: N-Methylcalystegine B2 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: NC(=O)C1=CN([C@@H](O)CC1)[C@@H]1O[C@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O NAME: (S)-NADHX(2-) REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O=C1N[C@@H](CC(C)C)[C@H]2[C@@]13[C@@]4(O)N[C@]5([C@H](O)CC[C@]([C@@H]5[C@H]3C=C(C)[C@H]2C)(O)C)C(C4)=O NAME: Aspochalazine A REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O[C@H]1C2CCC(O)(N2)[C@H](O)[C@@H]1O NAME: Calystegin B2 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: C1(C(C(=NC(N1[C@@H]2O[C@H](COP(O)(=O)O)[C@H](C2)O)=O)N)O)O NAME: 2'-deoxy-5,6-dihydroxy-5,6-dihydrocytidine 5'-monophosphate REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O=C1C=C2C=C[C@]3([C@@H](O)C)[C@@H]4[C@H](N2[C@@]1(O)C)[C@H](O3)[C@@H](C)N5C4=CC=C5C NAME: Bipolamine C REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: OC12N(C(C(O)C1)C(O)C(O)C2O)C NAME: N-Methylcalystegine C1 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O=C1C(OC)=C(C(=O)[C@@]2(C1=C3N4[C@@H]5[C@@H]6N(C)[C@@H]([C@H]4OC3)C[C@@H]6[C@H]7N([C@H]25)CCO7)O)C NAME: Aclidinomycin A REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: [H][C@@]12C[C@H]3[C@H](CC)[C@@H](O)N1[C@H]1C[C@@]4([C@H](OC(C)=O)C31)c1ccccc1N(C)[C@@]24[H] NAME: 17-O-acetylajmaline REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: NC(=O)C1=CN([C@@H](O)CC1)[C@@H]1O[C@H](COP(O)(=O)OP(O)(=O)OC[C@H]2O[C@H]([C@H](O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O NAME: (S)-NADHX REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: NC(=O)C1=CN([C@H](O)CC1)[C@@H]1O[C@H](COP(O)(=O)OP(O)(=O)OC[C@H]2O[C@H]([C@H](OP(O)(O)=O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O NAME: (R)-NADPHX REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: [H][C@@]12CC[C@]3([H])[C@]([H])(CC[C@@]4(C)[C@@]3([H])C[C@]3([H])O[C@@]5(NC[C@@H](CO[C@@H]6O[C@H](CO)[C@@H](O)[C@H](O)[C@H]6O)C[C@@H]5OC(C)=O)[C@@H](C)[C@]43[H])[C@@]1(C)CC[C@@H](C2)O[C@]1([H])O[C@H](CO)[C@H](O[C@]2([H])O[C@H](CO)[C@@H](O)[C@H](O[C@]3([H])OC[C@@H](O)[C@H](O)[C@H]3O)[C@H]2O[C@]2([H])O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)[C@H](O)[C@H]1O NAME: esculeoside A REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: C[C@@H]1[C@@]2(CN3CC[C@@]45C6=CC=CC=C6N(C(CO)=O)[C@]5([C@](CO1)([C@]2(C[C@@]43O)[H])[H])[H])[H] NAME: Splendoline REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O=C[C@H](O)[C@@H](O)[C@H](O[C@H]1O[C@@H]([C@@H](O[C@H]2O[C@@H]([C@@H](O[C@H]3O[C@@H]([C@@H](O[C@H]4O[C@@H]([C@@H](N[C@H]5O[C@@H]([C@@H](O[C@H]6O[C@@H]([C@@H](O[C@H]7O[C@@H]([C@@H](N[C@H]8O[C@@H]([C@@H](O[C@H]9O[C@@H]([C@@H](O[C@H]%10O[C@@H]([C@@H](O)[C@@H]([C@H]%10O)O)CO)[C@@H]([C@H]9O)O)CO)[C@@H]([C@H]8O)O)CO)[C@@H]([C@H]7O)O)C)[C@@H]([C@H]6O)O)CO)[C@@H]([C@H]5O)O)CO)[C@@H]([C@H]4O)O)C)[C@@H]([C@H]3O)O)CO)[C@@H]([C@H]2O)O)CO)[C@@H]([C@H]1O)O)CO)[C@H](O)CO NAME: Acarviostatin II23 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O1C23N4CC5(C1N6C7C8(C5OCC8)CC(=C9NC=%10C(C79CC6)=CC=CC%10)C(OC)=O)CC2CC%11%12C%13N(CCC3%13C%14=C4C(OC)=CC=C%14)CCC%12OCC%11 NAME: Amatain REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: S1S[C@@]23N([C@H]4NC=5C=CC=CC5C4([C@@H]2O)[C@]67C8=C(C=CC=C8)N[C@H]6N9C(=O)[C@H](CO)N(C([C@]9([C@H]7O)OC)=O)C)C([C@]1(N(C)C3=O)C(C)C)=O NAME: Leptosin M1 REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: NC(=O)C1=CN([C@H](O)CC1)[C@@H]1O[C@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](OP([O-])([O-])=O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O NAME: (R)-NADPHX(4-) REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: O1[C@@H](N2C(O)C(O)(C(=O)NC2=O)C)C[C@H](O)[C@H]1CO NAME: Thymidine glycol REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
 * SMILES: OC1N[C@@H]([C@@H](O)[C@@H]([C@@H]1O)O)CO NAME: Nojirimycin B REASON: WRONGLY CLASSIFIED Molecule contains a sugar backbone with at least one hydroxy group replaced by an amino group
False negatives: SMILES: O([C@H]1[C@H](O)[C@H](O[C@@H](O[C@H]2[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]2CO)O)[C@H]1O)CO[C@H]3O[C@@H]([C@@H](O)[C@H](O[C@H]4O[C@@H]([C@@H](O)[C@H](O)[C@@H]4O)CO)[C@@H]3O)CO[C@H]5O[C@@H]([C@@H](O)[C@H](O)[C@@H]5O)CO)[C@H]6O[C@@H]([C@@H](O)[C@H](O)[C@@H]6O[C@@H]7O[C@@H]([C@@H](O[C@@H]8O[C@@H]([C@H](O)[C@H](O[C@H]9O[C@@H]([C@H](O)[C@H](O)[C@H]9O)CO)[C@H]8O)CO)[C@H](O)[C@H]7NC(=O)C)CO)CO NAME: N-[(2R,3R,4R,5S,6R)-5-[(2S,3S,4S,5R,6R)-4-[(2R,3S,4S,5S,6R)-3-[(2S,3R,4R,5S,6R)-3-Acetamido-5-[(2S,3R,4S,5S,6R)-3,5-dihydroxy-6-(hydroxymethyl)-4-[(2R,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5R,6R)-3,5-dihydroxy-4-[(2S,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]oxan-2-yl]oxymethyl]-3,5-dihydroxyoxan-2-yl]oxy-2,4-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O1[C@@H]([C@@H](O[C@@H]2O[C@@H]([C@@H](O)[C@H](O)[C@H]2NC(=O)C)CO)[C@H](O[C@H]3O[C@@H]([C@@H](O)[C@H](O)[C@@H]3O)CO)[C@H](O)[C@@H]1O[C@H]4[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]4CO)O[C@H]5[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]5CO)O)CO[C@H]6O[C@@H]([C@@H](O)[C@H](O[C@H]7O[C@@H]([C@@H](O)[C@H](O)[C@@H]7O)CO)[C@@H]6O)CO[C@H]8O[C@@H]([C@@H](O)[C@H](O)[C@@H]8O)CO NAME: N-[(3R,4R,5S,6R)-5-[(2S,3R,4R,5S,6R)-3-Acetamido-5-[(2S,3S,4R,5R,6R)-5-[(2S,3R,4R,5S,6R)-3-acetamido-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5R,6R)-3,5-dihydroxy-4-[(2S,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]oxan-2-yl]oxymethyl]-3-hydroxy-4-[(2S,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O([C@H]1[C@@H](O[C@@H]2O[C@@H]([C@@H](O)[C@H](O)[C@H]2NC(=O)C)CO)[C@H](OC(O)[C@@H]1NC(=O)C)CO)[C@@H]3O[C@@H]([C@H](O)[C@H](O[C@]4(O[C@H]([C@H](NC(=O)C)[C@@H](O)C4)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]3O)CO NAME: (2S,4S,5R,6R)-5-Acetamido-2-[(2R,3R,4S,5S,6R)-2-[(3R,4R,5R,6R)-3-acetamido-5-[(2S,3R,4R,5S,6R)-3-acetamido-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2-hydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-4-hydroxy-6-[(1R,2R)-1,2,3-trihydroxypropyl]oxane-2-carboxylic acid REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O([C@H]1[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]1CO)O[C@H]2[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]2CO)O)[C@@H]3O[C@@H]([C@@H](O)[C@H](O[C@H]4O[C@@H]([C@@H](O)[C@H](O)[C@@H]4O[C@H]5O[C@@H]([C@@H](O)[C@H](O)[C@@H]5O)CO)CO)[C@@H]3O)CO[C@@H]6O[C@@H]([C@@H](O)[C@H](O)[C@@H]6O)CO NAME: N-[(2R,3R,4R,5S,6R)-5-[(2S,3R,4R,5S,6R)-3-Acetamido-5-[(2S,3S,4S,5R,6R)-4-[(2R,3S,4S,5S,6R)-4,5-dihydroxy-6-(hydroxymethyl)-3-[(2R,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-3,5-dihydroxy-6-[[(2R,3S,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]oxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O([C@H]1[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]1CO)O[C@H]2[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]2COC3O[C@H]([C@@H](O)[C@@H](O)[C@@H]3O)C)O)[C@@H]4O[C@@H]([C@@H](O)[C@H](O[C@H]5O[C@@H]([C@@H](O)[C@H](O)[C@@H]5OC6O[C@@H]([C@@H](OC7O[C@@H]([C@H](O)[C@H](O)[C@H]7O)CO)[C@H](O)[C@H]6NC(=O)C)CO)CO)[C@@H]4O)CO[C@H]8O[C@@H]([C@@H](O)[C@H](O)[C@@H]8OC9O[C@@H]([C@@H](OC%10O[C@@H]([C@H](O)[C@H](O)[C@H]%10O)CO)[C@H](O)[C@H]9NC(=O)C)CO)CO NAME: N-[(3R,4R,5S,6R)-5-[(2S,3R,4R,5S,6R)-3-Acetamido-5-[(2S,3S,4S,5R,6R)-4-[(2S,3S,4S,5S,6R)-3-[(3R,4R,5S,6R)-3-acetamido-4-hydroxy-6-(hydroxymethyl)-5-[(3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5S,6R)-3-[(3R,4R,5S,6R)-3-acetamido-4-hydroxy-6-(hydroxymethyl)-5-[(3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]-3,5-dihydroxyoxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-[[(3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxymethyl]oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O([C@@H]1[C@@H](O)[C@H](O[C@@H]([C@@H]1O)CO)O[C@H]2[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]2CO)O)[C@@H]3O[C@@H]([C@@H](O[C@@H]4O[C@@H]([C@H](O)[C@H](O)[C@H]4O)CO)[C@H](O)[C@H]3NC(=O)C)CO NAME: N-[(3R,4R,5S,6R)-5-[(2R,3R,4S,5S,6R)-4-[(2S,3R,4R,5S,6R)-3-Acetamido-4-hydroxy-6-(hydroxymethyl)-5-[(2S,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O1[C@@H](O[C@@H]2[C@@H](NC(=O)C)C(O[C@@H]([C@@H]2O)CO)O)[C@H](NC(=O)C)[C@@H](O[C@@H]3O[C@@H]([C@H](O)[C@H](O)[C@H]3O)CO)[C@H](O[C@@H]4O[C@H]([C@@H](O)[C@@H](O)[C@@H]4O)C)[C@H]1CO NAME: N-[(3R,4R,5R,6R)-4-[(2R,3R,4R,5S,6R)-3-Acetamido-6-(hydroxymethyl)-4-[(2R,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-5-[(2S,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-2-yl]oxy-2,5-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O([C@H]1[C@H](O[C@@H]2O[C@@H]([C@@H](O)[C@H](O)[C@H]2NC(=O)C)CO)[C@H](O[C@@H](O[C@H]3[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]3CO)O[C@H]4[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]4CO[C@@H]5O[C@H]([C@@H](O)[C@@H](O)[C@@H]5O)C)O)[C@H]1O)CO[C@H]6O[C@@H]([C@@H](O)[C@H](O)[C@@H]6O[C@@H]7O[C@@H]([C@@H](O)[C@H](O)[C@H]7NC(=O)C)CO)CO)[C@H]8O[C@@H]([C@@H](O[C@@H]9O[C@@H]([C@@H](O[C@@H]%10O[C@@H]([C@H](O)[C@H](O)[C@H]%10O)CO)[C@H](O)[C@H]9NC(=O)C)CO)[C@H](O)[C@@H]8O[C@@H]%11O[C@@H]([C@@H](O[C@@H]%12O[C@@H]([C@H](O)[C@H](O)[C@H]%12O)CO)[C@H](O)[C@H]%11NC(=O)C)CO)CO NAME: N-[(3R,4R,5S,6R)-5-[(2S,3R,4R,5S,6R)-3-Acetamido-5-[(2S,3S,4R,5R,6R)-5-[(2S,3R,4R,5S,6R)-3-acetamido-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2S,3S,4S,5S,6R)-3-[(2S,3R,4R,5S,6R)-3-acetamido-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]-4-[(2R,3S,4S,5S,6R)-3,5-bis[[(2S,3R,4R,5S,6R)-3-acetamido-4-hydroxy-6-(hydroxymethyl)-5-[(2S,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy]-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-3-hydroxyoxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-[[(2R,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxymethyl]oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O1[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@H]3[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]3CO)OC[C@H]4OC(O)[C@H](NC(=O)C)[C@@H](O[C@@H]5O[C@@H]([C@H](O)[C@H](O[C@@H]6O[C@@H]([C@@H](O[C@@H]7O[C@H]([C@@H](O)[C@@H](O)[C@@H]7O)C)[C@H](O[C@@H]8O[C@@H]([C@H](O)[C@H](O)[C@H]8O)CO)[C@H]6NC(=O)C)CO)[C@H]5O)CO)[C@H]4O)O[C@@H]([C@@H]2O)CO)[C@H](NC(=O)C)[C@@H](O[C@@H]9O[C@@H]([C@H](O)[C@H](O)[C@H]9O)CO)[C@H](O[C@@H]%10O[C@H]([C@@H](O)[C@@H](O)[C@@H]%10O)C)[C@H]1CO NAME: N-[(2R,3R,4R,5S,6R)-2-[[(2R,3R,4R,5R)-5-Acetamido-4-[(2S,3R,4S,5S,6R)-4-[(2S,3R,4R,5S,6R)-3-acetamido-6-(hydroxymethyl)-4-[(2R,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-5-[(2S,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-3,6-dihydroxyoxan-2-yl]methoxy]-5-[(2S,3R,4S,5S,6R)-4-[(2S,3R,4R,5S,6R)-3-acetamido-6-(hydroxymethyl)-4-[(2R,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-5-[(2S,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
 * SMILES: O1[C@@H](O[C@@H]2[C@@H](O[C@@H]3[C@H](O)[C@@H](O[C@@H]([C@H]3O)CO)O[C@H]4[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]4CO)O)O[C@@H]([C@@H](O)[C@@H]2O)CO)[C@H](NC(=O)C)[C@@H](O[C@@H]5O[C@H]([C@@H](O)[C@@H](O)[C@@H]5O)C)[C@H](O[C@@H]6O[C@@H]([C@H](O)[C@H](O)[C@H]6O)CO)[C@H]1CO NAME: N-[(3R,4R,5S,6R)-5-[(2S,3S,4S,5R,6R)-4-[(2R,3S,4S,5S,6R)-3-[(2S,3R,4R,5S,6R)-3-Acetamido-6-(hydroxymethyl)-5-[(2S,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4-[(2S,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-2,4-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: MISSED Amino group not attached to sugar backbone
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:28963
  name: amino sugar
  definition: Any sugar having one or more alcoholic hydroxy groups replaced by substituted
    or unsubstituted amino groups.
  parents:
  - CHEBI:63299
  xrefs:
  - KEGG:C05383
  - PMID:18424273
  - PMID:9056391
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: invalid syntax (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []