Attempt 3 at phosphatidyl-L-serine, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: P(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(13:0/18:4(6Z,9Z,12Z,15Z)) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCC/C=C\C/C=C\C/C=C\CCCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(20:3(8Z,11Z,14Z)/22:6(4Z,7Z,10Z,13Z,16Z,19Z)) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OCC(OC(=O)CCCCCCCCCCC=1OC(=CC1C)CCC)COC(=O)CCCCCCCCC=2OC(=C(C2C)C)CCC)(OCC(N)C(O)=O)(O)=O NAME: PS(DiMe(9,3)/MonoMe(11,3)) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(20:5(5Z,8Z,11Z,14Z,17Z)/18:1(9Z)) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCCC)(OC[C@H]([NH3+])C([O-])=O)([O-])=O NAME: 24:0-18:2-PS REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(21:0/12:0) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCC/C=C\CCCCCC)COC(=O)CCCCCCCCCCCCCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(16:0/18:1(11Z)) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: [H][C@](COP(OC[C@@](COC(CCCCCC/C=C\C/C=C\C/C=C\CCCCC)=O)(OC(CCCCCC/C=C\C/C=C\C/C=C\CCCCC)=O)[H])(=O)O)(C(O)=O)N NAME: PS(20:3(8Z,11Z,14Z)/20:3(8Z,11Z,14Z)) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(16:0/15:0) REASON: MISSED Missing L-serine moiety with correct stereochemistry
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\CCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(14:1(9Z)/20:0) REASON: MISSED Missing L-serine moiety with correct stereochemistry
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:18303
  name: phosphatidyl-L-serine
  definition: A class of aminophospholipids in which a phosphatidyl group is esterified
    to the hydroxy group of serine.
  parents:
  - CHEBI:52565
  - CHEBI:60971
  - CHEBI:84135
  xrefs:
  - DrugBank:DB00144
  - HMDB:HMDB0014291
  - KEGG:C02737
  - MetaCyc:L-1-PHOSPHATIDYL-SERINE
  - PMID:10540156
  - PMID:15533308
  - PMID:19687511
  - PMID:23543734
  - PMID:3106116
  - PMID:3196084
  - PMID:4153523
  - PMID:8204602
  - PMID:8626656
  - PMID:9677350
  - Patent:EP2322184
  - Patent:HK1046237
  - Patent:US2011098249
  - Wikipedia:Phosphatidylserine
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: unterminated string literal (detected at line 3) (<string>, line 3)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []