Reverting to best solution for steroid, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:35341
  name: steroid
  definition: Any of naturally occurring compounds and synthetic analogues, based
    on the cyclopenta[a]phenanthrene carbon skeleton, partially or completely hydrogenated;
    there are usually methyl groups at C-10 and C-13, and often an alkyl group at
    C-17. By extension, one or more bond scissions, ring expansions and/or ring contractions
    of the skeleton may have occurred. Natural steroids are derived biogenetically
    from squalene which is a triterpene.
  parents:
  - CHEBI:18059
  - CHEBI:51958
  xrefs:
  - KEGG:C00377
  - MetaCyc:Steroids
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 40
  log_lines_of_code: 3.6888794541139363
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - HasSubstructMatch
  - MolFromSmarts
  - MolFromSmiles
  methods_called_count: 3
  smarts_strings:
  - '"[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C)CC2)C'
  - '[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C)CC2)C(C)CC1'
  - '[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C)[C@@H]2C[C@@H]1[C@@H]5[C@@H]5'
  - '[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C[C@@H]([C@H](C)CC)C)CC2)CC1'
  - '[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C)[C@@H]2CC1)[C@@H]5[C@@H]5'
  - '[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C)CC2)CC(C)C1'
  - '[C@@]12[C@@H]([C@@H]3[C@@H]([C@@H]([C@@H]4[C@@H]([C@H](CC4)CC3)C)[C@@H]2CC1)[C@@H]5C5'
  smarts_strings_count: 7
  defs:
  - 'is_steroid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No cyclopenta[a]phenanthrene backbone found"
  - False, "Missing methyl groups at C-10 and/or C-13"
  - True, "Contains cyclopenta[a]phenanthrene backbone with methyl groups at C-10
    and C-13, and alkyl group at C-17, with possible ring expansions, contractions,
    or bond scissions"
  - True, "Contains cyclopenta[a]phenanthrene backbone with methyl groups at C-10
    and C-13, and alkyl group at C-17"
  - True, "Contains cyclopenta[a]phenanthrene backbone with methyl groups at C-10
    and C-13"
  returns_count: 6
  complexity: 3.137775890822787
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: '''('' was never closed (<string>, line 29)'
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0