Reverting to best solution for N-acyl-L-alpha-amino acid, f1=0.010991756182862855 iteration 2
---
chemical_class:
  id: CHEBI:48927
  name: N-acyl-L-alpha-amino acid
  definition: Any L-alpha-amino acid carrying an N-acyl substituent.
  parents:
  - CHEBI:21644
  xrefs:
  - KEGG:C02850
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 33
  log_lines_of_code: 3.4965075614664802
  max_indent: 4
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - GetSubstructMatches
  - MolFromSmiles
  - GetNeighbors
  - HasSubstructMatch
  - GetIdx
  - GetSymbol
  - GetAtomWithIdx
  - MolFromSmarts
  methods_called_count: 8
  smarts_strings:
  - '[NX3][CX3](=O)'
  - '[CX3](=O)[OX1H0-,OX2H1]'
  smarts_strings_count: 2
  defs:
  - 'is_N_acyl_L_alpha_amino_acid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES"
  - False, "No N-acyl group found"
  - False, "No carboxyl group found"
  - False, "Not an L-alpha-amino acid or missing N-acyl group"
  returns_count: 4
  complexity: 4.099301512293296
message: '

  Error: unterminated string literal (detected at line 3) (<string>, line 3)

  Attempt failed: F1 score of 0 is too low.

  Outcomes:

  ------

  True positives: NONE

  False positives: NONE

  False negatives: NONE

  ------

  In your reasoning step, analyze the previous program and the above outcomes, hypothesizing
  about what went wrong, and how to improve.

  '
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: O=C1OC2=C(O)C(OC)=CC(=C2C=3C1=C(O)C=C(O)C3)O
  name: Graphislactone F
  reason: No N-acyl group found
- smiles: O=C1C(O)=CC(C)(C)C(=C1C)/C=C/2\OC(=O)C=C2C
  name: Gamma-Abscisolactone
  reason: No N-acyl group found
- smiles: C(CCCCCC(CC)C)CCCC[C@@H](O)[C@@H](NC(CCCCCCCCCCCCCCCCCCCCC)=O)CO
  name: N-docosanoyl-14-methylhexadecasphinganine
  reason: No carboxyl group found
- smiles: O=C1C2=C(C(=O)CC3[C@@]2(CC[C@@H]([C@]3(CO)C)O)C)[C@@]4(C(=O)C[C@@H]([C@]4([C@@H]1OC(=O)C)C)C(CCC(=O)O)C)C
  name: Lucidenic acid R
  reason: No N-acyl group found
- smiles: O1[C@H]([C@H](NC(=O)CO)[C@@H](O)CC1(O[C@H]2[C@@H](O)[C@H](O[C@@H](O)[C@@H]2O)CO)C(O)=O)[C@H](O)[C@H](O)CO
  name: (4S,5R,6R)-4-Hydroxy-5-[(2-hydroxyacetyl)amino]-2-[(2R,3R,4S,5S,6R)-2,3,5-trihydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-6-[(1R,2R)-1,2,3-trihydroxypropyl]oxane-2-carboxylic
    acid
  reason: Not an L-alpha-amino acid or missing N-acyl group
- smiles: C[C@H]1CCCCO[C@H]([C@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)C3=CC=NC=C3)[C@@H](C)CO)C)CN(C)C(=O)C4CCCCC4
  name: N-[(3S,9R,10S)-9-[[[cyclohexyl(oxo)methyl]-methylamino]methyl]-12-[(2S)-1-hydroxypropan-2-yl]-3,10-dimethyl-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-16-yl]-4-pyridinecarboxamide
  reason: No carboxyl group found
- smiles: O=C(NC(CC(O)=O)C(O)=O)C(N)C
  name: Alanyl-Aspartate
  reason: Not an L-alpha-amino acid or missing N-acyl group
- smiles: C([C@@](COC(CCCCCCCCCCCCC)=O)(OC(CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)=O)[H])O
  name: DG(14:0/20:4(5Z,8Z,11Z,14Z)/0:0)
  reason: No N-acyl group found
- smiles: O=C1NC=2C=CC=CC2[C@@]1(O)C
  name: (-)-(3S)-3-hydroxy-3-methyloxindole
  reason: No carboxyl group found
- smiles: CCCCCCCCCCCCCC(C)C(O)C(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12
  name: 2-hydroxy-3-methylhexadecanoyl-CoA
  reason: No carboxyl group found
sample_false_negatives:
- smiles: C=1C=CC=C2NC=C(C12)CCCC(N[C@H](C(=O)O)CS)=O
  name: N-[4-(indol-3-yl)butanoyl]-L-cysteine
  reason: Not an L-alpha-amino acid or missing N-acyl group
attempt: 2
success: true
best: true
error: ''
stdout: null
num_true_positives: 44
num_false_positives: 7917
num_true_negatives: 134338
num_false_negatives: 1
num_negatives: null
precision: 0.005526943851274966
recall: 0.9777777777777777
f1: 0.010991756182862855
accuracy: 0.9443569922698525
negative_predictive_value: 0.9999925561452743