Reverting to best solution for aromatic primary alcohol, f1=0.08149010477299184 iteration 1
---
chemical_class:
  id: CHEBI:33857
  name: aromatic primary alcohol
  definition: Any primary alcohol in which the alcoholic hydroxy group is attached
    to a carbon which is itself bonded to an aromatic ring.
  parents:
  - CHEBI:15734
  - CHEBI:33854
  xrefs:
  - KEGG:C03485
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 23
  log_lines_of_code: 3.1354942159291497
  max_indent: 2
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - GetSubstructMatches
  - MolFromSmiles
  - MolFromSmarts
  methods_called_count: 3
  smarts_strings:
  - '[c]-[CH2;D2]-[OH]'
  smarts_strings_count: 1
  defs:
  - 'is_aromatic_primary_alcohol(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - True, "Primary alcohol group attached to aromatic carbon"
  - False, "No primary alcohol group adjacent to aromatic ring found"
  returns_count: 3
  complexity: 2.42709884318583
message: '

  Error: unexpected indent (<string>, line 1)

  Attempt failed: F1 score of 0 is too low.

  Outcomes:

  ------

  True positives: NONE

  False positives: NONE

  False negatives: NONE

  ------

  In your reasoning step, analyze the previous program and the above outcomes, hypothesizing
  about what went wrong, and how to improve.

  '
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: OC1=CC=C(C[C@@H](O)[C@@H](O)CC=2C3=C(C=CC=C3)NC2)C=C1
  name: Diolmycin A1
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCC/C=C\CCCCCCCC)(O)(O)=O
  name: PA(20:1(11Z)/21:0)
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: CCOC1=CC=C(C=C1)N2C(=C3C(=NN=C(C3=N2)SCCN4CCCC4)C)C
  name: 2-(4-ethoxyphenyl)-3,4-dimethyl-7-[2-(1-pyrrolidinyl)ethylthio]pyrazolo[3,4-d]pyridazine
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: OS(=O)(=O)OC1CCC2C(CCC3C4CCCC4CCC23)C1
  name: Steryl sulfate
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: C[C@@H]1CN(C(=O)C2=C(N=CC(=C2)C3=CCCCC3)O[C@H]1CN(C)C(=O)CC4=CC=NC=C4)[C@@H](C)CO
  name: N-[[(2R,3R)-8-(1-cyclohexenyl)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-pyrido[2,3-b][1,5]oxazocin-2-yl]methyl]-N-methyl-2-pyridin-4-ylacetamide
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: O=C(O)C(=C(C)C)CCC(=O)O
  name: 2-(1-Methylethylidene)pentanedioic acid
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: O1C(C(O)C(O)C(OC)C1COC(=O)/C=C/C2=CC(O)=C(O)C=C2)C3=C(O)C4=C(OC(=CC4=O)C5=CC(O)=C(O)C=C5)C=C3O
  name: 4''-Methyl-6''-(3,4-dihydroxy-E-cinnamoyl)isoorientin
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: O=C1C2=CC(=O)CC[C@@]2([C@H]3CC[C@]4([C@H]([C@@]53[C@H]1O5)CC[C@@H]4[C@@H](/C=C/[C@@H](C(C)C)C)C)C)C
  name: Talarosterone
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: C1C[C@@H]([C@@H](O[C@H]1CCNS(=O)(=O)C2=CC=CC=C2Cl)CO)NC(=O)CC3=CN=CC=C3
  name: N-[(2R,3S,6R)-6-[2-[(2-chlorophenyl)sulfonylamino]ethyl]-2-(hydroxymethyl)-3-oxanyl]-2-(3-pyridinyl)acetamide
  reason: No primary alcohol group adjacent to aromatic ring found
- smiles: SC[C@H](NC(=O)[C@@H](N)CC(O)=O)C(=O)N[C@@H](CS)C(O)=O
  name: Asp-Cys-Cys
  reason: No primary alcohol group adjacent to aromatic ring found
sample_false_negatives:
- smiles: C=1C2=C(C=CC1)SC(=C2)C(=O)N[C@@H](CC(C)C)C(=O)N3CCN(CC3)C(=O)[C@H](CO)NS(C=4C=CC(=CC4Cl)Cl)(=O)=O
  name: GSK1016790A
  reason: No primary alcohol group adjacent to aromatic ring found
attempt: 1
success: true
best: true
error: ''
stdout: null
num_true_positives: 35
num_false_positives: 788
num_true_negatives: 141476
num_false_negatives: 1
num_negatives: null
precision: 0.0425273390036452
recall: 0.9722222222222222
f1: 0.08149010477299184
accuracy: 0.9944553759662684
negative_predictive_value: 0.999992931713282