Attempt 2 at carboxamidine, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: SMILES: [O-][N+](=O)N=C1NCCN1Cc1ccc(Cl)nc1 NAME: imidacloprid REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C1=CC(=CC=C1NN=C2C(=NN=C2N)N)Cl NAME: 4-[(4-chlorophenyl)hydrazinylidene]pyrazole-3,5-diamine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C(C)(N1C(=O)CC(=N1)N)C2=CC(Cl)=C(C=C2)Cl NAME: muzolimine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C1CC(OC1)CNC2=NN=C(CS2)C3=C(C=CC(=C3)F)F NAME: 5-(2,5-difluorophenyl)-N-(2-oxolanylmethyl)-6H-1,3,4-thiadiazin-2-amine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C1OC2=C(O1)C=C(C=C2)NN=C3C(=NN(C3=N)C4=CC=CC=C4)N NAME: 4-(1,3-benzodioxol-5-ylhydrazinylidene)-5-imino-1-phenyl-3-pyrazolamine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CCCCSC1=NNC(=C2C=NC3=CC=CC=C32)N1C NAME: 3-[3-(butylthio)-4-methyl-1H-1,2,4-triazol-5-ylidene]indole REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CNC(=S)N\N=C1/SCC(=O)N1CC=C NAME: CGP 52608 REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CC1=CC(=C(N1C2=CC=C(C=C2)Cl)C)C3=NN=C(SC3)NC NAME: 5-[1-(4-chlorophenyl)-2,5-dimethyl-3-pyrrolyl]-N-methyl-6H-1,3,4-thiadiazin-2-amine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CC(=O)NC1=CC=C(C=C1)C2=NN=C(SC2)NC3=CC(=CC=C3)S(=O)(=O)N(C)C NAME: N-[4-[2-[3-(dimethylsulfamoyl)anilino]-6H-1,3,4-thiadiazin-5-yl]phenyl]acetamide REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: N=1[NH2+]N=NC1C(=O)N NAME: 2H-tetrazol-2-ium-5-carboxamide REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: O=C1N(C(=O)C2(NC(=O)N(N=C2N1C)C)C3N=C(N)NC3=O)C NAME: 2096A/B REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C1=CC=C(C=C1)N2C(=N)C(=NNC3=CC=CC=C3F)C(=N2)N NAME: 4-[(2-fluorophenyl)hydrazinylidene]-5-imino-1-phenyl-3-pyrazolamine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: N1N=C(NN=C1CC2=CC=CC=C2)CC3=CC=CC=C3 NAME: 3,6-dibenzyl-1,2-dihydro-1,2,4,5-tetraazine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CC1=C(C(=NC1=C2CSC(=NN2)NCC3=CC=CC=C3)C)C(=O)C NAME: 1-[2,4-dimethyl-5-[2-[(phenylmethyl)amino]-4H-1,3,4-thiadiazin-5-ylidene]-3-pyrrolyl]ethanone REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C1CC1C2=NN=C(C2=NNC3=CC(=C(C=C3)Cl)Cl)N NAME: 5-cyclopropyl-4-[(3,4-dichlorophenyl)hydrazinylidene]-3-pyrazolamine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: O=C1N(C(=O)[C@]2(NC(=O)N(N=C2N1C)C)CC(=O)C)C NAME: Pyrizinostatin REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: Cn1nc(N)c2cn([C@@H]3O[C@H](CO)[C@@H](O)[C@H]3O)c3ncnc1c23 NAME: triciribine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: [H]C(=C([H])C(=NN=C1NCC(C)(C)CN1)C([H])=C([H])c1ccc(cc1)C(F)(F)F)c1ccc(cc1)C(F)(F)F NAME: hydramethylnon REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CSC(=NN=CC1=CC2=C(C=C1)OCO2)N NAME: N'-(1,3-benzodioxol-5-ylmethylideneamino)carbamimidothioic acid methyl ester REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: COC1=C(C=C(C=C1)C=NN=C(C2=NON=C2N)N)OC NAME: 4-amino-N'-[(3,4-dimethoxyphenyl)methylideneamino]-1,2,5-oxadiazole-3-carboximidamide REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CC(=O)NC1=CC=C(C=C1)C2=NN=C(SC2)NCCOC NAME: N-[4-[2-(2-methoxyethylamino)-6H-1,3,4-thiadiazin-5-yl]phenyl]acetamide REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: OC(=O)C(NN=C(N)N)CCCN=C(N)N NAME: Guanidino arginine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CC1=C(C(=CC=C1)NC2=NN=C(CS2)C3=CC=CC=C3F)C NAME: N-(2,3-dimethylphenyl)-5-(2-fluorophenyl)-6H-1,3,4-thiadiazin-2-amine REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: CC1=CC(=CC=C1)COC2=C(C=C(C=C2Br)C=NN=C(C3=NON=C3N)N)OC NAME: 4-amino-N'-[[3-bromo-5-methoxy-4-[(3-methylphenyl)methoxy]phenyl]methylideneamino]-1,2,5-oxadiazole-3-carboximidamide REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
 * SMILES: C1=CC2C(=CN=NC2=NN)C=C1 NAME: 8aH-phthalazin-1-one hydrazone REASON: WRONGLY CLASSIFIED Contains the carboxamidine (-C(=N)-N) group
False negatives: SMILES: CC1=N[C@@H](CCN1)C(O)=O NAME: ectoine REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: P(=O)(N=C(N(CC)CC)C)(C)F NAME: A-230 nerve agent REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: CC\N=C(/N)c1ccc(cc1)-c1ccc(o1)-c1ccc(cc1)C(\N)=N\CC NAME: 2,5-bis{[4-(N-ethylamidino)]phenyl}furan REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: CN(C)C=Nc1cccc(O)c1 NAME: N'-(3-hydroxyphenyl)-N,N-dimethylformamidine REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: C(CCCOC1=CC=C(C=C1)C(N)=N)COC2=CC=C(C=C2)C(N)=N NAME: pentamidine REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: CN1CCCN=C1\C=C\c1cccs1 NAME: pyrantel REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: C[C@H]1O[C@H](O[C@@H]2[C@@H](O)[C@@H](O)[C@H](O)[C@H](O)[C@H]2O)[C@@H](N)C[C@@H]1NC(=N)C(O)=O NAME: kasugamycin REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: CON=CNC(=O)c1ccc(cc1C)C1=NO[C@@](C1)(c1cc(Cl)cc(Cl)c1)C(F)(F)F NAME: (S)-fluxametamide REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: NC(=N)c1ccc(NN=Nc2ccc(cc2)C(N)=N)cc1 NAME: diminazene REASON: MISSED No carboxamidine (-C(=N)-N) group found
 * SMILES: CC1([C@@H](N2[C@@H](S1)[C@@H](C2=O)N=CN3CCCCCC3)C(=O)OCOC(=O)C(C)(C)C)C NAME: 2,2-dimethylpropanoyloxymethyl (2S,5S,6R)-6-(azepan-1-ylmethylideneamino)-3,3-dimethyl-7-oxo-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylate REASON: MISSED No carboxamidine (-C(=N)-N) group found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:35359
  name: carboxamidine
  definition: Compounds having the structure RC(=NR)NR2. The term is used as a suffix
    in systematic nomenclature to denote the -C(=NH)NH2 group including its carbon
    atom.
  parents:
  - CHEBI:2634
  - CHEBI:35352
  xrefs:
  - KEGG:C06060
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: unterminated string literal (detected at line 15) (<string>, line 15)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []