Attempt 4 at inositol phosphoceramide, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: CCCCCCCCCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](O)[C@H](O)[C@H]1OC1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)[C@H](O)CCCCCCCCCCCCCCCCC NAME: Man-beta1-6-Ins-1-P-Cer(d20:0/2-OH-26:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](COP(O)(=O)O[C@H]1[C@H](O)[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O)[C@H](O)C(O)CCCCCCCCCCCCCCCC NAME: Ins-1-P-Cer(t20:0/2-OH-24:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](COP(O)(=O)O[C@H]1[C@H](O)[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O)[C@H](O)CCCCCCCCCCCCCCCCC NAME: Ins-1-P-Cer(d20:0/2-OH-26:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC(O)C(O)C(=O)N[C@@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](O)[C@H](O)[C@H]1OC1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)[C@H](O)C(O)CCCCCCCCCCCCCCCC NAME: Man-beta1-6-Ins-1-P-Cer(t20:0/2,3-OH-26:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](O)[C@H](O)[C@H]1O[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)[C@H](O)CCCCCCCCCCCCCCC NAME: Man-beta1-6-Ins-1-P-Cer(d18:0/24:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](O)[C@H](O)[C@H]1OC1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)[C@H](O)CCCCCCCCCCCCCCCCC NAME: Man-1-6-Ins-1-P-Cer(d20:0/24:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](O)[C@H](O)[C@H]1OC1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)[C@H](O)C(O)CCCCCCCCCCCCCCCC NAME: Man-1-6-Ins-1-P-Cer(t20:0/2-OH-24:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCC[C@H](O)C(=O)N[C@@H](COP(O)(=O)O[C@H]1[C@H](O)[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O)[C@H](O)CCCCCCCCCCCCCCC NAME: Ins-1-P-Cer(d18:0/2-OH-24:0) REASON: MISSED Exactly one inositol residue required
 * SMILES: C(CCCCCCCC[C@H]([C@H]([C@H](COP(O[C@H]1[C@@H]([C@H]([C@@H]([C@H]([C@H]1O)O)O)O)O)(=O)O)NC(=O)C(CCCCCCCCCCCCCCCCCCCCCCCC)O)O)O)CCCCC NAME: N-(2-hydroxyhexacosanoyl)phytosphingosine-1-phospho-(1D-myo-inositol) REASON: MISSED Exactly one inositol residue required
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](O)[C@H](O)[C@H]1OC1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)[C@H](O)CCCCCCCCCCCCCCCCC NAME: Man-1-6-Ins-1-P-Cer(d20:0/26:0) REASON: MISSED Exactly one inositol residue required
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:60245
  name: inositol phosphoceramide
  definition: A phosphosphingolipid in which an inositol residue and the ceramide
    moiety are linked via a phosphodiester bridge. The ceramide moiety contains substituents
    R(1) and R(2) which vary with different sphingoid bases and fatty acyl moieties.
  parents:
  - CHEBI:35786
  xrefs:
  - PMID:9804825
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: invalid decimal literal (<string>, line 13)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []