Attempt 1 at nitrile, f1=0.0
(currently fails to compile, but committing anyway

Here's a program to classify chemical entities of the class nitrile:
# INFORMATION:

---
chemical_class:
  id: CHEBI:18379
  name: nitrile
  definition: 'A compound having the structure RC#N; thus a C-substituted derivative
    of hydrocyanic acid, HC#N. In systematic nomenclature, the suffix nitrile denotes
    the triply bound #N atom, not the carbon atom attached to it.'
  parents:
  - CHEBI:23424
  xrefs:
  - KEGG:C00726
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 32
  log_lines_of_code: 3.4657359027997265
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - MolFromSmarts
  - MolFromSmiles
  - GetSubstructMatches
  - HasSubstructMatch
  methods_called_count: 4
  smarts_strings:
  - '[N;H]'
  - '[N+](=O)[O-]'
  - '[C#N]'
  smarts_strings_count: 3
  defs:
  - 'is_nitrile(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No cyano group (-C#N) found"
  - True, f"Contains {n_cyano} cyano groups (-C#N)"
  - True, "Contains a cyano group (-C#N) and a nitro group (-NO2)"
  - True, "Contains a cyano group (-C#N) and an amine (-NH2 or -NH-)"
  - True, "Contains a single cyano group (-C#N)"
  returns_count: 6
  complexity: 3.293147180559946
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: "Python argument types in\n    Mol.HasSubstructMatch(Mol, NoneType)\ndid not\
  \ match C++ signature:\n    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle\
  \ query, RDKit::SubstructMatchParameters params=True)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False,\
  \ bool useQueryQueryMatches=False)\n    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol\
  \ query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []