Attempt 3 at steroid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Error: exceptions must derive from BaseException
Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: NONE
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:35341
  name: steroid
  definition: Any of naturally occurring compounds and synthetic analogues, based
    on the cyclopenta[a]phenanthrene carbon skeleton, partially or completely hydrogenated;
    there are usually methyl groups at C-10 and C-13, and often an alkyl group at
    C-17. By extension, one or more bond scissions, ring expansions and/or ring contractions
    of the skeleton may have occurred. Natural steroids are derived biogenetically
    from squalene which is a triterpene.
  parents:
  - CHEBI:18059
  - CHEBI:51958
  xrefs:
  - KEGG:C00377
  - MetaCyc:Steroids
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: invalid syntax (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []