Reverting to best solution for ganglioside, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:28892
  name: ganglioside
  definition: A molecule composed of a glycosphingolipid (ceramide and oligosaccharide)
    with one or more sialic acids linked on the sugar chain.
  parents:
  - CHEBI:17761
  - CHEBI:36526
  xrefs:
  - MetaCyc:Gangliosides
  - PMID:16158191
  - PMID:2088646
  - PMID:38623278
  - PMID:38848944
  - PMID:38887845
  - PMID:39092231
  - Wikipedia:Ganglioside
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 58
  log_lines_of_code: 4.060443010546419
  max_indent: 3
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - MolFromSmiles
  - GetAtomWithIdx
  - MolFromSmarts
  - AtomRings
  - GetAtomicNum
  - HasSubstructMatch
  - GetRingInfo
  methods_called_count: 7
  smarts_strings:
  - sialic_smarts
  - chain_smarts
  - amide_smarts
  smarts_strings_count: 3
  defs:
  - 'is_ganglioside(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No sialic acid moiety detected"
  - False, "No amide bond found; ceramide (glycosphingolipid) portion missing"
  - False, "No long aliphatic chain detected; ceramide portion may be missing"
  - False, "No sugar ring detected; oligosaccharide portion missing"
  - True, "Molecule contains a ceramide part linked to an oligosaccharide with sialic
    acid moieties; consistent with a ganglioside structure"
  returns_count: 6
  complexity: 4.212088602109284
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_ganglioside('CC(=O)N[C@H]1[C@H](O)[C@H](O[C@H](OP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](O)[C@@H]2O)n2ccc(=O)[nH]c2=O)[C@H]1NC(C)=O)C([O-])=O'):\n\
  \ Python argument types in\n    Mol.HasSubstructMatch(Mol, NoneType)\ndid not match\
  \ C++ signature:\n    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle query,\
  \ RDKit::SubstructMatchParameters params=True)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False,\
  \ bool useQueryQueryMatches=False)\n    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol\
  \ query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0