Attempt 2 at organic sulfide, f1=0.0
(currently fails to compile, but committing anyway

The previous code seems to have a few issues that led to the low F1 score of 0.10:

1. **False positives**: The code classifies molecules as organic sulfides if they contain any sulfur atom with exactly two non-hydrogen substituents. However, some of the false positives like `cyclooctasulfur` and `Mo(VI)-molybdopterin guanine dinucleotide(4-)` contain sulfur atoms with more than two non-hydrogen substituents, which should not be classified as organic sulfides.

2. **False negatives**: The code misses some organic sulfides where the sulfur atom has one non-hydrogen substituent and one hydrogen substituent (e.g., `1-isothiocyanato-6-(methylsulfanyl)hexane`). According to the definition, organic sulfides should have the structure `RSR` where `R` can be any substituent except hydrogen.

3. **Handling tautomers**: The code does not account for tautomers, where the position of the hydrogen atom can shift between different resonance structures. For example, in `(Z)-N-(sulfonatooxy)prop-2-enimidothioate`, the sulfur atom has two non-hydrogen substituents in one tautomeric form but only one in the other.

To improve the performance, we can make the following changes:

1. **Check for exactly two non-hydrogen substituents**: Instead of checking that each sulfur atom has at least two non-hydrogen substituents, we should check that it has exactly two non-hydrogen substituents.

2. **Handle tautomers**: We can use the `Chem.MolFromSmiles` function with the `isomericSmiles=True` flag to generate the isomeric SMILES string, which considers all possible tautomeric forms.

3. **Check for specific functional groups**: We can look for specific functional groups or patterns that are indicative of organic sulfides, such as the presence of the `C-S-C` pattern.

Here's an improved version of the code:

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.10292692382244621 is too low.
Outcomes:
------

True positives: SMILES: CSC1=C(C)C=C(OC(=O)NCCC(O)=O)C=C1C NAME: MXNP REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CN1C=NC(=C1SC2=NN=CN2C)[N+](=O)[O-] NAME: 4-methyl-3-[(3-methyl-5-nitro-4-imidazolyl)thio]-1,2,4-triazole REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: N[C@@H](CS[C@H](\C=C\C=C\C=C/CCCC(O)=O)[C@@H](O)CCCC(O)=O)C(O)=O NAME: 16-carboxy-17,18,19,20-tetranor-leukotriene E3 REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: COC(=O)CCSCCO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O[C@@H]2O[C@H](CO)[C@H](O)[C@H](O)[C@H]2O)[C@H]1NC(C)=O NAME: methyl 3-({2-[(2-acetamido-2-deoxy-3-O-beta-D-galactopyranosyl-beta-D-glucopyranosyl)oxy]ethyl}sulfanyl)propanoate REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S(CCC)CCO NAME: 2-Hydroxyethyl propyl sulfide REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C=1C(=CC=CC1)SC NAME: thioanisole REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: [C@H]1([C@H]([C@H](CC1=O)SC[C@H](NC(CC[C@H](N)C(=O)O)=O)C(=O)NCC(=O)O)/C=C/[C@H](CCCCC)O)C/C=C\CCCC(=O)O NAME: (S)-PGA2-S-glutathione conjugate REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CSCCCC(=O)C(O)=O NAME: 5-methylthio-2-oxopentanoic acid REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C1=CNC(=C1)C(=O)CSC2=NN=C(O2)C3=CC=CO3 NAME: 2-[[5-(2-furanyl)-1,3,4-oxadiazol-2-yl]thio]-1-(1H-pyrrol-2-yl)ethanone REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C/C(=C(\SC)/[H])/[H] NAME: (Z)-1-(Methylthio)-1-propene REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C1=CC=C(C=C1)CSC2=CC=C(O2)C=C3C(=N)N4C(=NC3=O)SC=N4 NAME: 5-imino-6-[[5-(phenylmethylthio)-2-furanyl]methylidene]-[1,3,4]thiadiazolo[3,2-a]pyrimidin-7-one REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC1=C(C=C(C=C1)SC2=CC=C(C=C2)NC(=O)CCl)C NAME: 2-chloro-N-[4-[(3,4-dimethylphenyl)thio]phenyl]acetamide REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC(C)(C)C(=O)NC(C(Cl)(Cl)Cl)SC1=NC=CC=N1 NAME: 2,2-dimethyl-N-[2,2,2-trichloro-1-(2-pyrimidinylthio)ethyl]propanamide REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: [H][C@@]12Cc3c[nH]c4cccc(c34)[C@@]1([H])C[C@@H](CSC)CN2CCC NAME: pergolide REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC(=C1C(=O)C2=CC=CC=C2S1)NC3=CC=CC=C3O NAME: 2-[1-(2-hydroxyanilino)ethylidene]-1-benzothiophen-3-one REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: N(C(=O)O[C@H](C)C1=CC=CC=C1Cl)C2=C(C=3C=CC(CSCCC(=O)O)=CC3)ON=C2C NAME: (R)-KI16425 REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S(C1=CC=C(C=C1)C)C=2N=CC=CC2C(O)=O NAME: 2-[(4-Methylphenyl)thio]nicotinic acid REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CSC([C@H](N)C(O)=O)C(O)=O NAME: 3-methylthioaspartic acid REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC1=NN2C(=N)C(=CC3=CC=C(O3)SCC4=CC=CC=C4)C(=O)N=C2S1 NAME: 5-imino-2-methyl-6-[[5-(phenylmethylthio)-2-furanyl]methylidene]-[1,3,4]thiadiazolo[3,2-a]pyrimidin-7-one REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: ClC1=CC=2N=C3NC=4C(SC3=NC2C=C1)=CC=CC4 NAME: 9-chloro-12H-benzo[5,6][1,4]thiazino[2,3-b]quinoxaline REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CN(C1=C(N(C(=O)NC1=O)CC2=CC=CC=C2)N)C(=O)CSC3=NN=C(S3)N NAME: N-[6-amino-2,4-dioxo-1-(phenylmethyl)-5-pyrimidinyl]-2-[(5-amino-1,3,4-thiadiazol-2-yl)thio]-N-methylacetamide REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S(C(C)C(=O)C)C1=C(OC=C1)C NAME: (+/-)-3-[(2-methyl-3-furyl)thio]-2-butanone REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S(C1=C(F)C=C(F)C=C1)CC#N NAME: 2-[(2,4-Difluorophenyl)thio]acetonitrile REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CNCC1=CC=CC=C1SC2=C(C=C(C=C2)[N+]#[C-])N NAME: 5-isocyano-2-[[2-(methylaminomethyl)phenyl]thio]aniline REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: COC(=O)C1=CC(=C(C=C1)SC2=CC=C(C=C2)Cl)N NAME: 3-amino-4-[(4-chlorophenyl)thio]benzoic acid methyl ester REASON: CORRECT Contains sulfur atoms with two non-hydrogen substituents (RSR)
False positives: SMILES: [H][C@]12NC3=C(N[C@@]1([H])C1=C(S[Mo-]([O-])(=O)(=O)S1)[C@@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)N1C=NC4=C1N=C(N)NC4=O)O2)C(=O)NC(N)=N3 NAME: Mo(VI)-molybdopterin guanine dinucleotide(4-) REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CCSC1=NN=C(S1)NC(=O)CSC2=NCCS2 NAME: 2-(4,5-dihydrothiazol-2-ylthio)-N-[5-(ethylthio)-1,3,4-thiadiazol-2-yl]acetamide REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CSCC[C@H](NC(=O)CNC(=O)[C@H](CCCNC(N)=N)NC(=O)[C@@H](N)CCC(O)=O)C(O)=O NAME: Glu-Arg-Gly-Met REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: N[C@@H](CCSC[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1cnc2c(O)ncnc12)C(O)=O NAME: S-inosyl-L-homocysteine REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CN1C=CC=C1CC2=NN=C(N2C3=CC=C(C=C3)OC)SCC(=O)NCC4=CC=C(C=C4)F NAME: N-[(4-fluorophenyl)methyl]-2-[[4-(4-methoxyphenyl)-5-[(1-methyl-2-pyrrolyl)methyl]-1,2,4-triazol-3-yl]thio]acetamide REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S1SSSSSSS1 NAME: cyclooctasulfur REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: [H]C(=Cc1cc[n+](CCCC(CCCC(CCC[n+]2ccc(C([H])=CC([H])=C3Sc4ccccc4N3C)c3ccccc23)=[N+](C)C)=[N+](C)C)c2ccccc12)C([H])=C1Sc2ccccc2N1C NAME: ToTo-3(4+) REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC(C)(COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12)[C@@H](O)C(=O)NCCC(=O)NCCSC(=O)CC(O)=O NAME: malonyl-CoA REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C1=CC=C(C=C1)C2=NN3C(=NN=C3S2)CN4C5=CC=CC=C5N=N4 NAME: 3-(1-benzotriazolylmethyl)-6-phenyl-[1,2,4]triazolo[3,4-b][1,3,4]thiadiazole REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S1C(=NC(=C1)/C=C/C(OC)C(/C(/OC)=C\C(=O)OC)C)C=2N=C(C(=C)C)SC2 NAME: Melithiazol B REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S1C(CC2=CC=C(OCCN(C3=NC=C(OC4OC(C(O)C(O)C4O)C(O)=O)C=C3)C)C=C2)C(=O)NC1=O NAME: p-O-glucuronide rosiglitazone REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C[C@@H]1O[C@@H](OCCCCCCCC[C@@H](O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](O)[C@@H]2OP([O-])([O-])=O)N3C=NC4=C(N)N=CN=C34)[C@H](O)C[C@H]1O NAME: bhos#18-CoA(4-) REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC1=CC=CC2=C1NC3=C2N=NC(=N3)SCC=C NAME: 6-methyl-3-(prop-2-enylthio)-5H-[1,2,4]triazino[5,6-b]indole REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C(NC(CCNC(=O)[C@@H](C(COP([O-])(=O)[O-])(C)C)O)=O)CSC(=O)CCCCCCC/C=C\C/C=C\CCCCC NAME: S-(9Z,12Z-octadecadienoyl)-4'-phosphopantetheine(2-) REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCCCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12 NAME: (23Z,26Z,29Z,32Z)-octatriacontatetraenoyl-CoA REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: Cl.Cl.[H][C@@]1(NC(=O)Cc2csc(N)n2)C(=O)N2C(C(=O)OC(C)OC(=O)OC3CCCCC3)=C(CSc3nnnn3CCN(C)C)CS[C@]12[H] NAME: cefotiam hexetil dihydrochloride REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S1C(CNC)=CC=C1C2=CC=NC=C2 NAME: N-methyl-(5-pyrid-4-ylthien-2-yl)methylamine REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: COC1=CC=CC=C1C(=O)CSC2=NN=C(O2)C3=CC=CO3 NAME: 2-[[5-(2-furanyl)-1,3,4-oxadiazol-2-yl]thio]-1-(2-methoxyphenyl)ethanone REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC1(CC2=C(C(=NC(=C2CS1)C3=CC=CO3)N4CCN(CC4)C(=O)C5=CC=CO5)C#N)C NAME: 8-(2-furanyl)-6-[4-[2-furanyl(oxo)methyl]-1-piperazinyl]-3,3-dimethyl-1,4-dihydrothiopyrano[3,4-c]pyridine-5-carbonitrile REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C[C@H]1CN([C@@H](COC2=C(C=CC(=C2)NC(=O)C3=NC4=CC=CC=C4S3)C(=O)N(C[C@@H]1OC)C)C)CC5=CC=C(C=C5)OC NAME: N-[(5R,6S,9R)-5-methoxy-8-[(4-methoxyphenyl)methyl]-3,6,9-trimethyl-2-oxo-11-oxa-3,8-diazabicyclo[10.4.0]hexadeca-1(12),13,15-trien-14-yl]-1,3-benzothiazole-2-carboxamide REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC1=C(N=C(S1)N2C(=O)C3C4CCC(C3C2=O)C4=C(C)C)C5=CC=CC=C5 NAME: LSM-25805 REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: S(CC[C@H](NC(=O)[C@@H](N)CC(C)C)C(=O)N[C@@H](CC1=CC=CC=C1)C(O)=O)C NAME: Leu-Met-Phe REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC(C)CCCC(C)CCC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12 NAME: 4,8-dimethylnonanoyl-CoA(4-) REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: CC(C)C(=O)NNC(=O)CSC1=NC(=NC2=CC=CC=C21)C3CCCCC3 NAME: N'-[2-[(2-cyclohexyl-4-quinazolinyl)thio]-1-oxoethyl]-2-methylpropanehydrazide REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
 * SMILES: C1CC(=CC2=CC=CS2)C3=NC4=CC=CC=C4C(=C3C1)C(=O)OCC(=O)NC5=CC=CC=C5 NAME: 4-(thiophen-2-ylmethylidene)-2,3-dihydro-1H-acridine-9-carboxylic acid (2-anilino-2-oxoethyl) ester REASON: WRONGLY CLASSIFIED Contains sulfur atoms with two non-hydrogen substituents (RSR)
False negatives: SMILES: ClC=1C(S(=O)(=O)C(C)C)=C(SC1)SC NAME: 4-Chloro-3-(isopropylsulfonyl)-2-(methylthio)thiophene REASON: MISSED Sulfur atom has 4 non-hydrogen substituents, should be 2
 * SMILES: S(CCCCCCN=C=S)C NAME: 1-isothiocyanato-6-(methylsulfanyl)hexane REASON: MISSED Sulfur atom has 1 non-hydrogen substituents, should be 2
 * SMILES: [S-]/C(=[NH+]\OS([O-])(=O)=O)/CCCCSC NAME: (Z)-4-methylsulfanylbutyl-N-(sulfonatooxy)methanimidothioate REASON: MISSED Sulfur atom has 1 non-hydrogen substituents, should be 2
 * SMILES: C1CC2C(C(=C(C1C2)SC3=CC=CC=C3)C(C4=CC=C(C=C4Cl)S(C)(=O)=O)=O)=O NAME: 3-[2-chloro-4-(methylsulfonyl)benzoyl]-4-(phenylthio)bicyclo[3.2.1]oct-3-en-2-one REASON: MISSED Sulfur atom has 4 non-hydrogen substituents, should be 2
 * SMILES: CN(C)CC[C@H](CSC1=CC=CC=C1)NC1=C(C=C(C=C1)S(=O)(=O)NC(=O)C1=CC=C(C=C1)N1CCN(CC2=CC=CC=C2C2=CC=C(Cl)C=C2)CC1)[N+]([O-])=O NAME: ABT-737 REASON: MISSED Sulfur atom has 4 non-hydrogen substituents, should be 2
 * SMILES: N([C@@H]1[C@H]2C[C@@H](C1)CC2)C=3N=CN=C4N(C=NC34)C NAME: N-((1R,2S,4S)-Bicyclo[2.2.1]heptan-2-yl)-9-methyl-9H-purin-6-amine REASON: MISSED No sulfur atoms found
 * SMILES: [S-]/C(=N\OS([O-])(=O)=O)/C[C@H](C=C)O NAME: (Z)-(2R)-2-hydroxy-3-butenyl-N-(sulfonatooxy)methanimidothioate REASON: MISSED Sulfur atom has 1 non-hydrogen substituents, should be 2
 * SMILES: [S-]/C(=N\OS([O-])(=O)=O)/CC=C NAME: (Z)-N-(sulfonatooxy)prop-2-enimidothioate REASON: MISSED Sulfur atom has 1 non-hydrogen substituents, should be 2
 * SMILES: [C@H]1(O[C@@H]([C@@H](O)[C@@H]([C@H]1O)O)CO)S/C(=N\OS(O)(=O)=O)/CCCCCSC NAME: glucoberteroin REASON: MISSED Sulfur atom has 4 non-hydrogen substituents, should be 2
 * SMILES: CN1N=C(C(\C=C2/SC(=S)NC2=O)=C1SCC1=CC=C(Cl)C=C1)C(F)(F)F NAME: (5Z)-5-[(5-{[(4-chlorophenyl)methyl]sulfanyl}-1-methyl-3-(trifluoromethyl)pyrazol-4-yl)methylidene]-2-sulfanylidene-1,3-thiazolidin-4-one REASON: MISSED Sulfur atom has 1 non-hydrogen substituents, should be 2
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:16385
  name: organic sulfide
  definition: Compounds having the structure RSR (R =/= H). Such compounds were once
    called thioethers.
  parents:
  - CHEBI:26822
  - CHEBI:33261
  xrefs:
  - KEGG:C00297
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 26
  log_lines_of_code: 3.258096538021482
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmiles
  - GetSymbol
  - GetNeighbors
  - HasSubstructMatch
  - MolFromSmarts
  - GetAtoms
  - GetAtomicNum
  methods_called_count: 7
  smarts_strings:
  - '[C&!R]-[S&!R]-[C&!R]'
  smarts_strings_count: 1
  defs:
  - 'is_organic_sulfide(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No sulfur atoms found"
  - False, f"Sulfur atom has {sum(r_groups)} non-hydrogen substituents, should be
    2"
  - True, "Contains C-S-C pattern characteristic of organic sulfides"
  - True, "Contains sulfur atoms with two non-hydrogen substituents (RSR)"
  returns_count: 5
  complexity: 3.8516193076042966
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "Python argument types in\n    rdkit.Chem.rdmolfiles.MolFromSmiles(str)\ndid\
  \ not match C++ signature:\n    MolFromSmiles(boost::python::api::object SMILES,\
  \ bool sanitize=True, boost::python::dict replacements={})\n    MolFromSmiles(boost::python::api::object\
  \ SMILES, RDKit::v1::SmilesParserParams params)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []