Reverting to best solution for ceramide, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:17761
  name: ceramide
  definition: Ceramides (N-acyl-sphingoid bases) are a major subclass of sphingoid
    base derivatives with an amide-linked fatty acid. The fatty acids are typically
    saturated or monounsaturated with chain lengths from 14 to 26 carbon atoms; the
    presence of a hydroxyl group on carbon 2 is fairly common. Ceramides are generally
    precursors of more complex sphingolipids. In the illustrated generalised structure,
    R(1) = OH, OX (where X = acyl, glycosyl, phosphate, phosphonate, etc.), or H.
  parents:
  - CHEBI:26739
  - CHEBI:37622
  xrefs:
  - KEGG:C00195
  - LIPID_MAPS_class:LMSP02
  - PMID:7542630
  - Wikipedia:Ceramide
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 64
  log_lines_of_code: 4.1588830833596715
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 2
  methods_called:
  - MolFromSmarts
  - FragmentOnBonds
  - GetBondBetweenAtoms
  - count
  - CalcNumDoubleBonds
  - GetMolFrags
  - GetAtoms
  - GetSubstructMatches
  - GetIdx
  - MolFromSmiles
  - GetAtomicNum
  methods_called_count: 11
  smarts_strings:
  - '"[OX2H]"))'
  - '"[C][O][H]")'
  - C(=O)N
  smarts_strings_count: 3
  defs:
  - 'is_ceramide(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No amide bond found"
  - False, "Could not separate fatty acid and sphingoid base"
  - False, "Could not identify fatty acid and sphingoid base fragments"
  - False, f"Fatty acid chain length is {fatty_acid_carbons}, which is outside 14-26
    carbons"
  - False, f"Fatty acid has {fatty_acid_unsaturations} double bonds, should be saturated
    or monounsaturated"
  - False, f"Sphingoid base chain length is {sphingoid_base_carbons}, which is too
    short"
  - False, "No hydroxyl groups found on sphingoid base"
  - False, "Hydroxyl groups not attached to carbon in sphingoid base"
  - True, "Molecule is a ceramide with appropriate chain lengths and functional groups"
  returns_count: 10
  complexity: 5.8317766166719345
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_ceramide('O=C(N[C@H]([C@H](O)/C=C/C/C=C/C(O)(CCCCCCCCC)C)CO[C@@H]1O[C@@H]([C@@H](O)[C@@H]([C@H]1O)O)CO)[C@H](O)CCCCCCCCCCCCCC'):\n\
  \ module 'rdkit.Chem.rdMolDescriptors' has no attribute 'CalcNumDoubleBonds'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0