Attempt 1 at polyphenol, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:26195
  name: polyphenol
  definition: Members of the class of phenols that contain 2 or more benzene rings
    each of which is substituted by at least one hydroxy group.
  parents:
  - CHEBI:33853
  xrefs:
  - Wikipedia:Polyphenol
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []