Attempt 3 at carbonate ester, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.39622641509433965 is too low.
Outcomes:
------

True positives: SMILES: O=C1O[C@H]2C=C(C)[C@H]([C@@H]([C@H]2O1)O)O NAME: (3aR,4S,5R,7aS)-4,5-dihydroxy-6-methyl-3a,4,5,7a-tetrahydro-1,3-benzodioxol-2-one REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@H]2C(=C(CO)[C@H]([C@@H]([C@H]2O1)O)O)/C=C/CCCCC NAME: Phomoxin C REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@@H]2C(=C(CO)[C@H]([C@H]([C@@H]2O1)O)O)/C=C/C NAME: Aspergone Q REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: C=1C(=C(C(=C(C1)C(=O)C=2C=NN(C2O[C@@H](OC(OC)=O)C)CC)C)OCCOC)S(C)(=O)=O NAME: (S)-tolpyralate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: COC(=O)OC NAME: dimethyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: CCOC(O)=O NAME: monoethyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: [H]C1(COC(O)=O)c2ccccc2-c2ccccc12 NAME: fluoren-9-ylmethyl hydrogen carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@@H]2C(=C[C@@H]([C@H]([C@@H]2O1)O)O)C NAME: (3aS,4R,5S,7aR)-4,5-dihydroxy-7-methyl-3a,4,5,7a-tetrahydrobenzo[1,3]dioxol-2-one REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: C=1(C=CC(=CC1)[N+]([O-])=O)COC(OC)=O NAME: methyl 4-nitrobenzyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O(CC)C(OCC)=O NAME: Diethyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: CCOC(=O)OC1=C(C(=O)N(C)C11CCN(CC1)OC)C1=C(C)C=C(Cl)C=C1C NAME: spiropidion REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C(Oc1ccccc1)Oc1ccccc1 NAME: diphenyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: [H][C@]12[C@H](CC3=CC=CC=C3)NC(=O)[C@]11OC(=O)O\C=C\[C@H](C)C(=O)[C@@H](C)C\C=C\[C@H]1C=C(C)[C@H]2C NAME: cytochalasin Z16 REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: CCCC(=C(C(=C(C(=C(CCC1=CC=C(O1)OC(=O)O)[H])[H])[H])[H])[H])[H] NAME: 5-(undeca-3,5,7-trien-1-yl)-2-furyl hydrogen carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@H]2C(=C(CO)[C@@H]([C@@H]([C@H]2O1)O)O)/C=C/CCCCC NAME: Phomoxin REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@H]2[C@@](O)(C#CC(=C)C)[C@@H](O)CC[C@H]2O1 NAME: Stagonosporyne D REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@@H]2C=C[C@@H]([C@]([C@@H]2O1)(O)C#CC(=C)C)O NAME: Stagonosporyne E REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O1CCOC1=O NAME: Ethylene carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: CC/C=C\CCOC(OC)=O NAME: (Z)-hex-3-en-1-yl methyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: ClC1OC(OC1Cl)=O NAME: 4,5-Dichloro-1,3-dioxolan-2-one REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
 * SMILES: O(CCC(C)=C)C(OCC)=O NAME: Ethyl 3-methylbut-3-enyl carbonate REASON: CORRECT Contains carbonate ester functional group with organyl groups attached
False positives: SMILES: [H][C@]12SCC(COC)=C(N1C(=O)[C@H]2NC(=O)C(=N/OC)\c1csc(N)n1)C(=O)OC(C)OC(=O)OC(C)C NAME: cefpodoxime proxetil REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1OC=C[C@@](O)(C(=O)[C@@H](C)CC=C[C@@H]2[C@]3(O1)C(=O)N[C@H]([C@@H]3[C@H](C)[C@@]4([C@H]2O4)C)CC5=CC=C(OC)C=C5)C NAME: Phenochalasin B REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O(C1C(CCC(C1)C)C(C)C)C(OCCO)=O NAME: Menthyl ethylene glycol carbonate REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@H]([C@@H]([C@@H]2O[C@@H]2C=CC(=O)[C@H](C[C@H]([C@H]([C@H](C=C1)C)O[C@@H]3O[C@@H](C[C@]4([C@H]3O)OC(=O)O[C@H]4C)C)C)C)CO[C@@H]5O[C@@H]([C@@H](O)[C@@H]([C@H]5OC)OC)C)C NAME: Aldgamycin G REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O(C1C(CCC(C1)C)C(C)C)C(OCC(O)C)=O NAME: 2-Hydroxypropyl 2-isopropyl-5-methylcyclohexyl carbonate REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O1[C@@H]([C@@H](O)[C@H](O)[C@@H](O)[C@@H]1OC=2C(C(=O)CCC3=CC4=C(OC=C4)C=C3)=C(O)C=C(C2)C)COC(OC)=O NAME: ((2R,3S,4S,5R,6S)-6-(2-(3-(Benzofuran-5-yl)propanoyl)-3-hydroxy-5-methylphenoxy)-3,4,5-trihydroxytetrahydro-2H-pyran-2-yl)methyl methyl carbonate REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: [H+].[Cl-].[H][C@]12SC(C)(C)[C@@]([H])(N1C(=O)[C@H]2NC(=O)[C@H](N)c1ccccc1)C(=O)OC(C)OC(=O)OCC NAME: bacampicillin hydrochloride REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: OC(=O)OON=O NAME: nitrosoperoxycarbonic acid REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1OC=C[C@@](O)(C(=O)[C@@H](C)CC=C[C@@H]2[C@]3(O1)C(=O)N[C@H]([C@@H]3[C@H](C)C(C2O)=C)CC4=CC=CC=C4)C NAME: (1S,5E,7R,9S,11E,13S,16S,17S,18S)-18-benzyl-7,14-dihydroxy-7,9,16-trimethyl-15-methylidene-2,4-dioxa-19-azatricyclo[11.7.0.01,17]icosa-5,11-diene-3,8,20-trione REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@@H]([C@H](C=CCCC(=O)[C@@H](C[C@@H]([C@@H]([C@H](C=C1)C)O[C@@H]2O[C@@H](C[C@]3([C@H]2O)OC(=O)O[C@H]3C)C)C)C)CO[C@@H]4O[C@@H]([C@@H](O)[C@H]([C@H]4OC)OC)C)C NAME: Aldgamycin M REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O(C(O)=O)P(O)(=O)O NAME: carboxyphosphoric acid REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: CCOC(=O)OC(=O)OCC NAME: diethyl pyrocarbonate REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O1[C@@H]([C@@H](O)[C@H](O)[C@@H](O)[C@@H]1OC=2C(CC3=CC=C(OC)C=C3)=CC=CC2)COC(OCC)=O NAME: Sergliflozin etabonate REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: C(N(/C(=C(\SC(OCC)=O)/CCOC(OCC)=O)/C)C=O)C=1C(N)=NC(=NC1)C NAME: cetotiamine REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1OC(C2=C[C@@H](OC(=O)OC)[C@]3([C@H]([C@H](C2=C1)C)C[C@]4(C(=O)O[C@@H]5[C@H]4[C@H]3C(=O)[C@@H](O5)C)C)C)(C)C NAME: 22-deoxyminiolutelide A REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: CC(C)(C)OC(=O)OC(=O)OC(C)(C)C NAME: tert-butoxycarbonyl anhydride REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1[C@H]2[C@@]3(O)[C@](C(=O)O[C@H]3O[C@H]1C)(C[C@@H]4[C@H]2[C@H](OC(=O)OC)C=C5C(OC(CC5=C4C)=O)(C)C)C NAME: Isominiolutelide A REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1OC(C(C2OC2CCC(=O)C(CC(C(C(C=C1)C)O[C@@H]3O[C@@H](C[C@]4([C@H]3O)OC(=O)O[C@H]4C)C)C)C)CO[C@@H]5O[C@@H]([C@@H](O)[C@H]([C@H]5OC)OC)C)C NAME: Aldgamycin E REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: [H][C@@]1(CN2CC[C@@]34C(Nc5ccccc35)=C(C(=O)OC)[C@@]1([H])C[C@]24[H])[C@@H](C)OC(=O)OCC NAME: (-)-Alstolucine A, (rel)- REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: C(OC(OCC(C)C)=O)N1C(=O)CN(CC1=O)CCN2CC(=O)N(C(C2)=O)COC(OCC(C)C)=O NAME: Sobuzoxane REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: CCOC(=O)OC1=C(C=C(C=C1OC)C(=O)O[C@@H]2C[C@@H]3CN4CCC5=C([C@H]4C[C@@H]3[C@@H]([C@H]2OC)C(=O)OC)NC6=C5C=CC(=C6)OC)OC NAME: Syrosingopine REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1O[C@@](C#CC2=C(OC)C=C(OC)C(=C2C)OC)(C)[C@@](O1)(C#CC3=C(OC)C=C(OC)C(=C3C)OC)C NAME: Antrodioxolanone REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: Cl.Cl.[H][C@@]1(NC(=O)Cc2csc(N)n2)C(=O)N2C(C(=O)OC(C)OC(=O)OC3CCCCC3)=C(CSc3nnnn3CCN(C)C)CS[C@]12[H] NAME: cefotiam hexetil dihydrochloride REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O=C1N[C@@H](CC2=CC=CC=C2)[C@H]3[C@]1(OC(=O)OC)[C@@H](/C=C/C[C@@H](C(=O)C(O)(CC=O)C)C)[C@H](O)C(=C)[C@H]3C NAME: Cytochalasin Z19 REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
 * SMILES: O(C(OC1=C(OC)C=CC=C1)=O)C2=C(OC)C=CC=C2 NAME: guaiacol carbonate REASON: WRONGLY CLASSIFIED Contains carbonate ester functional group with organyl groups attached
False negatives: SMILES: CCOc1nc2cccc(C(=O)OCc3oc(=O)oc3C)c2n1Cc1ccc(cc1)-c1ccccc1-c1noc(=O)[nH]1 NAME: azilsartan medoxomil REASON: MISSED No carbonate ester functional group found
 * SMILES: O=C1OC(=O)C=CO1 NAME: Pleurone REASON: MISSED No carbonate ester functional group found
 * SMILES: CC(C)(C)C(=O)OCOP(=O)(COCCN1C=NC2=C1N=CN=C2N)OCOC(=O)C(C)(C)C NAME: adefovir pivoxil REASON: MISSED No carbonate ester functional group found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:46722
  name: carbonate ester
  definition: Any carbonate that is carbonic acid in which the hydrogens have been
    replaced by organyl groups.
  parents:
  - CHEBI:23016
  - CHEBI:33308
  xrefs:
  - Wikipedia:Carbonate_ester
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: invalid syntax (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []