Reverting to best solution for polymer, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:60027
  name: polymer
  definition: A polymer is a mixture, which is composed of macromolecules of different
    kinds and which may be differentiated by composition, length, degree of branching
    etc..
  parents:
  - CHEBI:60004
  xrefs:
  - Wikipedia:Polymer
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 36
  log_lines_of_code: 3.58351893845611
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem, rdMolDescriptors
  imports_count: 2
  methods_called:
  - CalcExactMolWt
  - FindMolChemicalEnvironmentOfAtoms
  - MolFromSmarts
  - GetMolFrags
  - SSMatSmin
  - MolFromSmiles
  - GetSubstructMatches
  methods_called_count: 7
  smarts_strings:
  - '[CX4,CX3]~[CX4,CX3]~[CX4,CX3]~[CX4,CX3]~[CX4,CX3]'
  smarts_strings_count: 1
  defs:
  - 'is_polymer(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Only one unique structural unit (monomer) found"
  - False, "Molecular weight too low or insufficient repeating units for polymer"
  - True, "Contains long carbon chains and repeating structural units (polymeric)"
  - True, "Contains repeating structural units (polymeric)"
  returns_count: 5
  complexity: 3.716703787691222
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: unterminated string literal (detected at line 1) (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0