Attempt 4 at mucopolysaccharide, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: O(C1C(O)C(C=C(C(OC(=O)N)C(OC)CCC=C(C(=O)NC=2C=C(CC(C1)C)C=C(O)C2)C)C)C)C NAME: [(4E,10E)-13,20-dihydroxy-8,14-dimethoxy-4,10,12,16-tetramethyl-3-oxo-2-azabicyclo[16.3.1]docosa-1(21),4,10,18(22),19-pentaen-9-yl] carbamate REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: O=C1NCC[C@H](O)[C@@H]2NC(=O)C(C2=O)=C(O)C=C[C@H]3[C@H](CC=C1)[C@H]4C=C[C@H]5[C@H](C(=O)CO)[C@@H](C[C@@H]5[C@H]4C3)C NAME: Clifednamide E REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: O=C1[C@H]2[C@@H]([C@H](O)[C@H]([C@@H](O)[C@H]([C@H](OC(=O)C)[C@@H]([C@@H](OC)C=CO[C@@]3(C(C4=C5C(C=6O[C@@](C1)(C(=O)NC6C=C5O)C)=C(O)C(=C4O3)C)=O)C)C)C)C)C2 NAME: Rifamorpholine C REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: O=C1NC(C(=O)NCCCC(C(NC(C1=O)C)=O)NC(=O)/C=C/CCC(C)C)C(C)C NAME: Eurystatin C REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: S1C2=NC(=C1)C(=O)NC(C=3SC=C(N3)C(=O)NC(C=4OC(=C(N4)C(=O)NC2C(C)C)C)C)C NAME: 4,7,18-Trimethyl-11-propan-2-yl-6-oxa-13,20-dithia-3,10,17,22,23,24-hexazatetracyclo[17.2.1.15,8.112,15]tetracosa-1(21),5(24),7,12(23),14,19(22)-hexaene-2,9,16-trione REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: S1[C@H](CC(=O)N[C@H](C=2SC[C@H](C(N[C@@H](C1)CO)=O)N2)CC3=CC=CC=C3)CC(C)C NAME: Thioamycolamide C REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: S1C2=NC(=C1)C(=O)N[C@H](C=3OC(C)=C(N3)C(=O)NCC4=NC(C(N[C@@H]2CCSC)=O)=CS4)C NAME: Nostocyclamide M REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: S1C2=NC(=C1)C(=O)N[C@H](C=3OC(=C(N3)C(=O)NCC=4SC=C(N4)C(=O)N[C@@H]2C(C)C)C)C NAME: nostocyclamide REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: O=C1C(=C[C@@H]([C@@H](O)[C@H](C=C[C@@H](O)CC=C(C(=O)C[C@H](O)[C@H](C=CC=CC=CC(NC=2C(C(C=3C1=C(O)C(=CC3C2O)C)=O)=O)=O)C)C)C)CO)C NAME: Naphthomycin K REASON: MISSED Missing uronic acid or glycosamine units
 * SMILES: O=C1NC2=C(O)C(=CC(=C2)O)[C@H](OC)[C@H](C[C@H](OC)[C@H](OC)[C@H](C=C([C@@H]([C@H](C=CC=C1C)OC)OC(=O)N)C)C)C NAME: Dihydroherbimycin A REASON: MISSED Missing uronic acid or glycosamine units
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:37395
  name: mucopolysaccharide
  definition: Any of the group of polysaccharides composed of alternating units from
    uronic acids and glycosamines, and commonly partially esterified with sulfuric
    acid.
  parents:
  - CHEBI:18085
  xrefs:
  - KEGG:C05114
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: unterminated string literal (detected at line 9) (<string>, line 9)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []