Attempt 1 at cephalosporin, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:23066
  name: cephalosporin
  definition: A class of beta-lactam antibiotics differing from the penicillins in
    having a 6-membered, rather than a 5-membered, side ring.  Although cephalosporins
    are among the most commonly used antibiotics in the treatment of routine infections,
    and their use is increasing over time, they can cause a range of hypersensitivity
    reactions, from mild, delayed-onset cutaneous reactions to life-threatening anaphylaxis
    in patients with immunoglobulin E (IgE)-mediated allergy.
  parents:
  - CHEBI:38311
  xrefs:
  - KEGG:C00875
  - PMID:10069359
  - PMID:11936371
  - PMID:12833570
  - PMID:24269048
  - PMID:3320614
  - PMID:6762896
  - PMID:8426246
  - Wikipedia:Cephalosporin
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []