Reverting to best solution for diterpenoid, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:23849
  name: diterpenoid
  definition: Any terpenoid derived from a diterpene. The term includes compounds
    in which the C20 skeleton of the parent diterpene has been rearranged or modified
    by the removal of one or more skeletal atoms (generally methyl groups).
  parents:
  - CHEBI:26873
  xrefs:
  - LIPID_MAPS_class:LMPR0104
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 32
  log_lines_of_code: 3.4657359027997265
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 2
  methods_called:
  - GetRingInfo
  - GetAtoms
  - GetAtomicNum
  - MolFromSmiles
  - IsInitialized
  - NumRings
  - AtomRings
  methods_called_count: 7
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_diterpenoid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Insufficient carbon atoms for diterpenoid (less than 20)"
  - False, "No ring structures found"
  - False, "Lacks larger ring structures typical of diterpenoids"
  - True, "Matches general diterpenoid structure based on ring presence and carbon
    count"
  returns_count: 5
  complexity: 3.693147180559945
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0