Reverting to best solution for secondary alpha-hydroxy ketone, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:2468
  name: secondary alpha-hydroxy ketone
  definition: An alpha-hydroxy ketone in which the carbonyl group and the hydroxy
    group are linked by a carbon bearing one hydrogen and one organyl group. Secondary
    alpha-hydroxy ketones are also known as acyloins, and are formally derived from
    reductive coupling of two carboxylic acid groups.
  parents:
  - CHEBI:139588
  - CHEBI:35681
  xrefs:
  - Wikipedia:Acyloin
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 36
  log_lines_of_code: 3.58351893845611
  max_indent: 4
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdChemReactions
  imports_count: 3
  methods_called:
  - GetIdx
  - HasQuery
  - GetTotalNumHs
  - GetAtoms
  - GetSymbol
  - append
  - FindAtomEnvironmentOfRadiusN
  - GetAtomWithIdx
  - MolFromSmarts
  - GetNeighbors
  - MolFromSmiles
  methods_called_count: 11
  smarts_strings:
  - carbonyl_smarts)
  - hydroxy_smarts)
  smarts_strings_count: 2
  defs:
  - 'is_secondary_alpha_hydroxy_ketone(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Missing carbonyl or hydroxy group"
  - True, "Contains a secondary alpha-hydroxy ketone moiety"
  - False, "No secondary alpha-hydroxy ketone moiety found"
  returns_count: 4
  complexity: 4.7167037876912215
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0