Reverting to best solution for long-chain fatty acyl-CoA(4-), f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:83139
  name: long-chain fatty acyl-CoA(4-)
  definition: A fatty acyl-CoA(4-) arising from deprotonation of the phosphate and
    diphosphate OH groups of any long-chain fatty acyl-CoA; major species at pH 7.3.
  parents:
  - CHEBI:77636
  xrefs:
  - MetaCyc:Long-Chain-Acyl-CoAs
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 31
  log_lines_of_code: 3.4339872044851463
  max_indent: 2
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - HasSubstructMatch
  - GetSubstructMatches
  - MolFromSmiles
  - MolFromSmarts
  methods_called_count: 4
  smarts_strings:
  - C[C,C,C=C,C=O]C(C)[C,C=C]
  - SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC
  - '[P](=O)([O-])([O-])O'
  smarts_strings_count: 3
  defs:
  - 'is_long_chain_fatty_acyl_CoA_4__(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No Coenzyme A structure found"
  - False, "No long-chain fatty acyl group detected"
  - False, "Insufficient phosphate groups (deprotonation assumed)"
  - True, "Identified as a long-chain fatty acyl-CoA(4-) structure"
  returns_count: 5
  complexity: 3.086797440897029
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Python argument types in\n    Mol.GetSubstructMatches(Mol, NoneType)\ndid\
  \ not match C++ signature:\n    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle\
  \ query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool uniquify=True, bool useChirality=False, bool\
  \ useQueryQueryMatches=False, unsigned int maxMatches=1000)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False,\
  \ unsigned int maxMatches=1000)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0