Attempt 2 at polysaccharide, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Error: No registered converter was able to produce a C++ rvalue of type unsigned int from this Python object of type numpy.int64
Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: NONE
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:18154
  name: polysaccharide
  definition: A biomacromolecule consisting of large numbers of monosaccharide residues
    linked glycosidically. This term is commonly used only for those containing more
    than ten monosaccharide residues.
  parents:
  - CHEBI:16646
  - CHEBI:167559
  - CHEBI:33694
  xrefs:
  - KEGG:C00420
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: unterminated string literal (detected at line 20) (<string>, line 20)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []