Reverting to best solution for 11,12-saturated fatty acyl-CoA(4-), f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:84948
  name: 11,12-saturated fatty acyl-CoA(4-)
  definition: Any fatty acyl-CoA(4-) in which the 11-12 bond of the fatty acyl group
    is saturated. This is needed for a reaction together with CHEBI:84947
  parents:
  - CHEBI:77636
  xrefs:
  - PMID:10563812
  - PMID:2295634
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 40
  log_lines_of_code: 3.6888794541139363
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - GetIdx
  - append
  - GetSubstructMatch
  - GetAtomWithIdx
  - MolFromSmiles
  - GetNeighbors
  - MolFromSmarts
  - GetAtomicNum
  - GetBondBetweenAtoms
  - HasSubstructMatch
  - GetBondType
  methods_called_count: 11
  smarts_strings:
  - '''SC(=O)'')'
  - CC(C)(COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12)C(O)C(=O)NCCC(=O)NCCS
  smarts_strings_count: 2
  defs:
  - 'is_11_12_saturated_fatty_acyl_CoA_4__(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Missing CoA substructure"
  - False, "Could not identify thioester carbon"
  - False, "Fatty acid chain too short to have a 11-12 bond"
  - False, "Could not identify bond between carbons 11 and 12"
  - False, "Bond between carbons 11 and 12 is not a single bond"
  - True, "Fatty acyl chain has a saturated bond between carbons 11 and 12 and is
    a CoA derivative"
  returns_count: 7
  complexity: 4.937775890822787
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_11_12_saturated_fatty_acyl_CoA_4__('CCCCC\\\\C=C/C\\\\\
  C=C/C\\\\C=C/C\\\\C=C/CCCCCCCCCCCC(=O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12'):\n\
  \ 'Atom' object has no attribute 'HasSubstructMatch'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0