Attempt 1 at 2-enoyl-CoA, f1=0.0
(currently fails to compile, but committing anyway

Here's a Python program to classify chemical entities of the class 2-enoyl-CoA:
# INFORMATION:

---
chemical_class:
  id: CHEBI:19573
  name: 2-enoyl-CoA
  definition: An unsaturated fatty acyl-CoA in which the S-acyl group contains a double
    bond between positions 2 and 3.
  parents:
  - CHEBI:51006
  xrefs:
  - KEGG:C00605
  - MetaCyc:D2-ENOYL-COA
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 30
  log_lines_of_code: 3.4011973816621555
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmiles
  - CalcNumRotatableBonds
  - HasSubstructMatch
  - MolToSmiles
  - MolFromSmarts
  - split
  - GetSubstructMatches
  methods_called_count: 7
  smarts_strings:
  - '[CX4,CX3]~[CX4,CX3]~[CX4,CX3]~[CX4,CX3]'
  - C(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(=O)([O-])O)n1cnc2c(N)ncnc12)[C@@H](O)C(=O)NCCC(=O)NCCSC
  - C=CC(=O)SC
  smarts_strings_count: 3
  defs:
  - 'is_2_enoyl_CoA(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Missing CoA backbone"
  - False, "No double bond between positions 2 and 3 of the acyl group"
  - False, "The acyl group is saturated"
  - False, "Missing fatty acid chain in the acyl group"
  - True, "Contains an unsaturated fatty acyl-CoA with a double bond between positions
    2 and 3"
  returns_count: 6
  complexity: 3.880239476332431
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_2_enoyl_CoA('CCCCC\\\\C=C\\\\C=C\\\\C(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12'):\n\
  \ module 'rdkit.Chem' has no attribute 'CalcNumRotatableBonds'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []