Attempt 4 at secondary alcohol, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.07111864941621963 is too low.
Outcomes:
------

True positives: SMILES: O[C@H]1[C@@H](Oc2cc(O)cc(O)c2C1=O)c1cc(O)c(O)c(O)c1 NAME: (-)-dihydromyricetin REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CCCCC[C@H](O)\C=C\[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(O)=O NAME: prostaglandin E1 REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])CC=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CC\C(=C\C)C(C)C NAME: isofucosterol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@]12N(C)C3=C(C=C(Cl)C(OC)=C3OC)[C@@]1(O)[C@@H](O)[C@@]13SS[C@@](C)(N(C)C1=O)C(=O)N23 NAME: sporidesmin A REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CC(C)[C@@H](C)\C=C\[C@@H](C)[C@H]1CC=C2C3=CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C NAME: (22E,24S)-24-methylcholesta-5,7,14,22-tetraen-3beta-ol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CCCCCCCCCCCCCCC(C)O NAME: hexadecan-2-ol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [C@@]12([C@]3([C@](CC[C@@]1([C@@]4(C(C[C@H](CC4)O)=CC2)C)[H])([C@](CC3)([C@H](C)CC[C@@H](C(C)C)OS(O)(=O)=O)[H])C)[H])[H] NAME: (24S)-hydroxycholesterol 24-sulfate REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)[C@H](O)C[C@H]1C[C@@H](O)CC[C@]31C NAME: 5alpha-androstane-3beta,7alpha,17beta-triol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: C(=C\C/C=C\CCCC(C)O)\CCCCCCCC(=O)O NAME: (9Z,12Z)-17-hydroxyoctadeca-9,12-dienoic acid REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@@]12CC[C@@]3([H])[C@]4([H])CC[C@]([H])([C@H](C)[C@@H](O)C[C@@H](C)C(C)C)[C@@]4(C)CC[C@]3([H])[C@@]1(C)CC[C@H](O)C2 NAME: 6-deoxycathasterone REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: C[C@@H](O)C(=O)O[C@H]1C=C[C@](CC(=O)C(O)=O)(C=C1)C(O)=O NAME: D-prephenyl lactate REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@@]12CC(C)(C)CC[C@]1(C)CC[C@]1(C)C2=C[C@@H](O)[C@]2([H])[C@@]3(C)CC[C@H](O)C(C)(C)[C@]3([H])CC[C@@]12C NAME: 11alpha-hydroxy-beta-amyrin REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: C(CCC)C/C=C\C/C=C\C[C@@H]([C@H](C/C=C\CCCC(O)=O)O)O NAME: (5Z,8S,9S,11Z,14Z)-8,9-dihydroxyicosatrienoic acid REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: N[C@@H](CS[C@H](\C=C\C=C\C=C/C\C=C/CCCCCO)[C@@H](O)CCCC(O)=O)C(O)=O NAME: 20-hydroxy-leukotriene E4 REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CCCCCCCCCC(O)CCCCCCCCC NAME: nonadecan-10-ol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@@]12CCC(=O)[C@@]1(C)CC[C@@]1([H])[C@@]2([H])[C@@H](O)C=C2C[C@@H](O)CC[C@]12C NAME: 7beta-hydroxydehydroepiandrosterone REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CC(C)NCC(O)c1ccc(NS(C)(=O)=O)cc1 NAME: sotalol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CCCCCCCCCCCCCCCCCCCCCC(O)CCCC NAME: hexacosan-5-ol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: O[C@H]1C(=C)C2(C(CO)=C3[C@@H]1CC(C)(C)C3)CC2 NAME: (3aS,4R)-7-(hydroxymethyl)-2,2-dimethyl-5-methylidenespiro[1,3,3a,4-tetrahydroindene-6,1'-cyclopropane]-4-ol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: COC1=C(O)C2=C(N=C1C1=COC(=N1)C1=CC=CC=C1N)C(=O)N(S2)[C@@H](CO)C(=O)NC[C@@H](O)C(=O)N[C@H](CO)CC(C)C NAME: levesquamide REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CC1(C)[C@H]2C[C@@H]1C(=C)[C@H](O)C2 NAME: (-)-trans-pinocarveol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@@]12CC=C3[C@]4([H])CC[C@]([H])([C@H](C)CCCC(C)C)[C@@]4(C)CC[C@]3([H])[C@@]1(C)CC[C@H](O)C2 NAME: 5alpha-cholest-7-en-3beta-ol REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: [H][C@]12CC[C@]3([H])[C@]([H])(CC[C@]4(C)[C@]([H])([C@@H](O)C[C@]34O)C3=CC(=O)OC3)[C@@]1(C)CC[C@H](O)C2 NAME: gitoxigenin REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: CC(C)[C@@]12CC[C@@](C)(OO1)C1=C([C@H](C)CC1=O)[C@H]2O NAME: nardoperoxide REASON: CORRECT Hydroxyl attached to secondary carbon
 * SMILES: O=C(N[C@H](C(=O)N[C@@H](CC(C)C)B(O)O)[C@H](O)C)C1=NC(C2=CC=CC=C2)=CC=C1 NAME: delanzomib REASON: CORRECT Hydroxyl attached to secondary carbon
False positives: SMILES: OC1=CC=C(C[C@@H](O)[C@@H](O)CC=2C3=C(C=CC=C3)NC2)C=C1 NAME: Diolmycin A1 REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O1C(C(O)C(O)C(OC)C1COC(=O)/C=C/C2=CC(O)=C(O)C=C2)C3=C(O)C4=C(OC(=CC4=O)C5=CC(O)=C(O)C=C5)C=C3O NAME: 4''-Methyl-6''-(3,4-dihydroxy-E-cinnamoyl)isoorientin REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O([C@@H]1[C@@]([C@]2([C@@]([C@@]3([C@]([C@]4(C([C@]5([C@@](CC4)(CCC(C5)(C)C)C(O[C@@H]6O[C@@H]([C@H](O)[C@H](O[C@@H]7O[C@H]([C@H](O)[C@@H](O)[C@H]7O)C)[C@H]6O[C@@H]8O[C@H]([C@H](O[C@@H]9OC[C@@H](O)[C@H](O[C@@H]%10OC[C@@H](O)[C@H](O)[C@H]%10O)[C@H]9O)[C@@H](O)[C@H]8O)C)C)=O)[H])=CC3)C)(CC2)C)[H])(CC1)C)[H])(C)C=O)[C@@H]%11O[C@@H]([C@@H](O)[C@H](O)[C@H]%11O[C@@H]%12O[C@@H]([C@H](O)[C@H](O)[C@H]%12O)CO)C(O)=O NAME: Goyasaponin II REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O(C1C(OC2C(O)C(O)C(OC2)O)OCC(O)C1O)C3OC(C(OC)C(O)C3O)C(O)=O NAME: 4-O-Methyl-a-D-glucosyl-(1->2)-b-D-xylosyl-(1->4)-D-xylose REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O1C(OC=2C(=CC3=C(OC(=O)C=C3)C2)C)C(O)C(O)C(O)C1C(O)=O NAME: 3,4,5-trihydroxy-6-[(6-methyl-2-oxo-2H-chromen-7-yl)oxy]oxane-2-carboxylic acid REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O([C@@H]1[C@@H](O)[C@H](O[C@@H]2[C@@H](NC(=O)C)[C@@H](O[C@@H]([C@H]2O)CO)O[C@@H]3[C@@H](O)[C@@H](O[C@@H]([C@@H]3O)CO)O[C@@H]4[C@@H](NC(=O)C)C(O[C@@H]([C@@H]4O)CO)O)O[C@@H]([C@@H]1O)CO[C@@H]5O[C@@H]([C@@H](O)[C@H](O[C@@H]6O[C@@H]([C@H](O)[C@H](O)[C@H]6O[C@@H]7O[C@H]([C@@H](O)[C@@H](O)[C@@H]7O)C)CO)[C@H]5NC(=O)C)CO)[C@@H]8O[C@@H]([C@@H](O)[C@H](O[C@@H]9O[C@@H]([C@H](O)[C@H](O[C@H]%10O[C@@H]([C@H](O)[C@H](O)[C@H]%10NC(=O)C)CO)[C@H]9O[C@@H]%11O[C@H]([C@@H](O)[C@@H](O)[C@@H]%11O)C)CO)[C@H]8NC(=O)C)CO NAME: N-[(2R,3R,4R,5R,6R)-2-[(2R,3R,4S,5S,6R)-2-[(2S,3R,4R,5S,6R)-3-Acetamido-2-[(2R,3R,4S,5S,6R)-2-[(2S,3R,4R,5S,6R)-3-acetamido-2-[(2R,3R,4S,5S,6R)-2-[(3R,4R,5R,6R)-3-acetamido-2,5-dihydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-5-hydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-6-[[(2R,3R,4R,5S,6R)-3-acetamido-4-[(2R,3R,4S,5R,6R)-4,5-dihydroxy-6-(hydroxymethyl)-3-[(2S,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-2-yl]oxy-5-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]-3,5-dihydroxyoxan-4-yl]oxy-5-hydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-5-hydroxy-6-(hydroxymethyl)-3-[(2S,3S,4R,5S,6S)-3,4,5-trihydroxy-6-methyloxan-2-yl]oxyoxan-4-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-3-yl]acetamide REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O=C1C(=C[C@H](CC=C[C@@H]2[C@]3(C(CC[C@H]1O)=O)C(=O)N[C@H]([C@@H]3[C@H](C)[C@]([C@H]2O)(O)C)CC=4C5=C(C=CC=C5)NC4)C)C NAME: Cytoglobosin I REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: C[C@@H]([C@@H](C1=CC=CC=C1)O)N(C)C NAME: (1R,2S)-2-(dimethylamino)-1-phenyl-1-propanol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: F[C@@]12C3(C(C(O)CC1C=4CC[C@@](C4CC2O)(O)C)CC(=O)CC3)C NAME: (1S,9bR)-9b-fluoro-1,5,10-trihydroxy-1,9a-dimethyl-2H,3H,3bH,4H,5H,5aH,6H,8H,9H,10H,11H-cyclopenta[a]phenanthren-7-one REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O=C1N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@@H]([C@H](O)CN)C(N[C@H](C(NC[C@H]([C@@H](C(NC1=CC)=O)NC(=O)CCCCCCCCCCC)O)=O)[C@@H](O)CN)=O)CCCN=C(N)N)CC(C)C)CCN NAME: Ogipeptin C REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O1C([C@@H](O)[C@H](O)C(O)[C@@H]1OC=2C(C=3OC=4C(C(=O)C3O)=C(O)C=C(O)C4)=C(O)C=CC2)CO NAME: 3,5,7,2',6'-Pentahydroxyflavone 2'-glucoside REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: C(=O)(C(CCCCCCCC/C=C\CCCCCCCC)O)O NAME: 2-hydroxygondoic acid REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O=C1C2=C(C(=O)CC3[C@@]2(CC[C@@H](C3(C)C)O)C)[C@@]4(C(=O)C[C@@H]([C@]4([C@@H]1O)C)/C(=C/C(=O)CC(C(=O)O)C)/C)C NAME: Resinacein L REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: [H][C@]12[C@H](OC(=O)c3ccccc3)[C@]3(O)C[C@H](OC(=O)[C@H](O)[C@@H](NC(=O)c4ccccc4)c4ccccc4)C(C)=C([C@@H](OC(C)=O)C(=O)[C@]1(C)[C@@H](O)C[C@H]1OC[C@@]21OC(C)=O)C3(C)C NAME: paclitaxel REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: OC(C(O)C/C=C(/C(O)CO)\C)(C)C NAME: 3,7-Dimethyl-3-octene-1,2,6,7-tetrol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O1[C@@]2(C#CC(=C)C)[C@@H](O)C=C[C@@H]([C@@H]12)O NAME: Speciosin C REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: OC1CC(C(C(=C1)C)/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C=C(/C=C/C=C(/C=C/C=C(/CCC=C(C)C)\C)\C)\C)(C)C NAME: epsilon,gamma-Caroten-3-ol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O([C@H]1[C@@H](O[C@H]2O[C@H]([C@@H](O)[C@@H](O)[C@@H]2O)C)[C@H](O[C@H](O)[C@@H]1O)CO)[C@@H]3O[C@@H]([C@@H](O)[C@H](O)[C@H]3O)CO NAME: (2R,3S,4R,5S,6S)-2-[(2R,3S,4R,5R,6S)-5,6-Dihydroxy-2-(hydroxymethyl)-4-[(2S,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-3-yl]oxy-6-methyloxane-3,4,5-triol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O([C@@H]1[C@@H](O)[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H]([C@H]2O)CO)O[C@H]3[C@H](O)[C@H](OC(O)[C@@H]3O)CO)O[C@@H]([C@H]1O)CO)[C@H]4O[C@@H]([C@@H](O)[C@H](O[C@H]5O[C@@H]([C@@H](O)[C@H](O[C@H]6O[C@@H]([C@@H](O)[C@H](O)[C@H]6O)CO)[C@H]5O)CO)[C@H]4O)CO NAME: (3R,4S,5R,6R)-4-[(2R,3R,4S,5R,6R)-4-[(2R,3R,4S,5R,6R)-4-[(2R,3R,4S,5R,6R)-4-[(2R,3R,4S,5R,6R)-3,5-Dihydroxy-6-(hydroxymethyl)-4-[(2R,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-(hydroxymethyl)oxane-2,3,5-triol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O[C@H]1[C@H](O)C(O)(COP([O-])([O-])=O)O[C@@H]1CS([O-])(=O)=O NAME: 6-deoxy-6-sulfo-D-fructofuranose 1-phosphate(3-) REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O=C1C2=C(O)C(=C(C)C=C2C(=O)C=3C1=C(O)C=C(OC)C3)[C@@H](O)C NAME: 1,8-dihydroxy-2-(1-hydroxyethyl)-6-methoxy-3-methylanthraquinone REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O=C1O[C@H]([C@@H](O)[C@@H]2O[C@H]2[C@H](O)/C=C\C#CC#CC#C)CC1 NAME: Collimonin A REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O1[C@@H]([C@H](O[C@@H]2O[C@@H]([C@@H](O)[C@H](O)[C@H]2O)CO)[C@H](O)[C@@H](O)[C@@H]1O[C@H]3[C@H](O)[C@H](OC(O)[C@@H]3O)CO)CO NAME: (3R,4S,5R,6R)-4-[(2S,3R,4R,5R,6R)-3,4-Dihydroxy-6-(hydroxymethyl)-5-[(2S,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]oxy-6-(hydroxymethyl)oxane-2,3,5-triol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: O1C(C(O)C(O)C(O)C1OC=2C=C(C3OC4=C(C3CO)C=C(C=C4OC)CCCO)C=CC2OC)CO NAME: 2-(Hydroxymethyl)-6-[5-[3-(hydroxymethyl)-5-(3-hydroxypropyl)-7-methoxy-2,3-dihydro-1-benzofuran-2-yl]-2-methoxyphenoxy]oxane-3,4,5-triol REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
 * SMILES: CC(=O)N[C@H]1C(O)O[C@H](CO)[C@@H](O[C@@H]2O[C@H](CO)[C@@H](O[C@@H]3O[C@H](CO[C@H]4O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]4O[C@@H]4O[C@H](CO)[C@@H](O)[C@H](O)[C@H]4NC(C)=O)[C@@H](O[C@@H]4O[C@H](CO)[C@@H](O)[C@H](O)[C@H]4NC(C)=O)[C@H](O)[C@@H]3O[C@H]3O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]3O[C@@H]3O[C@H](CO)[C@@H](O)[C@H](O)[C@H]3NC(C)=O)[C@H](O)[C@H]2NC(C)=O)[C@@H]1O NAME: beta-D-GlcpNAc-(1->2)-alpha-D-Manp-(1->6)-[beta-D-GlcpNAc-(1->4)]-[beta-D-GlcpNAc-(1->2)-alpha-D-Manp-(1->3)]-beta-D-Manp-(1->4)-beta-D-GlcpNAc-(1->4)-D-GlcpNAc REASON: WRONGLY CLASSIFIED Hydroxyl attached to secondary carbon
False negatives: SMILES: [H][C@@]1(COC(O)[C@]1([H])Cc1ccc2OCOc2c1)Cc1ccc(OC)c(OC)c1 NAME: (-)-3,4-dimethoxy-3,4-desmethylenedioxycubebin REASON: MISSED No secondary alcohol group detected
 * SMILES: O1C2/3C(=NCCC12)C=C\C3=C/C NAME: Latumcidin REASON: MISSED No hydroxyl group found
 * SMILES: OC1(C(O)=C(C(O)=C(C1=O)C(=O)C(C)C)CC=C(C)C)CC=C(C)C NAME: Cohumulone REASON: MISSED No secondary alcohol group detected
 * SMILES: O=C1C(O)=C(OC)[C@@]([C@@]1(O)C)(O)C(=O)OC NAME: 2,4,5-trihydroxy-3-methoxy-4-methoxycarbonyl-5-methyl-2-cyclopenten-1-one REASON: MISSED No secondary alcohol group detected
 * SMILES: O=C1C=C(C#N)C[C@]1(O)C=C NAME: Homothallin II REASON: MISSED No secondary alcohol group detected
 * SMILES: [H][C@@]1(CO[C@H](O)[C@]1([H])Cc1ccc2OCOc2c1)Cc1ccc2OCOc2c1 NAME: (-)-cubebin REASON: MISSED No secondary alcohol group detected
 * SMILES: O=C1C=C(N(C)C)C[C@]1(O)C=C NAME: 3-dimethylamino-5-hydroxy-5-vinyl-2-cyclopenten-1-one REASON: MISSED No secondary alcohol group detected
 * SMILES: C\C(CCC1=C(C)CCCC1(C)C)=C/CC\C(CO)=C/C=C/C1=CC(=O)OC1O NAME: aplysinoplide A REASON: MISSED No secondary alcohol group detected
 * SMILES: CC1=CC(O)OC1=O NAME: 5-hydroxy-3-methylfuran-2(5H)-one REASON: MISSED No secondary alcohol group detected
 * SMILES: OC1(C(O)=C(C(O)=C(C1=O)C(=O)CC(C)C)CC=C(C)C)CC=C(C)C NAME: (R)-Humulone REASON: MISSED No secondary alcohol group detected
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:35681
  name: secondary alcohol
  definition: A secondary alcohol is a compound in which a hydroxy group, -OH, is
    attached to a saturated carbon atom which has two other carbon atoms attached
    to it.
  parents:
  - CHEBI:30879
  xrefs:
  - KEGG:C00432
  - KEGG:C01612
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: unterminated string literal (detected at line 3) (<string>, line 3)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []