Reverting to best solution for polysaccharide, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:18154
  name: polysaccharide
  definition: A biomacromolecule consisting of large numbers of monosaccharide residues
    linked glycosidically. This term is commonly used only for those containing more
    than ten monosaccharide residues.
  parents:
  - CHEBI:16646
  - CHEBI:167559
  - CHEBI:33694
  xrefs:
  - KEGG:C00420
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 31
  log_lines_of_code: 3.4339872044851463
  max_indent: 5
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import MolFromSmiles, MolToSmiles
  - from rdkit.Chem.rdmolops import GetAdjacencyMatrix
  - import numpy as np
  imports_count: 4
  methods_called:
  - append
  - MolFromSmarts
  - GetNumAtoms
  - GetSubstructMatches
  - PathToSubmol
  - array
  - GetNumHeavyAtoms
  methods_called_count: 7
  smarts_strings:
  - '"[OX2H][CX4][CX3](O)[CX3](O)[CX3](O)[CX3][CX3]"))'
  smarts_strings_count: 1
  defs:
  - 'is_polysaccharide(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - True, f"Found repeating monosaccharide pattern of length {length}"
  - False, "No repeating monosaccharide pattern found"
  returns_count: 3
  complexity: 3.886797440897029
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: No registered converter was able to produce a C++ rvalue of type unsigned int
  from this Python object of type numpy.int64
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0