Reverting to best solution for nucleobase analogue, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:67142
  name: nucleobase analogue
  definition: A molecule that can substitute for a normal nucleobase in nucleic acids.
  parents:
  - CHEBI:33832
  xrefs:
  - Wikipedia:Base_analog
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 32
  log_lines_of_code: 3.4657359027997265
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - MMFFGetMoleculeProperties
  - GetAromaticRings
  - GetNumHeavyAtoms
  - MolFromSmiles
  - GetAtoms
  - GetAtomicNum
  methods_called_count: 6
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_nucleobase_analogue(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No heteroaromatic rings found"
  - False, "Missing N or O atoms"
  - False, "Structure is not sufficiently planar"
  - False, "Size deviates too much from typical nucleobases"
  - True, "Contains heteroaromatic rings and functional groups typical of nucleobases"
  returns_count: 6
  complexity: 3.693147180559945
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: '''Mol'' object has no attribute ''GetAromaticRings'''
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0