Reverting to best solution for 2-enoyl-CoA, f1=0.055627425614488996 iteration 1
---
chemical_class:
  id: CHEBI:19573
  name: 2-enoyl-CoA
  definition: An unsaturated fatty acyl-CoA in which the S-acyl group contains a double
    bond between positions 2 and 3.
  parents:
  - CHEBI:51006
  xrefs:
  - KEGG:C00605
  - MetaCyc:D2-ENOYL-COA
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 53
  log_lines_of_code: 3.970291913552122
  max_indent: 5
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - GetNeighbors
  - GetBondType
  - GetOtherAtomIdx
  - GetEndAtom
  - MolFromSmiles
  - GetSubstructMatches
  - HasSubstructMatch
  - MolFromSmarts
  - GetBonds
  - GetIdx
  - GetBeginAtomIdx
  - GetAtomWithIdx
  - GetSymbol
  - GetBeginAtom
  methods_called_count: 14
  smarts_strings:
  - '[CX3](=[OX1])[SX2][CX4H2][CX3]=[CX3]'
  - SCCNC(=O)CCNC(=O)
  - '[CX3](=[OX1])[SX2]'
  smarts_strings_count: 3
  defs:
  - 'is_2_enoyl_CoA(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES"
  - False, "Missing CoA moiety"
  - False, "No thioester group found"
  - True, "Acyl chain has double bond between positions 2 and 3"
  - True, "Double bond found between positions 2 and 3 of acyl chain"
  - True, "Double bond found between positions 2 and 3 of acyl chain"
  - False, "No double bond between positions 2 and 3 of acyl chain"
  returns_count: 7
  complexity: 6.194058382710424
message: '

  Error: unexpected indent (<string>, line 1)

  Attempt failed: F1 score of 0 is too low.

  Outcomes:

  ------

  True positives: NONE

  False positives: NONE

  False negatives: NONE

  ------

  In your reasoning step, analyze the previous program and the above outcomes, hypothesizing
  about what went wrong, and how to improve.

  '
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: O=C1NC=C2[C@@]3(O)[C@@H](O)[C@@H](OC2=C1OC(=O)[C@H]4[C@H]5[C@H](C=C[C@H]4C)C[C@H](C)CC5)[C@@H](O)CC3
  name: Arthpyrone D
  reason: Missing CoA moiety
- smiles: CCN(CC)S(=O)(=O)C1=CC=CC(=C1)C(=O)NC2=CC(=CC(=C2)C)C
  name: 3-(diethylsulfamoyl)-N-(3,5-dimethylphenyl)benzamide
  reason: Missing CoA moiety
- smiles: O=C1[C@@]([C@H]2[C@]([C@@H]3C(C[C@](C=C)(C)CC3)=CC2)(C)CC1)(CO[C@@H]4O[C@H](C(=O)O)[C@@H](O)[C@H]([C@@H]4O)O)C
  name: Virescenoside Z4
  reason: Missing CoA moiety
- smiles: C[C@H]1CN(C(=O)CCCN2C(=CN=N2)CO[C@@H]1CN(C)C(=O)NC3=CC=CC(=C3)C(F)(F)F)[C@@H](C)CO
  name: 1-[[(8S,9S)-6-[(2S)-1-hydroxypropan-2-yl]-8-methyl-5-oxo-10-oxa-1,6,14,15-tetrazabicyclo[10.3.0]pentadeca-12,14-dien-9-yl]methyl]-1-methyl-3-[3-(trifluoromethyl)phenyl]urea
  reason: Missing CoA moiety
- smiles: O([C@H]1[C@@H](O)[C@H](O[C@@H]2O[C@@H]([C@@H](O[C@@H]3O[C@@H]([C@H](O)[C@H](O[C@H]4O[C@@H]([C@H](O)[C@H](O)[C@H]4O)CO)[C@H]3O)CO)[C@H](O)[C@H]2NC(=O)C)CO)[C@H](O[C@@H]1O[C@H]5[C@H](O)[C@H](O[C@@H](O[C@H]6[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]6CO)O[C@H]7[C@H](O)[C@@H](NC(=O)C)C(O[C@@H]7CO[C@@H]8O[C@H]([C@@H](O)[C@@H](O)[C@@H]8O)C)O)[C@H]5O)CO[C@H]9O[C@@H]([C@@H](O)[C@H](O)[C@@H]9O[C@@H]%10O[C@@H]([C@@H](O[C@@H]%11O[C@@H]([C@H](O)[C@H](O[C@]%12(O[C@H]([C@H](NC(=O)C)[C@@H](O)C%12)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]%11O)CO)[C@H](O)[C@H]%10NC(=O)C)CO)CO)CO)[C@@H]%13O[C@@H]([C@@H](O[C@@H]%14O[C@@H]([C@H](O)[C@H](O[C@]%15(O[C@H]([C@H](NC(=O)C)[C@@H](O)C%15)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]%14O)CO)[C@H](O)[C@@H]%13NC(=O)C)CO
  name: CID 91846694
  reason: Missing CoA moiety
- smiles: CCOC(=O)NCC(C)(C)CNC(=O)OCC
  name: N-[3-(ethoxycarbonylamino)-2,2-dimethylpropyl]carbamic acid ethyl ester
  reason: Missing CoA moiety
- smiles: S1C(=NC(=C1)/C=C/C(OC)C(/C(/OC)=C\C(=O)OC)C)C2N=C(C3(OC3)C)SC2
  name: Melithiazol K
  reason: Missing CoA moiety
- smiles: CCCCC\C=C/C\C=C/CCCCCC(=O)O[C@@H](CO[C@@H]1O[C@H](CO)[C@H](O)[C@H](O)[C@H]1O)COC(=O)CCCCC\C=C/C\C=C/C\C=C/CC
  name: (2S)-1-O-(7Z,10Z,13Z)-hexadecatrienoyl-2-O-(7Z,10Z)-hexadecadienoyl-3-O-beta-D-galactopyranosyl-sn-glycerol
  reason: Missing CoA moiety
- smiles: CC(C)(C)OC(=O)N[C@H]1CCCCCC=C[C@@H]2C[C@]2(NC(=O)[C@@H]3C[C@H](CN3C1=O)OC(=O)N4CC5=C(C4)C(=CC=C5)F)CNS(=O)(=O)C6CC6
  name: LSM-5352
  reason: Missing CoA moiety
- smiles: O=C1O[C@@H]2C[C@@]3(O[C@H](/C(=C/C)/C)[C@@H](C)C[C@H]3O)O[C@@H](C2)CC=C(C[C@H](C=CC=C4[C@]5([C@H]1C=C([C@@H](O)C5OC4)COC(=O)CC6=COC=C6)O)C)C
  name: VM48642
  reason: Missing CoA moiety
sample_false_negatives: []
attempt: 1
success: true
best: true
error: ''
stdout: null
num_true_positives: 43
num_false_positives: 1460
num_true_negatives: 140797
num_false_negatives: 0
num_negatives: null
precision: 0.028609447771124417
recall: 1.0
f1: 0.055627425614488996
accuracy: 0.9897399859451862
negative_predictive_value: 1.0