Attempt 2 at ultra-long-chain fatty acid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.1073170731707317 is too low.
Outcomes:
------

True positives: SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCC(O)C(O)=O NAME: (12Z,15Z,18Z,21Z,24Z)-2-hydroxytriacontapentaenoic acid REASON: CORRECT Chain length is 30 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCC(O)C(O)=O NAME: (13Z,16Z,19Z,22Z)-2-hydroxyoctacosatetraenoic acid REASON: CORRECT Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCCCCC(O)=O NAME: (18Z,21Z,24Z,27Z,30Z,33Z)-hexatriacontahexaenoic acid REASON: CORRECT Chain length is 36 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCC(O)=O NAME: (12Z,15Z,18Z,21Z,24Z,27Z)-triacontahexaenoic acid REASON: CORRECT Chain length is 30 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCCCC[C@@H](O)C(O)=O NAME: (R)-2-hydroxyoctacosanoic acid REASON: CORRECT Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCC(O)=O NAME: (15Z,18Z,21Z,24Z)-triacontatetraenoic acid REASON: CORRECT Chain length is 30 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCCCC(O)=O NAME: (17Z,20Z,23Z,26Z)-dotriacontatetraenoic acid REASON: CORRECT Chain length is 32 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCCCCCC(O)=O NAME: (19Z,22Z,25Z,28Z)-tetratriacontatetraenoic acid REASON: CORRECT Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC(O)=O NAME: dotriacontanoic acid REASON: CORRECT Chain length is 32 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCCC(O)=O NAME: (16Z,19Z,22Z,25Z,28Z,31Z)-tetratriacontahexaenoic acid REASON: CORRECT Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCCCCCCCC[C@@H]1C[C@@H]1CCCCCCCCCCCCCCCC[C@H](OC)[C@@H](C)CCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-[(1R)-1-hydroxy-18-{(1R,2S)-2-[(17S,18S)-17-methoxy-18-methylhexatriacontyl]cyclopropyl}octadecyl]hexacosanoic acid REASON: CORRECT Chain length is 59 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCC(C)CCCCCCCCCCCCCCCCCCCCCCCCC(O)=O NAME: 26-methyloctacosanoic acid REASON: CORRECT Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCC(C)CCCCCCCCCCCCCCCCCCCCCCCCCCC(O)=O NAME: 28-methyltriacontanoic acid REASON: CORRECT Chain length is 30 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCC(O)=O NAME: (15Z,18Z,21Z,24Z,27Z)-triacontapentaenoic acid REASON: CORRECT Chain length is 30 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCCCCCC[C@H]1C[C@H]1CCCCCCCCCCCCCCCCCC[C@H](O)[C@@H](C)CCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-[(1R)-1-hydroxy-16-{(1S,2R)-2-[(19S,20S)-19-hydroxy-20-methyloctatriacontyl]cyclopropyl}hexadecyl]hexacosanoic acid REASON: CORRECT Chain length is 59 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCC(O)=O NAME: (14Z,17Z,20Z,23Z,26Z,29Z)-dotriacontahexaenoic acid REASON: CORRECT Chain length is 32 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCCCCCC[C@@H]1C[C@@H]1CCCCCCCCCCCCCCCCCCC(=O)C(C)CCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-{(1R)-1-hydroxy-16-[(1R,2S)-2-(20-methyl-19-oxooctatriacontyl)cyclopropyl]hexadecyl}hexacosanoic acid REASON: CORRECT Chain length is 59 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCCCCCC[C@@H]1C[C@@H]1CCCCCCCCCCCCCCCCCC[C@H](O)[C@@H](C)CCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-[(1R)-1-hydroxy-16-{(1R,2S)-2-[(20S)-20-methyl-19-oxooctatriacontyl]cyclopropyl}hexadecyl]hexacosanoic acid REASON: CORRECT Chain length is 59 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC(C)CCCCCCCCCCCCCCCCCCCCCCCCCCC(O)=O NAME: 28-methylnonacosanoic acid REASON: CORRECT Chain length is 29 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCC(O)=O NAME: (13Z,16Z,19Z,22Z)-octacosatetraenoic acid REASON: CORRECT Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCCCCCCCC[C@H]1C[C@H]1CCCCCCCCCCCCCCCC[C@@H](OC)[C@H](C)CCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-[(1R)-1-hydroxy-18-{(1S,2R)-2-[(17R,18R)-17-methoxy-18-methylhexatriacontyl]cyclopropyl}octadecyl]hexacosanoic acid REASON: CORRECT Chain length is 59 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCC[C@H]1C[C@H]1CCCCCCCCCCCCCC[C@H]1C[C@H]1CCCCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-{(1R)-1-hydroxy-12-[(1S,2R)-2-{14-[(1S,2R)-2-icosylcyclopropyl]tetradecyl}cyclopropyl]dodecyl}hexacosanoic acid REASON: CORRECT Chain length is 54 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCC[C@@H]1C[C@@H]1CCCCCCCCCCCCCC[C@@H]1C[C@@H]1CCCCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-{(1R)-1-hydroxy-12-[(1R,2S)-2-{14-[(1R,2S)-2-icosylcyclopropyl]tetradecyl}cyclopropyl]dodecyl}hexacosanoic acid REASON: CORRECT Chain length is 54 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC[C@H]([C@H](O)CCCCCCCCCCCCCCCCCC[C@@H]1C[C@@H]1[C@H](C)CCCCCCCCCCCCCCCC[C@H](OC)[C@@H](C)CCCCCCCCCCCCCCCCCC)C(O)=O NAME: (2R)-2-[(1R)-1-hydroxy-19-{(1R,2R)-2-[(2R,19S,20S)-19-methoxy-20-methyloctatriacontan-2-yl]cyclopropyl}nonadecyl]hexacosanoic acid REASON: CORRECT Chain length is 61 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCCCCCCCCCCC(O)=O NAME: (23Z,26Z,29Z,32Z)-octatriacontatetraenoic acid REASON: CORRECT Chain length is 38 carbons, qualifies as ultra-long-chain fatty acid
False positives: SMILES: OC(CC/C=C/[C@@]1(C=C(C[C@]2(O1)O[C@]3(CC2)[C@@H](C[C@@]4([C@](O3)(C[C@](O4)([C@H]([C@@]5(O[C@@]([C@H]([C@H](C5)O)C)(C(=C)C[C@@]67C[C@H](C[C@@H](O6)[C@@]8([C@](O7)(C[C@]9(O8)[C@H](C[C@H](CN9)C)C)[H])[H])C)[H])O)O)[H])[H])[H])C)C)[H])=O NAME: Azaspiracid-10 REASON: WRONGLY CLASSIFIED Chain length is 40 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1C(=CC=CC(=CC(O)C(=CCC(=O)O[C@H](CC=CC=CC=CC1O)[C@H]([C@H](O)[C@@H](CCC(O)/C=C\C)C)C)C)C)C NAME: Hamuramicin A REASON: WRONGLY CLASSIFIED Chain length is 30 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1OC(C(C2(OC(C(O)(C)C(C2OC)O)CCCOC)O)C)CC(C(O)C=C(C=C(C=C(C(C(C=C(C=C(C=C1C)OC)C)C)OC3OC(C(O)C(C3O)O)C)C)C)C)C NAME: Ammocidin D REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: OC(CCCCCCCCCCCCCC(O)/C=C/CCCCCC(=O)CCCCC#CC(O)C#CC(O)C(O)CCCC(O)/C=C/C(O)C#C)C(O)C#CC(O)=O NAME: Fulvyne G REASON: WRONGLY CLASSIFIED Chain length is 47 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: [C@@]123O[C@@](CC1)(C[C@@H](O2)[C@H]4O[C@@]([C@H]([C@H]5O[C@]6(CCC[C@@H]([C@H](C(O[C@@H]7[C@@H]([C@@H]([C@]8(OCC[C@H]([C@H]8O)C)O)O[C@@]7(C=CC(=C[C@@H](C[C@@]9(O[C@@H]3CC9)C)C)C)[H])O)=O)C)O6)CC5)O)(CC4=O)C)C NAME: pectenotoxin-11 REASON: WRONGLY CLASSIFIED Chain length is 40 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CC(CC(C)C1OC(=O)CC(=O)CCCC(=O)CC(O)CC(O)CC(O)CC(=O)CC(O)C(C(O)CC(OC2O[C@H](C)[C@@H](O)[C@H](N)[C@@H]2O)\C=C\C=C\C=C\C=C\C=C\C=C\C=C\C1C)C(O)=O)C(O)CC(=O)c1ccc(N)cc1 NAME: candicidin D REASON: WRONGLY CLASSIFIED Chain length is 49 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1OC2C(C3(OC(C2C)CCC(C=CC=CCC(C)C(C(C(C(C(C(C(C(C(C(C=C1)C)O)C)=O)C)O)C)=O)(O)C)O)CC)OC(C(C)CC3)CC(O)C)CC NAME: 44-Homooligomycin A REASON: WRONGLY CLASSIFIED Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1O[C@@H]([C@@]2(O[C@@H]([C@H](C)[C@@H]([C@H]2C)O)C[C@@H](O[C@@H]3O[C@H]([C@H](O[C@@H]4O[C@@H]([C@@H](O)[C@@H](C4)OC)C)[C@](C3)(O)C)C)COC)O)[C@@H](O)C[C@H](OC)[C@@H](O)CCC=C(C)C=C[C@H]([C@@H](C=C(C=C(C=C1C)C)C)C)O[C@@H]5O[C@H]([C@H](OC)[C@H]([C@@H]5O)O)C NAME: Isoapoptolidin REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O1[C@@]([C@@]2(O[C@](CC2)([C@@H](O)CCCC(O)CCCCCC)[H])[H])(CC[C@@]1([C@H](O)CCCCC(O)CCCCCCCC3=CC(OC3=O)C)[H])[H] NAME: Rollimusin REASON: WRONGLY CLASSIFIED Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1O[C@@H]2C[C@@]3(O[C@H](C(=CC)C)[C@@H](C)C[C@H]3O)O[C@@H](C2)CC=C(C[C@H](C=CC=C4[C@]5([C@H]1C=C([C@@H](OC)[C@H]5OC4)C)O)C)C NAME: VM-44864 REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O1C(C2OC(CC2)C(O)CCCCCCCC)CCC1C(O)CCCCCCCCCCC3OC(=O)C(C3)CC(=O)C NAME: Squamolinone REASON: WRONGLY CLASSIFIED Chain length is 32 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: C12OC(C(C(C1)O)O)CCCC(CC(O)C3C(CC(O3)CC(OC4C=C(C(C5OC(CCC(C=CC(C)=CCCC=6C7(C(C=C(C2)CC7CCN6)C(C)=CCC(C4)C)C)O)C(C(C5)O)O)O)C)=O)O)=C NAME: Prorocentrolide REASON: WRONGLY CLASSIFIED Chain length is 49 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1C2=C(O)C3=C(O)C=CC=C3C(C24C=C([C@H]1C5=C(O)C=6C(O)=C7C(=O)CCC(C7(C(=O)OC)OC6C=C5C4)O)C)OC(=O)C NAME: JBIR-97 REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: COc1cc(cc(C\C=C(/C)CC\C=C(/C)CC\C=C(/C)CC\C=C(/C)CC\C=C(/C)CC\C=C(/C)CC\C=C(/C)CC\C=C(/C)CCC=C(C)C)c1O)C(O)=O NAME: 3-nonaprenyl-4-hydroxy-5-methoxybenzoic acid REASON: WRONGLY CLASSIFIED Chain length is 42 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: OC([C@@H](C[C@@H](C[C@@H](C[C@@H](C[C@@H](C[C@@H](C[C@@H](C[C@H](C)C(O)=O)C)C)C)C)C)C)C)CCCCCCCCCCCCCCCCC NAME: Hydroxyphthioceranic acid (C42) REASON: WRONGLY CLASSIFIED Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCCCCCCCCCCC[C@@H](O)C[C@H](O)C[C@H](O)C[C@H](O)C[C@@H]1OC(=O)C=C[C@@H]1O NAME: cryptocaryol E REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1OC(C(C2(OC(C(OC3OC(C(O)C(C3)(O)C)C)(C)C(C2OC)O)CCCOC)O)C)CC(CC=C(C=C(C=C(C(C(C=C(C=C(C=C1C)OC)C)C)OC4OC(C(O)C(C4O)O)C)C)C)C)C NAME: Ammocidin C REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O1C(C2OC(CC2)C(O)CCCCCCCCCCC3=CC(OC3=O)C)CCC1C(O)CCCCC(O)CCCCC NAME: Atemoyacin B REASON: WRONGLY CLASSIFIED Chain length is 32 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C(O)/C(=C/[C@H]1O[C@@]2(O)CC[C@]3([C@H]([C@@]2(C1)C)CC[C@@H]4[C@@]3(C=5N6C=7C(=C8[C@@H](O)[C@@H]9C(OC(C=C9C8=CC7C5C4)(C)C)(C)C)C[C@@H]6C(=C)C)C)C)/C NAME: Nodulisporic acid B1 REASON: WRONGLY CLASSIFIED Chain length is 29 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1OC(C=CC(O)CC(O)CCCC(O)C(C(O)CCC(C(O)CC(O)CC(O)CCC(O)C(C(C=C(C(CC(CCCC(C(C(CC=CC=C(C(C(C2OC(C1)(O)C(C(O[C@@H]3O[C@@H]([C@@H](O)[C@@H]([C@H]3O)N(C)C)C)C2)C)C)O)C)O)C)O)O)O)C)CCCCC(C)C)O)C)C)C NAME: Stambomycin B REASON: WRONGLY CLASSIFIED Chain length is 51 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O=C1O[C@H]([C@@H](C=CC(O)CCC[C@@H](O)C[C@@H](O)C[C@H](O)C[C@@H]2O[C@@](C([C@H](C(CCC(CCCC(CC(CC=C1)O)O)O)C)O)=O)(O)[C@@H](O)[C@@H](C2)O)C)[C@@H]([C@@H](O)[C@H]([C@@H](O)[C@@H]([C@H](O[C@H]3O[C@@H]([C@H](O[C@H]4O[C@@H]([C@H](OC(=O)[C@@H]([C@H](O[C@H]5O[C@@H]([C@H](O)CC5)C)C6=CC=7C(=O)C=C(C)C(C7C=C6)=O)C)CC4)C)[C@](C3)(O)C)C)CC)C)C)C NAME: Astolide A REASON: WRONGLY CLASSIFIED Chain length is 43 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: OC(CC(/C=C/[C@@]1(C=CC[C@]2(O1)O[C@]3(CC2)[C@@H](C[C@@]4([C@](O3)(C[C@](O4)([C@H]([C@@]5(O[C@@]([C@H](CC5)C)(C(=C)C[C@@]67C[C@H](C[C@@H](O6)[C@@]8([C@](O7)(C[C@]9(O8)[C@H](C[C@H](CN9)C)C)[H])[H])C)[H])O)O)[H])[H])[H])C)[H])O)=O NAME: Azaspiracid-4 REASON: WRONGLY CLASSIFIED Chain length is 40 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: COC(=O)CCc1c(C)c2cc3[nH]c(cc4nc(cc5[nH]c(cc1n2)c(CCC(O)=O)c5C)c(C=C)c4C)C1=CC=C([C@H](C(=O)OC)[C@]31C)C(=O)OC NAME: (2S,2(1)R)-8-ethenyl-2(1),2(2)-bis(methoxycarbonyl)-17-(3-methoxy-3-oxopropyl)-2,7,12,18-tetramethyl-2,2(1)-dihydrobenzo[b]porphyrin-13-propanoic acid REASON: WRONGLY CLASSIFIED Chain length is 28 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: O1[C@](CC[C@H]1C(O)CC/C=C/CCCCCCCCCC)([C@H](O)CCCCCCCCCC[C@@H](O)CC2=C[C@@H](OC2=O)C)[H] NAME: Asiminenin A REASON: WRONGLY CLASSIFIED Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
 * SMILES: CCCCCC[C@H](O)CCC[C@H](O)[C@H]1CC[C@@H](O1)C1CC[C@@H](O1)[C@H](O)CCCCCCCCCCCCC1=C[C@H](C)OC1=O NAME: Squamocin REASON: WRONGLY CLASSIFIED Chain length is 34 carbons, qualifies as ultra-long-chain fatty acid
False negatives: NONE
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:143004
  name: ultra-long-chain fatty acid
  definition: Any very long-chain fatty acid which has a chain length greater than
    C27.
  parents:
  - CHEBI:27283
  xrefs:
  - PMID:27257090
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 69
  log_lines_of_code: 4.23410650459726
  max_indent: 5
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - GetAtoms
  - GetNeighbors
  - MolFromSmiles
  - GetSubstructMatches
  - IsInRing
  - GetAtomWithIdx
  - MolFromSmarts
  - GetIdx
  - GetAtomicNum
  methods_called_count: 9
  smarts_strings:
  - carboxyl_smarts
  smarts_strings_count: 1
  defs:
  - 'is_ultra_long_chain_fatty_acid(smiles: str):'
  - 'dfs(atom_idx, visited):'
  defs_count: 2
  returns:
  - False, "Invalid SMILES string"
  - False, "Molecule does not contain a carboxylic acid group"
  - False, "Carboxyl carbon is not attached to any carbon (no alkyl chain found)"
  - max_length
  - False, f"Chain length is {total_chain_length} carbons, which is not greater than
    C27"
  - False, (f"Chain length is {total_chain_length} carbons but the molecule has {total_carbons}
    carbons. "
  - True, f"Chain length is {total_chain_length} carbons, qualifies as ultra-long-chain
    fatty acid"
  returns_count: 7
  complexity: 5.446821300919452
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "invalid character '\u2010' (U+2010) (<string>, line 1)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []