Attempt 1 at proteinogenic amino acid, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:83813
  name: proteinogenic amino acid
  definition: Any of the 23 alpha-amino acids that are precursors to proteins, and
    are incorporated into proteins during translation. The group includes the 20 amino
    acids encoded by the nuclear genes of eukaryotes together with selenocysteine,
    pyrrolysine, and N-formylmethionine. Apart from glycine, which is non-chiral,
    all have L configuration.
  parents:
  - CHEBI:33709
  xrefs:
  - Wikipedia:Proteinogenic_amino_acid
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []