Attempt 1 at flavonoids, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:72544
  name: flavonoids
  definition: Any organic molecular entity whose stucture is based on derivatives
    of a phenyl-substituted 1-phenylpropane possessing a C15 or C16 skeleton, or such
    a structure which is condensed with a C6-C3 lignan precursors. The term is a 'superclass'
    comprising all members of the classes of flavonoid, isoflavonoid, neoflavonoid,
    chalcones, dihydrochalcones, aurones, pterocarpan, coumestans, rotenoid, flavonolignan,
    homoflavonoid and flavonoid oligomers. Originally restricted to natural products,
    the term is also applied to synthetic compounds related to them.
  parents:
  - CHEBI:25806
  - CHEBI:50860
  xrefs:
  - Wikipedia:Flavonoids
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []