Attempt 4 at amine, f1=0.0
(currently fails to compile, but committing anyway

We can improve on the earlier approach by not relying solely on a “negative SMARTS” rule but by iterating over each nitrogen atom and “asking” if it comes from ammonia. In our new version, the algorithm does the following:

• It first parses the molecule from the SMILES string.
• It then inspects every nitrogen (atomic number 7) not already “satisfied” (for example, quaternary, or part of a heteroaromatic ring such as pyridine are omitted).
• For each candidate nitrogen we:
 – Skip it if it is in a ring and aromatic (this will eliminate e.g. pyridine-type nitrogens which are not derivatives of ammonia).
 – Count the hydrogens (both implicit and explicit) so that we can “classify” it as primary (2 H’s), secondary (1 H) or tertiary (0 H’s).
 – Check its neighbors: if the nitrogen is directly bonded to a carbon that is double‐bonded to an oxygen (a typical amide) then we normally want to skip it. (Note that in a few cases a related “thio‐amide” or “carbamothioate” may be considered part of the amine class, so you might relax this later. Here we stick to a clear rule.)
• If at least one nitrogen “passes” these tests then we classify the molecule as an amine and report which kind of free (non‑amide) amine we found.

Below is the full Python code enclosed in a single code block:

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.026521490456923764 is too low.
Outcomes:
------

True positives: SMILES: Cl.C=1C=C(CCCN(CCNC2=CC(N(C(N2C)=O)C)=O)CCO)C=CC1[N+](=O)[O-] NAME: Nifekalant hydrochloride REASON: CORRECT Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: Cl.S1C(CN)=CC=C1C NAME: (5-Methylthien-2-yl)methylamine hydrochloride REASON: CORRECT Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)C(=O)NC3CCCCC3)[C@H](C)CO NAME: 3-cyclohexyl-1-[[(2S,3R)-8-(dimethylamino)-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-2-yl]methyl]-1-methylurea REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CCN(CCCNC(=O)C1=C(OC(=O)C=C1C)C)C2=CC=CC=C2 NAME: N-[3-(N-ethylanilino)propyl]-2,4-dimethyl-6-oxo-3-pyrancarboxamide REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CCCCCCCCCCCCCCCCCCN NAME: octadecan-1-amine REASON: CORRECT Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)CC2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)C(=O)NC3CCCCC3)[C@@H](C)CO NAME: 3-cyclohexyl-1-[[(2S,3S)-9-(dimethylamino)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-2,3,4,7-tetrahydro-1,5-benzoxazonin-2-yl]methyl]-1-methylurea REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CNc1ccccc1 NAME: N-methylaniline REASON: CORRECT Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)CC2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)CC3CC3)[C@@H](C)CO NAME: (2S,3S)-2-[[cyclopropylmethyl(methyl)amino]methyl]-9-(dimethylamino)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-2,3,4,7-tetrahydro-1,5-benzoxazonin-6-one REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CN(CCCCC(O)=O)c1ccc(cc1)\C=C\c1ccc(cc1)[N+]([O-])=O NAME: N-(trans-4'-nitro-4-stilbenyl)-N-methyl-5-aminopentanoic acid REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)C2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)CC3=CC=NC=C3)[C@@H](C)CO NAME: (2S,3S)-8-(dimethylamino)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-2-[[methyl(pyridin-4-ylmethyl)amino]methyl]-3,4-dihydro-2H-1,5-benzoxazocin-6-one REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: [H]N(C)C NAME: dimethylamine REASON: CORRECT Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@@H]1CN(C(=O)CC2=C(C=CC(=C2)N(C)C)O[C@@H]1CN(C)C(=O)NC(C)C)[C@@H](C)CO NAME: 1-[[(2S,3R)-9-(dimethylamino)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-2,3,4,7-tetrahydro-1,5-benzoxazonin-2-yl]methyl]-1-methyl-3-propan-2-ylurea REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)C2=C(C(=CC=C2)N(C)C)O[C@@H]1CN(C)S(=O)(=O)C3=C(ON=C3C)C)[C@H](C)CO NAME: N-[[(2S,3S)-10-(dimethylamino)-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-2-yl]methyl]-N,3,5-trimethyl-4-isoxazolesulfonamide REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CN(C)C1=CC=C(C=C1)NC2=C(CS(=O)(=O)C2)[N+](=O)[O-] NAME: N4,N4-dimethyl-N1-(4-nitro-1,1-dioxo-2,5-dihydrothiophen-3-yl)benzene-1,4-diamine REASON: CORRECT Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: CCCOP(=O)(C1=CC=C(C=C1)N(C)C)C(C2=CC=C(C=C2)C)NC3=CC=CC=C3 NAME: 4-[[anilino-(4-methylphenyl)methyl]-propoxyphosphoryl]-N,N-dimethylaniline REASON: CORRECT Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: NC(C(CCCCCCCCCCCC)CC1=CC=CC=C1)(C)C NAME: 3-benzyl-2-methyl-2-pentadecanamine REASON: CORRECT Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H](Cc1ccccc1)N(C)CC#C NAME: (-)-selegiline REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H](N)c1ccccc1 NAME: (1S)-1-phenylethanamine REASON: CORRECT Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)N(C)C)O[C@H]1CN(C)S(=O)(=O)C3=CC=CS3)[C@H](C)CO NAME: N-[[(2R,3R)-8-(dimethylamino)-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-2-yl]methyl]-N-methyl-2-thiophenesulfonamide REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C(NC1=CC=C(C=C1)C[C@@H]2CC[C@@H](N2)[C@@H](C3=CC=CC=C3)O)([C@H]4N5C(C=CN=C5CC4)=O)=O NAME: vibegron REASON: CORRECT Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)CC2=C(C=CC(=C2)N(C)C)O[C@H]1CN(C)C(=O)NC3=C(ON=C3C)C)[C@@H](C)CO NAME: 1-[[(2R,3S)-9-(dimethylamino)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-2,3,4,7-tetrahydro-1,5-benzoxazonin-2-yl]methyl]-3-(3,5-dimethyl-4-isoxazolyl)-1-methylurea REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: Cl.OC(=O)CCCN1CCC(=CC1)C2=CC=CC=C2 NAME: 4-[4-phenyl-3,6-dihydro-1(2H)-pyridinyl]butanoic acid hydrochloride REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CC(N)Cc1cccc(O)c1 NAME: alpha-Methyl-m-tyramine REASON: CORRECT Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)C2=C(C(=CC=C2)N(C)C)O[C@H]1CN(C)S(=O)(=O)C3=C(ON=C3C)C)[C@H](C)CO NAME: N-[[(2R,3S)-10-(dimethylamino)-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-2-yl]methyl]-N,3,5-trimethyl-4-isoxazolesulfonamide REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CN(C\C=C\C#CC(C)(C)C)Cc1cccc2ccccc12 NAME: terbinafine REASON: CORRECT Found a tertiary amine substructure that is not bound to a carbonyl.
False positives: SMILES: N(C(C(C(NCCN(CC(NCCN)=O)CC(NCCN)=O)=O)CCOCCOCCOCC#C)=O)CCN(CC(NCCN)=O)CC(NCCN)=O NAME: N(1),N(3)-bis[2-(bis{2-[(2-aminoethyl)amino]-2-oxoethyl}amino)ethyl]-2-[2-(2-{2-[(prop-2-yn-1-yl)oxy]ethoxy}ethoxy)ethyl]malonamide REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C1CCC(CC1)CN2C[C@H](COC[C@@H]3[C@@H]2CC[C@@H](O3)CC(=O)NCC4=CC=C(C=C4)F)O NAME: 2-[(3R,6aS,8R,10aS)-1-(cyclohexylmethyl)-3-hydroxy-3,4,6,6a,8,9,10,10a-octahydro-2H-pyrano[2,3-c][1,5]oxazocin-8-yl]-N-[(4-fluorophenyl)methyl]acetamide REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: [H][C@@](COCCCCCCCCCCCCCCCC)(COP(O)(=O)OCCN)OCCCCCCCCCCCCCCCC NAME: 1,2-dihexadecyl-sn-glycero-3-phosphoethanolamine REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: O=C(NCC(=O)N[C@@H](CO)C(O)=O)[C@@H](N)CC=1NC=NC1 NAME: His-Gly-Ser REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: [H][C@@]1(O[C@H](O[C@@H]2[C@H](O)[C@@H](O[C@H](CO)[C@@]3([H])O[C@H](O[C@H]4[C@@H](O)[C@H](O)[C@]([H])(O[C@@H]4O[C@H]4[C@@H](O)[C@H](O)[C@]([H])(O[C@@H]4OCCCN)[C@H](O)CO)[C@H](O)CO)[C@@H](O)[C@@H](O)[C@@H]3O)O[C@]([H])([C@H](O)CO)[C@H]2O)[C@@H](O)[C@@H](O)[C@@H]1O)[C@H](O)CO NAME: alpha-DD-Hep-(1->3)-alpha-DD-Hep-(1->6)-alpha-DD-Hep-(1->2)-alpha-DD-Hep-(1->2)-alpha-DD-Hep-O[CH2]3NH2 REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C1=CC(=CC=C1C(=O)NC(CCC(=O)NC(CCC(=O)NC(CCC(=O)O)C(=O)O)C(=O)O)C(=O)O)NCC2=CN=C3C(=N2)C(=O)NC(=N3)N NAME: Pteropterin REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: CC(C)SC1=NN=C(S1)NC2=CC=CC=C2 NAME: N-phenyl-5-(propan-2-ylthio)-1,3,4-thiadiazol-2-amine REASON: WRONGLY CLASSIFIED Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)NC(=O)CC3=CN(C4=CC=CC=C43)C)O[C@H]1CNC)[C@@H](C)CO NAME: N-[(2R,3R)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-2-(methylaminomethyl)-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-8-yl]-2-(1-methyl-3-indolyl)acetamide REASON: WRONGLY CLASSIFIED Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: N(CC1=CC=CC=C1)(C/C(=N/O)/N)C2=CC=CC=C2 NAME: cetoxime REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: O=C(N[C@@H](CCCN=C(N)N)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC=1NC=NC1)CC=2NC=NC2 NAME: His-His-Arg REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: ClC[C@H]1N[C@H](C(=O)N[C@H](C(=O)N2[C@H](C(=O)N3[C@H](C(=O)O)C[C@@H](C3)C)CCCC2)C(C)C)CC[C@@H]1OC NAME: Chloromyxamide B REASON: WRONGLY CLASSIFIED Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: CN1CCN(CC1)c1ccc2ccccc2n1 NAME: N-methylquipazine REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CN(C)CCN(CC1=CC=C(C=C1)OC)C2=NC=CC=N2 NAME: N'-[(4-methoxyphenyl)methyl]-N,N-dimethyl-N'-(2-pyrimidinyl)ethane-1,2-diamine REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C1[C@@H](O[C@@H]([C@H]2[C@@H]1C3=C(O2)C=CC(=C3)NS(=O)(=O)C4=CC=CC=C4)CO)CC(=O)NCC(F)(F)F NAME: 2-[(1R,3R,4aS,9aR)-6-(benzenesulfonamido)-1-(hydroxymethyl)-3,4,4a,9a-tetrahydro-1H-pyrano[3,4-b][1]benzofuran-3-yl]-N-(2,2,2-trifluoroethyl)acetamide REASON: WRONGLY CLASSIFIED Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: C1CCN(CC1)CCNC(=O)C[C@@H]2C[C@H]3[C@@H]([C@@H](O2)CO)OC4=C3C=C(C=C4)NC(=O)NC5CCCC5 NAME: 2-[(1S,3S,4aR,9aS)-6-[[(cyclopentylamino)-oxomethyl]amino]-1-(hydroxymethyl)-3,4,4a,9a-tetrahydro-1H-pyrano[3,4-b]benzofuran-3-yl]-N-[2-(1-piperidinyl)ethyl]acetamide REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C1CCN2[C@@H](CN(C1)CC3=CC=NC=C3)[C@@H]([C@@H]2CO)C4=CC=C(C=C4)C5=CCCC5 NAME: [(8R,9S,10R)-9-[4-(1-cyclopentenyl)phenyl]-6-(pyridin-4-ylmethyl)-1,6-diazabicyclo[6.2.0]decan-10-yl]methanol REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: O=C(N[C@H](C(=O)N[C@@H](CC(O)=O)C(O)=O)CO)[C@@H](N)[C@H](CC)C NAME: Ile-Ser-Asp REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: CCCN1C[C@H]([C@@H](CN(C(=O)C2=C(C=CC(=C2)NC(=O)C3=CC(=CC=C3)F)OC[C@@H]1C)C)OC)C NAME: 3-fluoro-N-[(4S,7R,8S)-8-methoxy-4,7,10-trimethyl-11-oxo-5-propyl-2-oxa-5,10-diazabicyclo[10.4.0]hexadeca-1(12),13,15-trien-14-yl]benzamide REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CCCCN(C1=NC(=NC2=CC=CC=C21)C3=CC=NC=C3)CCCC NAME: N,N-dibutyl-2-(pyridin-4-yl)quinazolin-4-amine REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: CC=CC1=CC=C(C=C1)[C@@H]2[C@@H]3CN(CCCCN3[C@H]2CO)S(=O)(=O)C4=CC=C(C=C4)OC NAME: LSM-40723 REASON: WRONGLY CLASSIFIED Found a tertiary amine substructure that is not bound to a carbonyl.
 * SMILES: C[C@H]1CN(C(=O)C2=C(N=CC(=C2)C3=CC(=CC=C3)C(=O)N(C)C)O[C@H]1CNC)[C@@H](C)CO NAME: 3-[(2R,3S)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-2-(methylaminomethyl)-6-oxo-3,4-dihydro-2H-pyrido[2,3-b][1,5]oxazocin-8-yl]-N,N-dimethylbenzamide REASON: WRONGLY CLASSIFIED Found a secondary amine substructure that is not bound to a carbonyl.
 * SMILES: O=C(N[C@H](C(=O)N[C@@H](C(C)C)C(O)=O)CO)[C@@H](N)CCCCN NAME: Lys-Ser-Val REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: C1[C@H]2[C@@H]([C@@H]([C@H](O2)N3C4=C(C(=NC=N4)N)N=C3SC5=CC=C(C=C5)Cl)O)OP(=O)(O1)O NAME: (4aS,6S,7S,7aR)-6-[6-amino-8-[(4-chlorophenyl)thio]-9-purinyl]-2-hydroxy-2-oxo-4a,6,7,7a-tetrahydro-4H-furo[3,2-d][1,3,2]dioxaphosphorin-7-ol REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: O=C(N[C@@H](CC1=CC=CC=C1)C(O)=O)[C@@H](NC(=O)[C@@H](N)C)CC2=CC=C(O)C=C2 NAME: Ala-Tyr-Phe REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
 * SMILES: [H][C@@]12C[C@@](C[C@H](N)C(O)=O)(O[C@]1([H])[C@H](O)[C@H](O)CO2)C(O)=O NAME: neodysiherbaine A REASON: WRONGLY CLASSIFIED Found a primary amine substructure that is not bound to a carbonyl.
False negatives: SMILES: CCCN(CCC)C(=O)SCC NAME: EPTC REASON: MISSED No qualifying amine functional group found.
 * SMILES: O=C(N[C@H](CO)CC1=C(O)C=CC=C1)/C=C/CCCCCCC(=O)O NAME: Cordytakaoamide B REASON: MISSED No qualifying amine functional group found.
 * SMILES: CCC(C(N)=O)(C(N)=O)c1ccccc1 NAME: Phenylethylmalonamide REASON: MISSED No qualifying amine functional group found.
 * SMILES: CCCSC(=O)N(CCC)CCC NAME: S-propyl dipropylcarbamothioate REASON: MISSED No qualifying amine functional group found.
 * SMILES: C1COC2=C(O1)C=CC(=C2)N3CC(CC3=O)C(=O)NC(CC4=CC=CC=C4)C5=NC6=CC=CC=C6N5 NAME: N-[1-(1H-benzimidazol-2-yl)-2-phenylethyl]-1-(2,3-dihydro-1,4-benzodioxin-6-yl)-5-oxo-3-pyrrolidinecarboxamide REASON: MISSED No qualifying amine functional group found.
 * SMILES: O(C[C@@H](NC(=O)C(NC(=O)C1=CC=CC=C1)CC2=CC=CC=C2)CC3=CC=CC=C3)C(=O)C NAME: aurantiamide acetate REASON: MISSED No qualifying amine functional group found.
 * SMILES: CCCCCCCCC=CCCCCCCCC(=O)NC(CC1=CC=C(C=C1)O)CO NAME: N-[1-hydroxy-3-(4-hydroxyphenyl)propan-2-yl]-9-octadecenamide REASON: MISSED No qualifying amine functional group found.
 * SMILES: C(=C\SC)(\C1=C(OCCCCC)C=CC=C1)/N2C=CN=C2 NAME: neticonazole REASON: MISSED No qualifying amine functional group found.
 * SMILES: C[C@@H](c1nc(cs1)-c1ccc(cc1)C#N)[C@@](Cn1cncn1)(OCOP(O)(O)=O)c1ccc(F)cc1F NAME: BMS 379224 REASON: MISSED No qualifying amine functional group found.
 * SMILES: C1=CC=C(C(=C1)C[C@]2([C@@H](OC(=N2)C3=CC=C(C=C3)OCCCO)C4=CC=CC=C4CN=[N+]=[N-])C(=O)N)CN=[N+]=[N-] NAME: (4S,5S)-5-[2-(azidomethyl)phenyl]-4-[[2-(azidomethyl)phenyl]methyl]-2-[4-(3-hydroxypropoxy)phenyl]-5H-oxazole-4-carboxamide REASON: MISSED No qualifying amine functional group found.
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:32952
  name: amine
  definition: A compound formally derived from ammonia by replacing one, two or three
    hydrogen atoms by hydrocarbyl groups.
  parents:
  - CHEBI:50047
  xrefs:
  - KEGG:C00706
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 30
  log_lines_of_code: 3.4011973816621555
  max_indent: 3
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - GetFormalCharge
  - GetAtomicNum
  - MolFromSmiles
  - GetAtoms
  - IsInRing
  - GetIsAromatic
  methods_called_count: 6
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_amine(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No qualifying free amine functional group found."
  returns_count: 2
  complexity: 3.080239476332431
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: "Error executing is_amine('Cl.C=1C=C(CCCN(CCNC2=CC(N(C(N2C)=O)C)=O)CCO)C=CC1[N+](=O)[O-]'):\n\
  \ 'Bond' object has no attribute 'IsDouble'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []