Attempt 4 at alpha-amino acid ester, f1=0.0
(currently fails to compile, but committing anyway

The previous program did not accurately identify alpha-amino acid esters because the SMARTS pattern used was too general and did not capture the specific structural features of an alpha-amino acid ester. This led to both false positives (molecules incorrectly classified as alpha-amino acid esters) and false negatives (molecules that are alpha-amino acid esters but were not identified).

To improve the classification, we need a more precise SMARTS pattern or a programmatic approach that captures the key features of an alpha-amino acid ester:

1. An **alpha-carbon** (a tetrahedral carbon with at least one hydrogen) connected to:
   - An **amino group** (nitrogen with one or two hydrogens).
   - A **carbonyl group** (C=O) that is part of an **ester linkage** (C(=O)O-C).

By explicitly checking for these connections, we can more accurately identify alpha-amino acid esters.

Here is the improved code:

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.7052023121387283 is too low.
Outcomes:
------

True positives: SMILES: COC(=O)[C@@H](N)CCCCN NAME: methyl L-lysinate REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: [C@H]1(CCC(N1C)=O)C(=O)OC NAME: methyl 1-methyl-5-oxo-L-prolinate REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: CC(C)C(C(=O)OCC(=O)C1=CNC2=CC=CC=C21)NS(=O)(=O)C3=C(C=CC=C3Cl)Cl NAME: 2-[(2,6-dichlorophenyl)sulfonylamino]-3-methylbutanoic acid [2-(1H-indol-3-yl)-2-oxoethyl] ester REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C1N(C(C(=O)OC)C(C)C)CC2=C1C=C(O)C3=C2OC4(C5(C(C(C(O)CC5)(C)C)CCC4C)C)C3 NAME: Stachartin C REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O(C(C)(C)C)C(=O)[C@@H](N)CCC(=O)N NAME: Glutamine t-butyl ester REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C(N(O)CCCC[C@H](NC(=O)CC(O)(C(=O)O)CC(=O)N[C@H](C(=O)O)CCCCN(O)C(=O)/C=C/C1=CC=CC=C1)C(=O)OC)/C=C/C2=CC=CC=C2 NAME: Nannochelin B REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: C1=CC=C2CN(C(C)=O)[C@H](C(OC3=CC(=CN=C3)Cl)=O)CC2=C1 NAME: (5-Chloropyridin-3-yl) (3S)-2-acetyl-3,4-dihydro-1H-isoquinoline-3-carboxylate REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C1N2[C@@H]3NC=4C=CC=CC4[C@]3(CC=C(C)C)C[C@@H]2C(=O)O[C@@H]1CC(C)C NAME: Mollenine A REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: Cl.COC([C@H](CS)N)=O NAME: Mecysteine hydrochloride REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C(OC)[C@@H](N=[N+]([O-])/C=C\CCCCCCCCCC(CC)C)C NAME: Azodyrecin B REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O(C(=O)CN1CCNCC1)CC NAME: Ethyl piperazinoacetate REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: NC1=NC=NC2=C1N=CN2[C@@H]3O[C@H](COP(=O)(O)O)[C@@H](OC([C@@H](N)CO)=O)[C@H]3O NAME: 3'-L-seryl-AMP REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O(C(C)(C)C)[C@@H]([C@H](N)C(OC)=O)C NAME: O-t-butyl-l-threonine methyl ester REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: C1(=CN(C(NC1=O)=O)C/C=C/CP(N[C@H](C(OCC2=CC=CC=C2)=O)C)(=O)OC3=CC=CC=C3)Cl NAME: Benzyl (2S)-2-[[[(E)-4-(5-chloro-2,4-dioxopyrimidin-1-yl)but-2-enyl]-phenoxyphosphoryl]amino]propanoate REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: NC1=NC=NC2=C1N=CN2[C@@H]3O[C@H](COP(=O)(O)O)[C@@H](OC([C@H](CC(C)C)N)=O)[C@H]3O NAME: 3'-L-leucyl-AMP REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O(CCCCCCCCCCCC)C(=O)C(N(C)C)C NAME: DDAIP REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C1N[C@H](C(=O)OC(C(O)C)C)CC1 NAME: (3'-hydroxybutan-20-yl)5-oxopyrrolidine-2-carboxylate REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: CC1=CC=C(C=C1)S(=O)(=O)NCC(=O)OC2CCOC2=O NAME: 2-[(4-methylphenyl)sulfonylamino]acetic acid (2-oxo-3-oxolanyl) ester REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: S(C[C@H](O)C(=O)O)C[C@@H](N1C(=O)[C@H](C)CC1=O)C(=O)OC NAME: Violaceimide A REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H]([C@@H](N)C(=O)OC2=C1C=CC=C2NC=O)C NAME: Streptomyceamide B REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: COC(=O)[C@@H]1[C@H]([C@@H]2CN3C(=CC=C(C3=O)C4=CC=CC=C4)[C@@H]2N1CC5=CC=CC=N5)CO NAME: (2S,3S,3aR,9bR)-3-(hydroxymethyl)-6-oxo-7-phenyl-1-(2-pyridinylmethyl)-3,3a,4,9b-tetrahydro-2H-pyrrolo[2,3-a]indolizine-2-carboxylic acid methyl ester REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: C1=CC=C(C=C1)S(=O)(=O)NCC(=O)OCC(=O)C2=CC=C(C=C2)[N+](=O)[O-] NAME: 2-(benzenesulfonamido)acetic acid [2-(4-nitrophenyl)-2-oxoethyl] ester REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H](C[C@@H](OC(=O)CNC=O)CCCCCCC)[C@@H]1CCCCCCCCCC NAME: Panclicin D REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@H](CC[C@H](C)C[C@H](C(N([C@H]1CC(C)C)C)=O)C)CCC/C=C\N(C(=O)/C=C(/OC)\CC)C NAME: Kanamienamide REASON: CORRECT Contains alpha-amino acid ester moiety
 * SMILES: CO[C@@H]1\C=C\C=C(C)\Cc2cc(OC)c(Cl)c(c2)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N(C)C(C)=O)[C@]2(C)O[C@H]2[C@H](C)[C@@H]2C[C@@]1(O)NC(=O)O2 NAME: maytansine REASON: CORRECT Contains alpha-amino acid ester moiety
False positives: SMILES: COC(=O)[C@H]1[C@@H]([C@H]2CN3C(=CC=C(C3=O)C4=CCCC4)[C@H]2N1C(=O)CC5=CN=CC=C5)CO NAME: methyl (2R,3R,3aS,9bS)-7-(cyclopenten-1-yl)-3-(hydroxymethyl)-6-oxo-1-(2-pyridin-3-ylacetyl)-3,3a,4,9b-tetrahydro-2H-pyrrolo[2,3-a]indolizine-2-carboxylate REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O(C[C@H](NC(=O)C1=C(O)C(O)=CC=C1)C(OC[C@H](NC(=O)C2=C(O)C(O)=CC=C2)C(O)=O)=O)C(=O)[C@@H](NC(=O)C3=C(O)C(O)=CC=C3)CO NAME: N,N',N''-Tris(2,3-dihydroxybenzoyl)-O-L-seryl-O-L-seryl L-serine REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@H](C(=O)N2[C@H](C(=O)N([C@H](C(=O)O[C@H](C(C(N[C@H](C(N([C@H]1[C@H](CC)C)C)=O)C(C)C)=O)C)CCCC#C)C(C)C)C)CCC2)CC3=CC=CC=C3 NAME: Hantupeptin A REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=NN(O)CCC[C@H]1NC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@H](NC([C@H](COC1=O)NC(=O)[C@H](NC(=O)CNC(=O)C[C@H](O)CCCCCCCCC)[C@@H](O)C(=O)O)=O)[C@H](O)C)CCCN(O)N=O)C NAME: Megapolibactin Bcyc REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C/1N[C@H](C(=O)NC(C(=O)N2[C@H](C(=O)NC(C(O)C(=O)N[C@H](C(=O)NCC(N3[C@H](C(N4[C@H](C(N[C@@H](C(N[C@H](C(N\C1=C\C)=O)CO)=O)[C@H](CC)C)=O)CCC4)=O)CCC3)=O)CCC(=O)N)CC(OC(=O)C(N(C(=O)C)C)CC5=CC=C(O)C=C5)CC(O)C(O)CC(C)C)CCC2)CCC6=CC=CC=C6)[C@H](O)C NAME: Lyngbyazothrin D REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H]([C@H](NC(=O)C2=C3N=C4C(=C(C(=O)C(=C4C(=O)N[C@@H]5C(=O)N[C@@H](C(=O)N6[C@H](C(=O)N(C)CC(N([C@H](C(O[C@@H]5CO)=O)C)C)=O)CC(C6)=O)C(C)C)N)C)OC3=C(C)C=C2)C(=O)N[C@@H](C(=O)N7[C@@H](C)C[C@@H]([C@H]7C(N(CC(N([C@H]1C(C)C)C)=O)C)=O)O)C(C)C)C NAME: Actinomycin Y7 REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: CCCCCC[C@H](C)C[C@H](C)[C@H]1OC(=O)[C@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](NC(=O)CNC(=O)[C@@H]1C)C(C)C NAME: emericellamide B REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: ClC=1N(O)C(C(=O)N[C@H](C(=O)N[C@H]2C(=O)NC(C(=O)NC(C(=O)N[C@@H]([C@@H](C3=CC=CC=C3)C)C(NC(C(N4[C@H](C(O[C@@H]2C)=O)C[C@H](/C=C\C)C4)=O)[C@H](CC)C)=O)CC5[C@H]([N+](=O)[O-])C5)[C@@H](C6=CC=CC=C6)C)CC7[C@H]([N+](=O)[O-])C7)=CC1 NAME: Takaokamycin REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H]([C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)C[C@H](O)CCCCCCC)CC(C)C)CCC(=O)N)C(=O)N[C@@H](C(=O)N[C@@H](C(=O)N[C@@H](C(N[C@H](C(N[C@@H](C(N[C@H]1[C@H](CC)C)=O)CO)=O)CC(C)C)=O)CO)CC(C)C)C(C)C)C NAME: Pseudodesmin A REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: S(=O)(CC[C@H](NC(=O)[C@@H](NC(=O)CCC)[C@H](CC)C)C(=O)NC1C(=O)N/C(/C(=O)N[C@@H]2C(=O)N([C@@H](CC3=CC=CC=C3)C(N([C@H](C(N[C@H](C(OC1C)=O)C(C)C)=O)CC4=CC=C(O)C=C4)C)=O)C(O)CC2)=C\C)C NAME: Symplostatin 2 REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: S(=O)(=O)(OC[C@@H](OC)C(=O)N[C@@H](C(=O)N[C@@H]1C(=O)N[C@@H](NCCCC[C@@H](N)C(=O)O)C(=O)N[C@@H]2C(=O)N([C@@H]([C@H](CC)C)C(N([C@H](C(N[C@H](C(O[C@@H]1C)=O)[C@H](CC)C)=O)CC3=CC=CC=C3)C)=O)[C@H](O)CC2)CCC4=CC=C(O)C=C4)O NAME: Oscillapeptin F REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1N(C(=O)/C=C/[C@@H](NC(=O)[C@@H](NC(=O)[C@@H](OC(=O)[C@@H](N(C)C)[C@H](CC)C)CC(C)C)CC(C)C)C)[C@@H](C)C(=C1)OC NAME: Gallinamide A REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: S1C2=N[C@H](C1)C=C(C(=O)N[C@H](C(=O)N([C@H](C(=O)N(C)[C@H](C(N3[C@H](C(O[C@@H](C[C@H](C[C@@H]([C@@H]2C)O)C)C(C)(C)C)=O)CCCC3)=O)[C@H](CC)C)C)C)CC4=CC=C(OC)C=C4)C NAME: Apratoxin H REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: P(=O)(O[C@H](C(=O)N)[C@H]1NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](NC(=O)[C@@H](NC(=O)[C@H](CC(=O)O)NC([C@H](NC([C@H]([C@H](OC(\C(\NC([C@@H](NC1=O)CCC(=O)O)=O)=C\C=2C3=C(C=CC=C3)NC2)=O)C)NC(=O)[C@@H](NC(=O)C4OC4CCC)CO)=O)CC=5C6=C(C=CC=C6)NC5)=O)CC(=O)O)C7=CC=C(O)C=C7)CC(=O)O)(O)O NAME: CDA2a REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: S(=O)(=O)(O[C@@H](C(=O)N[C@@H]1C(=O)N[C@H](C(=O)N[C@@H]2C(=O)N([C@@H]([C@H](CC)C)C(N([C@H](C(N[C@H](C(O[C@@H]1C)=O)[C@H](CC)C)=O)CC3=CC=CC=C3)C)=O)[C@H](OC)CC2)CCCN=C(N)N)CO)O NAME: Micropeptin MZ939B REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: S([C@@H]([C@@H](O)CCCC(O)=O)/C=C/C=C/C=C\C/C=C\CCCCC)C[C@H](N)C(O[C@H](COC(=O)CCCCCCCCCCCCCCCCCCCCCCC)COP(OCCN)(O)=O)=O NAME: PE(24:0/LTE4) REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H](C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(O[C@@H](C(N([C@H]1C(C)C)C)=O)[C@H](CC)C)=O)C(C)C)C)C(C)C)C(C)C)C)[C@H](CC)C NAME: Enniatin I REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O[C@H]1N2[C@@H](CC3=CC=CC=C3)C(=O)N(C(CC4=CC=C(O)C=C4)C(=O)N[C@@]([C@@H](CC)C)(C(O[C@@H]([C@H](NC(=O)[C@@H](NC(=O)C(C)C)CCCNC(=O)N)C(=O)N[C@H](C(=O)N[C@@](CC1)(C2=O)[H])CC(C)C)C)=O)[H])C NAME: (2S)-N-[(2S,8S,11R,12S,15S,18S,21R)-2-Benzyl-8-[(2R)-butan-2-yl]-21-hydroxy-5-[(4-hydroxyphenyl)methyl]-4,11-dimethyl-15-(2-methylpropyl)-3,6,9,13,16,22-hexaoxo-10-oxa-1,4,7,14,17-pentazabicyclo[16.3.1]docosan-12-yl]-5-(carbamoylamino)-2-(2-methylpropanoylamino)pentanamide REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: COC(=O)CNC(=O)c1ccccc1 NAME: methyl hippurate REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1N[C@]2(C(=O)O[C@]2(C1)C)[C@@H](O)[C@@H]3C=CCCC3 NAME: Salinosporamide K REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: ClC1=C(OC)C=CC(=C1)C[C@@H]2N(C(=O)[C@@H](N3C(=O)[C@@H](NC(=O)[C@H](CCCN=C(N)N)NC([C@H]([C@H](OC([C@@H](NC2=O)C(C)C)=O)C)NC(=O)[C@H](O)CO)=O)CC[C@H]3OC)[C@H](CC)C)C NAME: Micropeptin HU909 REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H]([C@H](N(C(=O)C2=CC=CC=C2)C)C(=O)N([C@H](C(=O)N[C@@H](C(C)C)C(N[C@H](C(N([C@H](C(N([C@H]1C(C)C)C)=O)CC(C)C)C)=O)C(C)C)=O)CC3=CC=CC=C3)C)C NAME: Pteratide III REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: O=C1O[C@@H](CC(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@@H](C)C(N2[C@@H](C(N[C@@H](C(N[C@H](C(N[C@H]1[C@H](OC)C)=O)C(C)C)=O)[C@H](CC)C)=O)CCC2)=O)C(C)C)[C@H](O)C)CCCCCCCCCCCCCCC/C=C\CCCCCCCC NAME: Peptidolipin E REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: P(=O)(OC12N(C(C(=O)OCC3=CC=C([N+](=O)[O-])C=C3)=C(C1(OC4=CC=CC=C4)C)OC5=CC=CC=C5)C(=O)C2C(O)C)(O)O NAME: Proteinase K REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
 * SMILES: C1CCC(CC1)C(=O)NCC(=O)OCC(=O)NC2=CC=C(C=C2)C#N NAME: 2-[[cyclohexyl(oxo)methyl]amino]acetic acid [2-(4-cyanoanilino)-2-oxoethyl] ester REASON: WRONGLY CLASSIFIED Contains alpha-amino acid ester moiety
False negatives: SMILES: O=C1N(C(=NC2=C1C=CC=C2)C(OC(=O)C)C(C)C)C3C(=O)OC4(C3)C5=C(C=CC=C5)N6C4N(O)C(C)C6=O NAME: Tryptoquivaline D REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: CCC1=CC2=C(C=C1)N(C3=NC4=CC=CC=C4N=C23)CC(=O)OC NAME: 2-(9-ethyl-6-indolo[3,2-b]quinoxalinyl)acetic acid methyl ester REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: O=C1N(C(=NC2=C1C=CC=C2)[C@H](OC(=O)C)C(C)C)[C@@H]3C(=O)O[C@@]4(C3)C5=C(C=CC=C5)N6[C@H]4NC(C)(C)C6=O NAME: Aspertoryadin D REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: O=C1N(C=NC2=C1C=CC=C2)C(C(=O)OC)C[C@]3(O)C4=C(C=CC=C4)N5[C@H]3N(O)C(C)(C)C5=O NAME: Tryptoquivaline R REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: O=C1N(C(=NC2=C1C=CC=C2)C(=O)C(C)C)[C@@H]3C(=O)O[C@]4(C3)C5=C(C=CC=C5)N6[C@@H]4NC(C)C6=O NAME: Deoxynortryptoquivalone REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: O(C1(C2N(C=3C1=CC=CC3)C(=O)C(N2O)(C)C)CC(N4C(=O)C=5C(N=C4)=CC=CC5)C(OC)=O)C(=O)C(C)C NAME: [3-hydroxy-4-[3-methoxy-3-oxo-2-(4-oxoquinazolin-3-yl)propyl]-2,2-dimethyl-1-oxo-3aH-imidazo[1,2-a]indol-4-yl] 2-methylpropanoate REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: O=C1OCC2=CC=C(N2[C@H]1C(C)C)C=O NAME: (S)-4-isopropyl-3-oxo-3,4-dihydro-1H-pyrrolo[2,1-c][1,4]oxazine-6-carbaldehyde REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: CC1=CC(=C(N1C2=CC=C(C=C2)OC)C)C(=O)COC(=O)CN3C=NC4=CC=CC=C43 NAME: 2-(1-benzimidazolyl)acetic acid [2-[1-(4-methoxyphenyl)-2,5-dimethyl-3-pyrrolyl]-2-oxoethyl] ester REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: O=C1N(C=NC2=C1C=CC=C2)C(C(=O)OC)C[C@]3(O)C4=C(C=CC=C4)N5[C@H]3NC(C)(C)C5=O NAME: Tryptoquivaline P REASON: MISSED Does not contain alpha-amino acid ester moiety
 * SMILES: CC1=CC2=C(O1)C=C3N2C=NN(C3=O)CC(=O)OC NAME: 2-(7-methyl-4-oxo-3-furo[3,4]pyrrolo[3,5-c][1,2,4]triazinyl)acetic acid methyl ester REASON: MISSED Does not contain alpha-amino acid ester moiety
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:46874
  name: alpha-amino acid ester
  definition: The amino acid ester derivative obtained the formal condensation of
    an alpha-amino acid with an alcohol.
  parents:
  - CHEBI:46668
  xrefs:
  - KEGG:C03317
  all_positive_examples: []
config: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: too many values to unpack (expected 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0