Attempt 4 at phosphatidylglycerol, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.39419588875453443 is too low.
Outcomes:
------

True positives: SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(19:0/15:0) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCCC)COC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:4(7Z,10Z,13Z,16Z)/19:1(9Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: C([C@@](COC(CCCCCCC/C=C\C/C=C\C/C=C\CC)=O)(OC(CCCCCCC/C=C\C/C=C\CCCCC)=O)[H])OP(=O)(O)OC[C@@](CO)([H])O NAME: PG(18:3(9Z,12Z,15Z)/18:2(9Z,12Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: C([C@@](COC(CCCC/C=C\C/C=C\C/C=C\CCCCC)=O)(OC(CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)=O)[H])OP(=O)(O)OC[C@@](CO)([H])O NAME: PG(18:3(6Z,9Z,12Z)/22:4(7Z,10Z,13Z,16Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCCC/C=C\CCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(17:1(9Z)/22:2(13Z,16Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCC/C=C\C/C=C\CCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:2(13Z,16Z)/21:0) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCCCCC\C=C/CCCCCCCC(=O)OC[C@H](COP(O)(=O)OC[C@@H](O)CO)OC(=O)CCCCCCC\C=C/CCCCCCCC NAME: 1,2-dioleoyl-sn-glycero-3-phospho-(1'-sn-glycerol) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: C([C@@](COC(CCCCCCC/C=C\CCCCCCCC)=O)(OC(CCCCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)=O)[H])OP(=O)(O)OC[C@@](CO)([H])O NAME: PG(18:1(9Z)/22:5(7Z,10Z,13Z,16Z,19Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCC)(OC[C@@H](O)COP(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCC)(O)=O)(O)=O NAME: CL(8:0/8:0/11:0/14:0) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCCC)COC(=O)CCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(14:0/19:1(9Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCC/C=C\CCCCCCCC)COC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:4(7Z,10Z,13Z,16Z)/20:1(11Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCCC)COC(=O)CCCCCCCCC/C=C\CCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(20:1(11Z)/19:1(9Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCCCCCCCCCCCCC(=O)OC[C@H](COP(O)(=O)OC[C@@H](O)CO)OC(=O)CCCCCCC\C=C/CCCCCCCC NAME: 1-hexadecanoyl-2-[(9Z)-octadec-9-enoyl]-sn-glycero-3-phospho-(1'-sn-glycerol) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(OC[C@@H](O)COP(O)(O)=O)(O)=O NAME: [(2S)-3-({[(2R)-2-[(7Z,10Z,13Z,16Z)-docosa-7,10,13,16-tetraenoyloxy]-3-(octadecanoyloxy)propoxy](hydroxy)phosphoryl}oxy)-2-hydroxypropoxy]phosphonic acid REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCC)COC(=O)CCCCCCCCC/C=C\CCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:1(11Z)/17:1(9Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCCC/C=C\CCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(19:1(9Z)/22:2(13Z,16Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(17:0/14:0) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCC\C=C/C\C=C/CCCCCCCC(=O)OC[C@@H](O)COP(O)(=O)OCC(O)COP(O)(=O)OC[C@H](O)COC(=O)CCCCCCC\C=C/C\C=C/CCCCC NAME: 1,1'-dilinoleyl 2,2'-dilysocardiolipin REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: [C@](COC(=O)CCCCCCCCCCCCCCCCCCCC)(OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)([H])COP(OCC(CO)O)(=O)O NAME: PG(21:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCC(O)=O)COC(=O)CCCCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PS-PG REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:4(7Z,10Z,13Z,16Z)/20:2(11Z,14Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCC/C=C\CCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:1(11Z)/22:6(4Z,7Z,10Z,13Z,16Z,19Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: [C@](COC(=O)CCCCCCCCCCCCCCCC)(COP(OCC(CO)O)(O)=O)(OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)[H] NAME: PG(17:0/20:4(5Z,8Z,11Z,14Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCC)COC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(22:4(7Z,10Z,13Z,16Z)/16:1(9Z)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCC(O)C(O)C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCC(C)C)(OC[C@@H](O)CO)(O)=O NAME: PG(i-24:0/20:3(8Z,11Z,14Z)-2OH(5,6)) REASON: CORRECT Contains glycerol-phosphate moiety with 2 fatty acid chains
False positives: SMILES: [C@@H]1(C(C(C([C@H](C1O)O)O)O)O)OP(OC[C@@](COC(CCCCCC/C=C\C/C=C\C/C=C\CCCCC)=O)(OC(CCCCCCCCC/C=C\CCCCCC)=O)[H])(O)=O NAME: PI(20:3(8Z,11Z,14Z)/18:1(11Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCC\C=C\C[C@@H]1[C@H]([C@H](O)C[C@@H]1O)/C=C/[C@@H](O)CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCC(CC)C)(O)(O)=O NAME: PA(a-25:0/PGF2alpha) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC1C(O)C(O)C(O)[C@@H](O)C1O)(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCCCCCC)(O)=O NAME: PI(22:0/18:4(6Z,9Z,12Z,15Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCC[C@H](O)[C@@H](O)/C=C/C=C/C=C\C=C\[C@@H](O)CCCCC)COC(=O)CCCCCCC)(O)(O)=O NAME: PA(8:0/20:4(7E,9E,11Z,13E)-3OH(5S,6R,15S)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCC)COC(=O)CCCCCCCCC/C=C\CCCCCCCC)(O)(O)=O NAME: PA(20:1(11Z)/16:1(9Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: [C@@H]1(C(C(C([C@H](C1O)O)O)O)O)OP(OC[C@@](COC(CCCCCC/C=C\C/C=C\C/C=C\CCCCC)=O)(OC(CCCCCCCCCCCCCCC)=O)[H])(O)=O NAME: PI(20:3(8Z,11Z,14Z)/16:0) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(O[C@H]1[C@H](O[C@H]2OC([C@@H](O)C(O)[C@H]2O)CO)C(O)[C@H](O)C(O)C1O)(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCC)COC(=O)CCCCCCC/C=C\C/C=C\CCCCCC)(O)=O NAME: PIM1(19:2(9Z,12Z)/16:1(9Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCCCCC\C=C/CCCCCCCC(=O)OCC(COP([O-])([O-])=O)OC(=O)CCCCCCC\C=C/CCCCCCCC NAME: dioleoylphosphatidate(2-) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCCCCCCCCCCCCCC(=O)O[C@H](COC(=O)CCCCCCC\C=C/CCCCCCCC)COP([O-])([O-])=O NAME: 1-oleoyl-2-heptadecanoyl-sn-glycero-3-phosphate(2-) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\CCCCC)(O)(O)=O NAME: PA(15:1(9Z)/21:0) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H]1O[C@@H](N2C=CC(=NC2=O)N)C(O)[C@H]1O)(OP(OC[C@H](OC(=O)CCCCCCCCCCC(CC)C)COC(=O)CCCCCCCCC(CC)C)(O)=O)(O)=O NAME: CDP-DG(a-13:0/a-15:0) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H]1O[C@@H](N2C=CC(=NC2=O)N)C(O)[C@H]1O)(OP(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCC/C=C\C/C=C\CCCCC)(O)=O)(O)=O NAME: CDP-DG(20:2(11Z,14Z)/18:2(9Z,12Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCCCCCCCCCCCCC(=O)OC[C@H](COP([O-])([O-])=O)OC(=O)CCCCCCC\C=C/C\C=C/CCCCC NAME: 1-hexadecanoyl-2-(9Z,12Z-octadecadienoyl)-sn-glycero-3-phosphate(2-) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P1(O[C@H]2[C@H](O)[C@@H](O)[C@H](O)[C@H]([C@@H](O)C[C@@H](O)[C@@H]([C@@H](O)[C@H]2O)/C=C/[C@@H](O)CCCCC)CC(=O)CCCCC(O[C@@H](CO1)COC(=O)CCCCCCC/C=C\CCCCCC)=O)(O)=O NAME: PI(16:1(9Z)/6 keto-PGF1alpha) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: CCCCCCCCCCCCCCCCCC(=O)OC[C@H](COP(O)(=O)O[C@@H]1[C@H](O)[C@H](O)[C@@H](OP(O)(O)=O)[C@H](OP(O)(O)=O)[C@H]1O)OC(=O)CCC\C=C/C\C=C/C\C=C/C\C=C/CCCCC NAME: 1-stearoyl-2-arachidonoyl-sn-glycero-3-phospho-1D-myo-inositol 4,5-biphosphate REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OCC(OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O NAME: 3-(Phosphonooxy)-1,2-propanediyl dioctadecanoate REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(O[C@H]1[C@H](O[C@H]2OC([C@@H](O)C(O)[C@H]2O)CO)C(O)[C@H](O)C(O)C1O)(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)=O NAME: PIM1(18:1(9Z)/16:2(9Z,12Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC1C(O)C(O)C(O)[C@@H](O)C1O)(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCC)COC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)=O NAME: PI(22:4(7Z,10Z,13Z,16Z)/17:2(9Z,12Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O NAME: PA(18:0/18:3(9Z,12Z,15Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC1C(O)C(O)C(O)[C@@H](O)C1O)(OC[C@H](OC(=O)CCC(O)/C=C/C(O)=O)COC(=O)CCCCCCCCCCCCCCC)(O)=O NAME: PHHdiA-PI REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: O([C@@H]1[C@@H]([C@@H]([C@H]([C@@H]([C@H]1O[C@@H]2[C@H]([C@H]([C@@H]([C@H](O2)COC(=O)CCCCCCCCCCCCCCC)O)O)O)OC(CCCCCCCCCCCCCCC)=O)O)O)O[C@@H]3[C@H]([C@H]([C@@H]([C@H](O3)CO)O)O)O)P(=O)([O-])OC[C@@H](COC(CCCCCCCC[C@H](CCCCCCCC)C)=O)OC(CCCCCCCCCCCCCCC)=O NAME: 2-O-alpha-D-mannosyl-1-O-{1-O-[(10S)-10-methyloctadecanoyl]-2-O-palmitoyl-sn-glycero-3-phosphonato}-5-O-palmitoyl-6-O-(6-O-palmitoyl-alpha-D-mannosyl)-1D-myo-inositol REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P1(OC[C@H]2O[C@@H](N3C=CC(=NC3=O)N)[C@H]([C@@H](O)C[C@@H](O)[C@@H]([C@H](O)[C@@H]2O)/C=C/[C@@H](O)CCCCC)CCCCCCC(OC[C@@H](OC(=O)CCCCCCCCCCCCCCCCC(CC)C)COP(O1)(O)=O)=O)(O)=O NAME: CDP-DG(PGF1alpha/a-21:0) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: [C@@H]1(C(C(C([C@H](C1O)O)O)O)O)OP(OC[C@@](COC(CCCC/C=C\C/C=C\C/C=C\CCCCC)=O)(OC(CCCCCCCC/C=C\C/C=C\C/C=C\CCCCC)=O)[H])(O)=O NAME: PI(18:3(6Z,9Z,12Z)/22:3(10Z,13Z,16Z)) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O NAME: PA(14:0/12:0) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
 * SMILES: P1(O[C@@H]2[C@H](O)[C@H](O)[C@H]([C@H](O)CC(=O)[C@@H]([C@@H](O)[C@H](O)[C@H]2O)CC=CCCCC(OC[C@@H](OC(=O)CCCCCCCCCCCCCCCCC)CO1)=O)/C=C/[C@@H](O)CCCCC)(O)=O NAME: PI(PGE2/18:0) REASON: WRONGLY CLASSIFIED Contains glycerol-phosphate moiety with 2 fatty acid chains
False negatives: SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(8:0/8:0) REASON: MISSED Molecular weight may be too low for phosphatidylglycerol
 * SMILES: P(OC[C@H](OC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCCCC)(OCCN)(O)=O NAME: PE(20:0/22:5(7Z,10Z,13Z,16Z,19Z)) REASON: MISSED Molecule appears to be a phosphatidylcholine or phosphatidylethanolamine
 * SMILES: CCCCCC(=O)OC[C@H](COP(O)(=O)OC[C@@H](O)CO)OC(=O)CCCCC NAME: 1,2-dihexanoyl-sn-glycero-3-phospho-(1'-sn-glycerol) REASON: MISSED Molecular weight may be too low for phosphatidylglycerol
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:17517
  name: phosphatidylglycerol
  definition: A glycerophosphoglycerol that is glycerol in which the hydrogen of one
    of the primary hydroxy groups has been replaced by a phosphatidyl group.
  parents:
  - CHEBI:24360
  xrefs:
  - KEGG:C00344
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: unterminated string literal (detected at line 31) (<string>, line 31)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []