Attempt 2 at monoterpenoid indole alkaloid, f1=0.0
(currently fails to compile, but committing anyway

Below is one possible answer. Note that any heuristic will have shortcomings. In the code below I first try to “extract” the tryptophan‐derived indole ring from the molecule (using one or two SMARTS patterns) and then examine the remaining “non‐indole” fragment. The idea is that many monoterpenoid indole alkaloids are built by covalently joining an indole unit (roughly 8–9 C atoms) with a diisoprenoid (monoterpene) fragment (roughly 8–15 C atoms) while the whole molecule has a total of about 20–35 carbons, at least 2 nitrogen atoms, and a molecular weight between about 250 and 600 Da. (You may need to adjust these cutoffs; there is no perfect answer.)

Below is the complete python code in a single code block.

------------------------------------------------

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.11836115326251896 is too low.
Outcomes:
------

True positives: SMILES: COC(=O)C1=CO[C@@H](C)[C@H]2CN3CCc4c([nH]c5ccc(OC)cc45)[C@@H]3C[C@H]12 NAME: Cabucine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: CCC1=C(CC(=O)OC)C(C=2C3=C(C=CN2)C4=CC=CC=C4N3)(OC)OC1=O NAME: O-methylgeissolaevine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: COC(=O)C1=CO[C@@H](C)[C@@H]2CN3CCc4c([nH]c5ccc(OC)cc45)[C@@H]3C[C@H]12 NAME: Aricine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C=C[C@]1(CN2CCC=3C=4C=CC(=CC4NC3[C@@]2(C[C@@]1(C[C@@]5(C6=C(CCN5C)C7=CC=CC=C7N6)[H])[H])[H])O)[H] NAME: 11-hydroxyusambarine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: COC(C1=CO[C@]([C@]2([C@@]1(C[C@@]34C5=C(CCN4C[C@]2(O3)[H])C6=CC=CC=C6N5)[H])[H])(OC7C(C(C(C(CO)O7)O)O)O)[H])=O NAME: cadambine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C=1C=CC=2NC=3[C@]4(N(CCC3C2C1)C[C@@]5([C@@](C(=CO[C@H]5C)C(OC)=O)(C4)[H])[H])[H] NAME: tetrahydroalstonine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C1=CC2=C(C=C1)C(CCN3C=C(CCC3)CC)=C(N2)C(C(OC)=O)=C NAME: secodine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C[C@H]1[C@@H]2CN3CCC4=C(C3C[C@@H]2C(=CO1)C(=O)OC)NC5=CC=CC=C45 NAME: LSM-6418 REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: CC[C@@H]1CN2CCc3c([nH]c4cccc(OC)c34)[C@@H]2C[C@@H]1\C(=C/OC)C(=O)OC NAME: Mitragynine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C/C=C\1/CN2CCC=3C=4C=C(C=CC4NC3C2CC1CCO)O NAME: 10-hydroxygeissoschizol REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C12=C(C=CC=C1)NC=3[C@]([C@@]4(C(=C[NH+](CC4)CCC32)CC)[H])(C(=O)OC)COC(C)=O NAME: dihydroprecondylocarpine acetate (enamine form) REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C(=C\1/CN2CCC3=C([C@@]2(C[C@@]1(CC=4C5=C(C=6C=CC=CC6N5)C=CN4)[H])[H])NC=7C=CC(=CC37)O)\C NAME: 10-hydroxyusambarensine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C=C[C@]1(CN2CCC=3C4=CC=CC=C4NC3[C@@]2(C[C@@]1(/C(=C(\OC)/[H])/C(=O)OC)[H])[H])[H] NAME: Corynantheine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C[C@@H]1[C@@H](C=O)[C@@]2(C[C@]3(C4=C(CCN3C(C2=CO1)=O)C5=CC=CC=C5N4)[H])[H] NAME: Naucleidinal REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C12=C(C=CC=C1)NC=3[C@H]([C@@]4(/C(/CN(CC4)CCC32)=C\C)[H])C(=O)OC NAME: (16S)-deshydroxymethyl-stemmadenine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C(OC)(=O)C=1[C@]2(C[C@@]3(C4=C(C5=C(N4)C=C(C(=C5)OC)OC)CCN3C[C@]2([C@@H](OC1)C)[H])[H])[H] NAME: reserpiline REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C/C=C\1/CN(C)C[C@]2(CC=3C4=CC=CC=C4NC3C(C[C@@]12[H])=O)[H] NAME: Methuenine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: COC(=O)C1=CO[C@H](C)C2=CN3CCc4c([nH]c5ccccc45)[C@@H]3C[C@H]12 NAME: 19-epi-Cathenamine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C/C=C\1/CN(C)[C@@]2(C(=C)[C@]1(CC(C3=C2C4=CC=CC=C4N3)=O)[H])[H] NAME: Ervitsine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C/C=C\1/C[N+]2(C)CCC=3C4=CC=CC=C4NC3[C@@]2(C[C@@]1(CC=5C6=C(C=CN5)C7=CC=CC=C7N6)[H])[H] NAME: Nb-methylusambarensine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C12=C(C=CC=C1)NC=3[C@@H]([C@@]4(/C(/CN(CC4)CCC32)=C\C)[H])C(=O)OC NAME: (16R)-deshydroxymethyl-stemmadenine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C/C=C\1/C[N+]2(C)[C@]3(CC=4C5=CC=CC=C5NC4[C@@]2(C[C@@]1(C3C(=O)[O-])[H])[H])[H] NAME: Panarine REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C=C[C@]1(CN2CC[C@]3(C=4C=CC(=CC4N=C3O)O)[C@@]2(C[C@@]1(C[C@]5(C6=C(CCN5C)C7=CC=CC=C7N6)[H])[H])[H])[H] NAME: Strychnofoline REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C=C[C@]1(CN2CC[C@]1(C[C@]2(C3=C(CCO)C4=CC=CC=C4N3)[H])[H])[H] NAME: Cinchonamine HCl REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C/C=C\1/C[N+]=2C=CC=3C=4C=CC=CC4NC3C2CC1CCO NAME: 3,4,5,6-tetradehydrogeissoschizol REASON: CORRECT Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
False positives: SMILES: C1(=C(C=C2C(=C1)C3=C(N2)[C@]4(C[C@@]5(C(=CO[C@H]([C@@]5(CN4CC3)[H])C)C(OCCN(C)C)=O)[H])[H])OC)OC.Cl.Cl NAME: Dimethylaminoethyl reserpilinate dihydrochloride REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: [H]\C(C)=C1/CN2[C@@]3([H])C[C@]1([H])[C@@]([H])(CO)[C@@]2([H])Cc1c3[nH]c2ccccc12 NAME: 10-deoxysarpagine REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N2[C@H](C(=O)N3[C@@]1(O)[C@H](OC)C=4C5=C(C=C(OC)C=C5)NC4[C@H]3C=C(C)C)CCC2 NAME: Rel-(8R)-9-hydroxy-8-methoxy-18-epi-fumitremorgin C REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C\C=C1\CN(C)[C@@H]2Cc3c([nH]c4ccccc34)C(=O)C[C@H]1C2CO NAME: Affinine REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N[C@H](C(=O)N[C@H]1CO)CC=2C3=C(C=CC=C3)NC2C(C=C)(C)C NAME: Rubrumline J REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: CCN(CC)C(=O)N[C@H]1CN([C@@H]2CC3=CNC4=CC=CC(=C34)C2=C1)C NAME: 3-[(6aR,9R)-7-methyl-6,6a,8,9-tetrahydro-4H-indolo[4,3-fg]quinoline-9-yl]-1,1-diethylurea REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: [H][C@@]12CCCN1C(=O)[C@H](Cc1c(CC=C(C)C)[nH]c3ccccc13)NC2=O NAME: tryprostatin B REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N2[C@@]3(C(=O)N[C@@]14[C@H](C(C=5NC6=C(C5C4)C=C7C=CC(OC7=C6)(C)C)(C)C)C3)CCC2 NAME: Asperversiamide D REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N[C@@H](CC2=CNC=3C2=C(N([C@H]1C(C)C)C)C=C4[C@](C(C)C)(CC[C@](C34)(C=C)C)C)CO NAME: Teleocidin B-3 REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: CC1(C)Oc2ccc3c(\C=C4/NC(=O)CNC4=O)c([nH]c3c2C=C1)C(C)(C)C=C NAME: Talathermophilins A REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N[C@H](C(=O)N[C@H]1CC=2C3=C(C(=CC(=C3)CC=C(C)C)C/C=C(\CO)/C)NC2C(C=C)(C)C)C NAME: 30-hydroxyechinulin REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1C(O)=C(C(=O)C(=C1C=2C3=C(C=CC=C3)NC2CC=C(C)C)O)C=4C5=C(C=CC=C5)NC4 NAME: Asterriquinone SU-5228 REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O1C(C(O)C(O)C(O)C1OC2=CC3=C(NC=C3CCNC(=O)/C=C/C4=CC(OC)=C(O)C=C4)C=C2)CO NAME: Nb-trans-Feruloylserotonin glucoside REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: FC=1C(N2C(=O)/C(/C(=O)NC2=O)=C/C=3C=4C(NC3)=CC=CC4)=CC=CC1 NAME: CHEMBL1465537 REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C1=CC=C2C(=C1)C(=CN2)CCNC(=O)C(=CC3=CC=C(O3)C4=CC=C(C=C4)Br)C#N NAME: 3-[5-(4-bromophenyl)-2-furanyl]-2-cyano-N-[2-(1H-indol-3-yl)ethyl]-2-propenamide REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1OC(C=2C3=C(C=CC=C3)NC2)=C(C1=O)C=4C5=C(C=CC=C5)NC4 NAME: Pityrialactone REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: CC(C)[C@@H]1N(C)c2ccc(c3[nH]cc(C[C@@H](CO)NC1=O)c23)C(C)(C)C=C NAME: Pendolmycin REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C/1NC(C(=O)N\C1=C/C=2C3=C(C=C(CC=C(C)C)C=C3)NC2C(C=C)(C)C)=C NAME: Neoechinulin C REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: C1=2C=3C=4[C@](N(C[C@@H](C4)C(N[C@@H](CC)CO)=O)C)(CC1=CNC2C=CC3)[H].C(/C=C\C(O)=O)(O)=O NAME: Methylergonovine Maleate REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N[C@H](C(=O)N[C@H]1CC=2C3=C(C(=CC(=C3)CC=C(C)C)C/C=C(/CO)\C)NC2C(C=C)(C)C)C NAME: 29-hydroxyechinulin REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N2[C@@](OC(C(=C)C)(C)C)(C(=O)NC1=CC=3C4=C(C=CC=C4)NC3C(C=C)(C)C)CCC2 NAME: 9xi-O-2(2,3-dimethylbut-3-enyl)brevianamide Q REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C1N2C(CC3=C(NC4=C3C=CC(OC)=C4)C2C=C(C)C)C(=O)N5C1CCC5 NAME: 12alpha-Fumitremorgin C REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: O=C/1N[C@H](C(=O)N\C1=C/C=2C3=C(C=CC(=C3)C[C@H](OC(=O)C)C(O)(C)C)NC2C(C=C)(C)C)C NAME: Rubrumline C REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: N12C([C@@H](NC([C@@]1(CCC2)[H])=O)CC3=C(NC4=C3C=CC5=C4C=CC(O5)(C)C)C(C=C)(C)C)=O NAME: notoamide E REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
 * SMILES: OC1[C@@]23NC(=O)[C@@]4(N(C2=O)CCC4)CC3C(C=5NC6=C(C15)C=CC=7OC(C=CC67)(C)C)(C)C NAME: Notoamide R_130070 REASON: WRONGLY CLASSIFIED Contains indole moiety, diisoprenoid fragment, and typical molecular properties for a monoterpenoid indole alkaloid
False negatives: SMILES: CC[C@]1(CN2CCC=3C4=CC(=C(C=C4NC3[C@@]2(C[C@@]1(CCO)[H])[H])OC)OC)[H] NAME: Ochropposinine REASON: MISSED No diisoprenoid (monoterpene) fragment found
 * SMILES: C(OC)(=O)[C@H]1[C@]2(C[C@@]3(C4=C(C5=C(N4)C=CC(=C5)OC)CCN3C[C@]2(C[C@H]([C@@H]1OC)OC(=O)C6=CC(OC)=C(C(=C6)OC)OC)[H])[H])[H] NAME: methoserpidine REASON: MISSED No diisoprenoid (monoterpene) fragment found
 * SMILES: C/C=C\1/CN2CCC=3C4=CC=CC=C4N5C3[C@@]2(C[C@@]1([C@H]5C(=O)OC)[H])[H] NAME: Pleiocarpamine REASON: MISSED No indole moiety found
 * SMILES: C/C=C\1/CN2[C@](C[C@@]34C5=CC=CC=C5N6C(C=C[C@@]([C@]1(C[C@@]32[H])[H])([C@@]46[H])[H])=O)([C@@]7(C=C8[C@]/9(C[C@]%10([C@@]%11(CCN%10C\C9=C\CO)C%12=CC=CC=C%12N([C@@]8%11[H])C7=O)[H])[H])[H])[H] NAME: 18-hydroxyisosungucine REASON: MISSED No indole moiety found
 * SMILES: O=C1N2[C@@]3([C@@]4([C@]5([N+](CC4)(C\C(\[C@](C5)(C3=CC1)[H])=C\CO)[O-])[H])C=6C2=CC=CC6)[H] NAME: isostrychnine N-oxide REASON: MISSED No indole moiety found
 * SMILES: C=12[C@@]3([C@H]4[NH+](CC3)C\C(\[C@@](C1C=O)(C4)[H])=C\C)C5=CC=CC=C5N2 NAME: norfluorocurarine REASON: MISSED No indole moiety found
 * SMILES: CC[C@@]12CCCN3C(C=C(C4=CC=CC=C4NC(CC1)=O)[C@@]23O)=O NAME: Leuconolam REASON: MISSED No indole moiety found
 * SMILES: C/C=C\1/CN(C)[C@]2(CC=3C4=CC=CC=C4N(C)C3C(CC1C2C(=O)OC)=O)[H] NAME: Ochropamine REASON: MISSED No indole moiety found
 * SMILES: COC([C@@H]1C[C@@]23CCCN4CCC5(C6=CC=CC=C6N(C(=O)OC)[C@]15CC2)[C@]34[H])=O NAME: Pleiocarpine REASON: MISSED No indole moiety found
 * SMILES: C=C[C@]1(CN2CCC=3C=4C=CC(=C([C@]5(CCCN5C)[H])C4NC3[C@@]2(C[C@@]1(C[C@]6(C7=C(CCN6C)C8=CC=CC=C8N7)[H])[H])[H])O)[H] NAME: Strychnopentamine REASON: MISSED Carbon count of 35 outside typical range (15-30) for monoterpenoid indole alkaloids
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:65323
  name: monoterpenoid indole alkaloid
  definition: A terpenoid indole alkaloid which is biosynthesised from L-tryptophan
    and diisoprenoid (usually secolaganin) building blocks.
  parents:
  - CHEBI:65321
  xrefs:
  - PMID:18280746
  - PMID:20717879
  - PMID:21425787
  - PMID:22679912
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 78
  log_lines_of_code: 4.356708826689592
  indent_by_line:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 1
  - 2
  - 2
  - 1
  - 1
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 1
  - 1
  - 1
  - 2
  - 2
  - 3
  - 3
  - 3
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 3
  - 1
  - 1
  - 2
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 2
  methods_called:
  - CalcExactMolWt
  - GetSSSR
  - GetAtoms
  - HasSubstructMatch
  - MolFromSmarts
  - SanitizeMol
  - GetMolFrags
  - DeleteSubstructs
  - MolFromSmiles
  - GetAtomicNum
  methods_called_count: 10
  smarts_strings:
  - smarts
  smarts_strings_count: 1
  defs:
  - 'is_monoterpenoid_indole_alkaloid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, f"Total carbon count of {total_c} outside expected range (20-35)"
  - False, f"Found only {total_n} nitrogen atoms; expect at least 2"
  - False, f"Molecular weight of {mw:.1f} Da outside expected range (250-600 Da)"
  - False, f"Found only {n_rings} rings; expected at least 3 for complex alkaloids"
  - False, "No indole moiety found"
  - False, "Indole found but could not extract residual fragment"
  - False, f"Largest residual fragment has {max_c} carbons; not typical for a diisoprenoid
    unit"
  - True, ("Contains indole moiety, evidence of a diisoprenoid fragment (after indole
    removal), and " +
  returns_count: 9
  complexity: 5.471341765337918
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "Error executing is_monoterpenoid_indole_alkaloid('CC[C@]1(CN2CCC=3C4=CC(=C(C=C4NC3[C@@]2(C[C@@]1(CCO)[H])[H])OC)OC)[H]'):\n\
  \ '<' not supported between instances of '_vectNSt3__16vectorIiNS_9allocatorIiEEEE'\
  \ and 'int'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0