Attempt 4 at fatty alcohol, f1=0.0
(currently fails to compile, but committing anyway

Below is one solution. I’ll explain my ideas before showing the code.

One problem with the previous version was that it “rejected” any molecule bearing carboxyl groups even though some fatty alcohol structures came along with extra (non‐alcohol) oxygenated groups. Also, by insisting that the “candidate” –OH be attached only to carbons we were (in effect) “locking in” an oversimplified view of what the long (fatty) chain should be. In addition, the DFS that “grew” the fatty chain sometimes underestimated the longest linear carbon stretch (especially when a branch could add extra carbons). Lastly, the minimum acceptable chain length was set too high so that borderline (but acceptable) fatty alcohols – for example, (2S)‐2‐heptanol – were missed.

In the improved solution the changes are:

1. We no longer reject a molecule if it contains other oxygenated groups (e.g. carboxylates).
2. When looking for an alcohol group we still require that a (putative) alcohol carbon must be “acyclic” (i.e. not in a ring) and that the only neighbors apart from the –OH are carbon atoms.
3. We build a “carbon graph” consisting of carbon atoms that are not aromatic and not in a ring. (This now includes both sp³ and non‐aromatic sp² carbons so that unsaturated “fatty” chains count.)
4. We compute the longest simple “chain” (that is, the longest path in that graph starting from the candidate alcohol carbon) using a DFS that explores every branch.
5. We add one more “purity” check: for the candidate chain the carbons should not be “decorated” by extra heteroatoms (other than the –OH on the alcohol carbon). (That is, besides the bonds along the chain, a carbon should not have extra bonds to non‐carbon atoms.)
6. Finally we require that the longest chain has at least MIN_CHAIN_LENGTH atoms (here we set it to 7 so that even (2S)-2-heptanol gets a chance). Then we return a true classification plus a descriptive reason.

Below is the complete single Python code block.

------------------------------------------------

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.1879458794587946 is too low.
Outcomes:
------

True positives: SMILES: CCCCCCC(C)O NAME: octan-2-ol REASON: CORRECT Molecule contains an alcohol group attached to a 7-carbon acyclic aliphatic chain
 * SMILES: O(C(=O)CCCCCCCCCCCCCCCCC)C[C@@H](OC(=O)CC/C=C\C/C=C\C/C=C\C\C=C\C=C\C(O)C/C=C\CC)CO NAME: DG(18:0/22:6(4Z,7Z,10Z,13E,15E,19Z)-OH(17)/0:0) REASON: CORRECT Molecule contains an alcohol group attached to a 17-carbon acyclic aliphatic chain
 * SMILES: CC(C)CCCCCCCCCCCCCCCCCCCO NAME: 20-methylhenicosan-1-ol REASON: CORRECT Molecule contains an alcohol group attached to a 21-carbon acyclic aliphatic chain
 * SMILES: OC(CCCCCCCCCCCCCCC)CC(=O)C1=CC=CC=C1 NAME: 3-Hydroxy-1-phenyl-1-octadecanone REASON: CORRECT Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: C(/C=C(/CCC=C(C)C)\C)C\C(\C)=C\CC\C(\C)=C\CC/C(/C)=C/CC\C(=C\CO)\C NAME: all-trans-hexaprenol REASON: CORRECT Molecule contains an alcohol group attached to a 24-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCCCC(O)CCCC NAME: nonadecan-5-ol REASON: CORRECT Molecule contains an alcohol group attached to a 15-carbon acyclic aliphatic chain
 * SMILES: O=C(OC)[C@@H]1O[C@@H](/C=C/C=C/[C@@H](C/C(=C/C=C/[C@H](CCO)C)/C)C)[C@@]2([C@H]1O2)C NAME: Penitalarin B REASON: CORRECT Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCCC(O)CCCCCCCCCCC NAME: pentacosan-12-ol REASON: CORRECT Molecule contains an alcohol group attached to a 14-carbon acyclic aliphatic chain
 * SMILES: OCCCCCCCCCCCCO NAME: 1,12-dodecanediol REASON: CORRECT Molecule contains an alcohol group attached to a 12-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCO NAME: tricosan-1-ol REASON: CORRECT Molecule contains an alcohol group attached to a 23-carbon acyclic aliphatic chain
 * SMILES: O[C@H](CCCCCCCCCCC(C)C)C NAME: (S)-13-Methyltetradecan-2-ol REASON: CORRECT Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: OC1=CC(O)=CC(=C1)CCCCCCCCCCCCCCC[C@@H](O)C NAME: Hansfordiol A REASON: CORRECT Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: OCCCCCCCCCCCCCC#CCC=C NAME: 17-OCTADECEN-14-YN-1-OL REASON: CORRECT Molecule contains an alcohol group attached to a 18-carbon acyclic aliphatic chain
 * SMILES: CCC(C)CCCCCCCCCCCCCCCCCO NAME: 18-methylicosan-1-ol REASON: CORRECT Molecule contains an alcohol group attached to a 20-carbon acyclic aliphatic chain
 * SMILES: OCCCCCCCC/C=C/C/C=C/C/C=C/CC NAME: 9,12,15-Octadecatrien-1-ol REASON: CORRECT Molecule contains an alcohol group attached to a 18-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCC(O)CCCCCCCC NAME: henicosan-9-ol REASON: CORRECT Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCC(O)CCCCC NAME: tridecan-6-ol REASON: CORRECT Molecule contains an alcohol group attached to a 8-carbon acyclic aliphatic chain
 * SMILES: O=C1O[C@H](CCCCCCCCCC(=O)CC[C@H](O)C)C=2C1=C(OC)C=C(O)C2 NAME: (+)-sporotricale REASON: CORRECT Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: O(CCCCCCCC/C=C/C(O)C#CC#CC(O)C=C)C(=O)C NAME: (9Z,11S,16S)-1-Acetoxy-9,17-octadecadiene-12,14-diyne-11,16-diol REASON: CORRECT Molecule contains an alcohol group attached to a 11-carbon acyclic aliphatic chain
 * SMILES: OCCC\C=C\C=C/CCCCCCCCC NAME: 4E,6Z-Hexadecadien-1-ol REASON: CORRECT Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCCCCCCCCCCC(O)CCCC NAME: hexacosan-5-ol REASON: CORRECT Molecule contains an alcohol group attached to a 22-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCC(O)CCCCCCCCCCCC NAME: pentacosan-13-ol REASON: CORRECT Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCC(O)\C=C/C#CC#CC(O)C=C NAME: Seselidiol REASON: CORRECT Molecule contains an alcohol group attached to a 10-carbon acyclic aliphatic chain
 * SMILES: OC1=CC(O)=CC(=C1)CCCCCCCCCCCCCCCC(O)C(O)CCCCCCCC NAME: SNF-4794-9 REASON: CORRECT Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCC(O)CCC NAME: undecan-4-ol REASON: CORRECT Molecule contains an alcohol group attached to a 8-carbon acyclic aliphatic chain
False positives: SMILES: O=C(O[C@@H]1[C@@H](O[C@@H]2O[C@H]([C@H](O)COC(=O)\C=C/C=C\CCCCC)[C@@H]([C@@H]2O)O)[C@@H](O[C@@H]([C@H]1O)C3=C(O)C=C(O)C=C3CO)CO)\C=C/C=C/C[C@H](O)/C=C/C=C\CCC NAME: Chaetiacandin REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 8-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCC\C=C\[C@@H](O)[C@H](CO[C@@H]1O[C@H](CO)[C@@H](O[C@@H]2O[C@H](CO)[C@H](O)[C@H](O)[C@H]2O)[C@H](O)[C@H]1O)NC(=O)CCCCCCCCCCCCC\C=C/CCCCCCCC NAME: beta-D-galactosyl-(1->4)-beta-D-glucosyl-(1<->1)-N-[(15Z)-tetracosenoyl]sphingosine REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: CC\C=C\C=C(/OC)C(O)C(C)CC(OC)\C=C\C=C\C1OC(=O)C=CC1OC NAME: Pterocidin REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 8-carbon acyclic aliphatic chain
 * SMILES: O1C(CCC1C(O)CCCCCCCCCCCC)C(O)CCCCCC(O)CCCCC2OC(=O)C(C2)CC(=O)C NAME: Isoannoreticuin REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: O[C@H](CO)CC#CC#C/C=C/CO NAME: 8(E)-decene-4,6-diyn-1,2,10-triol REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 9-carbon acyclic aliphatic chain
 * SMILES: C(C[C@@H](C[C@@H](CC(/C=C/C=C/C=C/CCCCC)=O)O)O)(=O)[H] NAME: virensol D REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: C[C@@H]1[C@H](CC2(C([C@@H](C(O2)[C@@H](C[C@H]([C@@H](C)[C@H]([C@@H](C)C=C(C)C(=CC=CC(=CC#N)C)C)O)O)OC)OP(=O)(O)O)(C)C)O[C@@H]1CC=CC3=COC(=N3)[C@H](C)CCNC(=O)[C@@H]([C@@H]([C@@H](COC)N(C)C)O)O)O NAME: [(3S,7R,8R,9S)-2-[(1R,3R,4R,5S,6S)-14-cyano-3,5-dihydroxy-1-methoxy-4,6,8,9,13-pentamethyltetradeca-7,9,11,13-tetraenyl]-7-[3-[2-[(2R)-4-[[(2R,3R,4R)-4-(dimethylamino)-2,3-dihydroxy-5-methoxy-1-oxopentyl]amino]butan-2-yl]-4-oxazolyl]prop-2-enyl]-9-hydroxy-4,4,8-trimethyl-1,6-dioxaspiro[4.5]decan-3-yl] dihydrogen phosphate REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: O=C(N[C@H](C(=O)NC(OC)CC(C)C)CCC(=O)N)[C@@H](NC(=O)C[C@H](O)CCCCCCCCC)CC(=O)N NAME: Penicimutalide C/D REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 10-carbon acyclic aliphatic chain
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCC(=O)NC(CO)CCCCCCCCCC NAME: N-(1-hydroxydodecan-2-yl)tetracosanamide REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 12-carbon acyclic aliphatic chain
 * SMILES: Cl/C=C(\C[C@H](O)CC[C@H](C[C@H]([C@H](O)CCCC[C@H]([C@H](O)CC=C)C)C)C)/CCCC#C NAME: Trichophycin H REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: O=C1N[C@@H](CC2=CC=C(O)C=C2)C(C1=C(O)/C=C/C(=C/[C@@H]([C@@H](O)C)C)/C)=O NAME: Syn-12-hydroxypretenellin A REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 7-carbon acyclic aliphatic chain
 * SMILES: CC(C)\C=C(/C)[C@H](O)[C@H](C)\C=C(C)\C=C\C=C/C=C/C=C(\C)C(=O)N[C@@H](C)CO NAME: Myxalamid B REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 13-carbon acyclic aliphatic chain
 * SMILES: O=C(N[C@H]([C@H](O)/C=C/CC/C=C(/CCCCCCCCC)\C)CO)[C@H](O)CCCCCCCCCCCCCC NAME: (2S,2′R,3R,4E,8E)-N-2′-hydroxyhexadecanoyl-2-amino-9-methyl-4,8-octadecadiene-1,3-diol REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: OC1=CC=C(C[C@@H](NC)[C@H](O)CC/C=C/[C@H](C[C@H](CC)C)C)C=C1 NAME: Tyroscherin REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 10-carbon acyclic aliphatic chain
 * SMILES: CO[C@H]([C@H](O)CC(=O)[C@@H](C)[C@@H](O)CC[C@@H](C)[C@@H]1O[C@]2(CC[C@@H](C)[C@H](CC[C@H](C)C(C)=O)O2)CC[C@@H]1C)[C@H](OC(=O)C[C@@H](O)C1=C(C)C(=O)OC1=O)C(C)C NAME: Tautomycin REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 9-carbon acyclic aliphatic chain
 * SMILES: O=C(O[C@@H]1C([C@H]2[C@](C=3C([C@]4([C@]([C@@H]([C@@H](CC/C=C(/CO)\C)C)CC4)(C)CC3)C)=CC2)(C)CC1)(C)C)C NAME: 3-acetyl-ganodermadiol REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 7-carbon acyclic aliphatic chain
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCCCCC[C@@H](O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12 NAME: (3R,17Z,20Z,23Z,26Z)-3-hydroxydotriacontatetraenoyl-CoA REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 30-carbon acyclic aliphatic chain
 * SMILES: O=C(OCC(O)C(O)C(O)CO)/C(=C/C(C(O)/C(=C/C(C(O)/C(=C/C(C(O[C@@H]1O[C@@H]([C@@H](O)[C@@H]([C@@H]1O)O)CO)/C(=C/C(CC(CC)C)C)/C)C)/C)C)/C)C)/C NAME: Bionectriol A REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 16-carbon acyclic aliphatic chain
 * SMILES: O=C1OC(C2=C(O)C=CC(=C2)O)C=C1CC/C=C(/C(O)C/C=C(/COC(=O)/C=C/C3=CC=C(O)C=C3)\C)\CO NAME: Zizhine H REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 7-carbon acyclic aliphatic chain
 * SMILES: O=C1N[C@@H](C(=O)NCC(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(N[C@@H](CC(N[C@@H](C(N[C@@H]1[C@H](O)C2=CC=C(O)C=C2)=O)CO)=O)C[C@@H](O)[C@@H](O)[C@@H](O[C@@H]3OC[C@@H](O)[C@@H]([C@H]3O)O)CCCCCCCCCCC)=O)[C@H](O)C(=O)N)CO)CC(=O)N)CCN NAME: Burkholidine 1215 REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 14-carbon acyclic aliphatic chain
 * SMILES: O1C(O[C@H](C(O)(C)C)CC/C(=C/C=C/C(=C/C=C/C(=C/C=C/C=C(/C=C/C=C(/C=C/C2=C(C[C@@H](O)CC2(C)C)C)\C)\C)/C)/C)/C)[C@@H](O)[C@H](O)[C@@H]([C@@H]1C)O NAME: (3R,2'S)-myxol 2'-fucoside REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 24-carbon acyclic aliphatic chain
 * SMILES: CC[C@H](OC)[C@H](C)CCCC[C@@H](O)C[C@@H](O)CCCCCCCCCCCCCCCCCCc1ccc(O[C@@H]2O[C@@H](C)[C@H](O)[C@@H](OC)[C@H]2O[C@@H]2O[C@@H](C)[C@H](O[C@H]3O[C@H](COC)[C@@H](O)[C@H](OC)[C@H]3O)[C@@H](OC)[C@H]2OC)cc1 NAME: 4-(18,20-dihydroxy-26-methoxy-25-methyloctacosyl)phenyl 3,6-di-O-methyl-beta-D-Glc-(1->4)-2,3-di-O-methyl-alpha-L-Rha-(1->2)-3-O-methyl-alpha-L-Rha REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 21-carbon acyclic aliphatic chain
 * SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C=C\[C@H](O)CC)COC(=O)CCCCCCCCCCCCCC)(OCCN)(O)=O NAME: PE(15:0/20:5(5Z,8Z,11Z,14Z,16E)-OH(18R)) REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 18-carbon acyclic aliphatic chain
 * SMILES: O=C1C(OC)=C(OC)NC(=C1C)C/C=C(/C/C(=C/C(=C/C(C(O)/C(=C/C(=C/C)/C)/C)C)/C)/C)\C NAME: IT-143-A REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 10-carbon acyclic aliphatic chain
 * SMILES: O=[N+]([O-])/C(=C(/C=C/C=C\C=C(/C(O)C(C(=O)NC/C=C/C=C/C(O)C(CC(OC)C1(O)C2(N(C)C(C1C)=O)C(=O)OC2C)C)(C)C)\C)\C)/C NAME: Lajollamycin REASON: WRONGLY CLASSIFIED Molecule contains an alcohol group attached to a 10-carbon acyclic aliphatic chain
False negatives: SMILES: O=C1O[C@@H](CCCCCCCCCCCCC[C@H](O)C)[C@H](C1=C)C(=O)O NAME: Allo-murolic acid REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: O=C1OC(C(O)C(=O)O)C(C1=C(O)C(O)C(O)CCCCCCCCCCC)=O NAME: F-36316 C REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: O=C(OC(C(O)C(O)C(=O)O)CO)C(C(=O)/C(=C/C(CC(CCCCC(O)CCCCCCCCCCC)C)C)/C)C NAME: Haplofungin A REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: CCCCC[C@H](C)O NAME: (2S)-2-heptanol REASON: MISSED Longest aliphatic chain starting from an alcohol carbon is only 6 atoms (need at least 7)
 * SMILES: CCCCCC(O)C=C NAME: oct-1-en-3-ol REASON: MISSED Longest aliphatic chain starting from an alcohol carbon is only 6 atoms (need at least 7)
 * SMILES: O=C(O[C@@H]([C@@H](/C=C(/[C@@H](O)C/C=C/C=C/C=C/C[C@@H](O)[C@@H](O)CC)\C)C)C)CCC(=O)O NAME: Succinilene B REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: O=C(O)C1=C(O)C=C(O)C=C1CCCCCCCCCCC[C@@H](O)CCCCC NAME: Penixylarin C REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: O=C(O[C@@H]([C@@H](/C=C(/[C@@H](O)C/C=C/C=C/C=C/C[C@@H](O)C(=O)CC)\C)C)C)CCC(=O)O NAME: Succinilene C REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: O=C(O)C1=C(O)C=CC=C1CCCCCCC/C=C\C/C=C\C[C@H](O)CCC NAME: 2-hydroxy-6-((R,8Z,11Z)-14-hydroxyheptadeca-8,11-dien-1-yl)benzoic acid REASON: MISSED Molecule contains a carboxylic acid/carboxylate group
 * SMILES: Clc1c2COC(=O)c2c(Cl)c(Cl)c1Cl NAME: 4,5,6,7-tetrachloro-2-benzofuran-1(3H)-one REASON: MISSED No alcohol (-OH) group found on a saturated carbon
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:24026
  name: fatty alcohol
  definition: An aliphatic alcohol consisting of a chain of 3 to greater than 27 carbon
    atoms. Fatty alcohols may be saturated or unsaturated and may be branched or unbranched.
  parents:
  - CHEBI:30879
  - CHEBI:61697
  xrefs:
  - LIPID_MAPS_class:LMFA05
  - MetaCyc:Fatty-Alcohols
  - Wikipedia:Fatty_alcohol
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 127
  log_lines_of_code: 4.844187086458591
  max_indent: 6
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - append
  - GetIdx
  - GetIsAromatic
  - GetAtomicNum
  - MolFromSmiles
  - GetAtomWithIdx
  - GetAtoms
  - MolFromSmarts
  - get
  - GetNeighbors
  - add
  - HasBondBetween
  - IsInRing
  - GetSubstructMatches
  methods_called_count: 14
  smarts_strings:
  - alcohol_smarts
  smarts_strings_count: 1
  defs:
  - 'is_fatty_alcohol(smiles: str):'
  - 'dfs_longest(current, visited):'
  - 'chain_is_pure(chain):'
  defs_count: 3
  returns:
  - False, "Invalid SMILES string"
  - "False, \"No proper alcohol (-OH) group found on a non\u2010ring carbon\""
  - best_path
  - 'False'
  - 'True'
  - True, candidate_reason
  - False, (f"Longest acyclic aliphatic chain from any candidate alcohol group is
    only "
  returns_count: 7
  complexity: 6.968837417291718
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: "Error executing is_fatty_alcohol('CCCCCCC(C)O'):\n 'Atom' object has no attribute\
  \ 'HasBondBetween'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []