Reverting to best solution for quaternary ammonium ion, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:35267
  name: quaternary ammonium ion
  definition: A derivative of ammonium, NH4(+), in which all four of the hydrogens
    bonded to nitrogen have been replaced with univalent (usually organyl) groups.
  parents:
  - CHEBI:25697
  - CHEBI:35274
  xrefs:
  - KEGG:C06703
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 23
  log_lines_of_code: 3.1354942159291497
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdqueries
  imports_count: 2
  methods_called:
  - GetAtomWithIdx
  - MolFromSmiles
  - GetNeighbors
  - AtomIsAliphaticNitrogen
  - AtomIsPositivelyCharged
  - GetSubstructMatches
  methods_called_count: 6
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_quaternary_ammonium_ion(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No quaternary nitrogen found"
  - False, "Quaternary nitrogen does not have 4 substituents"
  - True, "Contains a positively charged quaternary nitrogen with 4 substituents"
  returns_count: 4
  complexity: 3.42709884318583
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_quaternary_ammonium_ion('P(OCC[N+](C)(C)C)(OC[C@H](OC(=O)CCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\\\
  \\CCCCCCC)([O-])=O'):\n module 'rdkit.Chem.rdqueries' has no attribute 'AtomIsPositivelyCharged'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0