Reverting to best solution for guaiacols, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:134251
  name: guaiacols
  definition: Any phenol carrying an additional methoxy substituent at the ortho-position.
  parents:
  - CHEBI:25235
  - CHEBI:33853
  xrefs:
  - MetaCyc:Guaiacols
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 23
  log_lines_of_code: 3.1354942159291497
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - HasSubstructMatch
  - MolFromSmarts
  - MolFromSmiles
  methods_called_count: 3
  smarts_strings:
  - c1([OH])c([OCH3])ccccc1
  smarts_strings_count: 1
  defs:
  - 'is_guaiacol(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - None, "Invalid SMARTS pattern"
  - True, "Has Guaiacol substructure"
  - False, "Does not have Guaiacol substructure"
  returns_count: 4
  complexity: 2.6270988431858298
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0