Reverting to best solution for phytosterols, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:26125
  name: phytosterols
  definition: Sterols similar to cholesterol which occur in plants and vary only in
    carbon side chains and/or presence or absence of a double bond.
  parents:
  - CHEBI:15889
  - CHEBI:26124
  xrefs:
  - Wikipedia:Phytosterol
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 26
  log_lines_of_code: 3.258096538021482
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmiles
  - MolFromSmarts
  - HasSubstructMatch
  - GetSubstructMatches
  methods_called_count: 4
  smarts_strings:
  - '[C]1[C]([C])([H])[C]([H])([C]([H])([H])[C]2([C]([H])([H])[C]3([C]([H])([H])[C]([H])([C]([H])([H])[C]4([C]([H])([H])[C]([H])([C]([H])(O)[C]([H])([H])[C]14)[C]([H])([H])[H])[C]23)[H])([H])[H])'
  - '[OX2H1]'
  smarts_strings_count: 2
  defs:
  - 'is_phytosterols(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Does not have the core steroid structure"
  - False, f"Must have exactly 1 hydroxyl group, found {len(hydroxyl_matches)}"
  - True, "Has core steroid structure with a single hydroxyl group"
  returns_count: 4
  complexity: 2.851619307604296
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_phytosterols('OC1CC2[C@@](C3C(C4[C@@](C(CC4)[C@@H](CCCC(C)C)C)(CC3)C)CC2)(CC1)C'):\n\
  \ Python argument types in\n    Mol.HasSubstructMatch(Mol, NoneType)\ndid not match\
  \ C++ signature:\n    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle query,\
  \ RDKit::SubstructMatchParameters params=True)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False,\
  \ bool useQueryQueryMatches=False)\n    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol\
  \ query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0