Reverting to best solution for thiosugar, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:73754
  name: thiosugar
  definition: A carbohydrate derivative in which one or more of the oxygens or hydroxy
    groups of the parent carbohydrate is replaced by sulfur or -SR, where R can be
    hydrogen or any group.
  parents:
  - CHEBI:33261
  - CHEBI:63299
  xrefs:
  - PMID:16240117
  - PMID:23330717
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 28
  log_lines_of_code: 3.332204510175204
  max_indent: 3
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdqueries
  imports_count: 3
  methods_called:
  - HasSubstructMatch
  - MolFromSmarts
  - GetIdx
  - GetAtoms
  - MolFromSmiles
  - GetAtomicNum
  methods_called_count: 6
  smarts_strings:
  - '[C;X4;R][S;X2]'
  - '[C;X4;R][C;X4;R][C;X4;R]'
  smarts_strings_count: 2
  defs:
  - 'is_thiosugar(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No carbohydrate backbone found"
  - False, "No sulfur atoms found"
  - True, "Molecule contains a sulfur atom replacing an oxygen or hydroxy group in
    the carbohydrate backbone"
  - False, "Sulfur atom(s) not directly attached to the carbohydrate backbone"
  returns_count: 5
  complexity: 3.6664409020350406
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Python argument types in\n    Mol.HasSubstructMatch(Mol, Mol)\ndid not match\
  \ C++ signature:\n    HasSubstructMatch(RDKit::ROMol self, RDKit::MolBundle query,\
  \ RDKit::SubstructMatchParameters params=True)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False,\
  \ bool useQueryQueryMatches=False)\n    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol\
  \ query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0