Reverting to best solution for aromatic amino acid, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:33856
  name: aromatic amino acid
  definition: An amino acid whose structure includes an aromatic ring.
  parents:
  - CHEBI:33659
  - CHEBI:33709
  xrefs:
  - KEGG:C01021
  - Wikipedia:Aromatic_amino_acid
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 26
  log_lines_of_code: 3.258096538021482
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - GetSubstructMatches
  - GetAromaticRingsAsMol
  - Mol
  - MolFromSmarts
  - GetRingInfo
  - AtomRings
  - MolFromSmiles
  - HasRingOnRing
  methods_called_count: 8
  smarts_strings:
  - C(=O)O
  - N
  smarts_strings_count: 2
  defs:
  - 'is_aromatic_amino_acid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Missing amino acid functional groups"
  - False, "No aromatic rings found"
  - True, "Contains amino acid functional groups and aromatic ring(s)"
  returns_count: 4
  complexity: 3.651619307604297
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0