Attempt 4 at tetraterpenoid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: O(C(CCC/C(=C/C=C/C(=C/C=C/C(=C/C=C/C=C(/CC/C=C(/CC/C=C(/CCC=C(C)C)\C)\C)\C)/C)/C)/C)(C)C)C NAME: 3,4,11′,12′-tetrahydrospheroidene REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: O[C@@]1(C(C[C@H](O)C[C@]1(O)C)(C)C)/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C=C(/C=C/C=C(/C=C/[C@@]2(O)C(C[C@H](O)C[C@]2(O)C)(C)C)\C)\C NAME: Mactraxanthin REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: O=C(OCC1OC(O[C@@H]2CC(=C(/C=C/C(=C/C=C/C(=C/C=C/C=C(/C=C/C=C(/C=C/C3=C(CCCC3(C)C)C)\C)\C)/C)/C)C(C2)(C)C)C)C(O)C(C1O)O)CCCCCCCCCCCC(C)C NAME: C1-15 thermocryptoxanthin-15 REASON: MISSED Number of carbon atoms (61) outside expected range for tetraterpenoids (40-60)
 * SMILES: O=C1CC(C(C(=C1)C)\C=C\C(\C)=C\C=C\C(\C)=C\C=C\C=C(\C=C\C=C(\C=C\C2C(CC(=O)C=C2C)(C)C)/C)/C)(C)C NAME: e,e-carotene-3,3'-dione REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: OC([C@@H](CC=C(C)C)/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C=C(/C=C/C=C(/C=C/C=C(/C=C/C=C(C)C)\C)\C)\C)(C)C NAME: (3S,4E,6E,8E,10E,12E,14E,16E,18E,20E,22E,24E,26E,28E)-2,6,10,14,19,23,27,31-octamethyl-3-(3-methylbut-2-enyl)dotriaconta-4,6,8,10,12,14,16,18,20,22,24,26,28,30-tetradecaen-2-ol REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: O[C@H]1CC(C(=C(C1)C)/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C=C(/C=C/C=C(\C=C\C=2C(C[C@H](O)CC2C)(C)C)/C)\C)(C)C NAME: (3R,3'R,9-cis)-b,b-Carotene-3,3'-diol REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: CC(\C=C\C=C(C)\C=C\C1=C(C)C[C@@H](O)CC1(C)C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/[C@@]12O[C@]1(C)C[C@@H](O)CC2(C)C NAME: antheraxanthin REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: O=C1C(=C(/C=C/C(=C/C=C/C(=C/C=C/C=C(/C=C/C=C(/C=C/C=C(/C=C/[C@H](O)C(O[C@H]2O[C@H]([C@H](O)[C@H]([C@@H]2O)O)COC(=O)CCCCCCCCCCCC(C)C)(C)C)\C)\C)\C)/C)/C)C(C)(C)CC1)C NAME: Salinixanthin REASON: MISSED Number of carbon atoms (61) outside expected range for tetraterpenoids (40-60)
 * SMILES: CCC(C)CCCCCCCCCCC(=O)OC[C@H]1O[C@@H](OC(=O)C(\C)=C\C=C\C(C)=C\C=C\C(C)=C\C=C\C=C(C)\C=C\C=C(/C)CCC=C(C)C)[C@H](O)[C@@H](O)[C@@H]1O NAME: staphyloxanthin REASON: MISSED Fewer than 8 isoprene units detected
 * SMILES: C[C@@H]1O[C@@H](O[C@@H](\C=C\C(C)=C\C=C\C(C)=C\C=C\C(C)=C\C=C\C=C(C)\C=C\C=C(C)\C=C\C2=C(C)CCCC2(C)C)C(C)(C)O)[C@@H](O)[C@H](O)[C@@H]1O NAME: (2'S)-Deoxymyxol 2'-alpha-L-fucoside REASON: MISSED Fewer than 8 isoprene units detected
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:26935
  name: tetraterpenoid
  definition: Any terpenoid derived from a tetraterpene. The term includes compounds
    in which the C40 skeleton of the parent tetraterpene has been rearranged or modified
    by the removal of one or more skeletal atoms (generally methyl groups).
  parents:
  - CHEBI:26873
  xrefs:
  - LIPID_MAPS_class:LMPR0107
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: "invalid character '\u2032' (U+2032) (<string>, line 7)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []