Reverting to best solution for primary alcohol, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:15734
  name: primary alcohol
  definition: A primary alcohol is a compound in which a hydroxy group, -OH, is attached
    to a saturated carbon atom which has either three hydrogen atoms attached to it
    or only one other carbon atom and two hydrogen atoms attached to it.
  parents:
  - CHEBI:30879
  xrefs:
  - KEGG:C00226
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 22
  log_lines_of_code: 3.091042453358316
  max_indent: 4
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmiles
  - GetTotalNumHs
  - GetAtoms
  - GetNeighbors
  - GetSymbol
  methods_called_count: 5
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_primary_alcohol(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - True, "Contains a primary alcohol group (-OH attached to a saturated carbon atom
    with either three hydrogen atoms or one other carbon atom and two hydrogen atoms)"
  - False, "Does not contain a primary alcohol group"
  returns_count: 3
  complexity: 3.218208490671663
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: unterminated string literal (detected at line 1) (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0