Reverting to best solution for N-hydroxy-alpha-amino-acid, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:50760
  name: N-hydroxy-alpha-amino-acid
  definition: Any amino acid in which at least one hydrogen attached to the amino
    group is replaced by a hydroxy group.
  parents:
  - CHEBI:24662
  - CHEBI:24709
  xrefs:
  - KEGG:C05710
  all_positive_examples: []
config: null
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: '(unicode error) ''unicodeescape'' codec can''t decode bytes in position 7-8:
  malformed \N character escape (<string>, line 31)'
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0