Attempt 1 at N-sulfonylurea, f1=0.0
(currently fails to compile, but committing anyway

None
# INFORMATION:

---
chemical_class:
  id: CHEBI:76983
  name: N-sulfonylurea
  definition: A urea in which one of the hydrogens attached to a nitrogen of the urea
    group is replaced by a sulfonyl group. The N-sulfonylurea moiety is a key group
    in various herbicides, as well as in a number of antidiabetic drugs used in the
    management of type 2 diabetis mellitus.
  parents:
  - CHEBI:35358
  - CHEBI:47857
  xrefs:
  - PMID:23237384
  - PMID:23594109
  - PMID:23609875
  - Wikipedia:Sulfonylurea
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: false
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []