Reverting to best solution for thiosugar, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:73754
  name: thiosugar
  definition: A carbohydrate derivative in which one or more of the oxygens or hydroxy
    groups of the parent carbohydrate is replaced by sulfur or -SR, where R can be
    hydrogen or any group.
  parents:
  - CHEBI:33261
  - CHEBI:63299
  xrefs:
  - PMID:16240117
  - PMID:23330717
  all_positive_examples: []
config: null
code_statistics: null
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: '''QueryAtom'' object has no attribute ''SetQueryAtomProp'''
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0