Reverting to best solution for flavonols, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:28802
  name: flavonols
  definition: Any hydroxyflavone in which is the ring hydrogen at position 3 of the
    heterocyclic ring is replaced by a hydroxy group.
  parents:
  - CHEBI:192499
  - CHEBI:24698
  xrefs:
  - MetaCyc:Flavonols
  - Wikipedia:Flavonol
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 22
  log_lines_of_code: 3.091042453358316
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmiles
  - MolFromSmarts
  - HasSubstructMatch
  methods_called_count: 3
  smarts_strings:
  - '[c1]2[c]([c]([c]([o]2)[OH])[O])-[c]([c]([c]1=O)[O])'
  - '[c1]2[c]([c]3[c]([c]([c]2[o]1)[O])[O])-[c]([c]([c]3=O)[O])'
  smarts_strings_count: 2
  defs:
  - 'is_flavonol(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Not a flavonoid (missing benzopyran backbone)"
  - False, "No hydroxy group at position 3 of heterocyclic ring"
  - True, "Contains a hydroxyflavone backbone with a hydroxy group at position 3"
  returns_count: 4
  complexity: 2.6182084906716634
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: name 'is_flavonols' is not defined
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0