Attempt 3 at triterpenoid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: O=C(O[C@H]([C@](O)(CC/C=C(/CCCC(O)(C)C)\C)C)CC[C@H](OC(=O)C)[C@](O)(CC/C=C(/CCCC(O)(C)C)\C)C)C NAME: Irpenigirin B REASON: MISSED Molecule does not have a C30 skeleton (found 34 carbons)
 * SMILES: [H][C@@]1(CC[C@@]2(C)C3=C(CC[C@]12C)[C@@]1(C)CCC(=O)C(C)(C)[C@]1([H])CC3)[C@@H](CC[C@H](O)C(C)(C)O)C(O)=O NAME: fomitopinic acid A REASON: MISSED No evidence of a triterpenoid scaffold
 * SMILES: O=C1[C@@]23C(=O)N[C@H]([C@@H]2[C@H](C)C(=C[C@@H]3C=C(CCC([C@H]4[C@H]5[C@H]1[C@]67C8=C(C)C([C@]5(O)[C@]6(O[C@@]9(O)[C@H](O)CCC(C)=C[C@@H]%10[C@]%11(C([C@@H]%12[C@@H]8O[C@@H]7[C@H]%129)=O)C(=O)N[C@H]([C@@H]%11[C@H](C)C(=C%10)C)CC(C)C)O4)=O)=O)C)C)CC(C)C NAME: Amichalasine C REASON: MISSED Molecule does not have a C30 skeleton (found 57 carbons)
 * SMILES: CO[C@@H]1C=C2[C@@H]3CC(C)(C)CC[C@@]3(CC[C@@]2(C)[C@]2(C)CC[C@H]3C(C)(C)[C@H](O)CC[C@]3(C)[C@@H]12)C(O)=O NAME: fatsicarpain F REASON: MISSED Molecule does not have a C30 skeleton (found 31 carbons)
 * SMILES: O([C@@H]1C([C@]2([C@@]([C@@]3(C([C@@]4([C@]([C@]5([C@@](CC4)(CC[C@H]([C@@H]5C)C)C)[H])(CC3)C)C)=CC2)[H])(CC1)C)[H])(C)C)C(=O)C NAME: Bauerenyl acetate REASON: MISSED Molecule does not have a C30 skeleton (found 32 carbons)
 * SMILES: O=C1C2=C(C(=O)CC3[C@@]2(CCC(C3(C)C)=O)C)[C@@]4([C@@H](O)C[C@@H]([C@]4(C1)C)[C@@H](CC(=O)CC(C(=O)OC)C)C)C NAME: methyl ganoderate J REASON: MISSED Molecule does not have a C30 skeleton (found 31 carbons)
 * SMILES: O1C2(C3(C(CC2)(C4=C(C5(C(C(C(O)CC5)(CO)CO)CC4)C)CC3)C)C)C(CC1C(=O)CC)C NAME: (3beta,17alpha,23S)-17,23-Epoxy-3,28,29-trihydroxy-27-norlanost-8-en-24-one REASON: MISSED Molecule does not have a C30 skeleton (found 29 carbons)
 * SMILES: [H][C@]1(O[C@@H](C)[C@H](O)[C@@H](O)[C@H]1O)O[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1OC(=O)[C@]12CCC(C)(C)C[C@@]1([H])C1=CC[C@]3([H])[C@@]4(C)C[C@@H](O)[C@H](O[C@]5([H])O[C@H](CO)[C@@H](O)[C@H](O)[C@H]5O)[C@@](C)(CO)[C@]4([H])CC[C@@]3(C)[C@]1(C)CC2 NAME: 3-O-[beta-D-glucopyranosyl]-28-O-[alpha-L-rhamnopyranosyl-(1->2)-beta-D-glucopyranosyl]arjunolic acid REASON: MISSED Molecule does not have a C30 skeleton (found 48 carbons)
 * SMILES: O[C@@H]1[C@]2(C(C3=C([C@@]4(C(C([C@H](OC(=O)CC(O)=O)CC4)(C)C)CC3)C)C1)(CC[C@@]2([C@@H](CCC([C@@H](C)C(O)=O)=C)C)[H])C)C NAME: (2R,6R)-6-[(3R,10S,12S,13R,17R)-3-(2-Carboxyacetyl)oxy-12-hydroxy-4,4,10,13,14-pentamethyl-2,3,5,6,7,11,12,15,16,17-decahydro-1H-cyclopenta[a]phenanthren-17-yl]-2-methyl-3-methylideneheptanoic acid REASON: MISSED Molecule does not have a C30 skeleton (found 34 carbons)
 * SMILES: O1C(O)C(C2C3(C(C=4C(C5(C(C(C(O)C=C5)(C)C)CC4)C)CC3)(CC2)C)C)CC1C6OC6(C)C NAME: Murrayenol REASON: MISSED No evidence of a triterpenoid scaffold
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:36615
  name: triterpenoid
  definition: Any terpenoid derived from a triterpene. The term includes compounds
    in which the C30 skeleton of the parent triterpene has been rearranged or modified
    by the removal of one or more skeletal atoms (generally methyl groups).
  parents:
  - CHEBI:26873
  xrefs:
  - KEGG:C06085
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: invalid syntax (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []