Reverting to best solution for cephalosporin, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:23066
  name: cephalosporin
  definition: A class of beta-lactam antibiotics differing from the penicillins in
    having a 6-membered, rather than a 5-membered, side ring.  Although cephalosporins
    are among the most commonly used antibiotics in the treatment of routine infections,
    and their use is increasing over time, they can cause a range of hypersensitivity
    reactions, from mild, delayed-onset cutaneous reactions to life-threatening anaphylaxis
    in patients with immunoglobulin E (IgE)-mediated allergy.
  parents:
  - CHEBI:38311
  xrefs:
  - KEGG:C00875
  - PMID:10069359
  - PMID:11936371
  - PMID:12833570
  - PMID:24269048
  - PMID:3320614
  - PMID:6762896
  - PMID:8426246
  - Wikipedia:Cephalosporin
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 28
  log_lines_of_code: 3.332204510175204
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - MolFromSmiles
  - MolFromSmarts
  - HasSubstructMatch
  - GetSubstructMatches
  methods_called_count: 4
  smarts_strings:
  - N[C@H](C=O)[C@H]1[N]2C(=O)C([C@H]2[?]S1)[?][?][?]
  - C(=O)O
  - S1C[C@H]2N(C1)C(=O)[C@@H]2[?][?]
  smarts_strings_count: 3
  defs:
  - 'is_cephalosporin(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Core 6-membered dihydrothiazine and beta-lactam ring not found"
  - False, "No carboxylic acid group found"
  - False, "No acylamino group on position 7"
  - True, "Contains core cephalosporin structure with a carboxylic acid and acylamino
    group"
  returns_count: 5
  complexity: 3.066440902035041
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: "Error executing is_cephalosporin('[H][C@]12SCC(CSc3nc(C)c(CC(O)=O)s3)=C(N1C(=O)[C@H]2NC(=O)C(=N/OC)\\\
  \\c1csc(N)n1)C(O)=O'):\n Python argument types in\n    Mol.HasSubstructMatch(Mol,\
  \ NoneType)\ndid not match C++ signature:\n    HasSubstructMatch(RDKit::ROMol self,\
  \ RDKit::MolBundle query, RDKit::SubstructMatchParameters params=True)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    HasSubstructMatch(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool recursionPossible=True, bool useChirality=False,\
  \ bool useQueryQueryMatches=False)\n    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol\
  \ query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0