Attempt 2 at lysophosphatidic acids, f1=0.0
(currently fails to compile, but committing anyway

Below is one way to “tighten” the rules. In our previous attempt we looked for a phosphate, a glycerol‐like fragment (using a very generic “OCC(O)CO” pattern) and simply counted acyl esters using a generic SMARTS. That ended up “finding” glycerol in many molecules (for example in nucleotides or sugar‐containing metabolites) and even picked up acyl ester groups that were not really attached to the glycerol–phosphate core.

In this version we try to improve the specificity by:

1. Checking that the molecule contains a phosphate group (using the SMARTS "[P](=O)(O)(O)")
2. Searching for a three‐carbon “glycerol core” that is not part of any ring (SMARTS "[CH2;!r]-[CH;!r]-[CH2;!r]") so that sugar‐ring fragments are less likely to count.
3. Looking for an acyl ester substructure using the SMARTS "[O;!$([O]-P)]C(=O)[#6]". Then, for each match we require that the oxygen (of the acyl ester) is “nearby” (in terms of bond–distance) one of the phosphorus atoms of the phosphate group. In glycerol phosphate the connecting path (acyl–oxygen … glycerol … phosphate) usually spans 3–5 bonds.
4. Finally, we require that exactly one such acyl ester is found. (If more are found the molecule is likely a diacyl or polyacyl phospholipid; if none are found, the molecule does not match the monoacyl definition.)

One can tweak the distance cutoff (here we require that the shortest bond–path between the acyl–oxygen and a phosphate P has between 3 and 5 bonds) and also the SMARTS definitions. (If one has better training data it might be necessary to change the cutoffs.)

Below is the complete Python code in one code block.

--------------------------------------------------

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.06635071090047392 is too low.
Outcomes:
------

True positives: SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCCCCCC)(O)(O)=O NAME: 1-docosanoyl-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: O(C[C@H](COP(=O)(O)O)O)C(=O)CCCCCCC/C=C\C/C=C\CCCCC NAME: 1-linoleoyl-sn-glycerol 3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O NAME: 1-heneicosanoyl-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCC/C=C\C/C=C\CCCCC)(O)(O)=O NAME: 1-(13Z,16Z-docosadienoyl)-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCC/C=C\CCCCCCCCCC)(O)(O)=O NAME: 1-(11Z-docosenoyl)-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(O)(O)=O NAME: 1-myristoyl-sn-glycerol 3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(OC(=O)CCCCCCC/C=C\CCCCCCCC)CO)(O)(O)=O NAME: LysoPA(0:0/18:1(9Z)) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CC\C=C/C\C=C/C\C=C/CCCCCCCC(=O)OC[C@@H](O)COP(O)(O)=O NAME: 1-linolenoyl-sn-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(OC(=O)CCCCCCC/C=C\C/C=C\CCCCC)CO)(O)(O)=O NAME: LysoPA(0:0/18:2(9Z,12Z)) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCC\C=C/C\C=C/C\C=C/C\C=C/CCCC(=O)O[C@H](CO)COP(O)(O)=O NAME: 2-arachidonoyl-sn-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCCCC/C=C\C/C=C\CCCC)(O)(O)=O NAME: PA(17:2(9Z,12Z)/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(OC(=O)CCC/C=C/C/C=C/C\C=C\C\C=C\CCCCC)CO)(O)(O)=O NAME: 1-Lyso-2-arachidonoyl-phosphatidate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(O)COC(=O)CCCCCCCCCCCCCCCCC(C)C)(O)(O)=O NAME: LysoPA(i-20:0/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(O)COC(=O)CCCCCCCCC/C=C\C/C=C\CCCCC)(O)(O)=O NAME: LysoPA(20:2(11Z,14Z)/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCC)(O)(O)=O NAME: PA(13:0/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(O)(O)=O NAME: 1-stearoyl-sn-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCC\C=C/CCCCCCCC(=O)OC[C@@H](O)COP(O)(O)=O NAME: 1-oleoyl-sn-glycerol 3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(O)(O)=O NAME: 1-palmitoyl-sn-glycerol 3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(O)COC(=O)CCCCCC/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O NAME: LysoPA(20:4(8Z,11Z,14Z,17Z)/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCC)(O)(O)=O NAME: PA(15:0/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: [H]C(CCCCCCCC)=C([H])CCCCCCCC(=O)OCC(O)COP(O)(O)=O NAME: 1-octadec-9-enoylglycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(O)(O)=O NAME: 1-icosanoyl-sn-glycero-3-phosphate REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(O)COC(=O)CCCCCCC)(O)(O)=O NAME: LysoPA(8:0/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC(O)COC(=O)CCCCCCC/C=C/CCCCCCCC)(O)(O)=O NAME: 1-oleoyl-lysophosphatidic acid REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O)COC(=O)CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O NAME: PA(22:4(7Z,10Z,13Z,16Z)/0:0) REASON: CORRECT Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
False positives: SMILES: CC(C)(COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12)C(O)C(=O)NCCC(=O)NCCSC(=O)C(\S)=C\CC(O)=O NAME: (2Z)-4-carboxy-2-sulfanylbut-2-enoyl-CoA REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: NC1=NC=NC2=C1N=CN2[C@@H]3O[C@H](COP(=O)(O)O)[C@@H](OC([C@@H](N)CO)=O)[C@H]3O NAME: 3'-L-seryl-AMP REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: O(C[C@@H](COP(OC[C@H](CO)O)(=O)[O-])O)C(CCCCCCCCCCCCCCCCC)=O NAME: 3-stearoyl-sn-glycero-1-phospho-(1'-sn-glycerol)(1-) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CC(=O)N[C@H]1[C@@H](O)[C@H](O)[C@H](O[C@H]1OP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1ccc(=O)[nH]c1=O)C(O)=O NAME: UDP-N-acetyl-beta-D-mannosaminouronic acid REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCC)COCCCCCCCCCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(O-20:0/17:2(9Z,12Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC1C(O)C(O)C(O)[C@@H](O)C1O)(OC[C@H](O)COC(=O)CCCCCCCCC/C=C\C/C=C\CCCCC)(O)=O NAME: PI(20:2(11Z,14Z)/0:0) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: Nc1ncnc2n(cnc12)[C@@H]1O[C@H](COP(O)(O)=O)[C@@H](OC(=O)c2ccccc2O)[C@H]1O NAME: 3'-O-salicyl-AMP REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: O[C@@H]1[C@@H](COP([O-])(=O)OP([O-])(=O)O[C@H]2O[C@@H]([C@@H](O)[C@H](O)[C@H]2O)C([O-])=O)O[C@H]([C@@H]1O)n1ccc(=O)[nH]c1=O NAME: UDP-alpha-D-glucuronate(3-) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CC1=CC(=O)O[C@H](CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](O)[C@@H]2OP([O-])([O-])=O)n2cnc3c(N)ncnc23)C1(C)C NAME: [(2R)-3,3,4-trimethyl-6-oxo-3,6-dihydro-1H-pyran-2-yl]acetyl-CoA(4-) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCCCCCCCCCCCC(=O)O[C@H](COCCCCCCCCCCCCCCCCCC)COP([O-])(=O)OCC[N+](C)(C)C NAME: 1-octadecyl-2-docosanoyl-sn-glycero-3-phosphocholine REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCC)CO/C=C\CCCCCCCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(P-20:0/22:0) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: C([C@](CO/C=C\CCCCCC/C=C\CCCCCCCC)([H])OC(CCCCCCC/C=C\CCCCCC)=O)OP([O-])(=O)OCC[N+](C)(C)C NAME: PC(P-18:1(9Z)/16:1(9Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CC(C)(COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12)[C@@H](O)C(=O)NCCC(=O)NCCSC(=O)CCC([O-])=O NAME: succinyl-CoA(5-) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC1C(O)C(O)C(O)[C@@H](O)C1O)(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCCC)COCCCCCCCCCCCCCCCCCC)(O)=O NAME: PI(O-18:0/19:1(9Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](O/C=C\CCCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(OCCN)(O)=O NAME: PE(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/P-18:0) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: C([C@@](CO/C=C\CCCCCCCCCCCCCC)(OC(CCC/C=C\C/C=C\C/C=C\CCCCCCCC)=O)[H])OP(=O)(O)OCCN NAME: PE(P-16:0/20:3(5Z,8Z,11Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCC(O)CC(=O)O[C@@H]1[C@@H](N)C(O[C@H](CO)[C@H]1O)OP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)n1ccc(=O)[nH]c1=O NAME: UDP-3-O-(3-hydroxytetradecanoyl)-D-glucosamine REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CCCCCCCCCCCCCCCC\C=C/OC[C@H](COP([O-])(=O)OCC[NH3+])OC(=O)CCC\C=C/C\C=C/C\C=C/C\C=C/CCCCC NAME: 1-(1Z-octadecenyl)-2-arachidonoyl-sn-glycero-3-phosphoethanolamine zwitterion REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: C([C@@](CO/C=C\CCCCCCCCCCCCCCCC)(OC(CCCCCCCCC/C=C\CCCCCC)=O)[H])OP([O-])(=O)OCC[N+](C)(C)C NAME: PC(P-18:0/18:1(11Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(=O)(OC1OC(C(O)C(C1NC(=O)CNC(=O)/C=C/C(=C/C(CCCCCCCC(CC)C)C)/C)O)CO)(OC(C(=O)O)C(OC2OC(C(O)C(C2O)O)CO)C[C@H]3O[C@@H](N4C(=O)NC(=O)C=C4)[C@@H]([C@@H]3O)O)O NAME: 2-[[4,5-dihydroxy-6-(hydroxymethyl)-3-[[2-[[(2E,4E)-4,6,14-trimethylhexadeca-2,4-dienoyl]amino]acetyl]amino]oxan-2-yl]oxy-hydroxyphosphoryl]oxy-4-[(2R,3S,4R,5R)-5-(2,4-dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]-3-[3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxybutanoic acid REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCC)COCCCCCCCCCCCCCCCC)(OC[C@@H](O)CO)(O)=O NAME: PG(O-16:0/14:1(9Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: OC[C@@H](O)[C@@H](O)[C@](O)(COP(O)(O)=O)C(O)=O NAME: 2-carboxy-D-arabinitol 1-phosphate REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: P(OCC[N+](C)(C)C)(OC[C@H](O)COC(=O)CC=CCC=CCCCCCCCCCCCCCCCCC)(O)=O NAME: LPC(24:2) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: CC(C)(COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12)C(O)C(=O)NCCC(=O)NCCSC(=O)C(\S)=C\CC([O-])=O NAME: (2Z)-4-carboxylato-2-sulfanylbut-2-enoyl-CoA(5-) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
 * SMILES: O(C[C@](COP([O-])(=O)OCC[N+](C)(C)C)(OC(CCCCCCCCC/C=C\CCCCCC)=O)[H])CCCCCCCC/C=C\CCCCCCCC NAME: PC(o-18:1(9Z)/18:1(11Z)) REASON: WRONGLY CLASSIFIED Molecule has a phosphate group, glycerol backbone, and one acyl ester group characteristic for lysophosphatidic acids
False negatives: SMILES: OC[C@H](COP(O)(=O)OC[C@@H](CO)OC(CCCCCCC/C=C\CCCCCCCC)=O)OC(CCCCCCC/C=C\CCCCCCCC)=O NAME: (R,R)-bis(2-oleoylglycero)-3-phosphate REASON: MISSED Multiple acyl ester groups found (2 groups); expected monoacyl structure
 * SMILES: OC[C@@H](COP(O)(=O)OC[C@H](CO)OC(CCCCCCC/C=C\CCCCCCCC)=O)OC(CCCCCCC/C=C\CCCCCCCC)=O NAME: (S,S)-bis(2-oleoylglycero)-1-phosphate REASON: MISSED Multiple acyl ester groups found (2 groups); expected monoacyl structure
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:32957
  name: lysophosphatidic acids
  definition: Any monoacylglycerol phosphate obtained by hydrolytic removal of one
    of the two acyl groups of any phosphatidic acid or derivatives therein.
  parents:
  - CHEBI:16961
  xrefs:
  - Wikipedia:Lysophosphatidic_acid
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 72
  log_lines_of_code: 4.276666119016055
  max_indent: 4
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdMolDescriptors, rdmolops
  imports_count: 2
  methods_called:
  - MolFromSmarts
  - update
  - GetSubstructMatches
  - HasSubstructMatch
  - MolFromSmiles
  - GetShortestPath
  methods_called_count: 6
  smarts_strings:
  - glycerol_core_smarts
  - acyl_smarts
  - phosphate_smarts
  smarts_strings_count: 3
  defs:
  - 'is_lysophosphatidic_acids(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Phosphate group not found"
  - False, "Glycerol backbone (non-ring 3-carbon chain) not found"
  - False, "No acyl ester group found (expect exactly one fatty acid chain)"
  - "False, \"No acyl ester group attached to glycerol\u2013phosphate (within expected\
    \ bond distance) found\""
  - False, f"Multiple acyl ester groups found ({candidate_acyl_count} groups); expected
    monoacyl structure"
  - "True, \"Molecule has a phosphate group, a suitable non-ring glycerol backbone,\
    \ and exactly one acyl ester group appropriately linked to the glycerol\u2013\
    phosphate core\""
  returns_count: 7
  complexity: 4.455333223803211
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "Error executing is_lysophosphatidic_acids('P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCCCCCC)(O)(O)=O'):\n\
  \ Python argument types in\n    Mol.GetSubstructMatches(Mol, str)\ndid not match\
  \ C++ signature:\n    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle query,\
  \ RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool uniquify=True, bool useChirality=False, bool\
  \ useQueryQueryMatches=False, unsigned int maxMatches=1000)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False,\
  \ unsigned int maxMatches=1000)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []