Attempt 2 at alkaloid, f1=0.0
(currently fails to compile, but committing anyway

Below is one possible solution. In our reasoning we noted that a simple “nitrogen‐in‐ring” check (the previous heuristic) incorrectly flags many small, “simple” heterocycles (such as pyrazines) as alkaloids while also missing some known cases (like (–)‐selegiline) whose sole nitrogen is exocyclic but is connected to an aromatic “benzyl” fragment. To improve matters we now combine several heuristics:

1. We first reject invalid molecules.
2. We compute a “heteroatom ratio” (that is the fraction of non‐carbon/non‐hydrogen atoms) as a rough way to exclude peptides/nucleotides that tend to have many oxygens.
3. We obtain ring information and check whether any nitrogen lies in a ring. However, if the molecule has only one ring and that ring is small (6 atoms or fewer) and fully aromatic then we assume it is a “simple” heterocycle (not really a complex natural alkaloid).
4. If no nitrogen is in a ring, we then search for a benzylamine motif (an exocyclic nitrogen attached via a –CH2– to an aromatic ring) since several documented alkaloids (for instance (–)‐selegiline) match that pattern.

Note that any single heuristic is imperfect; because alkaloids comprise a very diverse group of natural products no simple “rule” fully captures the class. (If the task proves too difficult one may always return (None,None).)

Below is the complete Python code.

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.07424853020707943 is too low.
Outcomes:
------

True positives: SMILES: CN1CC2(CCN(CC2)C(=O)CN3CCOCC3)C4=C([C@@H]1CO)N(C5=C4C=CC(=C5)OC)C NAME: 1-[(1R)-1-(hydroxymethyl)-7-methoxy-2,9-dimethyl-1'-spiro[1,3-dihydropyrido[3,4-b]indole-4,4'-piperidine]yl]-2-(4-morpholinyl)ethanone REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CC[C@@H](C)C(=O)O[C@H]1[C@H](O)[C@H]2[C@@H](CN3C[C@@H](C)CC[C@H]3[C@@]2(C)O)[C@@H]2C[C@@]34O[C@@]5(O)[C@@H]([C@@H](OC(C)=O)[C@@H](OC(C)=O)[C@H]3[C@]12O)[C@]4(C)CC[C@@H]5OC(=O)[C@@](C)(O)[C@@H](C)O NAME: Protoveratrine B REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CN1C2=C(C=CC(=C2)OC)C3=C1[C@H](NCC34CCN(CC4)C(=O)NC5=C(C=C(C=C5)F)F)CO NAME: (1S)-N-(2,4-difluorophenyl)-1-(hydroxymethyl)-7-methoxy-9-methyl-1'-spiro[2,3-dihydro-1H-pyrido[3,4-b]indole-4,4'-piperidine]carboxamide REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: COc1ccc2C[C@@H]3N(C)CCc4cc(OC)c(Oc5c(O)c(OC)cc6[C@H](Cc7ccc(Oc1c2)cc7)N(C)CCc56)cc34 NAME: Thalmine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O1C=2C=C3C=4N(CCC3=CC2OC1)CC5=C(C4)C=CC(OC)=C5OC NAME: Lambertine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O(C1C(C2C(CN3C(C2)C=4NC5=C(C4CC3)C=CC(OC)=C5)CC1O)C(O)=O)C NAME: 18-Hydroxy-11,17-dimethoxyyohimban-16-carboxylic acid REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CN1C2=CC=CC=C2C(=O)C2=C1C1=C(OC(C1)C(C)(O)CO)C=C2O NAME: gravacridonediol REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1(=C(C=C2C(=C1)[C@@]34[C@@](N(C2)CC3)(CC(C=C4)=O)[H])O)OC NAME: (4aS,10bR)-noroxomaritidine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1(C2CCCC[NH2+]2)CCCN=C1 NAME: tetrahydroanabasine(1+) REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O[C@]12N[C@](C[C@@H]1O)([C@@H](O)C[C@H]2O)[H] NAME: Calystegine B5 REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: OC(/C=C/C(O)=O)=O.C1=C(C=C2C(=C1)C3=C4N2[C@](C[C@]5([C@@]4(N(CC3)CCC5)[H])CC)(C(=O)OC)O)Br NAME: Brovincamine fumarate REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O1C2C(N(CCC=3C2=CC(OC)=C(OC)C3)C)C4=C(C1OC)C=5OCOC5C=C4 NAME: Glaudine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CC[C@]12C[N@@]3C[C@@H](C[C@@](C(=O)OC)(c4[nH]c5ccccc5c4CC3)c3cc4c(cc3OC)N(C)[C@@H]3[C@]44CCN5CC=C[C@](CC)([C@@H]45)[C@@H](OC(C)=O)[C@]3(O)C(=O)OC)[C@H]1O2 NAME: Leurosine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: [H][C@]12N[C@@H](C)C(=O)N1c1ccccc1[C@@]2(O)C[C@@H]1C(=O)N[C@@H](C)c2nc3ccccc3c(=O)n12 NAME: fumiquinazoline A REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CN(C)CC(=O)N1CCC2(CC1)CN([C@@H](C3=C2C4=C(N3)C=C(C=C4)OC)CO)C(=O)C5=CN=CC=C5 NAME: 2-(dimethylamino)-1-[(1S)-1-(hydroxymethyl)-7-methoxy-2-[oxo(3-pyridinyl)methyl]-1'-spiro[3,9-dihydro-1H-pyrido[3,4-b]indole-4,4'-piperidine]yl]ethanone REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: OC[C@H]1[C@@]2(N(C=3C([C@@]42[C@H]5N(CC4)C\C(\[C@@]1(C5)[H])=C\C)=CC=CC3)C(=O)C)[H] NAME: isoretuline REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: COCC(=O)N1CC2(C1)CN([C@H](C3=C2C4=C(N3)C=C(C=C4)OC)CO)CC5=CC(=CC=C5)OC NAME: 1-[(1R)-1-(hydroxymethyl)-7-methoxy-2-[(3-methoxyphenyl)methyl]-1'-spiro[3,9-dihydro-1H-pyrido[3,4-b]indole-4,3'-azetidine]yl]-2-methoxyethanone REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: [H][C@]12C[C@@]3([H])[C@]45C[C@@]([H])([C@@]1([H])COC4=Nc1c(OC)cc(OC)c(OC)c51)[N+]3([O-])C\C2=C/COC NAME: gardneramine-N(4)-oxide REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O[C@@]12N[C@@](C[C@H]1O)(CC[C@H]2O)[H] NAME: Calystegine A6 REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: OC=1C2=C3[C@@](N(CCC3=CC1OC)C)(CC=4C2=CC=5OCOC5C4)[H] NAME: Domesticine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C/C=C\1/C[N+]=2C=CC=3C=4C=CC=CC4NC3C2C[C@@]1(C5=CN6C7=CC=CC=C7[C@]89CCN%10C\C(=C\C)\[C@](C[C@@]8%10[H])([C@@]([C@@H]5O)([C@@]96[H])[H])[H])[H] NAME: 3',4',5',6'-tetradehydrolongicaudatine Y REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1[C@@]2(N3C(C[C@@]42[C@]5(N(C=6C4=CC(=C(C6)OC)OC)C(C[C@]7([C@@]5([C@@]1(C(=CCO7)C3)[H])[H])[H])=O)[H])=O)[H] NAME: 5-oxobrucine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CC1=CC(=CC=C1)S(=O)(=O)N2CCC3(CC2)CN([C@@H](C4=C3C5=C(N4)C=C(C=C5)OC)CO)C(=O)NC6=CC(=CC=C6)F NAME: (1S)-N-(3-fluorophenyl)-1-(hydroxymethyl)-7-methoxy-1'-(3-methylphenyl)sulfonyl-2-spiro[3,9-dihydro-1H-pyrido[3,4-b]indole-4,4'-piperidine]carboxamide REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: [H][C@@]12Cc3ccccc3CN1CCc1ccccc21 NAME: alpha-berbine REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O=C(C1=C[C@H](O)C[C@H]2N[C@@H]1CC2)CC NAME: 4R-Hydroxyhomoanatoxin-A REASON: CORRECT Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
False positives: SMILES: CN(C)C(=O)C1=CC=C(C=C1)C2=CC=C(C=C2)[C@@H]3[C@H]4CN(CC(=O)N4[C@H]3CO)C(=O)CC5CC5 NAME: 4-[4-[(6S,7R,8R)-4-(2-cyclopropyl-1-oxoethyl)-8-(hydroxymethyl)-2-oxo-1,4-diazabicyclo[4.2.0]octan-7-yl]phenyl]-N,N-dimethylbenzamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: N1=C(C(=NC=C1C)C)/C=C/C NAME: 2,5-Dimethyl-3-(1-propenyl)pyrazine REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C[C@H]1CN(C(=O)C2=CC(=CN=C2O[C@@H]1CN(C)C(=O)CC3=CN=CC=C3)C=CC4=CC=CC=C4)[C@@H](C)CO NAME: LSM-7408 REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: [C@H]1(N2C=CC(=O)NC2=O)[C@@H]([C@@H]([C@@]([C@H](C(N)=O)O)(O1)[H])O)O NAME: uridine-5'-carboxamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: COC1=CC=CC=C1CNC(=O)C[C@@H]2CC[C@H]3[C@H](O2)COC[C@@H](CN3C(=O)NC4=CC=C(C=C4)F)O NAME: (3R,6aS,8S,10aS)-N-(4-fluorophenyl)-3-hydroxy-8-[2-[(2-methoxyphenyl)methylamino]-2-oxoethyl]-3,4,6,6a,8,9,10,10a-octahydro-2H-pyrano[2,3-c][1,5]oxazocine-1-carboxamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1CCC(CC1)CN2C[C@H](COC[C@@H]3[C@@H]2CC[C@@H](O3)CC(=O)NCC4=CC=C(C=C4)F)O NAME: 2-[(3R,6aS,8R,10aS)-1-(cyclohexylmethyl)-3-hydroxy-3,4,6,6a,8,9,10,10a-octahydro-2H-pyrano[2,3-c][1,5]oxazocin-8-yl]-N-[(4-fluorophenyl)methyl]acetamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O=C(NCC(=O)N[C@@H](CO)C(O)=O)[C@@H](N)CC=1NC=NC1 NAME: His-Gly-Ser REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CCC(=O)N1C[C@@H]2[C@H]([C@H](N2C(=O)C1)CO)C3=CC=C(C=C3)C#CCC(C)C NAME: (6S,7R,8S)-8-(hydroxymethyl)-7-[4-(4-methylpent-1-ynyl)phenyl]-4-(1-oxopropyl)-1,4-diazabicyclo[4.2.0]octan-2-one REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1=CC(=CC=C1C(=O)NC(CCC(=O)NC(CCC(=O)NC(CCC(=O)O)C(=O)O)C(=O)O)C(=O)O)NCC2=CN=C3C(=N2)C(=O)NC(=N3)N NAME: Pteropterin REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CCCNC(=O)N(C)C[C@@H]1[C@@H](CN(C(=O)C2=CC(=CN=C2O1)Br)[C@H](C)CO)C NAME: 1-[[(2S,3R)-8-bromo-5-[(2R)-1-hydroxypropan-2-yl]-3-methyl-6-oxo-3,4-dihydro-2H-pyrido[2,3-b][1,5]oxazocin-2-yl]methyl]-1-methyl-3-propylurea REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CC(C)SC1=NN=C(S1)NC2=CC=CC=C2 NAME: N-phenyl-5-(propan-2-ylthio)-1,3,4-thiadiazol-2-amine REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: COC1=CC=CC2=C1C(=CN2)CN=C=S NAME: (4-methoxyindol-3-ylmethyl)isothiocyanate REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C[C@@H]1CN(C(=O)C2=C(C=CC(=C2)NC(=O)CC3=CN(C4=CC=CC=C43)C)O[C@H]1CNC)[C@@H](C)CO NAME: N-[(2R,3R)-5-[(2S)-1-hydroxypropan-2-yl]-3-methyl-2-(methylaminomethyl)-6-oxo-3,4-dihydro-2H-1,5-benzoxazocin-8-yl]-2-(1-methyl-3-indolyl)acetamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O=C(N[C@@H](CCCN=C(N)N)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC=1NC=NC1)CC=2NC=NC2 NAME: His-His-Arg REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O=C1N(O)CCCCC1NC(=O)C(C(OC(=O)C(NC(=O)C2N=C(C3=C(O)C=CC=C3)OC2C)CCCCN(O)C(=O)/C=C\CCCCCCCCCC(=O)O)CC)C NAME: Carboxymycobactin-7 REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: ClC[C@H]1N[C@H](C(=O)N[C@H](C(=O)N2[C@H](C(=O)N3[C@H](C(=O)O)C[C@@H](C3)C)CCCC2)C(C)C)CC[C@@H]1OC NAME: Chloromyxamide B REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CN1CCN(CC1)c1ccc2ccccc2n1 NAME: N-methylquipazine REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1CC1CC(=O)N2[C@@H]([C@@H](C23CN(C3)C(=O)NC4=CC=CC=C4F)C5=CC=CC=C5)CO NAME: (2S,3S)-1-(2-cyclopropyl-1-oxoethyl)-N-(2-fluorophenyl)-2-(hydroxymethyl)-3-phenyl-1,6-diazaspiro[3.3]heptane-6-carboxamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CN(C)CCN(CC1=CC=C(C=C1)OC)C2=NC=CC=N2 NAME: N'-[(4-methoxyphenyl)methyl]-N,N-dimethyl-N'-(2-pyrimidinyl)ethane-1,2-diamine REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: COC1=C(C=C(C=C1)N2C(=NN=N2)SCC(=O)NC3=CC4=C(C=C3)OCCO4)OC NAME: N-(2,3-dihydro-1,4-benzodioxin-6-yl)-2-[[1-(3,4-dimethoxyphenyl)-5-tetrazolyl]thio]acetamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O=C1N2[C@H](C(=O)NCC(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H]1[C@H](O)C)=O)[C@H](CC)C)=O)[C@H](O)C)=O)CC3=CC=C(O)C=C3)=O)CC(C)C)CC=4NC=NC4)[C@H](O)C)CCC2 NAME: Piricyclamide GTHLYTITP REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: O=C(NC(C(=O)O)CC(=O)N)/C(=C/C=C/C=C/C=C/C=C/C=C/C=C/C=C/[C@H]1N=C(/C=C/C=2NC=CC2)O[C@@H]1C)/C NAME: DKxanthene 556 REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1CCN(CC1)CCNC(=O)C[C@@H]2C[C@H]3[C@@H]([C@@H](O2)CO)OC4=C3C=C(C=C4)NC(=O)NC5CCCC5 NAME: 2-[(1S,3S,4aR,9aS)-6-[[(cyclopentylamino)-oxomethyl]amino]-1-(hydroxymethyl)-3,4,4a,9a-tetrahydro-1H-pyrano[3,4-b]benzofuran-3-yl]-N-[2-(1-piperidinyl)ethyl]acetamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: C1CCN2[C@@H](CN(C1)CC3=CC=NC=C3)[C@@H]([C@@H]2CO)C4=CC=C(C=C4)C5=CCCC5 NAME: [(8R,9S,10R)-9-[4-(1-cyclopentenyl)phenyl]-6-(pyridin-4-ylmethyl)-1,6-diazabicyclo[6.2.0]decan-10-yl]methanol REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
 * SMILES: CCCN1C[C@H]([C@@H](CN(C(=O)C2=C(C=CC(=C2)NC(=O)C3=CC(=CC=C3)F)OC[C@@H]1C)C)OC)C NAME: 3-fluoro-N-[(4S,7R,8S)-8-methoxy-4,7,10-trimethyl-11-oxo-5-propyl-2-oxa-5,10-diazabicyclo[10.4.0]hexadeca-1(12),13,15-trien-14-yl]benzamide REASON: WRONGLY CLASSIFIED Contains a nitrogen incorporated in a ring system; matches key features of alkaloids
False negatives: SMILES: C[C@H](Cc1ccccc1)N(C)CC#C NAME: (-)-selegiline REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: [H][C@@]12CC[C@]3([H])[C@]([H])(CC[C@]4(C)C(=CC[C@@]34[H])[C@H](C)N(C)C)[C@@]1(C)CC[C@H](NC(=O)C=C(C)C)[C@@H]2O NAME: hookerianamide J REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: CN[C@H]1CC[C@]23C[C@]22CC[C@]4(C)[C@H](CC[C@@]4(C)[C@@H]2CC[C@H]3C1(C)C)[C@H](C)N(C)C NAME: Cycloprotobuxine C REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: CN(C)CCc1ccc(O)cc1 NAME: hordenine REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: [H][C@@]12CC[C@@]3([H])[C@]4([H])CC[C@]([H])([C@H](C)NC)[C@@]4(C)CC[C@]3([H])[C@@]1(C)CC[C@@H](C2)N(C)C(=O)c1ccccc1 NAME: hookerianamide I REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: C1(=C(C=C(C=C1)CNCCC2=CC=C(C=C2)O)O)O NAME: norbelladine REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: [H][C@@]12CC[C@]3([H])C(=CC[C@]4(C)[C@]([H])([C@H](O)C[C@@]34C)[C@H](C)N(C)C)C=C1CC[C@H](NC)C2(C)C NAME: (+)-buxaminol C REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: C[C@H](N)[C@@H](O)C1=CC=CC=C1 NAME: cathine REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: COc1cc(\C=C\C(=O)NCCCCNC(N)=N)ccc1O NAME: feruloylagmatine REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
 * SMILES: [H][C@@]12CC[C@]3([H])C(=CC[C@]4(C)[C@]([H])([C@H](O)C[C@@]34C)[C@H](C)N(C)C)C=C1CC[C@H](N(C)C)C2(C)C NAME: buxaminol A REASON: MISSED All nitrogen atoms are exocyclic; likely an amine, not an alkaloid
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:22315
  name: alkaloid
  definition: Any of the naturally occurring, basic nitrogen compounds (mostly heterocyclic)
    occurring mostly in the plant kingdom, but also found in bacteria, fungi, and
    animals. By extension, certain neutral compounds biogenetically related to basic
    alkaloids are also classed as alkaloids. Amino acids, peptides, proteins, nucleotides,
    nucleic acids, amino sugars and antibiotics are not normally regarded as alkaloids.
    Compounds in which the nitrogen is  exocyclic (dopamine, mescaline, serotonin,
    etc.) are usually classed as amines rather than alkaloids.
  parents:
  - CHEBI:35352
  xrefs:
  - Wikipedia:Alkaloid
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 66
  log_lines_of_code: 4.189654742026425
  max_indent: 5
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - GetIdx
  - GetAtomicNum
  - MolFromSmiles
  - AtomRings
  - PathToSubmol
  - GetAtoms
  - HasSubstructMatch
  - MolFromSmarts
  - items
  - GetNumAtoms
  - GetRingInfo
  - GetIsAromatic
  methods_called_count: 12
  smarts_strings:
  - '[NX3;H2,H1;!$(*@R)]-CH2-c1ccccc1'
  smarts_strings_count: 1
  defs:
  - 'is_alkaloid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "High heteroatom ratio suggests peptide/nucleotide rather than alkaloid"
  - False, "No nitrogen atoms found; alkaloids require at least one nitrogen."
  - False, "Only a single small, fully aromatic ring detected; likely a simple heterocycle
    (amine) rather than an alkaloid"
  - True, "Nitrogen present in a ring system within a sufficiently complex scaffold;
    matches features of alkaloids"
  - True, "Exocyclic nitrogen in a benzylamine-like motif attached to an aromatic
    ring; matches known alkaloid features"
  - False, "All nitrogen atoms are exocyclic and no benzylamine motif was found; likely
    an amine rather than an alkaloid"
  returns_count: 7
  complexity: 5.837930948405285
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "Error executing is_alkaloid('[Cl-].CCn1cc[n+](C)c1'):\n Range Error\n\tidx\n\
  \tViolation occurred on line 329 in file Code/GraphMol/ROMol.cpp\n\tFailed Expression:\
  \ 8 < 8\n\tRDKIT: 2024.09.1\n\tBOOST: 1_85\n"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []