Attempt 2 at cyclic fatty acid, f1=0.0
(currently fails to compile, but committing anyway

The previous program only checked for the presence of a carboxylic acid group and any ring structures in the molecule. This led to misclassifications because it did not verify if the molecule is actually a fatty acid.

A fatty acid is typically a molecule that consists of a long aliphatic chain with a terminal carboxylic acid group. The chain is usually unbranched and can be saturated or unsaturated. In cyclic fatty acids, there is a ring somewhere in the aliphatic chain.

To improve the classification, we need to:

1. **Ensure the molecule has a long aliphatic chain connected to a carboxylic acid group.** We'll define a minimal chain length (e.g., 8 carbons) to consider it a fatty acid.

2. **Check for the presence of any ring structures in the molecule.**

By implementing these criteria, we can reduce false positives (molecules that have rings and carboxylic acid groups but are not fatty acids) and false negatives (fatty acids that were missed due to inadequate pattern matching).

Now, here's the improved code:

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.017556212739989675 is too low.
Outcomes:
------

True positives: SMILES: O1C(=CC=C1C(=O)C#C/C=C/C)/C=C\C(O)=O NAME: Wyeronic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: CCCCCCCCC1=C(CCCCCCC(O)=O)C1 NAME: malvalic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C1[C@H]([C@@](C=2CC[C@]3([C@H](C2C1)CC[C@@H]3C(=O)CO)C)(CCC(=O)O)C)[C@@H](O)C NAME: Nodulisporisteroid Q REASON: CORRECT Contains 3 ring(s) and a carboxylic acid group
 * SMILES: O1C(CCCCCCC(O)=O)=C(C(=C1CCC)C)C NAME: 3,4-Dimethyl-5-propyl-2-furanheptanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: C(CCC(O)=O)/C=C\C/C=C\C=C\[C@H](C[C@H]1[C@@H](CCCCC)O1)OO NAME: (12S)-hydroperoxy-(14S,15R)-epoxy-(5Z,8Z,10E)-icosatrienoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: C(CCC)C/C=C\C[C@@H]1[C@H](C/C=C\C/C=C\CCCC(O)=O)O1 NAME: (11S,12R)-EET REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O1C(CCCC(O)=O)=CC(=C1CCC(O)=O)C NAME: 3-methyl-5-carboxypropyl-2-furanpropanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: [H]C(\C=C/CCCCCCCC(O)=O)=C1O[C@H]1C\C=C/CC NAME: (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: C(C(O)=O)C/C=C\C/C=C\CC1C(C/C=C\C/C=C\C/C=C\CC)O1 NAME: (4Z,7Z,13Z,16Z,19Z)-10,11-epoxydocosapentaenoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: [C@H]1(CCCC(O)=O)[C@H](/C=C/C=C/C=C\C/C=C\C=C\C(CC)O)O1 NAME: 5(S),6(S)-epoxy-18-hydroxy-(7E,9E,11Z,14Z,16E)-icosapentaenoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: C(\C([C@H]1[C@H](C/C=C\CCCCC)O1)O)=C\C/C=C\CCCC(=O)O NAME: hepoxilin B3 REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: CC\C=C/C#CC(=O)c1ccc(\C=C\C(O)=O)o1 NAME: Wyerone acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C(O)/C(=C/C[C@]12O[C@H]1[C@@H](O)C=C([C@H]2O)/C=C/CCCCC)/C NAME: Pestalic acid B REASON: CORRECT Contains 2 ring(s) and a carboxylic acid group
 * SMILES: C(\CC)=C\C/C=C\C/C=C\CC1C(C/C=C\CCCC(=O)O)O1 NAME: (5Z,11Z,14Z,17Z)-8,9-epoxyicosatetraenoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: C\C(CC[C@H]1OC1(C)C)=C/CC\C(C)=C\C(O)=O NAME: juvenile hormone III acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O1C(CCCC(O)C)=C(C(=C1CCC(O)=O)C(O)=O)C NAME: 3-carboxy-4-methyl-5-(4-hydroxypentyl)-2-furanpropanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: CCCCC\C=C/CC1OC1C\C=C/C\C=C/CCCC(O)=O NAME: 11,12-EET REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C1C=C(/C=C/CCCCC)[C@H](O)[C@]2([C@@H]1O2)C/C=C(/C(=O)O)\C NAME: (E)-4-[(1S,2S,6S)-3-[(E)-hept-1-enyl]-2-hydroxy-5-oxo-7-oxabicyclo[4.1.0]hept-3-en-1-yl]-2-methylbut-2-enoic acid REASON: CORRECT Contains 2 ring(s) and a carboxylic acid group
 * SMILES: CC\C=C/CC1C(CCCCCCCC(O)=O)CCC1=O NAME: 8-{3-oxo-2-[(2Z)-pent-2-en-1-yl]cyclopentyl}octanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O1C(CCCCCC(O)=O)=C(C(=C1CCC(O)=O)C)C NAME: 3,4-dimethyl-5-carboxyethyl-2-furanhexanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: CCCCCCC1CC1CCCCCCCCCC(O)=O NAME: 11,12-methyleneoctadecanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: OC(CC/C=C\C/C=C\C/C=C\C/C=C\C=C\1/[C@H](C/C=C\CC)O1)=O NAME: 17S,(16)-epoxy-(4Z,7Z,10Z,13Z,19Z)-docosahexa-4,7,10,13,15,19-enoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: CCN1CCN(CC1)C(=O)C=CC(=O)O NAME: 4-(4-ethyl-1-piperazinyl)-4-oxo-2-butenoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O1C(CCCCCCCCCC(O)=O)=C(C(=C1CCCCC)C)C NAME: 10-(3,4-dimethyl-5-pentylfuran-2-yl)-decanoic acid REASON: CORRECT Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C1C2=C(C(=O)C[C@H]([C@@]2(CCC(=O)O)C)[C@@]3(OC3)C)[C@@]4(CC[C@H]5[C@]4(C1=O)CO[C@]5(CCC(=O)CC)C)C NAME: Ganoboninone A REASON: CORRECT Contains 5 ring(s) and a carboxylic acid group
False positives: SMILES: S(=O)(=O)(CC[C@@H]1NC(=O)[C@H](NC(=O)C(N(C(=O)CC[C@@H](NC([C@H]([C@@H](NC([C@@H](NC(C[C@@H](NC1=O)C(=O)O)=O)CCCN=C(N)N)=O)/C=C/C(=C/[C@@H]([C@@H](OC)CC2=CC=CC=C2)C)/C)C)=O)C(=O)O)C)=C)C)C NAME: [D-Asp3]MC-M(O2)R REASON: WRONGLY CLASSIFIED Contains 2 ring(s) and a carboxylic acid group
 * SMILES: O=C(N[C@@H](CC1=CC=CC=C1)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC2=CC=C(O)C=C2)CCCCN NAME: Tyr-Lys-Phe REASON: WRONGLY CLASSIFIED Contains 2 ring(s) and a carboxylic acid group
 * SMILES: N[C@@H](Cc1cc(I)c(O)c(I)c1)C(=O)N[C@@H](Cc1cc(I)c(O)c(I)c1)C(O)=O NAME: 3,5-diiodo-L-tyrosyl-3,5-diiodo-L-tyrosine REASON: WRONGLY CLASSIFIED Contains 2 ring(s) and a carboxylic acid group
 * SMILES: [H][C@@]1(CC[C@@]2([H])C3=C(C(=O)C[C@]12C)[C@@]1(C)CC[C@@H](O)[C@](C)(O)[C@]1([H])CC3=O)[C@H](C)CCC(=C)C(C)C(O)=O NAME: Camphoratin C REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: OC=1C(=CC(O)=C(O)C1O)C(=O)NCC(O)=O NAME: 2-{[hydroxy(2,3,4,5-tetrahydroxyphenyl)methylidene]amino}acetic acid REASON: WRONGLY CLASSIFIED Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O([C@H]1[C@H](O)[C@H](O[C@@H](O[C@H]2[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]2CO)O[C@H]3[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]3CO)O)[C@H]1O)CO[C@H]4O[C@@H]([C@@H](O)[C@H](O)[C@H]4O[C@@H]5O[C@@H]([C@@H](O[C@@H]6O[C@@H]([C@H](O)[C@H](O[C@]7(O[C@H]([C@H](NC(=O)C)[C@@H](O)C7)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]6O)CO)[C@H](O)[C@H]5NC(=O)C)CO)CO)[C@H]8O[C@@H]([C@@H](O)[C@H](O)[C@H]8O[C@@H]9O[C@@H]([C@@H](O[C@@H]%10O[C@@H]([C@H](O)[C@H](O[C@]%11(O[C@H]([C@H](NC(=O)C)[C@@H](O)C%11)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]%10O)CO)[C@H](O)[C@H]9NC(=O)C)CO)CO NAME: (2S,4S,5R,6R)-5-Acetamido-2-[(2S,3R,4S,5S,6R)-2-[(2R,3S,4R,5R,6S)-5-acetamido-6-[(2S,3R,4S,5S,6R)-2-[[(2R,3R,4S,5S,6S)-4-[(2R,3R,4S,5S,6R)-3-[(2S,3R,4R,5S,6R)-3-acetamido-5-[(2S,3R,4S,5S,6R)-4-[(2S,4S,5R,6R)-5-acetamido-2-carboxy-4-hydroxy-6-[(1R,2R)-1,2,3-trihydroxypropyl]oxan-2-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4-hydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-4,5-dihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[(2R,3S,4R,5R,6S)-5-acetamido-6-[(2R,3S,4R,5R,6R)-5-acetamido-4,6-dihydroxy-2-(hydroxymethyl)oxan-3-yl]oxy-4-hydroxy-2-(hydroxymethyl)oxan-3-yl]oxy-3,5-dihydroxyoxan-2-yl]methoxy]-4,5-dihydroxy-6-(hydroxymethyl)oxan-3-yl]oxy-4-hydroxy-2-(hydroxymethyl)oxan-3-yl]oxy-3,5-dihydroxy-6-(hydroxymethyl)oxan-4-yl]oxy-4-hydroxy-6-[(1R,2R)-1,2,3-trihydroxypropyl]oxane-2-carboxylic acid REASON: WRONGLY CLASSIFIED Contains 11 ring(s) and a carboxylic acid group
 * SMILES: OC1C(C(C(O)C1)/C=C/C(O)CC(CCCC)C)CCCCCCC(O)=O NAME: 17,20-dimethyl Prostaglandin F1alpha REASON: WRONGLY CLASSIFIED Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C(O)C1=C2O[C@]3(O)[C@@H](CCCC3)[C@@H]4C2=C([C@@H]([C@@H](C)O4)C)C(=C1O)C NAME: Penicitrinol O REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: OC(=O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2)C1=O NAME: daprodustat REASON: WRONGLY CLASSIFIED Contains 3 ring(s) and a carboxylic acid group
 * SMILES: C1[C@@]2([C@]3(C[C@@H]([C@]4([C@]([C@@]3(CC[C@@]2(C[C@@H](C1)O)[H])[H])(CC[C@@]4([C@@H](CCC(NCC(O)=O)=O)C)[H])[H])C)O)[H])C NAME: glycodeoxycholic acid REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: COCCCN1C(=CC=C1C2=CC=CS2)CCC(=O)O NAME: 3-[1-(3-methoxypropyl)-5-thiophen-2-yl-2-pyrrolyl]propanoic acid REASON: WRONGLY CLASSIFIED Contains 2 ring(s) and a carboxylic acid group
 * SMILES: O1[C@H]([C@H](NC(=O)C)[C@@H](O)C[C@]1(OC[C@H]2OC(O)[C@H](NC(=O)C)[C@@H](O[C@H]3O[C@@H]([C@H](O)[C@H](O)[C@H]3O)CO)[C@H]2O)C(O)=O)[C@H](O)[C@H](O)CO NAME: (2R,4S,5R,6R)-5-Acetamido-2-[[(2R,3R,4R,5R)-5-acetamido-3,6-dihydroxy-4-[(2S,3R,4S,5R,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyoxan-2-yl]methoxy]-4-hydroxy-6-[(1R,2R)-1,2,3-trihydroxypropyl]oxane-2-carboxylic acid REASON: WRONGLY CLASSIFIED Contains 3 ring(s) and a carboxylic acid group
 * SMILES: O[C@@H]1C=2[C@]3([C@@]([C@](CC3=O)([C@@H](CC(=O)C[C@@H](C)C(O)=O)C)[H])(CC(=O)C2[C@@]4([C@](C([C@@H](O)CC4)(C)C)(C1)[H])C)C)C NAME: Ganoderic acid B REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: SC[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CC1=CC=C(O)C=C1)CC2=CC=CC=C2)C(O)=O NAME: Tyr-Phe-Cys REASON: WRONGLY CLASSIFIED Contains 2 ring(s) and a carboxylic acid group
 * SMILES: CC(C)C[C@@H](C(=O)O)NC(=O)C1=C(C=C(C=C1)NC[C@H](CS)N)C2=CC=CC3=CC=CC=C32 NAME: (2S)-2-[[[4-[[(2R)-2-amino-3-mercaptopropyl]amino]-2-(1-naphthalenyl)phenyl]-oxomethyl]amino]-4-methylpentanoic acid REASON: WRONGLY CLASSIFIED Contains 3 ring(s) and a carboxylic acid group
 * SMILES: O=C1C2=C([C@]3(CC[C@@H]([C@]([C@@H]3C1)(C(=O)O)C)O)C)C[C@@H](OC(=O)C)[C@]4(O[C@]2(O)CC[C@@H]4[C@@H](CCC(=C)C(C)C)C)C NAME: Gloeophyllin I REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: CC(=C)[C@H]1CN[C@@H]([C@H]1CC(O)=O)C(O)=O NAME: kainic acid REASON: WRONGLY CLASSIFIED Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C1C([C@H]2[C@](C3=C([C@]4([C@]([C@@H]([C@@H]([C@@H](OC(=O)C)CC=C(C(=O)O)C)C)C[C@@H]4OC(=O)C)(C)CC3)C)[C@@H](C2)O)(C)CC1)(C)C NAME: Ganorbiformin D REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: [C@@]12([C@@]3([C@@](C[C@@H](C1)O)([C@@]4(CC[C@@]5(C[C@@]4([C@H]3C(=O)O)CC5=C)O)[H])COC2=O)[H])C NAME: gibberellin A98 REASON: WRONGLY CLASSIFIED Contains 5 ring(s) and a carboxylic acid group
 * SMILES: [H][C@@]12C[C@H](O)CC[C@]1(C)[C@@]1([H])C[C@H](O)[C@]3(C)[C@]([H])(CC[C@@]3([H])[C@]1([H])[C@H](O)C2)[C@H](C)C[C@H](C)C(O)=O NAME: (23S)-methyl-3alpha,7alpha,12alpha-trihydroxy-5beta-cholan-24-oic acid REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: O=C1C=2C(N(C=C1C(O)=O)C3=C(F)C=C(C=C3)F)=NC(=C(C2)F)N4C[C@]5([C@@](C4)([C@@H]5NC([C@@H](NC([C@H](C)N)=O)C)=O)[H])[H] NAME: alatrofloxacin REASON: WRONGLY CLASSIFIED Contains 5 ring(s) and a carboxylic acid group
 * SMILES: O1C(=O)C(CCCCCCCCCCCCCCCCC/C=C(/C(CC(O)=O)C(O)=O)\C(O)=O)=C(C1=O)C NAME: Skeletocutin P REASON: WRONGLY CLASSIFIED Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O[C@@H]1[C@]2([C@]3([C@@]([C@](CC3)([C@@H](CCC(O)=O)C)[H])(CC[C@@]2([C@@]4(C(=C1)C[C@@H](O)CC4)C)[H])C)[H])[H] NAME: 3beta,7beta-Dihydroxychol-5-en-24-oic Acid REASON: WRONGLY CLASSIFIED Contains 4 ring(s) and a carboxylic acid group
 * SMILES: OC[C@H]1O[C@@H](O[C@H]([C@@H](O)C=O)[C@H](O)[C@H](O)C(O)=O)[C@H](O)[C@@H](O)[C@@H]1O NAME: 3-O-beta-D-glucosyl-D-glucuronic acid REASON: WRONGLY CLASSIFIED Contains 1 ring(s) and a carboxylic acid group
 * SMILES: O=C(N1[C@H](CCC1)C(O)=O)[C@@H](NC(=O)[C@@H](N)CCC(=O)N)CCC(=O)N NAME: Gln-Gln-Pro REASON: WRONGLY CLASSIFIED Contains 1 ring(s) and a carboxylic acid group
False negatives: SMILES: CC\C=C/C#CC(=O)c1ccc(\C=C\C(=O)OC)o1 NAME: Wyerone REASON: MISSED No carboxylic acid group found
 * SMILES: O=C(C=1OC(CCCC(=O)C)=CC1)[C@@H](O)C NAME: Irpexlacte D REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(CCCCCCCCC(O[C@H](COC(=O)CCCCCCCCC=2OC(=C(C2C)C)CCC)CO)=O)=C(C(=C1CCC)C)C NAME: DG(9D3/9D3/0:0) REASON: MISSED No carboxylic acid group found
 * SMILES: O=C(C=1OC(C(O)CCCC)=CC1)C(O)C NAME: 2-hydroxy-1-(5-(1-hydroxypentyl)-furan-2-yl)-propan-1-one REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(=CC=C1/C=C\C(OC)=O)C(=O)C#CCCCC NAME: Dihydrowyerone REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(=CC=C1C(OC)CCCC)C(O)C(O)C NAME: 1-(5-(1-methoxypentyl)furan-2-yl)propane-1,2-diol REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(=CC=C1C(OC)CCC=C)C(O)C(O)C NAME: 1-(5-(1-methoxypent-4-en-1-yl)furan-2-yl)propane-1,2-diol REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(CCCCCCCCCCCCC(O[C@H](COC(=O)CCCCCCCCC=2OC(CCCCC)=CC2C)CO)=O)=C(C(=C1CCCCC)C)C NAME: (2S)-1-hydroxy-3-{[9-(3-methyl-5-pentylfuran-2-yl)nonanoyl]oxy}propan-2-yl 13-(3,4-dimethyl-5-pentylfuran-2-yl)tridecanoate REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(CCCCCCCCCCC(OC[C@@H](OC(=O)CCCCCCCCCCC=2OC(CCCCC)=CC2C)CO)=O)=C(C(=C1CCCCC)C)C NAME: DG(11D5/11M5/0:0) REASON: MISSED No carboxylic acid group found
 * SMILES: O1C(CCCCCCCCCCCCC(OC[C@@H](OC(=O)CCCCCCCCCCC=2OC(CCCCC)=CC2C)CO)=O)=C(C(=C1CCCCC)C)C NAME: DG(13D5/11M5/0:0) REASON: MISSED No carboxylic acid group found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:59238
  name: cyclic fatty acid
  definition: Any fatty acid containing anywhere in its structure a ring of atoms.
  parents:
  - CHEBI:35366
  xrefs:
  - PMID:17113094
  - PMID:9300789
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 56
  log_lines_of_code: 4.02535169073515
  max_indent: 3
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - MolFromSmiles
  - GetAtomicNum
  - GetNeighbors
  - GetSubstructMatches
  - NumRings
  - GetIdx
  - append
  - MolFromSmarts
  - add
  - GetRingInfo
  - GetAtomWithIdx
  methods_called_count: 11
  smarts_strings:
  - C(=O)[O;H1]
  smarts_strings_count: 1
  defs:
  - 'is_cyclic_fatty_acid(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No terminal carboxylic acid group found"
  - False, f"Aliphatic chain too short ({max_chain_length} carbons), not a fatty acid"
  - False, "No ring structures found"
  - True, f"Contains {num_rings} ring(s) and a fatty acid chain of {max_chain_length}
    carbons"
  - max_length
  returns_count: 6
  complexity: 5.00507033814703
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "Error executing is_cyclic_fatty_acid('O1C(=CC=C1C(=O)C#C/C=C/C)/C=C\\\\C(O)=O'):\n\
  \ 'Atom' object has no attribute 'IsAromatic'"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []