Reverting to best solution for amino sugar, f1=0.48014375561545375 iteration 1
---
chemical_class:
  id: CHEBI:28963
  name: amino sugar
  definition: Any sugar having one or more alcoholic hydroxy groups replaced by substituted
    or unsubstituted amino groups.
  parents:
  - CHEBI:63299
  xrefs:
  - KEGG:C05383
  - PMID:18424273
  - PMID:9056391
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 23
  log_lines_of_code: 3.1354942159291497
  max_indent: 2
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - MolFromSmarts
  - HasSubstructMatch
  - MolFromSmiles
  methods_called_count: 3
  smarts_strings:
  - '[CX4;R][NX3;H2,H1,H0]'
  - C1[C@H]([O])[C@@H]([O])[C@H]([O])[C@H](O)O1
  smarts_strings_count: 2
  defs:
  - 'is_amino_sugar(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No typical sugar-like ring structure found"
  - False, "No amino group replacing a hydroxy group found"
  - True, "Contains a sugar-like ring structure with one or more hydroxyl groups replaced
    by amino groups"
  returns_count: 4
  complexity: 2.6270988431858298
message: '

  Error: exceptions must derive from BaseException

  Attempt failed: F1 score of 0 is too low.

  Outcomes:

  ------

  True positives: NONE

  False positives: NONE

  False negatives: NONE

  ------

  In your reasoning step, analyze the previous program and the above outcomes, hypothesizing
  about what went wrong, and how to improve.

  '
true_negatives: null
false_negatives: null
sample_true_negatives:
- smiles: CN(C)C1=CC2=C(C=C1)O[C@@H]3[C@H]2C[C@@H](O[C@H]3CO)CC(=O)NCCN4CCCCC4
  name: 2-[(1S,3R,4aS,9aR)-6-(dimethylamino)-1-(hydroxymethyl)-3,4,4a,9a-tetrahydro-1H-pyrano[3,4-b]benzofuran-3-yl]-N-[2-(1-piperidinyl)ethyl]acetamide
  reason: No typical sugar-like ring structure found
- smiles: C[C@@H](C(=O)O)NC(=O)OC(C)(C)C
  name: N-Boc-L-alanine
  reason: No typical sugar-like ring structure found
- smiles: O=C1C2=C(O)C(=C(O)C=C2C(=O)C=3C1=C(O)C=C(O)C3)/C=C/CCCC
  name: Averythrin
  reason: No typical sugar-like ring structure found
- smiles: O=C(N[C@@H](CC=1NC=NC1)C(O)=O)[C@@H](NC(=O)[C@@H](N)CCC(=O)N)[C@H](CC)C
  name: Gln-Ile-His
  reason: No typical sugar-like ring structure found
- smiles: O1C2C3C(CCC3=C)C(CCC2C(C1=O)=C)=C
  name: 3,6,9-Trimethylidene-3a,4,5,6a,7,8,9a,9b-octahydroazuleno[4,5-b]furan-2-one
  reason: No typical sugar-like ring structure found
- smiles: C1CN(CC2=CC=CC=C21)CCCNC(=O)CN3C(=O)COC4=CC=CC=C43
  name: N-[3-(3,4-dihydro-1H-isoquinolin-2-yl)propyl]-2-(3-oxo-1,4-benzoxazin-4-yl)acetamide
  reason: No typical sugar-like ring structure found
- smiles: Cc1c(c[nH]c1C(=O)Nc1c(O)c2ccc(O)c(C)c2oc1=O)C(O)=O
  name: Coumeroic acid
  reason: No typical sugar-like ring structure found
- smiles: O=C1OC(=CC(=C1CCCCCC)O)CC(C)C
  name: Photopyrone A
  reason: No typical sugar-like ring structure found
- smiles: '[C@H]1(O)[C@@H](O)O[C@H](CS(O)(=O)=O)[C@H]([C@@H]1O)O'
  name: 6-sulfo-alpha-D-quinovose
  reason: No amino group replacing a hydroxy group found
- smiles: SC[C@H](NC(=O)CNC(=O)[C@@H](N)CC(O)=O)C(O)=O
  name: Asp-Gly-Cys
  reason: No typical sugar-like ring structure found
sample_false_negatives:
- smiles: OC[C@H]1O[C@@H](O)[C@H](NC(=O)CCCCCNc2c(cc(cc2[N+]([O-])=O)[N+]([O-])=O)C(O)=O)[C@@H](O)[C@@H]1O
  name: N-[6-(DNCP-amino)hexanoyl]-beta-D-glucosamine
  reason: No typical sugar-like ring structure found
- smiles: '[H]C([H])(C=O)[C@@]([H])(N)[C@]([H])(O)[C@]([H])(C)O'
  name: acosamine
  reason: No typical sugar-like ring structure found
- smiles: O1C2C(O)(C(O)C13OCC(C(OC(=O)C4=CC=C(O)C=C4)C3)C)C(O)CC(C2)C(OC5C(OC6OC(C(O)C(O)C6NC(=O)C)CO)C(O)C(O)C(O)C5)=O
  name: Phyllanthusol A
  reason: No typical sugar-like ring structure found
- smiles: '[H][C@]1(O[C@](O)(C[C@H](O)[C@H]1NC(C)=O)C(O)=O)[C@H](O)[C@H](O)CO'
  name: N-acetyl-alpha-neuraminic acid
  reason: No typical sugar-like ring structure found
- smiles: O1[C@@H]([C@H](O)[C@@H](O)[C@@H](NC(=O)C)C1O)CO
  name: N-Acetyl-D-Gulosamine
  reason: No typical sugar-like ring structure found
- smiles: CN[C@@H]1[C@@H](O)[C@H](O[C@H]2O[C@@H](CC[C@H]2N)[C@H](C)N)[C@@H](N)[C@H](O)[C@@H]1OC
  name: Fortimicin KR
  reason: No typical sugar-like ring structure found
- smiles: N[C@H]1C(O)O[C@H](COP(O)(O)=O)[C@@H](O)[C@@H]1O
  name: 2-amino-2-deoxy-D-glucopyranose 6-phosphate
  reason: No typical sugar-like ring structure found
- smiles: CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1OP(O)(=O)OCCCN
  name: 3-aminopropyl N-acetyl-alpha-D-glucosamine-1-phosphate
  reason: No typical sugar-like ring structure found
- smiles: N[C@H]1CO[C@H](O)[C@H](O)[C@H]1O
  name: 4-amino-4-deoxy-beta-L-arabinopyranose
  reason: No typical sugar-like ring structure found
- smiles: CC(=O)N[C@@H]1[C@H](O)O[C@H](CO)[C@@H](O)[C@@H]1O
  name: N-acetyl-beta-D-mannosamine
  reason: No typical sugar-like ring structure found
attempt: 1
success: true
best: true
error: ''
stdout: null
num_true_positives: 2672
num_false_positives: 5453
num_true_negatives: 133842
num_false_negatives: 333
num_negatives: null
precision: 0.3288615384615385
recall: 0.8891846921797005
f1: 0.48014375561545375
accuracy: 0.9593394237526353
negative_predictive_value: 0.9975181665735048