Attempt 3 at oligosaccharide, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Error: Error executing is_oligosaccharide('O([C@@H]1[C@@H](O)[C@@H](O[C@@H]([C@@H]1O)CO)O[C@H]2[C@H](O)[C@@H](O)[C@@H](O[C@@H]2CO)O)[C@H]3O[C@@H]([C@H](O)[C@H](O[C@H]4O[C@@H]([C@H](O)[C@H](O)[C@H]4NC(=O)C)CO)[C@H]3O)CO'):
 Python argument types in
    Mol.GetSubstructMatches(Mol, NoneType)
did not match C++ signature:
    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle query, RDKit::SubstructMatchParameters params)
    GetSubstructMatches(RDKit::ROMol self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)
    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False, unsigned int maxMatches=1000)
    GetSubstructMatches(RDKit::ROMol self, RDKit::ROMol query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False, unsigned int maxMatches=1000)
Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: NONE
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:50699
  name: oligosaccharide
  definition: A compound in which monosaccharide units are joined by glycosidic linkages.
    The term is commonly used to refer to a defined structure as opposed to a polymer
    of unspecified length or a homologous mixture. When the linkages are of other
    types the compounds are regarded as oligosaccharide analogues.
  parents:
  - CHEBI:16646
  - CHEBI:167559
  xrefs:
  - KEGG:C00930
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 2
success: false
best: false
error: unterminated string literal (detected at line 13) (<string>, line 13)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []