Attempt 2 at sphingoid, f1=0.0
(currently fails to compile, but committing anyway

Below is one possible solution. In my reasoning I noticed that the prior approach (which was based solely on one‐or‐two simple SMARTS matches) was too permissive (so that many peptide fragments or partial motifs got “hit”) and in some cases the very short “core” motifs were not specific enough to exclude false positives. Therefore, in the code below I combine (a) a check that the molecule contains a long, contiguous aliphatic (non‐ring) carbon chain (using a DFS‐style search on atoms that are “aliphatic” carbons), (b) the presence of at least one nitrogen and at least one hydroxyl (or if absent, a note that the compound may be a deoxy variant) and (c) a substructure search for a more specific “sphingoid‐core” fragment (one of several SMARTS patterns that roughly capture the polar head group of sphinganine and its unsaturated or deoxy variants).

This combination of requirements helps to avoid many false positives (for instance, peptide fragments with isolated –C(O)NH– groups) while still catching many known sphingoid derivatives. (Note that no rule‐based procedure is perfect, so this is only one heuristic approach.)

Below is the complete Python code in one code block:

------------------------------------------------

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0.008989874042973574 is too low.
Outcomes:
------

True positives: SMILES: CCCCCCCCCCCCCCCCCC(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-octadecanoyl-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCC[C@@H](O)[C@@H](O)[C@@H]([NH3+])CO NAME: C16 phytosphingosine(1+) REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-(2-hydroxytetracosanoyl)-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-(2-hydroxyoctacosanoyl)-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: OC[C@@]([C@@](CCCCCCCCCCCCCC)(O)[H])(N)[H] NAME: heptadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCC\C=C\[C@@H](O)[C@@H](N)CO NAME: tetradecasphingosine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCC[C@@H](O)[C@@H](O)[C@@H](N)CO NAME: tetradecaphytosphingosine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](COP([O-])(=O)OCC[N+](C)(C)C)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-(2-hydroxynonadecanoyl)-4-hydroxy-15-methylhexadecasphinganine-1-phosphocholine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCC\C=C\CC\C=C\[C@@H](O)[C@@H](N)CO NAME: sphinga-4E,8E-dienine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCC(C)CCCCCCCC\C=C\[C@@H](O)[C@@H]([NH3+])CO NAME: 14-methylhexadecasphingosine(1+) REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCC\C=C\[C@@H](O)[C@@H]([NH3+])CO NAME: sphingosine(1+) REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: C(\CC/C=C/[C@H]([C@H](CO)[NH3+])O)=C\CCCCCCCCC NAME: sphinga-(4E,8Z)-dienine(1+) REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-pentacosanoyl-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCCCC(=O)N[C@@H](COP([O-])(=O)OCC[N+](C)(C)C)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-octadecanoyl-4-hydroxy-15-methylhexadecasphinganine-1-phosphocholine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCC\C=C\[C@@H](O)[C@@H](N)CO NAME: hexadecasphing-4-enine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-icosanoyl-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CC(C)CCCCCCCCCCCC(=O)[C@@H](N)CO NAME: 3-dehydro-15-methylhexadecasphinganine REASON: CORRECT Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: CCCCCCCCCCCCC\C=C\C(=O)[C@@H](N)CO NAME: 3-dehydrosphingosine REASON: CORRECT Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: CCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-nonadecanoyl-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCC[C@@H](O)[C@@H](O)[C@@H](N)CO NAME: phytosphingosine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCC[C@@H](O)[C@H](C)[NH3+] NAME: 1-deoxysphinganine(1+) REASON: CORRECT Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: CC(CC\C=C(/C)CCCC(C)C(O)CC=C(C)C)C[C@@H](O)[C@@H](N)CO NAME: aplidiasphingosine REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCC\C=C\[C@@H](O)[C@@H]([NH3+])CO NAME: tetradecasphingosine(1+) REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: [H]C(CCCCCCCCCCCCC)=C([H])[C@H](O)[C@H](N)CO NAME: (2R,3S)-2-aminooctadec-4-ene-1,3-diol REASON: CORRECT Matches normal sphingoid backbone motif
 * SMILES: CCCCCCCCCCCCCCCC(O)C(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C NAME: N-(2-hydroxyheptadecanoyl)-1-O-beta-D-glucosyl-4-hydroxy-15-methylhexadecasphinganine REASON: CORRECT Matches normal sphingoid backbone motif
False positives: SMILES: O=C(N[C@@H](CC=1NC=NC1)C(O)=O)[C@@H](NC(=O)[C@@H](N)[C@H](O)C)CC2=CC=CC=C2 NAME: Thr-Phe-His REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: O=C1N(O)CCC[C@@H]1N2C(=O)[C@@H](CCCN(O)C(=O)CCNC(=O)[C@@H](NC(=O)[C@H](NC(=O)C3=C(O)C=CC=C3)CO)C)N(C2)C NAME: Madurastatin E1 REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: [C@@H](C(CCCCCCCCCCCCCCC)=O)(CO)NC(=O)CCCCCCCCCCCCC NAME: N-myristoyl-3-ketodihydrosphingosine REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: S(CC[C@H](NC(=O)[C@@H](N)[C@H](CC)C)C(=O)NCC(O)=O)C NAME: Ile-Met-Gly REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: O=C(N[C@H](C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(O)=O)CO)[C@@H](N)CCCN=C(N)N NAME: Arg-Ser-Tyr REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: O=C(N[C@@H](CC1=CC=CC=C1)C(=O)N[C@@H](CC=2NC=NC2)C(O)=O)[C@@H](N)CC(C)C NAME: Leu-Phe-His REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: O=C(N[C@@H](CCC(O)=O)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC(=O)N)CCC(=O)N NAME: Asn-Gln-Glu REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: [C@@H]1([C@H]([C@H]([C@@H]([C@H]([C@@H]1O)O)O[C@@H]2[C@@H]([C@H]([C@@H]([C@H](O2)CO)O[C@@H]3[C@H]([C@H]([C@@H]([C@H](O3)CO[C@@H]4[C@H]([C@H]([C@@H]([C@H](O4)COP(OCCN)(=O)O)O)O)O[C@@H]5[C@H]([C@H]([C@@H]([C@H](O5)CO)O)O)O)O)O)O)O)N)OP(OCCCCCCS)(=O)O)O)O NAME: [alpha-D-Man-(1->2)-6-PEA-alpha-D-Man-(1->6)-alpha-D-Man-(1->4)-alpha-D-GlcN-(1->6)]-1-O-(6-thiohexylphosphono)-D-myo-inositol REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: C[C@@H]1CN(S(=O)(=O)C2=C(C=C(C=C2)C#C[C@@H](C)O)O[C@@H]1CN(C)C(=O)NC(C)C)[C@@H](C)CO NAME: 1-[[(4R,5S)-8-[(3R)-3-hydroxybut-1-ynyl]-2-[(2S)-1-hydroxypropan-2-yl]-4-methyl-1,1-dioxo-4,5-dihydro-3H-6,1$l^{6},2-benzoxathiazocin-5-yl]methyl]-1-methyl-3-propan-2-ylurea REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: C[C@H]1CCCCO[C@H]([C@H](CN(C(=O)C2=C(O1)C=CC(=C2)NC(=O)NC(C)C)[C@H](C)CO)C)CN(C)CC3=CC=NC=C3 NAME: 1-[(3S,9R,10S)-12-[(2R)-1-hydroxypropan-2-yl]-3,10-dimethyl-9-[[methyl(pyridin-4-ylmethyl)amino]methyl]-13-oxo-2,8-dioxa-12-azabicyclo[12.4.0]octadeca-1(14),15,17-trien-16-yl]-3-propan-2-ylurea REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: O([C@H]1[C@H](O)[C@H](O[C@@H]2O[C@@H]([C@@H](O[C@@H]3O[C@@H]([C@H](O)[C@H](O)[C@H]3O)CO)[C@H](O)[C@H]2NC(=O)C)CO)[C@H](O[C@@H]1CO)O[C@H]4[C@H](O)[C@H](O[C@@H](O[C@H]5[C@H](O)[C@@H](NC(=O)C)[C@@H](O[C@@H]5CO)O[C@@H]([C@H](O)[C@@H](NC(=O)C)CO)[C@H](O)CO)[C@H]4O)CO[C@H]6O[C@@H]([C@@H](O)[C@H](O)[C@@H]6O[C@@H]7O[C@@H]([C@@H](O[C@@H]8O[C@@H]([C@H](O)[C@H](O[C@]9(O[C@H]([C@H](NC(=O)C)[C@@H](O)C9)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]8O)CO)[C@H](O)[C@H]7NC(=O)C)CO)CO)[C@@H]%10O[C@@H]([C@@H](O[C@@H]%11O[C@@H]([C@H](O)[C@H](O[C@]%12(O[C@H]([C@H](NC(=O)C)[C@@H](O)C%12)[C@H](O)[C@H](O)CO)C(O)=O)[C@H]%11O)CO)[C@H](O)[C@H]%10NC(=O)C)CO NAME: CID 91845170 REASON: WRONGLY CLASSIFIED Matches normal sphingoid backbone motif
 * SMILES: C(CCCCCCCCC)CC\C=C\[C@@H](O)[C@@H](NC(=O)CCCCCCCCCCC)COP(OCC[NH3+])(=O)[O-] NAME: N-lauroyl-heptadecasphingosine-1-phosphoethanolamine zwitterion REASON: WRONGLY CLASSIFIED Matches normal sphingoid backbone motif
 * SMILES: C[C@H]([NH3+])CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12 NAME: L-3-aminobutanoyl-CoA(3-) REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: P(OC[C@@H](CO)OC(CCCCCCC)=O)(=O)(OCC[N+](C)(C)C)[O-] NAME: 2-octanoyl-sn-glycero-3-phosphocholine REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: CC(C)CCCC(C)CCCC(C)CCCC(C)C(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12 NAME: pristanoyl-CoA REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: S(CC[C@H](NC(=O)[C@@H](N)CCCCN)C(=O)N[C@@H](CC1=CC=CC=C1)C(O)=O)C NAME: Lys-Met-Phe REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: N[C@@H](CCC(=O)N[C@@H](CSC1C=CC(Br)=CC1O)C(=O)NCC(O)=O)C(O)=O NAME: 3,4-Dihydro-3-hydroxy-4-S-glutathionyl bromobenzene REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: CC1=CC2=C(C=C1C)N(C=N2)[C@@H]3[C@@H]([C@@H]([C@H](O3)CO)OP(=O)(O)O[C@H](C)CNC(=O)CC[C@@]4([C@H]([C@@H]5[C@]6([C@@]([C@@H](C(=C(C7=NC(=CC8=NC(=C(C4=N5)C)[C@H](C8(C)C)CCC(=O)N)[C@H]([C@]7(C)CC(=O)N)CCC(=O)N)C)[N-]6)CCC(=O)N)(C)CC(=O)N)C)CC(=O)N)C)O.[C-]#N.[Co+3] NAME: cobalt(3+) [(2R,3S,4R,5S)-5-(5,6-dimethylbenzimidazol-1-yl)-4-hydroxy-2-(hydroxymethyl)oxolan-3-yl] [(2R)-1-[3-[(1R,2R,3R,4Z,7S,9Z,12S,13S,14Z,17S,18S,19R)-2,13,18-tris(2-amino-2-oxoethyl)-7,12,17-tris(3-amino-3-oxopropyl)-3,5,8,8,13,15,18,19-octamethyl-2,7,12,17-tetrahydro-1H-corrin-21-id-3-yl]propanoylamino]propan-2-yl] hydrogen phosphate cyanidecobalt(3+) [(2R,3S,4R,5S)-5-(5,6-dimethylbenzimidazol-1-yl)-4-hydroxy-2-(hydroxymethyl)oxolan-3-yl] [(2R)-1-[3-[(1R,2R,3R,5Z,7S,10Z,12S,13S,15Z,17S,18S,19R)-2,13,18-tris(2-amino-2-oxoethyl)-7,12,17-tris(3-amino-3-oxopropyl)-3,5,8,8,13,15,18,19-octamethyl-2,7,12,17-tetrahydro-1H-corrin-24-id-3-yl]propanoylamino]propan-2-yl] hydrogen phosphate cyanidecobalt(3+) [(2R,3S,4R,5S)-5-(5,6-dimethylbenzimidazol-1-yl)-4-hydroxy-2-(hydroxymethyl)oxolan-3-yl] [(2R)-1-[3-[(1R,2R,3R,7S,12S,13S,17S,18S,19R)-2,13,18-tris(2-amino-2-oxoethyl)-7,12,17-tris(3-amino-3-oxopropyl)-3,5,8,8,13,15,18,19-octamethyl-2,7,12,17-tetrahydro-1H-corrin-24-id-3-yl]propanoylamino]propan-2-yl] hydrogen REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: CC\C=C/C\C=C/C\C=C/C\C=C/C\C=C/C\C=C/CCCCCCCCCC[C@@H](O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12 NAME: (3R,14Z,17Z,20Z,23Z,26Z,29Z)-3-hydroxydotriacontahexaenoyl-CoA REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative)
 * SMILES: O=C(N[C@@H](C(C)C)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC1=CC=C(O)C=C1)[C@H](CC)C NAME: Tyr-Ile-Val REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC/C=C\C/C=C\CCCCC)COCCCCCCCCCCCCCCCCCC)(OC[C@H](N)C(O)=O)(O)=O NAME: PS(O-18:0/22:2(13Z,16Z)) REASON: WRONGLY CLASSIFIED Matches normal sphingoid backbone motif
 * SMILES: O=C(N[C@@H](CCC(=O)N)C(=O)N[C@@H](CCC(=O)N)C(O)=O)[C@@H](N)CC(C)C NAME: Leu-Gln-Gln REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: P(OCC[N+](C)(C)C)(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCCC)([O-])=O NAME: PC(17:0/17:2(9Z,12Z)) REASON: WRONGLY CLASSIFIED Matches partial sphingoid backbone motif (may be a deoxy derivative) (no OH found, so may be a deoxy derivative)
 * SMILES: O=C(N[C@@H]([C@H](CC)C)C(O)=O)[C@@H](NC(=O)[C@@H](N)CC(=O)N)CCCCN NAME: Asn-Lys-Ile REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
 * SMILES: O=C(N[C@@H](CCCN=C(N)N)C(O)=O)[C@@H](NC(=O)[C@@H](N)CCC(=O)N)CC1=CC=CC=C1 NAME: Gln-Phe-Arg REASON: WRONGLY CLASSIFIED Matches deoxy/unsaturated sphingoid backbone motif (lacking OH at first carbon)
False negatives: SMILES: CCCCCCCCCCCCCCCC(=O)CN NAME: 1-deoxymethyl-3-dehydrosphinganine REASON: MISSED No sphingoid backbone motif found in molecule
 * SMILES: CCCCCCCCCCCCCCCC(=O)[C@H](C)N NAME: 1-deoxy-3-dehydrosphinganine REASON: MISSED No sphingoid backbone motif found in molecule
 * SMILES: CCCCCCCCCCCCCCCC(=O)[C@H](C)[NH3+] NAME: 1-deoxy-3-dehydrosphinganine(1+) REASON: MISSED No sphingoid backbone motif found in molecule
 * SMILES: CCCCCCCCCCCCCCCC(=O)C[NH3+] NAME: 1-deoxymethyl-3-dehydrosphinganine(1+) REASON: MISSED No sphingoid backbone motif found in molecule
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.

# INFORMATION:

---
chemical_class:
  id: CHEBI:35785
  name: sphingoid
  definition: Sphinganine, its homologs and stereoisomers, and the hydroxy and unsaturated
    derivatives of these compounds.
  parents:
  - CHEBI:26739
  xrefs:
  - LIPID_MAPS_class:LMSP01
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 97
  log_lines_of_code: 4.574710978503383
  max_indent: 5
  imports:
  - from rdkit import Chem
  imports_count: 1
  methods_called:
  - GetSymbol
  - GetNeighbors
  - GetAtomicNum
  - add
  - HasSubstructMatch
  - IsInRing
  - GetIdx
  - MolFromSmarts
  - GetIsAromatic
  - get
  - GetSubstructMatches
  - GetAtomWithIdx
  - MolFromSmiles
  - GetAtoms
  - append
  methods_called_count: 15
  smarts_strings:
  - '[OX2H]'
  - '[C;!R]-[C;!R]([NX3;H2,H1])-[C;!R][OX2H]'
  - '[C;!R]=[C;!R]([NX3;H2,H1])'
  - '[OX2H][C;!R]-[C;!R]([NX3;H2,H1])- [C;!R][OX2H]'
  smarts_strings_count: 4
  defs:
  - '_longest_aliphatic_chain_length(mol):'
  - 'dfs(current, visited):'
  defs_count: 2
  returns:
  - max_len
  - longest
  - False, "Invalid SMILES string"
  - False, f"Longest continuous aliphatic carbon chain is only {chain_len} (need at
    least 14)"
  - False, "No nitrogen found (expected an amino or acylamino group in sphingoid compounds)"
  - False, "No sphingoid core motif found in molecule"
  - True, reason
  returns_count: 7
  complexity: 6.714942195700677
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 1
success: false
best: false
error: "Error executing is_sphingoid('CCCCCCCCCCCCCCCCCC(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@H]1O)[C@H](O)[C@H](O)CCCCCCCCCCC(C)C'):\n\
  \ Python argument types in\n    Mol.GetSubstructMatches(Mol, NoneType)\ndid not\
  \ match C++ signature:\n    GetSubstructMatches(RDKit::ROMol self, RDKit::MolBundle\
  \ query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, RDKit::SubstructMatchParameters params)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::MolBundle query, bool uniquify=True, bool useChirality=False, bool\
  \ useQueryQueryMatches=False, unsigned int maxMatches=1000)\n    GetSubstructMatches(RDKit::ROMol\
  \ self, RDKit::ROMol query, bool uniquify=True, bool useChirality=False, bool useQueryQueryMatches=False,\
  \ unsigned int maxMatches=1000)"
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []