Reverting to best solution for 4'-hydroxyflavanones, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:140331
  name: 4'-hydroxyflavanones
  definition: Any hydroxyflavanone having a hydroxy substituent located at position
    4'.
  parents:
  - CHEBI:24697
  xrefs:
  - MetaCyc:4-Hydroxyflavanones
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 37
  log_lines_of_code: 3.6109179126442243
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import AllChem
  imports_count: 2
  methods_called:
  - GetSubstructMatches
  - GetAtomicNum
  - GetAtomWithIdx
  - items
  - HasSubstructMatch
  - GetDegree
  - GetNeighbors
  - MolFromSmiles
  - GetIdx
  - MolFromSmarts
  methods_called_count: 10
  smarts_strings:
  - c1ccc2C(=O)CC(c3ccccc3)Oc2c1
  - c1ccc(O)cc1
  - c1ccccc1
  smarts_strings_count: 3
  defs:
  - 'is_4__hydroxyflavanones(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "Molecule does not contain a flavanone core"
  - True, "Molecule contains a flavanone core with a hydroxy substituent at the 4'
    position of the phenyl ring"
  - False, "Molecule does not have a hydroxyl substituent at the 4' position of the
    phenyl ring"
  returns_count: 4
  complexity: 4.122183582528845
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0