Attempt 4 at monoterpenoid indole alkaloid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: C=C[C@]1(CN2CCC=3C4=CC=CC=C4NC3[C@@]2(C[C@@]1(CCO)[H])[H])[H] NAME: Corynantheol REASON: MISSED No indole substructure found
 * SMILES: C/C=C\1/CN2[C@]3(C[C@@]1(C4([C@@]2(CC5(C6=CC=CC=C6N(C)[C@]35[H])[C@@H]4O)[H])C(=O)OC)[H])[H] NAME: Vincamajine REASON: MISSED No indole substructure found
 * SMILES: COC(=O)C1=CO[C@@H](C)[C@H]2CN3CCc4c([nH]c5ccc(OC)cc45)[C@@H]3C[C@H]12 NAME: Cabucine REASON: MISSED No indole substructure found
 * SMILES: C/C=C\1/CN2CC[C@@]34C5=CC=CC=C5N6[C@]4([C@@](C=C([C@]7(C[C@@]89C%10=CC=CC=C%10N%11C=C%12[C@]/%13(C[C@]%14([C@@]%15(CCN%14C\C%13=C\C)C%16=CC=CC=C%16N(C=C([C@]/%17(C[C@@]8(N7C\C%17=C\C)[H])[H])[C@@]9%11[H])[C@@]%12%15[H])[H])[H])[H])C6=O)([C@]1(C[C@@]32[H])[H])[H])[H] NAME: Strychnohexamine REASON: MISSED No indole substructure found
 * SMILES: C/C=C\1/C2CC[N@+]3(CC[C@]4(C5=CC=CC=C5NC4=C2C(=O)OC)[C@@]13[H])[O-] NAME: Condylocarpine N-oxide REASON: MISSED No indole substructure found
 * SMILES: COC(=O)[C@H]1[C@H]2C[C@H]3C4=C(CCN3C[C@@H]2CCC1O)C5=CC=CC=C5N4 NAME: (1S,15R,19S,20S)-18-hydroxy-1,3,11,12,14,15,16,17,18,19,20,21-dodecahydroyohimban-19-carboxylic acid methyl ester REASON: MISSED No indole substructure found
 * SMILES: C(OC)(=O)C=1[C@]2(C[C@@]3(C4=C(C5=C(N4)C=C(C(=C5)OC)OC)CCN3C[C@]2([C@@H](OC1)C)[H])[H])[H] NAME: reserpiline REASON: MISSED No indole substructure found
 * SMILES: C/C=C\1/C[N+]2(C)[C@]3(CC=4C5=CC=CC=C5NC4[C@@]2(C[C@@]1(C3C(=O)[O-])[H])[H])[H] NAME: Panarine REASON: MISSED No indole substructure found
 * SMILES: COC=1C=CC=2C=3CCN4C[C@@]5(CC[C@@]([C@@]([C@]5(C[C@]4(C3NC2C1)[H])[H])(C(=O)OC)[H])(O)[H])[H] NAME: 11-methoxyyohimbine REASON: MISSED No indole substructure found
 * SMILES: CN1C=2C=CC(CC=3C=CC4=C(C3)[C@@]56CCN7CCC[C@@]8(CC([C@@]5(CC8)N4C)C(OC)=O)[C@@H]67)=CC2C9%10CCN%11CCC[C@@]%12(CC(C91CC%12)C(OC)=O)[C@@H]%10%11 NAME: Pleiokomenine A REASON: MISSED No indole substructure found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:65323
  name: monoterpenoid indole alkaloid
  definition: A terpenoid indole alkaloid which is biosynthesised from L-tryptophan
    and diisoprenoid (usually secolaganin) building blocks.
  parents:
  - CHEBI:65321
  xrefs:
  - PMID:18280746
  - PMID:20717879
  - PMID:21425787
  - PMID:22679912
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: unterminated string literal (detected at line 11) (<string>, line 11)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []