Attempt 4 at tetraterpenoid, f1=0.0
(currently fails to compile, but committing anyway

None

# PREVIOUS ATTEMPT:

Attempt failed: F1 score of 0 is too low.
Outcomes:
------

True positives: NONE
False positives: NONE
False negatives: SMILES: CC(/C=C/C=C(C)\C=C\C1=C(C)CCCC1(C)C)=C\C=C\C=C(C)\C=C\C=C(C)\C=C\C1=C(C)CCCC1(C)C NAME: 9-cis-beta-carotene REASON: MISSED No terpenoid-like isoprene units found
 * SMILES: CC(\C=C\C=C(C)\C=C\[C@@H]1C(C)=CCCC1(C)C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C1=C(C)CCCC1(C)C NAME: (6'S)-beta,epsilon-carotene REASON: MISSED No terpenoid-like isoprene units found
 * SMILES: O([C@H]1CC(C(=C(C1)C)/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C=C(/C=C/C=C(/C=C/C=2C(C[C@H](O[C@@H]3O[C@@H]([C@@H](O)C(O)C3O)CO)CC2C)(C)C)\C)\C)(C)C)[C@@H]4O[C@@H]([C@@H](O)C(O)C4O)CO NAME: Zeaxanthin diglucoside/ Zeaxanthin beta-D-diglucoside REASON: MISSED Does not have a C40 skeleton (found 52 carbons)
 * SMILES: OC1CC(C(C(=C1)C)\C=C\C(\C)=C\C=C\C(\C)=C\C=C\C=C(\C=C\C=C(\C=C\C2C(CC(=O)C=C2C)(C)C)/C)/C)(C)C NAME: 3'-hydroxy-e,e-caroten-3-one REASON: MISSED No terpenoid-like isoprene units found
 * SMILES: O([C@H]1CC(C(=C(C1=O)C)\C=C\C(\C)=C\C=C\C(\C)=C\C=C\C=C(\C=C\C=C(\C=C\C=2C(C[C@H](O[C@@H]3O[C@@H]([C@@H](O)C(O)C3O)CO)C(=O)C2C)(C)C)/C)/C)(C)C)[C@@H]4O[C@@H]([C@@H](O)C(O)C4O)CO NAME: Astaxanthin diglucoside/ Astaxanthin beta-D-diglucoside REASON: MISSED Does not have a C40 skeleton (found 52 carbons)
 * SMILES: O1C(C1CC/C(/C)=C/C=C/C(/C)=C/C=C/C(=C/C=C/C=C(/C=C/C=C(/C=C/C=2C(CCCC2C)(C)C)\C)\C)/C)(C)C NAME: (S)-1',2'-Epoxy-1',2'-dihydro-b,y-carotene REASON: MISSED No terpenoid-like isoprene units found
 * SMILES: OC1CC(C(=C(C1=O)C)/C=C/C(/C)=C/C=C/C(/C)=C/C=C/C=C(/C=C/C=C(/C=C/C=C(/CCC=C(C)C)\C)\C)\C)(C)C NAME: 4-Oxogazaniaxanthin REASON: MISSED No terpenoid-like isoprene units found
 * SMILES: O=C/C(=C/C=C/C(=C/C=C/C(=C/C=C/C(=C/C=C/C=C(/C=C/C=C(/C=C/C1=C(CCCC1(C)C)C)\C)\C)/C)/C)/C)/C NAME: Torularhodinaldehyde REASON: MISSED No terpenoid-like isoprene units found
 * SMILES: C(\C=C\C(OC)=O)(=C\C=C\C(=C\C=C\C=C(\C=C\C=C(\C=C\C(=O)O)/C)/C)\C)/C NAME: bixin REASON: MISSED Does not have a C40 skeleton (found 25 carbons)
 * SMILES: O=C1CC(C(C(=C1)C)\C=C\C(\C)=C\C=C\C(\C)=C\C=C\C=C(\C=C\C=C(\C=C\C2C(CC(=O)C=C2C)(C)C)/C)/C)(C)C NAME: e,e-carotene-3,3'-dione REASON: MISSED No terpenoid-like isoprene units found
------

In your reasoning step, analyze the previous program and the above outcomes, hypothesizing about what went wrong, and how to improve.
IMPORTANT NOTE: I do not have 100% confidence in the benchmark I am using. There may be occasional and systematic mistakes. Use your best judgment, and if you think the classifications your program are consistent with your understanding if the meaning of the chemical class, then you can ignore outliers, but explain your reasoning in doing so. I have great confidence in your broad understanding of chemistry and your ability to translate this into code.
# INFORMATION:

---
chemical_class:
  id: CHEBI:26935
  name: tetraterpenoid
  definition: Any terpenoid derived from a tetraterpene. The term includes compounds
    in which the C40 skeleton of the parent tetraterpene has been rearranged or modified
    by the removal of one or more skeletal atoms (generally methyl groups).
  parents:
  - CHEBI:26873
  xrefs:
  - LIPID_MAPS_class:LMPR0107
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 0
  log_lines_of_code: 0.0
  max_indent: 0
  imports: []
  imports_count: 0
  methods_called: []
  methods_called_count: 0
  smarts_strings: []
  smarts_strings_count: 0
  defs: []
  defs_count: 0
  returns: []
  returns_count: 0
  complexity: 0.0
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 3
success: false
best: false
error: unterminated string literal (detected at line 27) (<string>, line 27)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0
sample_true_positives: []