Reverting to best solution for prenylquinone, f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:26255
  name: prenylquinone
  definition: 'A quinone substituted by a polyprenyl-derived side-chain. Prenylquinones
    occur in all living cells. Due to their amphiphilic character, they are mainly
    located in biological membranes where they function as electron and proton carriers
    in the photosynthetic and respiratory electron transport chains. Some prenylquinones
    also perform more specialised roles sucy as antioxidants and enzyme cofactors.
    Prenylquinones are classified according to ring structure: the main classes are
    menaquinones, phylloquinones, ubiquinones and plastoquinones.'
  parents:
  - CHEBI:25830
  xrefs:
  - PMID:19928587
  - PMID:21777468
  - PMID:21844348
  - PMID:22371323
  - PMID:3985624
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 33
  log_lines_of_code: 3.4965075614664802
  max_indent: 2
  imports:
  - from rdkit import Chem
  - from rdkit.Chem import rdqueries
  - from rdkit.Chem import rdMolDescriptors
  imports_count: 3
  methods_called:
  - GetIdx
  - intersection
  - GetSubstructMatches
  - CalcNumAliphaticRings
  - IsotonicQueriesFromSmarts
  - MolFromSmiles
  - HasSubstructMatch
  methods_called_count: 7
  smarts_strings: []
  smarts_strings_count: 0
  defs:
  - 'is_prenylquinone(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES string"
  - False, "No quinone substructure found"
  - False, "No prenyl side-chain found"
  - False, "Prenyl side-chain(s) not connected to quinone"
  - False, "Only one prenyl unit found, need at least two"
  - True, "Contains a quinone substructure with one or more polyprenyl side-chains"
  returns_count: 6
  complexity: 3.899301512293296
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: exceptions must derive from BaseException
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0