Reverting to best solution for 3-oxo-fatty acyl-CoA(4-), f1=0.0 iteration 0
---
chemical_class:
  id: CHEBI:57347
  name: 3-oxo-fatty acyl-CoA(4-)
  definition: An acyl-CoA(4-) arising from deprotonation of the phosphate and diphosphate
    groups of any 3-oxo-fatty acyl-CoA.
  parents:
  - CHEBI:77636
  - CHEBI:90726
  xrefs:
  - MetaCyc:3-KETOACYL-COA
  all_positive_examples: []
config: null
code_statistics:
  lines_of_code: 27
  log_lines_of_code: 3.295836866004329
  max_indent: 2
  imports: []
  imports_count: 0
  methods_called:
  - GetFormalCharge
  - GetSubstructMatches
  - MolFromSmiles
  - HasSubstructMatch
  - GetAtoms
  - MolFromSmarts
  methods_called_count: 6
  smarts_strings:
  - SCCNC(=O)
  - '[O-]P(=O)([O-])[O-]'
  - '[CX3]=[OX1]-[CX3]=[OX1]-S'
  - n1cnc2c(N)ncnc12
  smarts_strings_count: 4
  defs:
  - 'is_3_oxo_fatty_acyl_CoA_4__(smiles: str):'
  defs_count: 1
  returns:
  - False, "Invalid SMILES"
  - False, "No 3-oxo group adjacent to thioester"
  - False, "Missing pantetheine part of CoA"
  - False, "Missing adenine moiety"
  - 'False, f"Insufficient phosphate groups with negative charges: {len(phosphate_matches)}"'
  - False, f"
  returns_count: 6
  complexity: 3.659167373200866
message: null
true_negatives: null
false_negatives: null
sample_true_negatives: null
sample_false_negatives: null
attempt: 0
success: false
best: true
error: unexpected indent (<string>, line 1)
stdout: ''
num_true_positives: 0
num_false_positives: 0
num_true_negatives: 0
num_false_negatives: 0
num_negatives: null
precision: 0.0
recall: 0.0
f1: 0.0
accuracy: null
negative_predictive_value: 0.0